### ISSUE TITLE
Setting `showPanel` as component-level parameter doesn't seem to work

### ISSUE THREAD

**Issue by adamchipperfield** [storybookjs/storybook#10109]
When I set parameter options on a Component level basis, the following occurs:

1. I set a Component to have `parameters.options.showPanel` set to `false`.
2. Storybook loads on a different Component (with no config set) and the panel shows.
3. Click on the Component (from step 1) and the panel hides. So far so good.
4. I click on the Component from step 2 (or any other Component) and the panel is still hidden.

So what I want to happen is for the panel to hide for one component and then show again on the others. This surely is possible? Am I doing something wrong?

Here is the Component with the options:
```
export default {
  title: 'Color',
  parameters: {
    options: {
      showPanel: false,
    },
  },
}
```

Any help would be hugely appreciated!

**Comment by shilman** [comment]
I think this might have more to do with how Storybook UI handles state and less to do with component parameters. What happens when you set `showPanel: true` globally?

**Comment by adamchipperfield** [comment]
Thanks @shilman. Annoyingly this doesn't work.

If it helps, I've also tried by explicitly setting `showPanel: true` on another component. The panel shows back up when clicking into that component. But then the same happens when returning to the original, no-panel component.

**Comment by adamchipperfield** [comment]
Clearly setting `showPanel: true` on every other component will fix it, but this isn't ideal nor future-proof.

**Comment by shilman** [comment]
You can set parameters globally, per component, and per story. These are all workarounds. I believe @tmeasday  started on a proper solution once upon a time but it’s buried in an issue somewhere

**Comment by tmeasday** [comment]
Yeah, TBH although I realise there are legitimate use cases where this is nice my current feeling is that setting options per-story (or component) is too messy and complicated to really be worth it. I reckon we should drop this as a "feature".

**Comment by danielo515** [comment]
Can somebody stop stalebot flagging this as staled? It is not. It is a real problem that I'm also facing because I am following the official docs.

**Comment by Dashue** [comment]
Chipping in here setting it to true on a global level makes it work to disable it on a story level.

Just verified with 
showPanel: false,
isToolshown: false,

So in my case it seems it's an issue with nothing being set before i set it to false in my component?

Perhaps defaulting to true on all options if nothing is being set by the user in preview.ts might resolve my use-case?

**Comment by danielo515** [comment]
this "issue" is still existing. If the intention is to "not fix it" then I will not close it without stating that.

**Comment by shilman** [comment]
Which version of Storybook?

**Comment by beautyfree** [comment]
Same issue with 5.3.19 storybook

**Comment by shilman** [comment]
@danielo515 do you want to fix it? if you want to contribute you are very welcome to. just because i don't have time to look into it doesn't mean that we should close the issue. Storybook is a community-driven project with almost 1000 contributors. If I close the issue then there is almost no chance that somebody will fix it. Stale bot and issue upvotes (this issue currently has only 2 upvotes for a project used by tens of thousands of teams!) are the mechanism we use to triage.

**Comment by danielo515** [comment]
Yeah, I completely understand that @shilman 
It is just that the bot usually closes issues that are not fixed, and at the end it is not clear if the intention was to not fix it or if the bot just closed them. That's why I was suggesting to add a won't fix label if that was the case

**Comment by shilman** [comment]
whose call is that? i'd say there are very few issues that we "won't fix" but a lot of issues that we "can't fix" due to time constraints. which ones are those? the ones that stale out. how long does it take to determine the issues that stale out? a month or two. during that time, i can see the upvote/comment activity and whether people have signed up to fix them ("in progress"). if a bug/feature looks like a dealbreaker to me, or somebody is signed up to do it i'll mark it as "todo", which also tells the stale bot to go away. after 6.0 ships, i hope to have more hands on deck and will spend more time on product management and community organization, at which point i'd consider revising this strategy. in the meantime, leaning on stale bot has been the only way to manage a large, complex project like this while chipping away at key platform features to make storybook more useful.

**Comment by marcellino-ornelas** [comment]
Posted this solution in another issue because I couldn't find a solution. I then found out @shilman posted a solution in this issue. I think the `stalebot` message threw me off made it seem like this wasn't resolved so skipped this issue. Hopefully this comment will help other folks 😃 

Solution that worked for me is to set option globally and then override it in individual stories. 

 ----
https://github.com/storybookjs/storybook/issues/14442#issuecomment-1089165153

I had a similar use case where I wanted to show the addon panel to all my stories but wanted to disabled it in a specific story that I didn't need it.

Adding a `showPanel` option to my specific story seemed to apply to all my stories. Not sure why 🤷‍♂️

I was able to solve this by adding a global `showPanel` option to `true` in `preview.js` and then overriding that option in each story that I didn't want it to show

`preview.js`
```ts
export const parameters = {
	options: {
		showPanel: true,
	},
	/* ...rest */
};
```

Then in my story file I was able to hid the panel with:

```ts
export default {
	title: 'Button',
	component: Button,
	parameters: { options: { showPanel: false } },
} as ComponentMeta<typeo f Button>;
```

This would hide the panel for all stories in that file. If you want a specific story turned off you can use

```ts
export const Primary = Template.bind({});
Primary.parameters = {
	options: { showPanel: false },
};
```
