### ISSUE TITLE
CSS Resources addon works in docs mode for React but not for Angular

### ISSUE THREAD

**Issue by CodeByAlex** [storybookjs/storybook#10165]
**Describe the bug**
CSS Resources addon works in docs mode for React but not for Angular

**To Reproduce**
Pull up an Angular storybook app - add a style sheet or 2 using the code parameter (as seen in the official example). Then go to the css resources addon and check one of the themes. Then go to the docs view and see that the theme has NOT been applied.

Pull up the React Official storybook app - go to the css resources addon and then check one of the themes. Then go to the docs view and see that the theme HAS been applied.

**Expected behavior**
The themes should apply in the preview as well as the docs view

**Additional context**
Angular (and maybe other frameworks that render components in iframes) does not apply the theme in docs mode

**Comment by bbech** [comment]
I faced this issue and this is due to the fact that stroybook use `iframe`  for angular.
I fixed this by configure storybook with inline decorator for angular thanks to this documentation  [https://github.com/storybookjs/storybook/pull/13525](https://github.com/storybookjs/storybook/pull/13525)

Add : `npm add -D @angular/elements @webcomponents/custom-elements`
Then update your `.storybook/preview.js` :

```javascript
import { addParameters } from '@storybook/angular';
import { prepareForInline } from '@storybook/addon-docs/angular/inline';
addParameters({
  docs: {
    inlineStories: true,
    prepareForInline,
  },
});
```

This is ok since 6.2.0
