### ISSUE TITLE
Allow linear-gradient in ColorItem doc block

### ISSUE THREAD

**Issue by maniax89** [storybookjs/storybook#10232]
**Is your feature request related to a problem? Please describe.**

When using the `<ColorPalette><ColorItem /></ColorPalette>` doc blocks, the `<ColorItem>` accepts a `colors` parameter that ultimately gets set to `backgroundColor`.

would be nice to allow setting `background` or `backgroundImage` to allow setting things like gradients `linear-gradient(white, black)`

**Describe the solution you'd like**

Could we have an additional prop called `colorType` (defaults to `backgroundColor`) or something that allows you to override what css property the `color` gets set to?

```
<ColorItem colors={['linear-gradient(white,black)']} colorType={'image'} />
```

**Describe alternatives you've considered**

We've also just built our own story to showcase the color swatches in our application which works fine, but I imagine others might be wondering why they can't use things like gradients in the `ColorPalette`

**Are you able to assist bring the feature to reality?**
yes, I can... (if given the proper go-ahead for API changes)

**Comment by shilman** [comment]
Gonna defer to @domyen on this one.. WDYT?

**Comment by domyen** [comment]
Thanks for the detail and suggestion @maniax89! I'd be open to adding more flexibility. This sounds like it should be possible by: 
1. Changing  `backgroundColor` to `background` [here](https://github.com/storybookjs/storybook/blob/next/lib/components/src/blocks/ColorPalette.tsx#L129). 
2. Adding `text-overflow: ellipsis` [here](https://github.com/storybookjs/storybook/blob/next/lib/components/src/blocks/ColorPalette.tsx#L41).

I acknowledge that the swatch labels may be obfuscated because linear-gradient definitions are quite long. I'd recommend folks make their own component if the use case for gradients is more complex though.

**Comment by maniax89** [comment]
@domyen added https://github.com/storybookjs/storybook/pull/10237

**Comment by shilman** [comment]
Good golly!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.0.0-alpha.30 containing PR #10237 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.
