### ISSUE TITLE
add store feature to @storybook/addon-toolbars

### ISSUE THREAD

**Issue by smmoosavi** [storybookjs/storybook#10240]
**Is your feature request related to a problem? Please describe.**
after reloading page, the state of globalArgs will be restart. some times we need to state to be more sticky. for example, the default theme is light, but you are focusing to fix a bug in dark mode.

**Describe the solution you'd like**
add `store` option to `globalArgTypes` definition. it can be `false`, `'session'` or `'local'`

- `false`: do not store value (default)
- `'session'`: store the latest value in `sessionStorage`. (per tab storage)
- `'local'`: store the latest value in `localStorage`. (long term and shared between tabs)

```js
export const globalArgTypes = {
    locale: {
        name: 'Theme',
        description: 'Theme type',
        defaultValue: 'ligth,
        store: 'session' // it can be false, session, local
        toolbar: {
            icon: 'globe',
            items: ['light', 'dark'],
        },
    },
}
```
**Are you able to assist bring the feature to reality?**
no

**Comment by shilman** [comment]
cc @tmeasday

**Comment by tmeasday** [comment]
Yeah, fair point.

I think at this stage rather than make it configurable we should maybe just always store it for the session? WDYT @shilman?

However this is going to be a bit tricky because we store state on the manager side. So we'd need to tell the story store about it after the manager+preview booted, leading to a flash of the wrong globals.

The alternative is to store the globals in local/session storage on the preview side. That feels more correct, but we don't currently have a mechanism for that. I guess we should do this though.

**Comment by shilman** [comment]
Yeah I like your solution @tmeasday (non-configurable session storage on the preview side). Is that something you can work your magic on?

**Comment by tmeasday** [comment]
Yeah assign it to me

**Comment by shilman** [comment]
Yowza!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.0.0-beta.38 containing PR #11345 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.
