### ISSUE TITLE
Can't render list items when using MDX

### ISSUE THREAD

**Issue by mamoonraja** [storybookjs/storybook#10270]
## Description

I have a list of items in my `MDX` files, as defined below:

```
### Items

1. Item A.
1. Item B.
1. Item C.
```

**Storybook renders it as:**

![image](https://user-images.githubusercontent.com/16810846/78053023-fc40c280-734d-11ea-8fbe-82a17c4e7e5c.png)

**Expected behavior:**

![image](https://user-images.githubusercontent.com/16810846/78053062-0d89cf00-734e-11ea-90de-8167d0eb81f4.png)

**Additional context**

Looks like `list-style` has been disabled by [default](https://github.com/storybookjs/storybook/blob/953c43bec6e5ecf09689d1d86fcc01fee5eb11f4/docs/src/components/Docs/Container/style.css#L11). Is there a workaround available that I can use?

**Comment by shilman** [comment]
That looks like a bug. cc @domyen

**Comment by frassinier** [comment]
Hello @mamoonraja, 

Nothing related to the piece of code you are linking at 🤔 

Do you use a reset CSS library like [normalize.css](https://necolas.github.io/normalize.css/) or [reset.css](https://meyerweb.com/eric/tools/css/reset/)? 
Tailwind has its one too based on normalize!
Because they use to disable the default list style.

Maybe related?

**Comment by shilman** [comment]
Good golly!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.0.0-rc.16 containing PR #11281 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.
