### ISSUE TITLE
addon-docs doesnt show prop table with imported component from npm package

### ISSUE THREAD

**Issue by Schum123** [storybookjs/storybook#10297]
**Describe the bug**
Hello, I'm having problems using the ``addon-docs``  and storybook for vue. I have a library where i store all my components and importing them in my stories.

The component renders its story but not the props table.

**To Reproduce**
1. import { MyComponent } from '@mylib/mylib-vue-components';
2. Go to docs
3. props table does not render

**Expected behavior**
prop table should render

**Code snippets**
```
import { MyComponent } from '@mylib/mylib-vue-components';

export default {
  title: 'Path/To/MyComponent',
  component: MyComponent,
}
```

**System:**
```
Environment Info:

  System:
    OS: Windows 10 10.0.1629910.15.3
    CPU: (8) x64 Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz
  Binaries:
    Node: 12.16.1 - C:\Program Files\nodesjs\node.exe
    Yarn: 1.17.3 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.13.4 - C:\Program Files\nodesjs\npm.CMD
  Browsers:
    Edge: 41.16299.1480.0
  npmPackages:
    "@storybook/addon-actions": "v6.0.0-alpha.9"
    "@storybook/addon-doc"s: "v6.0.0-alpha.9"
    "@storybook/addon-links": "v6.0.0-alpha.9"
    "@storybook/addons": "v6.0.0-alpha.9"
    "@storybook/vue": "v6.0.0-alpha.9"
```

**Additional context**
If i create the exact same component inside my storybook app like this,

```
import MyComponent from './MyComponent';

export default {
  title: 'Path/To/MyComponent',
  component: MyComponent,
}
```
then it renders correct with prop table.

**Comment by shilman** [comment]
That's the expected behavior. `Props` works by running some babel or webpack loader on the source code of your component to analyze its interface, and it only runs on files in your project for performance reasons.

If that source code is part of the distribution, there might be some custom webpack tricks you could play to also get it to run on that code. But it's not supported by Storybook at the moment, and in general that information would not necessarily be contained in the bundled package distribution for your components.

**Comment by Schum123** [comment]
Ok! thx for quick answer! Will look into my webpack config and see if can manage to fix it.

**Comment by MaximeMohandi** [comment]
@Schum123 sorry to re-open this but did you find a solution with the webpack ?

**Comment by Schum123** [comment]
@MaximeMohandi Sorry no. Decided to use Storybook alongside my component library instead.
