### ISSUE TITLE
Addon-docs: Update type/value rendering for 6.0 recommendations

### ISSUE THREAD

**Issue by shilman** [storybookjs/storybook#10311]
<img width="614" alt="Addons___Docs___mdx_-_hello_story_⋅_Storybook" src="https://user-images.githubusercontent.com/488689/78453995-d73ead80-76c7-11ea-8773-78fb7c8eb7e0.png">

Storybook 5.3 has a nice type rendering system based on `react-docgen-typescript-loader`. In SB 6.0 we've [updated the recommended configuration](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#react-prop-tables-with-typescript), which brings a lot of improvements. However, the new setup exercises a new codepath that contains poor type/value rendering heuristics. These need to be updated before launch:

- [ ] Union
- [ ] Intersection
- [ ] Function
- [ ] etc.

**Comment by sunyatasattva** [comment]
@shilman Is there any news on this? The docs point out, for example, to the dealbreaker of imported types not working in `react-docgen` and link to the relevant PR, mentioning it is open. The PR has since been closed (https://github.com/reactjs/react-docgen/pull/352) and instead another one has been merged (https://github.com/reactjs/react-docgen/pull/464). Probably the docs should be updated accordingly as this is not anymore a deal breaker for `react-docgen`.

Otherwise, is there any plan to figure out things like `union` or `signature` with the current recommended configuration?

**Comment by shilman** [comment]
@sunyatasattva We now recommend `react-docgen-typescript` as the recommended docgen handler for Typescript. Any PRs to improve `react-docgen` handling would be highly appreciated.

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
