### ISSUE TITLE
`preview-body.html` not working as expected (?)

### ISSUE THREAD

**Issue by amypellegrini** [storybookjs/storybook#10403]
Hi, thanks for taking the time to look into this.

**Describe the bug**

The rendered content is not being appended in the `preview-body.html` file as the documentation suggests:

https://storybook.js.org/docs/configurations/add-custom-body/

**To Reproduce**

Add a `preview-body.html` file inside the `.storybook` config folder as suggested in the docs, containing a single custom `<div id="custom-root"></div>` div wrapper.

**Expected behavior**

I would expect this element to be the root of the rendered content, unless I'm missing something. Instead, the usual `#root` div container is used.

**Screenshots**

As shown in the screenshot, an extra div is added to the content, but this div is empty and is not serving the purpose of being the root for the rendered content.

<img width="415" alt="Screenshot 2020-04-13 at 12 23 44" src="https://user-images.githubusercontent.com/583564/79116946-aa526080-7d81-11ea-87d3-397d7b534006.png">

**System:**
```
Environment Info:

  System:
    OS: macOS Mojave 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
  Binaries:
    Node: 12.7.0 - ~/.nvm/versions/node/v12.7.0/bin/node
    Yarn: 1.21.1 - /usr/local/bin/yarn
    npm: 6.10.0 - ~/.nvm/versions/node/v12.7.0/bin/npm
  Browsers:
    Chrome: 80.0.3987.163
    Firefox: 74.0.1
    Safari: 13.1
  npmPackages:
    @storybook/react: ^5.0.6 => 5.2.8
```

**Comment by IuliiaBondarieva** [comment]
Have the same problem :/

**Comment by IuliiaBondarieva** [comment]
Needed it to add attribute on DOM Element.
Found some workaround for now. Updated loadStories function in .storybook/config.js:
`const req = require.context('../src', true, /.stories.js$/)
function loadStories() {
  document.body.onload = function () {
    document.body.setAttribute('theme', 'myTheme')
  }
  req.keys().forEach(filename => req(filename))
}`

**Comment by shilman** [comment]
@amypellegrini AFAIK the custom body simply injects more HTML into the body of the page. It doesn't rewrite the page or modify the storybook root.

**Comment by IuliiaBondarieva** [comment]
@shilman in my case it does nothing at all. That means that I can't find any custom-root element in DOM. 
I have "@storybook/react": "5.1.9" package.

**Comment by amypellegrini** [comment]
@shilman Thanks for your answer. I was trying to add a custom root to render the content and I found the link I refer to in the issue (https://storybook.js.org/docs/configurations/add-custom-body/), it sounds like there is some confusion on my part on how to achieve this, and I lack clear instructions on how to do it.

Do you think that adding a few more details on how to render the examples in a custom root, or making it somehow more obvious would help other people like me who are not familiar with how this works? Would this be unreasonable to ask?

Thanks again!

**Comment by fvilers** [comment]
I came to this topic while looking for how to inject the rendered stories inside a custom div tag instead of the traditional `<div id="root">`. Are there more instructions somewhere on how to do this?

My app design is based on CSS rules using #root which I should not use inside storybook so I created a preview-body.html file with another div ID and expected storybook to render to it.

**Comment by shilman** [comment]
AFAIK there is no way to render stories in a custom root cc @ndelangen

**Comment by fvilers** [comment]
@shilman Thanks for the answer.

**Comment by ndelangen** [comment]
Indeed there isn't the `#root` is hard-coded, and non-configurable.

Perhaps we should rename the `#root` to something a bit more storybook specific?

**Comment by shilman** [comment]
@ndelangen `#sb-root` as a breaking change for 6.0?

**Comment by ndelangen** [comment]
I could change that @shilman

**Comment by shilman** [comment]
Probably a good idea. @tmeasday any objections from a chromatic / third party standpoint?

**Comment by ndelangen** [comment]
Do we have a list of other integration parties who we should notify of this change upfront?

**Comment by shilman** [comment]
yeah, i can handle that

**Comment by ndelangen** [comment]
I'll open a PR for the change then

**Comment by tmeasday** [comment]
Yeah I guess this is OK, although it will be annoying for integrators I guess.

**Comment by johnmcdowall** [comment]
It's extremely surprising that using the documented 'custom root` file just injects that into the DOM and continues to use an unaltered `div#root`.

I expected that the custom root would be used instead, so that I can put the custom classes I need on that root.

**Comment by Cyclodex** [comment]
I had no issue with the `div#root` itself, but I needed to wrap my Stories into a specific div with a class (eg. `class="v-app"`).
I expected that the `preview-body.html` will help solving this, but as already mentioned by others, its not.

## Workaround
The way @IuliiaBondarieva mentioned [here](https://github.com/storybookjs/storybook/issues/10403#issuecomment-613495278) would also work, I did this temporary for me:

```
// preview.js
document.body.onload = function() {
  document.body.classList.add("v-app");
};
```

## Final Solution: Global decorators
[Documentation](https://storybook.js.org/docs/vue/writing-stories/decorators#global-decorators)
Finally I found out that its probably the cleanest way to simply solve it with a "global decorator":
```
// preview.js
export const decorators = [
  () => ({ template: '<div class="v-app"><story /></div>' }),
];
```
This solves my problem. It took me some time to understand this, so maybe it helps someone else too:

```
// generated storybook html
<div id="root">
  <div class="v-app">
    <button type="button">Button content</button>
  </div>
</div>
```

Maybe it would be good to make this more clear in the documentation?!

**Comment by dejanvasic85** [comment]
Recently started playing around with [Daisy UI](https://daisyui.com/) which requires data attribute on the html element unfortunately to set a theme and decorators just didn't do enough.

```
document.body.onload = function () {
  document.getElementsByTagName('html')[0].setAttribute('data-theme', 'light');
};

```

**Comment by ndelangen** [comment]
preview-body.html is working as designed. It's simply not designed to allow users to replace the full html.

There is an option though pretty advanced usage for this:
`previewMainTemplate`

https://github.com/storybookjs/storybook/blob/647fd6f23e6de62a5e504702c470975e9fdbde08/docs/addons/writing-presets.md#L213
https://storybook.js.org/docs/react/addons/writing-presets#previewmanager-templates

https://github.com/storybookjs/storybook/blob/next/lib/core-common/src/templates/index.ejs

**Comment by shilman** [comment]
Yowza!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.0-alpha.24 containing PR #10638 that references this issue. Upgrade today to the `@future` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

**Comment by 50bbx** [comment]
@ndelangen The link in the docs does not work because they changed the code structure in the `next` branch (Because of the 7.x release, I believe).

 Here's what I think is the 7.x template link: https://github.com/storybookjs/storybook/blob/next/code/lib/core-common/templates/preview.ejs

If you are still on 6.x and you need to get a different template in order to change it, here it is: https://github.com/storybookjs/storybook/blob/v6.5.10/lib/core-common/templates/index.ejs

Since I needed to add a custom element to the end of the page (I am testing a component with a portal), I copied this `.ejs` template in my `.storybook/template.ejs` file and then added my custom html element and added `previewMainTemplate: '.storybook/template.ejs',` to my `.storybook/main.js` config file.

This works for my case, howerver you cannot change the ID of the root element where everything gets rendered. It is just to add a DOM element you can use for a portal

**Comment by PaulieScanlon** [comment]
For anyone still wondering. Something like this seems to work.


```javascript
// .storybook/preview.js

import { DocsContainer } from '@storybook/addon-docs/blocks';

export const parameters = {
  actions: { argTypesRegex: '^on[A-Z].*' },
  controls: {
    matchers: {
      color: /(background|color)$/i,
      date: /Date$/
    }
  },
  docs: {
    container: ({ children, context }) => {
      return (
        <DocsContainer context={context}>
          <div className="some-class">{children}</div>
        </DocsContainer>
      );
    }
  }
};


```

**Comment by jrodriguez-sch** [comment]
I also ended up here in my search, for anyone else in the same boat...

The solution from @Cyclodex worked for me except that when using {template: '...'} as my JSX, I was barked at with
> Objects are not valid as a React child (found: object with keys {template}). If you meant to render a collection of children, use an array instead.

I looked up global decorators (which wasn't something I was originally aware of) and reading [this doc](https://storybook.js.org/docs/react/writing-stories/decorators) led me to change to:

```
// preview.js
import React from 'react'

export const decorators = [
 Story => (<div className="new"><Story /></div>)
]
```

resulted in:
```
<div id="root">
  <div class="new">
    ...
  </div>
</div>
```

**Comment by FirstVertex** [comment]
I discovered that inside your preview-body.html, if you use the id of `storybook-root` it will be used instead of the `storybook-root` generated by system.

Here is the contents of my preview-body.html
```
<ace-styles></ace-styles>
<div id="storybook-root" class="ace-con"></div>
```
Like this I can add my pre-requisite tag of `ace-styles` at the sibling level of story, and add my pre-requisite class of `ace-con` to story container.

It results in a structure of 
```
<body>
<ace-styles></ace-styles>
<div
    id="storybook-root"
    class="ace-con">
<!-- my stories are output here -->
</div>

<div id="storybook-root"></div>
<!-- system generated one stays empty lol -->
```

**Comment by ndelangen** [comment]
@FirstVertex That's not an intended feature and could possibly break in the future.
Just giving you a head's up.

**Comment by ChristianUlbrich** [comment]
@FirstVertex This works, due to the fact, that `querySelector('#storybook-root')` will always return the **first** matching one. This will always work, as long, as Storybook does its insertion via _good olde_ `querySelector` (or similar mechanisms), which I figure will be for a long time. This is prone to a _race condition_, but I think Storybook will always run / compose the stuff in `preview-body.html` first, so to cut a long story short, this will most likely always work, as long as you sync to the _"current"_ `id` of the _root div container_, i.e. for latest Storybook this (seems to be `storybook-root`). For ancient  (6.4) Storybook its `root` (yes, who cares about other applications leveraging the **same** id; guess that's why the _prefixed_ is in later versions).
