### ISSUE TITLE
Angular compiler added in final bundle 

### ISSUE THREAD

**Issue by thomasoreilly** [storybookjs/storybook#10437]
**Is your feature request related to a problem? Please describe.**
I noticed the Angular Complier is being added to the vendor bundle.

**Describe the solution you'd like**
To not include this package as it is large.  

**Describe alternatives you've considered**
Have not explored any.

**Are you able to assist bring the feature to reality?**
Not sure 

**Additional context**
This is more of a question really. Why is this package included in vendor bundle? What module uses it? 
I've been working on a lazy host component using the new Ivy compilation and require the use of the compiler, however I can also lazy load it.

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
