### ISSUE TITLE
Addon-Docs：Custom Props table

### ISSUE THREAD

**Issue by YuunYang** [storybookjs/storybook#10443]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I can pass a parameter to control the props table,
- Pass a array to define which item should we display
- Can use custom item name, like I want to display Chinese `th` like `['姓名', '类型', '默认值','描述']` but not `['name', 'type', 'default', 'description']`

So I want to display `name, type, default, description` when I pass a parameter
```javascipt
[
  {
    key: 'name',
    label: '姓名',
  },
  {
    key: 'type',
    label: '类型',
  },
  {
    key: 'default',
    label: '默认值',
  },
  {
    key: 'description',
    label: '描述',
  }
]
``` 

**Are you able to assist bring the feature to reality?**
![image](https://user-images.githubusercontent.com/15278220/79413421-79209d00-7fda-11ea-8585-488df1206a36.png)

![image](https://user-images.githubusercontent.com/15278220/79413448-85a4f580-7fda-11ea-9854-8f241c2f37a8.png)

https://github.com/storybookjs/storybook/blob/bf1b95564053aacc8d4b00479485beb655ef21b4/lib/components/src/blocks/PropsTable/PropsTable.tsx

Seems it really a feature need to add -_-, I really want to do contribution

**Comment by chenxiaoyao6228** [comment]
Have the same request for this feature !

**Comment by Smolations** [comment]
I think there is a bigger opportunity here. I have some decorator components that largely have the same API as the core component on which they are based, so in order to prevent a lot of boilerplate importing, the decorator components can be used to access (via convenience) common subcomponents:
```js
// components/Dialog/index.js
import Dialog from './Dialog';
import DialogBody from './DialogBody';
import DialogActions from './DialogActions';

import ModalDialog from './ModalDialog';


Dialog.Body = DialogBody;
Dialog.Actions = DialogActions;

ModalDialog.Body = DialogBody;
ModalDialog.Actions = DialogActions;


export {
  Dialog,
  ModalDialog,
};
```

When I add the decorator subcomponents to a story file's default export, the props documentation comes through as expected, which is _**FANTASTIC**_.  e.g.:
```js
export default {
  title: 'Components|Dialog/ModalDialog',
  component: ModalDialog,
  subcomponents: {
    'ModalDialog.Body': ModalDialog.Body, // props table matches DialogBody
    'ModalDialog.Actions': ModalDialog.Actions, // props table matches DialogActions
  },
  // ...
```

However, sometimes I mention the core subcomponent in some of its prop descriptions, and these end up showing for the mapped decorator subcomponents docs (e.g. a prop description for `ModalDialog.Body` includes "DialogBody"). So, in addition to having access to the labels for the props, I'd love to access to the entire props table JSON blob (or whatever form it takes) in order to modify descriptions when appropriate for my use cases. Perhaps this kind of access obviates the need for a property on the default export object, or perhaps just changes what that might be. For instance, it could look something like this:
```js
export default {
  title: 'Components|Dialog/ModalDialog',
  component: ModalDialog,
  subcomponents: {
    'ModalDialog.Body': ModalDialog.Body, // props table matches DialogBody
    'ModalDialog.Actions': ModalDialog.Actions, // props table matches DialogActions
  },
  props: (propTables) => {
    const bodyProps = propTables.find(pTable => pTable.componentName === 'ModalDialog.Body');

    // change a label
    bodyProps.props.someProp.label = 'customPropName';

    // change a description
    bodyProps.props.someProp.description = bodyProps.props.someProp.description.replace('DialogBody', 'ModalDialog.Body');
  },
  // ...
```

I also included an example of how a label could be changed to address the OP's original request. Keep in mind I have no idea about the structure of a "propTables" schema or what any schema types are, but hopefully I got my idea across.  😋

**Comment by shilman** [comment]
@Smolations good news. 6.0 props are super configurable, using a completely different mechanism. Will try to get your use case across when I write that part of the documentation.

**Comment by shilman** [comment]
Semi-documented here for 6.0 here: https://github.com/storybookjs/storybook/blob/next/addons/docs/docs/props-tables.md#customizing-argtypes

**Comment by fgaleano** [comment]
> Semi-documented here for 6.0 here: https://github.com/storybookjs/storybook/blob/next/addons/docs/docs/props-tables.md#customizing-argtypes

@shilman  How can this customizations be applied to subcomponents used in story?

This works great for the main component's props table, but when I have multiple subcomponents with their own props table, I can't figure out how to configure those props tables. I'm talking about this:

```
export default {
    title: 'Header',
    component: Header,
    subcomponents: { 
        Navigation,
        NavigationItem, 
        SecondaryNav: null, 
        SecondaryNavItem: null, 
    },
    parameters: { docs: { description: { component: readme } } },
    args: {
        useSparkPanel: false,
    },
    argTypes: {
        useSparkPanel: {
            table: {
                disable: true
            }
        },
        children: {
            table: {
                type: { 
                    summary: 'instace of <Header.Nav>', 
                    detail: 'Expects instance of <Header.Nav> with collection of <Header.NavItem>.' 
                },
            },
            control: {
                type: null,
            },
        },
        secondaryNav: {
            table: {
                type: { 
                    summary: 'instace of <SecondaryNav>', 
                    detail: 'Expects instance of <Header.SecondaryNav> with collection of <Header.SecondaryNavItem>' 
                },
            },
            control: {
                type: null,
            },
        }
    }
};
```

I need to add some custom `type` values to some of those subcomponents. Can it be done with the current APIs available?

Thanks!
