### ISSUE TITLE
Re-open DevTools failed to load SourceMap

### ISSUE THREAD

**Issue by webberwang** [storybookjs/storybook#10469]
I'd imagine its low priority, functionally doesn't do anything. Just annoying having to see the message in console.log. Could not be related to Storybook

Reopen https://github.com/storybookjs/storybook/issues/9732

> **Describe the bug**
> Warning in console:
> `DevTools failed to load SourceMap: Could not load content for http://localhost:6006/unfetch.mjs.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE`.
> 
> **To Reproduce**
> 
> 1. Starting Storybook
> 
> **Expected behavior**
> No warning.
> 
> **Screenshots**
> If applicable, add screenshots to help explain your problem.
> ![image](https://user-images.githubusercontent.com/3224165/73705610-59930b80-4731-11ea-9683-78c13acef8a9.png)
> 
> **Code snippets**
> this my `webpack.config.js`
> 
> ```js
> const webpack = require('webpack');
> const _ = require('lodash');
> const WebpackNotifierPlugin = require('webpack-notifier');
> const WebpackShellPlugin = require('webpack-shell-plugin');
> const FilterWarningsPlugin = require('webpack-filter-warnings-plugin');
> 
> module.exports = ({ config }) => {
>   config.resolve.extensions.push('.ts', '.tsx', '.js', '.jsx', '.json');
>   config.module.rules.push(
>     {
>       test: /\.tsx?$/,
>       exclude: /node_modules/,
>       use: [
>         {
>           loader: 'babel-loader',
>           options: { cacheDirectory: true }
>         },
>         {
>           loader: 'ts-loader',
>           options: { transpileOnly: true }
>         }
>       ]
>     },
> ```

**Comment by yannbf** [comment]
Hey @webberwang, thanks for opening this issue! From what I understand this seems to be a [bug on chromium](https://bugs.chromium.org/p/chromium/issues/detail?id=1052872) which affects libraries that point to source maps. This would affect some chrome extensions too. 

This issue has been happening since february (which is when #9732 was opened), and they are planning to fix it most likely in their next release, version 82.

Now I know the issue is annoying, but doesn't seem to be related to storybook. If you want to supress it for now, you can tick `Selected context only` in your dev tools:

![image](https://user-images.githubusercontent.com/1671563/79696579-b8bae380-827d-11ea-86cf-e36e4ac80b54.png)

**Comment by wakilsarfaraz** [comment]
Hi all,
I am a new learner in using django for dynamic web development. I came across this error in the inspection->console of google chrome upon adopting an open-source web template.

DevTools failed to load SourceMap: Could not load content for http://127.0.0.1:8000/static/styles/bootstrap4/bootstrap.min.css.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

Any help would be much appreciated!

**Comment by Sielik** [comment]
It is chrome or some extension bug. In my case I had to disable the lastPass extension to remove the error. Others say that addBlock make the problem. You may find some more information here:
https://superuser.com/questions/1523427/google-chrome-devtools-failed-to-parse-sourcemap-chrome-extension/1524565#1524565

**Comment by rantjobs** [comment]
i have a wordpress website using amp and DevTools failed to load SourceMap too

insidenobs.com

**Comment by Soundharya19** [comment]
Wakal,I also face the same issue.If you find or have any solution please help with that.

**Comment by TamasFelix** [comment]
Hello, i have the same issue
DevTools failed to load SourceMap: Could not load content for /modules/revws/views/js/front-1_1_0.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for /themes/core.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
[https://www.kiwigym.ro/sanatate-incheieturi/universal-nutrition-animal-flex-44plicuri](https://www.kiwigym.ro/sanatate-incheieturi/universal-nutrition-animal-flex-44plicuri)
![similar-kiwigym-min](https://user-images.githubusercontent.com/50567469/99867682-3522f580-2bc4-11eb-80a6-3505116da1a6.jpg)
Did I found the solution?
Thanks

**Comment by ctd629** [comment]
Is this an issue that only shows up during development?

**Comment by D1no** [comment]
This is constantly in my console in storybook while developing
![image](https://user-images.githubusercontent.com/2397125/158029620-6948899f-d349-4d14-97ae-e129354a34f6.png)

**Comment by yannbf** [comment]
> This is constantly in my console in storybook while developing
> ![image](https://user-images.githubusercontent.com/2397125/158029620-6948899f-d349-4d14-97ae-e129354a34f6.png)

@kylegach I think this might be related to the component library! Could you check?

**Comment by xemlock** [comment]
It looks like it's caused by some kind of misconfiguration in the storybook webpack pipeline. I've examined generated `vendors-node_modules_*.bundle.js` files, and found in many of them multiple `//# sourceMappingURL=` comments, which come from included files. I believe each bundle should have only one sourcemap comment, at the bottom of the file - all other such comments should be removed.

I'm using storybook@6.4.22, builder-webpack5@6.4.22, manager-webpack5@6.4.22 and preset-create-react-app@4.1.0

**Comment by xdebbie** [comment]
Any news from that? Still having this issue on @storybook/react: ^6.5.9
