### ISSUE TITLE
Storybook for Angular page describes incorrect configuration

### ISSUE THREAD

**Issue by egorpavlikhin** [storybookjs/storybook#10472]
Link: https://storybook.js.org/docs/guides/guide-angular/#step-5-write-your-stories
Step 5 lists code that is valid (as in it will run), but ultimately incorrect for Angular projects. The proper syntax is listed in this demo https://storybookjs.netlify.app/angular-cli/?path=/story/addon-background--background-component and this allows for usual angular component syntax.

**Comment by shilman** [comment]
@egorpavlikhin any chance you can submit a PR with the fix?

**Comment by matheo** [comment]
@egorpavlikhin  I just reviewed https://storybook.js.org/docs/guides/guide-angular/#step-5-write-your-stories and I see nothing wrong with theCSF example there. Maybe there's a confusion because the old `storiesOf` API is not updated to CSF on the `angular-cli` examples. You can pass custom Angular Components in CSF too, and Button seems to be a valid one:
```
import { Button } from '@storybook/angular/demo';
```

@shilman I guess that this one can be closed :)
