### ISSUE TITLE
Unexpected automatic 'dark mode' in latest chrome? (Version 84.0.4124.1 (Official Build) canary (64-bit))

### ISSUE THREAD

**Issue by rbutera** [storybookjs/storybook#10542]
I'm using Storybook on the latest chrome canary (Version 84.0.4124.1 (Official Build) canary (64-bit)) with no dark-mode addon installed.

For some reason storybook in this browser is dark, whereas in Brave and in regular Chrome it's light?

(To be clear, I want it to be light in all browsers).

Why might this be happening?

**Screenshots**
![image](https://user-images.githubusercontent.com/6047293/80234384-fccc3080-864f-11ea-814d-0852bfefda65.png)

**Comment by yannbf** [comment]
Hey @rbutera, thanks for opening this issue. Can you, just in case, try it on incognito mode and see if it's still dark? Also, is there any chance you might have [storybook-dark-mode](https://github.com/hipstersmoothie/storybook-dark-mode) in your project?

Lastly, could you please run the following command and paste the output here? `npx -p @storybook/cli@next sb info`

**Comment by rbutera** [comment]
@yannbf I don't have storybook-dark-mode in my project, no.

here is my environment info:

```shell
Environment Info:

  System:
    OS: macOS 10.15.4
    CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
  Binaries:
    Node: 13.13.0 - ~/.nvm/versions/node/v13.13.0/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.4 - ~/.nvm/versions/node/v13.13.0/bin/npm
  Browsers:
    Chrome: 81.0.4044.122
    Firefox: 57.0.4
    Safari: 13.1
  npmPackages:
    @storybook/addon-actions: ^5.3.18 => 5.3.18
    @storybook/addon-knobs: ^5.3.17 => 5.3.18
    @storybook/addon-links: ^5.3.18 => 5.3.18
    @storybook/addon-storyshots: ^5.3.17 => 5.3.18
    @storybook/addons: ^5.3.18 => 5.3.18
    @storybook/react: ^5.3.18 => 5.3.18

```

on Chrome 81 I don't have this issue. It's only on chrome canary (version 84)

I was about to write "I haven't tried incognito mode but I doubt that's the issue" but I've just tried it and weirdly it's in light mode!?

Is there a native dark mode toggle in storybook?

**Comment by yannbf** [comment]
@rbutera thanks for taking the effort to give more information! Well, Storybook does have a dark theme, however I am not sure about a toggle option. @shilman thoughts?

**Comment by shilman** [comment]
Before 6.0, themes were set in `.storybook/preview.js` using parameters. For performance reasons, we cached the themes in `localStorage`. Because of this, if you ran a Storybook on a specific port with a dark theme, and then ran a Storybook with NO theme on the same port, the second Storybook would also show up with the dark theme.

Starting in 6.0, themes are uncached and there is a different API for setting them in `.storybook/manager.js`, so this edge case problem should go away.

**Comment by syropian** [comment]
Hi, I noticed the same thing happening as well, using the Brave browser. We aren't using any kind of dark mode plugin, but when I change my _browser appearance_, Storybook seems to change its own appearance on refresh as well. Is there any way to disable this?

**Comment by shilman** [comment]
OK I'm wrong. Looks like Storybook is color scheme aware: https://github.com/storybookjs/storybook/pull/8271

What's the desired behavior on this?

**Comment by rbutera** [comment]
Color scheme awareness is cool, but it should be able to be overridden as a toggle in the menu IMO.

As a user this feature is useful to be able to develop both light and dark themes but without the ability to toggle this on and off it's a little invasive

**Comment by yannbf** [comment]
@rbutera I agree it's nice to be able to toggle the theme while using storybook, but you're aware that the dark mode we are talking about is for Storybook and not the components you have built, right? 
If you wanted to toggle theme for the components you're developing, that would depend on your implementation.

**Comment by rbutera** [comment]
If it was unclear: yes I am aware. 

As Storybook is for both developers and designers (and everybody in between), it is often used by the former as a blank 'canvas' for component design.

I'm just saying that for this reason it is useful to have a light or dark backdrop that is aligned with the color of the browser's theme. 

My initial thoughts when running into this 'bug' were "cool! this will be so useful when designing for dark mode! But right now I'm designing the light mode theme and I can't see my form input labels 😨

**Comment by yannbf** [comment]
Hey @shilman what do you think should be the next steps here?
Should the Preview not have its styles influenced by Storybook theme, but rather by the users custom css/addon backgrounds if they want to?

Current version (you can picture the issue mentioned above):
![image](https://user-images.githubusercontent.com/1671563/82118327-dbee8b00-9776-11ea-849d-d60e7699d8a1.png)

Version where preview keeps a light background unless changed via addon-backgrounds:
![image](https://user-images.githubusercontent.com/1671563/82118341-0e988380-9777-11ea-9253-1d2d1e8fd552.png)

**Comment by shilman** [comment]
If we install addon-backgrounds by default in 6.0 as part of essentials, does this problem go away? @yannbf

**Comment by yannbf** [comment]
Only partially, because it would require the users to use addon-backgrounds to just to be able to see their components which should be an easy experience out of the box IMHO. It would also only affect people who are either starting a new SB or using addon-essentials already, rather than everyone using storybook.

I'd say it's better to have it the other way around, where you don't have the styles applied by default, and a starter would come with light/dark backgrounds (where the values would match the storybook theme) to show that it's possible to change the background to set their themes.

Would be nice to have more points of view on this. Maybe let's check on the discord community (and if someone is reading this please chime in in the discussion!)

**Comment by rbutera** [comment]
Can we not just have a toggle in the menu for this behaviour?

**Comment by shilman** [comment]
@yannbf starting in 6.0 we will be installing essentials by default. that means users won't need to do anything to get backgrounds, they'll just be there. i don't mind fixing this issue in another way (config option?), but generally if we can address the issue with near-term product improvements we should be focusing on those, rather than increasing complexity to handle corner cases.

**Comment by steffchep** [comment]
I have this issue too, as of today, in latest Firefox (Was working fine before (I assume) an update to the latest version of either Browser or storybook

No Windows dark mode enabled, no dark-mode addon installed. It's storybook 6.4.8 (but I also get an info telling me the latest version of storybook couldn't be fetched)

It is also dark if I use a private window, and I've tried deleting cookies and localstorage as well

**Comment by drcobel** [comment]
We're running SB 6.5.9 and we still experience the issue. It should be a way to avoid Storybook changing the background of your documents based on the dark/light mode 
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/56694561/179825262-5044c979-63e9-4923-a653-78d9c05d2f2b.png">
