### ISSUE TITLE
Cannot change output dir for builld-storybook

### ISSUE THREAD

**Issue by Adam-Michalski** [storybookjs/storybook#10570]
**Description**
Running `build-storybook` with `--output-dir` variable does not change output directory it is always `./storybook-static`
As described in [CLI options for build-storybook](https://storybook.js.org/docs/configurations/cli-options/#for-build-storybook)

**To Reproduce**

Build any project with  
`npm run build-storybook -o dist\storybook`
or
`npm run build-storybook --output-dir dist\storybook`

message after build
`info => Output directory: ../my-project\storybook-static`

**Comment by yannbf** [comment]
Hey @Adam-Michalski, thanks for opening this issue!
**Short answer:**
You're passing dynamic arguments in a wrong way. Also you should use forward slash for the directory.
This solves your issue: `npm run build-storybook -- -o dist/storybook`

**Long answer:**
If you have in your `package.json` a script like `"build-storybook": "build-storybook -s public"`, you can change that script to directly set the output dir:
`"build-storybook": "build-storybook -s public -o dist/storybook"` in case you always want to have the build in that directory. 
This way you just need to run `npm run build-storybook`!

If you want something more dynamic, then you need to pass the output as arguments, like you showed in the issue. 
However the api for running scripts is as follows: `npm run [command] [-- <args>]`

In order to pass extra arguments to the script, you need to append them by passing `--` first, like `npm run build-storybook -- -o dist/storybook`.

I hope this helps!

**Comment by Jakobud** [comment]
Would be good to add this to the documentation for those using `npm` instead of `yarn`. I know yarn is better but in some cases a developer is locked into using npm in order to be consistent with their development team and standardized workflow.

**Comment by JoseLLamasT** [comment]
i am using 
angular": "14.3.0
storybook/angular": "7.3.2"

i could solve this issue in angular.json in adding.

"build-storybook": {
 "options": {
 "outputDir": "where you want to save all",
 }
}
![image](https://github.com/storybookjs/storybook/assets/69245960/a762b867-e6b5-4886-97e0-1881a3ff9998)

**Comment by EliezerB123** [comment]
I am using 
Angular: ^15.2.9
Storybook: 7.3.2

While @JoseLLamasT 's solution of modifying **angular.json** works perfectly, if you want to run this from the **command line** (We needed to for our CI/CD pipeline), you can run:

`ng run myProject:build-storybook --output-dir nameOfDirectory`
