### ISSUE TITLE
Unable to build storybook, "command not found"

### ISSUE THREAD

**Issue by ml-tsai** [storybookjs/storybook#10682]
I have an issue when i try to build my storybook. It will always return "command not found". 
Can anyone advise or help?

**Comment by yannbf** [comment]
Hey @ml-tsai, could you provide us a bit more information? What command are you trying to run exactly? Are you running that command in the same place of your `package.json`? Does it contain a script like `"build-storybook": "build-storybook -s public"`?

**Comment by ml-tsai** [comment]
Hi @yannbf, I just type "build-storybook" in terminal and it returns "command not found".
This is my first time trying, not good with command prompt.

Below is my package.json
![Screenshot 2020-05-11 at 09 20 53](https://user-images.githubusercontent.com/702772/81515923-b9203900-9368-11ea-870e-1c45c7430c5a.png)

**Comment by yannbf** [comment]
@ml-tsai thanks for the additional info! Also nice that you're trying out the command prompt!

So "build-storybook" is actually just the name of the npm script, but in order to run it you need to first open the terminal at the root folder of your project (where package.json is located) and do either:
1 - `npm run build-storybook` if you're using npm
2 - `yarn build-storybook` if you're using yarn

if you want to learn more about npm scripts, there is a really nice article about it [here](https://blog.jayway.com/2014/03/28/running-scripts-with-npm/).

Please let me know if this fixes your issue!

**Comment by ml-tsai** [comment]
@yannbf you da man!!
I finally got it to build storybook. Am using the npm command.

Cheers man, really appreciate the help.

**Comment by yannbf** [comment]
Hey @ml-tsai great that it's working! I'm happy to help.
Now if you don't mind I will be closing this issue as it has been solved.

Enjoy Storybook!
