### ISSUE TITLE
Support multiple canvases with Toolbar / Global Args

### ISSUE THREAD

**Issue by kenpowers-signal** [storybookjs/storybook#10767]
**Is your feature request related to a problem? Please describe.**

As discussed in [the RFC Doc](https://docs.google.com/document/d/1Mhp1UFRCKCsN8pjlfPdz8ZdisgjNXeMXpXvGoALjxYM/edit#), at Signal we have a Storybook setup with a global decorator that sets up knobs so we can render the same story in multiple contexts (themes, modes, etc) side-by-side. See the following screenshot:

![image](https://user-images.githubusercontent.com/49649953/81848483-2ed00480-9523-11ea-9e86-243d5aa224fb.png)

**Describe the solution you'd like**

It would be nice to support this as a native feature of toolbars / global args in Storybook 6.

**Comment by ndelangen** [comment]
I had the same idea at some point:
https://next--storybookjs.netlify.app/official-storybook/?path=/story/basics-colorpalette--page

We could do this in a few ways:

- a new viewMode that shows all stories (in a grid)
  each story has it's own context/wrapper

- a decorator that displays the story multiple times (in a grid)

- a parameter like `layout` that automatically adds a the decorator

I'm leaning towards a decorator, since it requires some setup (what context to wrap the story with).

We also have to answer this question:

When displaying the stories in a grid, is it OK to do that in 1 frame? Or would we have to have each story rendered in it's own iframe?

I'm leaning towards, yes that's probably fine for 99%.
