### ISSUE TITLE
addon-docs Prop Table versioned React components 'No props found for this component'

### ISSUE THREAD

**Issue by christinec01** [storybookjs/storybook#10771]
If you are reporting a bug or requesting support, start here:
### Bug or support request summary

Following the Storybook setup instructions for adding Docs to my Storybook project which uses React components. After adding `'@storybook/addon-docs'` to my main.js file, and ensuring that my component field is correct 
```
import { Radio } from './radio/radio';

export default {
  title: 'Controls|Radio',
  component: Radio,
};
```
The Docs tab loads and the component renders, however the props table and code snippet are unavailable. 

![image](https://user-images.githubusercontent.com/16041595/81860961-5cfe1600-951c-11ea-9b48-a5f5b27c5e49.png)

### Steps to reproduce

This is a private repo so STR is difficult, but I'm not using anything 'custom' outside of the standard set up outlined in the addon-docs instructions. 

### Please specify which version of Storybook and optionally any affected addons that you're running

- @storybook/react 5.3.8
- @storybook/addon-something 5.3.18

Thanks and please let me know if I need to provide any further detail!

**Comment by shilman** [comment]
- Does `Radio.__docgenInfo` exist?
- Is your component written in Typescript or PropTypes?
- Are you using a custom webpack setup? Custom babel setup?

**Comment by christinec01** [comment]
Thanks for the fast reply! 

* `Radio.__docgenInfo` does not exist
* My component is written in React with PropTypes and is published, then imported into the App running Storybook
* I am using some custom Webpack configuration and babel setup - comparing the output of my project's webpack config with what I see in the Storybook docs, one difference is the loader used. My project is using `babel-loader-8`, is there a requirement for a different babel version?

I can't really recreate with the template you provided because of the privacy issue, however, I can share the output `--debug-webpack` if that would help?

**Comment by christinec01** [comment]
Update: I was reading through [this thread ](https://github.com/storybookjs/storybook/issues/9415) and thought perhaps my issue might be related - I downgraded my project's version of `@storybook/addon-docs` to v5.2.0 and am now seeing a props table with prop data, so I imagine adding `babel-plugin-react-docgen` as a dev dependency and adding `react-docgen` to my `babel-loader` should do the trick, however, my code snippet preview is still missing (though this may warrant a separate issue)

![Screen Shot 2020-05-18 at 5 44 05 PM](https://user-images.githubusercontent.com/16041595/82272348-34688880-992f-11ea-9e32-125118b4ba7d.png)

Out of curiosity, why wasn't the removal of the fallback code path justification for a breaking change in the storybook/addon-docs package?

**Comment by shilman** [comment]
@christinec01 currently props tables only work for components defined in your app/library. by the time the components are published to NPM, most the useful information has been stripped out. it's an important use case, so we'll need to figure it out, but for now we're just getting all the basics working smoothly.

Re: the breaking change, we release version all core packages in sync, and we typically make one major release per year in an attempt to minimize disruption to our users. Storybook is a complex system with hundreds of contributors, so sometimes small breaking changes slip through the cracks. In this particular case, we felt that the fallback code was typically masking user babel/webpack configuration problems and adding more confusion / support burden. It partially enables your use case of props tables for "external libraries", which I don't think we considered in the decision because we don't officially support that.
