### ISSUE TITLE
CLI: colocate example components together with generated stories

### ISSUE THREAD

**Issue by yannbf** [storybookjs/storybook#10793]
### Work summary
Currently some frameworks have colocated components along with the stories like [Vue](https://github.com/storybookjs/storybook/tree/next/lib/cli/src/generators/VUE/template-csf/stories), and others use demo components like [React](https://github.com/storybookjs/storybook/blob/next/lib/cli/src/generators/REACT/template-csf/stories/0-Welcome.stories.js#L3). We need standardize all frameworks and ship components with the stories. 

By doing so:
- Props tables will work out of the box, which is super important.
- Stories and components will be colocated per our recommendations.
- It will also make tutorials easier because we can ask users to edit the added components.

This work is part of #10723

### Where to start

Demo components are located under [app](https://github.com/storybookjs/storybook/blob/next/app/) then `<framework>/src/demo`
Usage of the components is in the templates under [generators](https://github.com/storybookjs/storybook/tree/next/lib/cli/src/generators).

@ndelangen @shilman please elaborate more in this issue about what to do, like either adding the missing demo components and then copying them over to the folders in the CLI step, or some other solution. 

### Acceptance criteria

- [ ] CLI tests are passing
- [ ] E2E tests are passing
- [ ] Changes are properly reviewed by some of the members mentioned below

### Who to contact

@shilman @ndelangen @tooppaaa @gaetanmaisse @yannbf

**Comment by tooppaaa** [comment]
I started to copy the Welcome component in src/Welcome.tsx (or jsx where ts is not set).
When I was almost done, I realize there are lots of reference to `import { Welcome } from '@storybook/react/demo';`

It would also mean duplicating this component in react, cra, webpack react, for each one, csf, mdf, csf-ts.
React is obviously the worst case but my option would be to leave it in demo and copy it from a beautiful path
`../../../../../app/<framework>/src/demo/welcome.(j|t)sx` with a unit test that asserts from cli, the existence of a file outside the project. 

Now jsx, or tsx, I'm assuming we do all of this to get a nice demo of the props table so tsx only ?

**Comment by shilman** [comment]
@tooppaaa Sounds ok to me. Alternatively, we could create a `FRAMEWORKS` directory inside the CLI to make everything more self-contained?

As far as JSX vs TSX, ideally this would be based on which template the user is using (JS template => JSX, TS => TSX)? 

This is maybe late to suggest it, but what do you think of a template scheme that `fetch`es the templates from a network location, so we can keep adding more templates and more stuff to the templates without blowing up the size of the `@storybook/cli`?

**Comment by tooppaaa** [comment]
Just realizing that ../../../app/* won't exists on user's machine. I'll go for Frameworks inside cli.
I think the idea of fetching templates from network is also one of @yannbf idea and surely something we can do in a second step.

We might be able to track in a different repo examples generated by e2e script and reuse these examples as templates !

**Comment by tooppaaa** [comment]
Let's discuss the approach from the WIP PR before spending time on other frameworks !

**Comment by tooppaaa** [comment]
While working on this I found that I'm not sure where to go. What would be the target for all framework ?

Here's a suggestion of post-init:

![image](https://user-images.githubusercontent.com/599163/82810970-008de580-9e90-11ea-9513-2ab77d7ac7f9.png)

## < framework >/ts OR < framework >/js OR < framework >

We can define components & stories per language. With the following logic:
if /ts exists, use it. otherwise if /js exists, use it, otherwise if framework folder exists, use it, otherwise, throw.

## cross-framework stories

The Welcome story is a perfect example of a mdx page. we can write it once and copy all from /cross-framework folder to user's folder

## mdx format

Because we'll use essentials, this can be removed for free.
With the cross-framework stories that are MDX, will have docs demo.
The purpose of 3-Text.stories.mdx is to demonstrate that we can include stories in mdx
`<Story id="2-text--demo" />` 

## src or not src

If src folder exists, copy story folder into it. Otherwise copy into root folder.

## CLI architecture

The above to me leads to a CLI folder structure like:

- cli
  - src
    - frameworks
      - < framework >
        - js 
          - (same as bellow)
        - ts
          - 1-Button.stories.tsx
          - 2-Text.stories.tsx
          - Button.tsx
          - Text.tsx
    - cross-framework
      - 0-Welcome.stories.mdx
      - 3-Text.stories.mdx
    - generators
      - < GENERATOR >
          - .storybook
            - extra files but main.js
          - index.ts


index.ts would include a generateConfig method to create one main.js when it can be shared except when it's customized (like WEB_COMPONENTS)

**Comment by shilman** [comment]
@tooppaaa This sounds totally reasonable to me!! ❤️

**Comment by ndelangen** [comment]
Yeah this sounds good to me too!

**Comment by shilman** [comment]
fixed in https://github.com/storybookjs/storybook/pull/11136
