### ISSUE TITLE
Core: Refactor RENDER_CURRENT_STORY event

### ISSUE THREAD

**Issue by shilman** [storybookjs/storybook#10893]
When stories finish loading (prior to #10892) the StoryStore sent a `RENDER_CURRENT_STORY` event. This deserves a refactor:

- User code / addons can send `command` events
- `StoryStore` shouldn't send _command_ events, only _response_ events (past tense)
- `StoryRenderer` should interpret those _response_ events to figure out when to re-render

**Comment by tmeasday** [comment]
Plan here:

 - drop `RENDER_CURRENT_STORY` event
 - listen to `CURRENT_STORY_WAS_SET` event in StoryRenderer
 - think about whether we should set initial global args over with the `SET_STORIES` event

**Comment by tmeasday** [comment]
Note part of the problem here is that when you update global args we *force re-render* which bypasses the checks that would otherwise had not made this a problem.

**Comment by tmeasday** [comment]
This is good but less pressing after https://github.com/storybookjs/storybook/pull/10910

**Comment by tmeasday** [comment]
The complication is that the `StoryRenderer` should really wait until the store has finished configuring, which is kind of internal state for the store. I feel unsure we should do this after all.

**Comment by tmeasday** [comment]
OK, I ended up doing this as a part of #10910 -https://github.com/storybookjs/storybook/pull/10910/commits/8c5ef6b39111d5a3706b5ba313bebf5d48c32cd1

**Comment by shilman** [comment]
w00t!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.0.0-beta.18 containing PR #10910 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.

**Comment by tmeasday** [comment]
OK, I didn't address in that PR in the end, as I wanted to simplify it. Here's where we stand on this.

There are three areas of concern that need to be resolved:

1. The confusion about imperative vs declarative events in the preview -- should the story tell the renderer `RENDER_CURRENT_STORY` (after consulting it's own state) or should the renderer listen for `CURRENT_STORY_WAS_SET`, and then choose to render based on its own state and possibly the store's state (which it can query).

2. Support for the old `storyName=X` URL scheme in the preview (https://github.com/storybookjs/storybook/issues/10960) means that the preview doesn't set its selection until the `SET_STORIES` event fires, even if it has been loaded with `id=X` in the URL.

3. The manager currently hides the preview window until the `SET_STORIES` event fires, which has two problems:
  a. As per 2. the story may not have yet rendered at this point (the preview has to run it's own event handler for that event). Probably that event handler would run first, but this seems a big dodgy.
  b. When the SB is loaded with no story selected, the manager also waits for `SET_STORIES` to set an initial selection. In this case the story *definitely* hasn't been rendered, and you get a "flash of no preview" (FONP): https://www.loom.com/share/1102766b73764f969c61eba6e7bcb50c

If you unpack it a bit there are two related problems here:

A. How to coordinate the preview to display the right thing while it waits for the story data to load and the selection to be set?

B. How to ensure the manager shows a spinner until the preview has reached its "end state"?

A proposal to solve B. would be be to change 3. above so instead the manager waits for the events related to stories rendering (or failing to render), namely: `STORY_RENDERED`, `DOCS_RENDERED`, `STORY_ERRORED`, `STORY_THREW_EXCEPTION`, `STORY_MISSING`. [1]

However, that would rely on A. being resolved in such a way that exactly *one* of each of the above events is triggered in all cases. I think the following cases are important:

Case|User URL | Preview URL |  Seq. of events
-----|----------|--------------|---------------
i.| `/`            | `id=*`            | 1. preview:`SET_STORIES` 2. mgr: `SELECT_STORY` => preview: `CURRENT_STORY_WAS_SET`
ii. |`/path=..`| `id=abc--xyz| 1. preview: `CURRENT_STORY_WAS_SET` 2. preview `SET_STORIES` [2]
iii. | '/iframe.html`| 👈 (no id) | 1. preview:`SET_STORIES` [that's it]

The tricky part is rendering "no story selected" in case iii. without doing the same in cases i. or ii.

My proposal here, which I think works, is for the story renderer to do the following:
  - Wait for `SET_STORIES` or `CURRENT_STORY_WAS SET`, and conditionally render
  - If the store is configuring, don't do anything (this handles case ii.)
  - If the selection is "*", don't do anything (this handles case i.)  -- basically this tells the preview "wait for the manager to make a selection". [3]

In case iii. we'll fall through both those guards and hit the `STORY_MISSING` / no selection case.

[1] Another option would not to show the spinner in the manager but instead show it in the preview? Still we would to solve A to avoid double rendering.
[2] This assumes we do https://github.com/storybookjs/storybook/issues/10960, as things stand it is actually the other way around.
[3] Note this means if you manually load up `/iframe.html?id=*` it'll spin forever, which I think is OK.

**Comment by ndelangen** [comment]
Regarding moving the spinner to the preview:

It makes sense in some ways, but not in others.

**It makes sense because**:
- the preview knows best what it's doing
- no need to communicate this precise state

**It doesn't make sense**:
- it breaks the convention of "render as few as possible into the preview"
- scaling / zooming might mess it up (could be fixed)
- might not make sense with viewports & backgrounds etc.

Do we want a smarter or dumber preview application is really the question here.

**Here's my proposal**:

Case|User URL | Preview URL |  Seq. of events
-----|----------|--------------|---------------
i.| `/`            | `id=*`            | 1. preview:`SET_STORIES` 2. preview: `CURRENT_STORY_WAS_SET`
ii. |`/path=..`| `id=abc--xyz`| 1. preview:`SET_STORIES` 2. preview: `CURRENT_STORY_WAS_SET`
iii. | `/iframe.html`| 👈 (no id) | 1. preview:`SET_STORIES` [that's it]
iv. | `/iframe.html?id=id=abc--xyz`| `id=abc--xyz` | 1. preview:`SET_STORIES` 2. preview: `CURRENT_STORY_WAS_SET`

The big change here is that if id=* we assume the first possible story should be rendered.
This is how it works in the manager, right now. We'd be making the rendering quite a bit faster and solving the FONP

**Another suggestion**:
If the preview receives no story selection id at all, we render a "no stories were selected" message instead of the "story is missing"

**Comment by tmeasday** [comment]
@ndelangen OK, good points.

1. I think you are correct that we should keep the spinner in the manager. So the manager needs to know when to hide the spinner, ie when the first story has "rendered" (or failed to render etc).

2. I also agree the best way to achieve that is for the preview to consistently emit the `CURRENT_STORY_WAS_SET` event when it is time to render (in fact this can be the equivalent of `RENDER_CURRENT_STORY` now).

3. I also agree that it feels a bit simpler for the story_store to allow the selection to be `'*'` and to simply select the first story it sees in that case.[1]

[1] In theory it could even do this immediately when `.addStory()` is called, rather than waiting for configuration to end and `SET_STORIES` to be triggered, although my instinct is that is asking for trouble.

---

So with that in mind, the proposal would be:

1. In the story store, at configuration end, right after emitting `SET_STORIES`, select the story selected in the URL and emit `CURRENT_STORY_WAS_SET`:
  a. in case i. select the first story in the store
  b. in case ii. select `abc-xyz`
  c. in case iii. select nothing but still emit `CURRENT_STORY_WAS_SET`
  d. case iv. is the same as case ii. from the preview's pespective.

This will mean we don't actually have to do https://github.com/storybookjs/storybook/issues/10960 and I think maybe we just deprecate it.

2. The manager shows the preview on `CURRENT_STORY_WAS_SET` (it could keep using `SET_STORIES` if that's hard to change).

3. The manager no longer chooses the first story on `SET_STORIES` if none is selected.

4. The manager changes the selection in its own store when `CURRENT_STORY_WAS_SET` fires (keeping in mind most of the time it'll be in response to `SET_CURRENT_STORY` which is triggered from a selection in the manager).

**Comment by ndelangen** [comment]
Yes, That seems 💯 to me!

**Comment by tmeasday** [comment]
OK I’ll give it a go in the next few days.

**Comment by shilman** [comment]
Son of a gun!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.0.0-beta.33 containing PR #11080 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.
