### ISSUE TITLE
Angular Not Compiling Correctly:  False Terminal Warning and Error with Class-Validator Package

### ISSUE THREAD

**Issue by tommyc38** [storybookjs/storybook#11309]
**Describe the bug**
Storybook is not compiling correctly in Angular.  Throws false warnings (https://github.com/webpack/webpack/issues/7378) and does not work with class-validator in a mono repo, both very popular.  

**To Reproduce**
https://github.com/tommyc38/nest-pipe-repro

The README has all of the instructions.  Should be pretty easy and straight forward.

**Expected behavior**

If you follow my repro, you will see Angular running without issues side by side Storybook. I would expect the same results in Storybook.

**Comment by Marklb** [comment]
@tommyc38 I tried your repro and once I saw the output log, I recognized it as one I used to spend hours trying to figure out. I don't think it has anything to do with Storybook though. I mainly got the warnings when building an Angular library.

Now that Typescript has `import type {} from ''`, is there a reason you wouldn't use that, because importing only types is what you are doing. I saw you mentioned that would stop the warnings, but didn't mention why you wouldn't do it that way.

The following is what I started doing that seems to have kept me from seeing these warning for a while:

I always keep things that can be stripped out during compilation, such as exported `interface`, `type`, or `enum`, out of any file that also exports something that can be stripped out, such as `class` or `const`. In your repro, the file `libs/api-interfaces/src/lib/text/text.ts` exports a `const`, which is causing the compiler to strip out the `type` and `interface` exports early. (I don't know why, but have seen many issues about it, but now that Typescript has `import type {} from ''` that is probably the recommended solution I would think.) If you move that `const` export to it's own file(ex. `libs/api-interfaces/src/lib/text/media-extensions.ts`) and export it from your barrel file(`libs/api-interfaces/src/lib/text/index.ts`), then the warning should go away.

There are multiple workarounds I have found, but splitting the files, like I mentioned above, is the only thing I found that didn't seem like a hack. One example is making each of those types, giving the warning, a union of themselves when used. For example, on line 19 in `libs/shared-ui/src/lib/trans/trans.component.ts` you can change it to `_status: Status | Status = 'waiting';` and the warning will go away, but it isn't a solution I would consider actually doing.
