### ISSUE TITLE
The `@storybook/addon-knobs` addon package, contains `@types/react-color` as a dependency.

### ISSUE THREAD

**Issue by psimk** [storybookjs/storybook#11315]
**Describe the bug**
The `@storybook/addon-knobs` addon package, contains `@types/react-color` as a dependency.

Disregarding the fact that JS users will see no benefit from this additional dependency. I encountered a TS error due to it's inclusion. The dependency creates a conflict between  `@types/react-color`'s `@types/react` and the `@types/react` of my project. I am assuming that TypeScript has no idea how to handle duplicate typings and thus throws an error for every type in `@types/react` (see screenshot) marking that it's _duplicated_.

**Expected behavior**
 `@types/react-color` should not be a dependency of `@storybook/addon-knobs`, if it is indeed required it should be a devDependency.

**Screenshots**
![image](https://user-images.githubusercontent.com/21334130/85744059-421ee400-b70d-11ea-9ada-05595840662c.png)

**System:**
![image](https://user-images.githubusercontent.com/21334130/85744123-4fd46980-b70d-11ea-8ff4-e7a31296298e.png)

**Comment by shilman** [comment]
@gaetanmaisse @ndelangen can somebody summarize why we chose to include these things as dependencies rather than devDependencies?

**Comment by gaetanmaisse** [comment]
These types are used (only a few of them) to type parameter of the `handleChange` function in [Color.tsx](https://github.com/storybookjs/storybook/blob/master/addons/knobs/src/components/types/Color.tsx#L106). When TypeScript is transpiled and declaration files emitted, we end up with `Color.d.ts` containing:

```ts
import { ColorResult } from 'react-color';
...
    handleChange: (color: ColorResult) => void;
...
```

So types from `@storybook/addon-knob` are depending on the one from `@types/react-color`, that's why we need the latter to be regular deps instead of devDeps (otherwise TSC complains about missing dependency when it tries to use `Color.d.ts`).

However, I agree with you @psimk this is not great to have one more dep only for 1 type. And it looks like `handleChange` and `handleClick` should be private functions as they are used to handle internal stuff. Making it `private` will lead to the following `Color.d.ts`:

```ts
...
    private handleChange;
...
```

No type imported from `@types/react-color` and so we can move it to devDep 🎉 . 

@ndelangen can you take a quick look to double-check my suggestion to make `handleChange` private?

**Comment by shilman** [comment]
FYI, we’ve released addon-controls in 6.0-beta. Controls are portable, auto-generated knobs that are intended to replace addon-knobs long term.

- [Controls README](https://github.com/storybookjs/storybook/tree/next/addons/controls)
- [Migration instructions](https://github.com/storybookjs/storybook/blob/next/addons/controls/README.md#how-do-i-migrate-from-addon-knobs)
- [Walkthrough: Controls w/ CRA & TypeScript](https://gist.github.com/shilman/69c1dd41a466bae137cc88bd2c6ef487)

Please upgrade and try them out today!

**Comment by ndelangen** [comment]
@gaetanmaisse that looks 💯 to me!

**Comment by shilman** [comment]
Boo-yah!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.0.0-rc.15 containing PR #11690 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.
