### ISSUE TITLE
Addon-docs : Wrap the story blocks in iframes

### ISSUE THREAD

**Issue by TomPradat** [storybookjs/storybook#11328]
**Is your feature request related to a problem? Please describe.**
I have a react component that creates a modal in the body.

This opens the modal on most of the page instead of just the story block.

**Describe the solution you'd like**
I'd expect the modal to open only in the corresponding block.

**Describe alternatives you've considered**
I don't see any alternative solution right now. I guess the problem could be solved by wrapping the story blocks into iframes. Are there some reasons against that ?

**Are you able to assist bring the feature to reality?**
I'm willing to help if I can

**Comment by shilman** [comment]
You can already force `addon-docs` to render your stories in iframes https://github.com/storybookjs/storybook/blob/next/addons/docs/react/README.md#inline-stories

You can also configure this globally, on a component level, or on individual stories using story parameters.

Rendering multiple iframes on the page can have performance issues which is why we avoid it as the default for all frameworks that support inline story rendering (currently react, vue, web-components)

**Comment by TomPradat** [comment]
Alright, I completely missed this option. Thanks 👍
