### ISSUE TITLE
Yarn 2 support

### ISSUE THREAD

**Issue by Gieted** [storybookjs/storybook#11511]
Both automatic and manual Storybook setups seams to fail, when using Yarn 2 (berry).

1. `yarn init -y`
2. `yarn set version berry`
3. `yarn install`
4. `npx -p @storybook/cli sb init --type html`

**Console output:**
![obraz](https://user-images.githubusercontent.com/35242233/87230056-5a4d5f00-c3ad-11ea-9c68-0bba246f991e.png)

**System:**
![obraz](https://user-images.githubusercontent.com/35242233/87230107-ad271680-c3ad-11ea-929c-8adbe003bc22.png)

Setting `nodeLinker` to `node-modules` will lead to the same result as above.
Manual installation will lead to build error, that doesn't happen on Yarn 1.

**Comment by gaetanmaisse** [comment]
@Gieted which version of Storybook are you trying to use? 
Yarn 2 will start to be supported with Storybook 6 (see https://github.com/storybookjs/storybook/issues/9527 for details), there are still some issues with `addon-docs` but we are working on them!

You can give a try to Storybook 6 RC by running:
 - `npx -p @storybook/cli@next sb init --type html` or `yarn dlx -p @storybook/cli@next sb init --type html` as you're using Yarn 2 😉 
 - `yarn add -D webpack react react-dom` -> These are needed peer dependencies of `storybook/html`, we are working on adding them automatically during `sb init`
 - `yarn storybook`

As of `6.0.0-rc.3` there is an issue with `@babel/plugin-transform-react-jsx` that will be fixed with https://github.com/storybookjs/storybook/pull/11342

**Comment by Gieted** [comment]
Sorry, I thought Yarn 2 support already is on @latest version.
