### ISSUE TITLE
Storybook fails to load BrowserAnimationsModule in Angular

### ISSUE THREAD

**Issue by rafehi** [storybookjs/storybook#11716]
**Describe the bug**
After upgrading to Angular 9 / Storybook 5.3.19, Storybook is failing to load BrowserAnimationsModule / NoopAnimationsModule.

**To Reproduce**
I tested with the following stories (using both template and component) in a fresh Angular project. I've also tried with CSF, with the same result.

```ts
@Component({
  selector: 'app-animation',
  template: `<div [@anim]>Animation</div>`,
})
export class AnimationComponent { }

storiesOf('Animation', module).addDecorator(
  moduleMetadata({
    imports: [BrowserAnimationsModule],
  })
).add('test', () => ({
  template: `<div [@anim]>Hello</div>`,
})).add('test2', () => ({
  component: AnimationComponent
}));
```

Navigate to the story, and notice the following error in the console:
![image](https://user-images.githubusercontent.com/3108685/88753812-9439a600-d1a0-11ea-9872-d79516e763ea.png)

**Expected behavior**
Story should run without issue - the animations module should be correctly loaded.

**Comment by Marklb** [comment]
I see two problems that would cause this error, but neither are an issue with Storybook. Unless you striped out to much in the snippet you posted, I don't see how it would have ever worked.

The error message is a little misleading. I don't know why the error isn't more specific, but what seems to be happening is that Angular sees `@anim` and knows that it is an animation trigger, but it can't handle it, so it is making a guess that maybe your missing an animation module. 

If I hadn't used animations in Angular, then that error message wouldn't have really helped, but I just recognized the problem by thinking through what the code is supposed to do. When I looked to see what the animation does for the trigger `anim`, I realized there isn't a trigger `anim` defined in your snippet.

The problem with both stories:

Story **test1**: The problem is that you are trying to use an animation trigger on a template, but the component Storybook dynamically creates from the template doesn't support the animations property of the **Component** decorator's input object.
> I was able to make Storybook support defining animations on the **Component** created from the stories template, but it would be a new feature, so Storybook version 5 would most likely not get it.

Story **test2**: The problem is that your component doesn't define an animation trigger named `anim`. If you define the trigger, like the following example, it will work.
```ts
@Component({
  selector: 'app-animation',
  template: `<div [@anim]>Animation</div>`,
  animations: [
    trigger('anim', [
      transition( ':enter', [] )
    ])
  ]
})
export class AnimationComponent { }
```

**Comment by rafehi** [comment]
You're right that the code I used above was largely stripped down, was there to just demonstrate. Strangely, the production code seems to be working again, not sure why. It was working fine prior to upgrading Angular/Storybook. Thanks for your help.
