### ISSUE TITLE
A story suddenly disappears when using CDKPortal in component

### ISSUE THREAD

**Issue by huneeeee** [storybookjs/storybook#11715]
While i am making a component using Angular CDK Portal to inject other component, Suddenly story that is showing the component is disappeared!

There is no error log and warning log.

So, i removed all component and remaked.
when i am remaking these component, i found that
when i uses @Input() decorator into the component that is injected to Portal, this problem happens.

```
@Component
export class InjectedComponent implements OnInit {
  // @ts-ignore
  @Input() tempInput;

  constructor() {
  }

  ngOnInit() {
  }
}
```

```
@Component
export class ComponentA implements AfterViewInit {
  //@ts-ignore
  @Input() data;

  selectedPortal: Portal<any>;

  constructor() {
  }

  ngAfterViewInit() {
    this.selectedPortal = new ComponentPortal(InjectedComponent)
  }
}
```

**Comment by Marklb** [comment]
@huneeeee You probably need to make a repro of the problem or at least more detail. I am using `CdkPortal` in multiple components and multiple different ways of using it. None of my stories have had a problem with it.

My assumption is that it has something to do with how your story is defined, but nothing about that is in the description. There were some issues that caused stories to disappear in early versions of Storybook `6.0.0-rc-*`.

I have noticed that Storybook seems to be either hiding some errors or ignoring some for an unclear reason, but I haven't narrowed down a consistent reproduction that shows a hidden problem that is clearly not my fault, yet.

I use `CdkPortal` in multiple components with working stories. Some use it to just swap between a few components in a `cdkPortalOutlet`, some insert components into various `CdkOverlay`s, etc, so I don't think its the problem.

Do you have any warnings in the devtools?

I have had some stories not displaying, with the only indication that anything was wrong, is warnings logged in the devtools.
The warnings that caused my problem happened to be caused by the package `@ngneat/until-destroy`, and any story that used a component that used that package would not display the story in the sidebar. The most recent version of that package doesn't cause that problem any more. I think it had something to do with a difference in how Angular 10 defines the components and the JIT compiler couldn't handle it, but even though `ng serve` and `ng build` didn't error, it wasn't really a Storybook issue.

Since the warning had nothing pointing to the story or component, I narrowed down my problem by modifying the `stories` glob in `.storybook/main.js` to only match the specific file with the story that didn't load. It was inconvenient, but that was how I realized the warnings were indicating my problem. Before doing that, I had been ignoring the warnings, assuming they were just from stories I hadn't updated yet.

**Comment by huneeeee** [comment]
Thank u guys! your advices are helpful for me.
