### ISSUE TITLE
Remove unneccessary scrollbar from iFrame

### ISSUE THREAD

**Issue by albert-schilling** [storybookjs/storybook#11799]
Hi there, 

we just added viewport to our storybook. Everything works fine except we always have a scrollbar in our stories.

At the moment, I believe this is because of the following line where scrolling is set to yes on the iframe tag:

https://github.com/storybookjs/storybook/blob/94dc910229992a78ddfecbd252edde321c184a2b/lib/ui/src/components/preview/iframe.tsx#L86

If I go to .../node_modules/@storybook/ui/dist/components/preview/iframe.js and change scrolling to no in the render function the scroll bar disappears:

```
return _react["default"].createElement(StyledIframe, _extends({
        scrolling: "no",
        id: id,
        title: title,
        src: src,
        allowFullScreen: allowFullScreen
      }, rest));
```

I can then easily define and control my desired scrolling behavior e.g. via a custom decorator in main.js if required.

Versions we use:
    "@storybook/preset-create-react-app": "^1.5.2",
    "@storybook/react": "^5.3.19",
    "@storybook/addon-viewport": "^5.3.19",

Any feedback on this issue would be much appreciated. 

P.S. By the way, scrolling option on iframe is deprecated according to MDN: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe

**Comment by shilman** [comment]
cc @ndelangen @domyen

**Comment by Marklb** [comment]
Do you happen to have a css rule with `{ height: 100vh; }` in your global styles or something that may cause a similar effect of shifting off frame from a container padding? Your problem may not be that, but it did confuse me for a little while, since I had initially gotten used to thinking of my story's template as the only thing in its own isolated iframe.

We had a lot of our stories get messed up when padding was added to the stories by default. The way our apps layout is designed, a lot of our components expect to fill their container, so I had the stories defined in a way that a wrapper component would fill the container height and I could use the viewport addon to try different sizes. All the stories I had like that got pushed off the iframe slightly, which caused a scrollbar to appear. Now that I have gotten used to the padding and fixed my wrapper elements rules to expect it, I am starting to prefer it on most stories, but had to get rid of it on some.

If your problem is because of that padding like mine was, then possible fixes could be adding `:not(.sb-show-main)` to your CSS rule causing the height, adding CSS rule `.sb-show-main { padding: 0 !important; }`(*I don't recommend that one though, because it basically prevents configurable padding.*), or using a padding addon to customize the padding.

**Comment by albert-schilling** [comment]
@Marklb Hi Mark, thank you for the tip. Indeed, the problem was that our css framework bulma set `overflow-y: scroll` by default for the html tag. It might still be a good idea to remove 'scrolling=yes' from the iframe since this attribute is deprecated.

**Comment by ndelangen** [comment]
@albert-schilling would you mind opening a PR removing both instances of `scrolling="yes"` ?

**Comment by ndelangen** [comment]
Can this issue be closed?

**Comment by albert-schilling** [comment]
@ndelangen Yes, sorry, the issue can be closed and of course, I'll submit a PR at the end of this week at the latest.

**Comment by albert-schilling** [comment]
@ndelangen  Here is the tiny pull request: https://github.com/storybookjs/storybook/pull/12223

**Comment by shilman** [comment]
Boo-yah!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.1.0-alpha.0 containing PR #12223 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

**Comment by apsinghhhh1** [comment]
how to remove the scrollbar without affecting the scroll.
