### ISSUE TITLE
Storybook + TypeScript Setup Documentation is Unclear

### ISSUE THREAD

**Issue by thedanchez** [storybookjs/storybook#11873]
**Is your feature request related to a problem? Please describe.**
I feel that the current structure of the [TypeScript setup documentation](https://storybook.js.org/docs/configurations/typescript-config/) is unorganized and not clear for users of certain environments. It's frustrating because I'm facing this problem and I do not know the full scope of what I do or do not need from the current documentation.

**Describe the solution you'd like**
I'd like for the TypeScript setup documentation to be reorganized into sections like or akin to the following:
1. If you are using Storybook with Create React App + TypeScript
2. If you are using Storybook with Ejected Create React App (or custom Webpack config)
3. etc...

**Describe alternatives you've considered**
Storybook has the features that I need but not clear enough documentation.

**Are you able to assist bring the feature to reality?**
No, because I do not have the context to set up the Storybook tooling with TypeScript.

**Additional context**
None.

**Comment by shilman** [comment]
Updated for 6.0

**Comment by jonniebigodes** [comment]
@thedanchez thank you for bringing this issue to our attention. We've done a bit of an overhaul on the documentation and tried to present the information consistently. As all documentation goes, we have room for additions and improvements and fine tuning where it should be fine tuned. I'm going to take a better look at it and see if we can come up with a possible solution for this, so that not only you, but the rest of the community can benefit as well.

Once i have a concrete answer materialized in the form of a pull request i'll mention this issue. 

Sounds good?

Stay safe

**Comment by thedanchez** [comment]
@jonniebigodes Yes, absolutely! Really appreciate your attention on this -- I think this is going to be super valuable to users of Storybook. 

The other thing I forgot to mention is also the use of things like SCSS Modules in a TypeScript context so I'm hoping there's also content for that in the new documentation 😄

**Comment by shilman** [comment]
Hey do you think we still need to improve the Typescript docs? Closing for now but happy to reopen!
