### ISSUE TITLE
Problem of  options-knob  with display='multi-select'

### ISSUE THREAD

**Issue by liuhann** [storybookjs/storybook#11923]
**Describe the bug**

When using options knob valueObjects to be array of Object, on choose of mutil options, the select box would fallback to empty

**To Reproduce**

`
import { optionsKnob } from '@storybook/addon-knobs';

const label = 'Fruits';
const valuesObj = {
  Kiwi: { label: 'kiwi' },
  Guava: { label: 'Guava' },
  Watermelon: { label: 'Watermelon' },
};
const defaultValue = [{ label: 'kiwi' }];
const optionsObj = {
  display: 'multi-select',
};
const groupId = 'GROUP-ID1';

const value = optionsKnob(label, valuesObj, defaultValue, optionsObj, groupId);
`

**Expected behavior**

I think problems goes here: 
`
 if (isMulti) {
      defaultValue = options.filter(function (i) {
        return knob.value.includes(i.value);
      });

      handleChange = function handleChange(values) {
        return onChange(values.map(function (item) {
          return item.value;
        }));
      };
    }

    return _react["default"].createElement(OptionsSelect, {
      value: defaultValue,
      options: options,
      isMulti: isMulti,
      onChange: handleChange
    });
`

The knob panel receive message back(which is deserialized) , and  the 
 options.filter(function (i) {
        return knob.value.includes(i.value);
 });

would result in [] because the value are type of object

**Comment by shilman** [comment]
FYI, we’ve released addon-controls in Storybook 6.0. Controls are portable, auto-generated knobs that are intended to replace addon-knobs long term.

- [Controls documentation](https://storybook.js.org/docs/react/essentials/controls)
- [Migration instructions](https://github.com/storybookjs/storybook/blob/next/addons/controls/README.md#how-do-i-migrate-from-addon-knobs)

Please upgrade and try them out today!

**Comment by liuhann** [comment]
That's Great! I will try 6.0 and addon-control

**Comment by awreese** [comment]
@shilman 

I think this is a bug that could and should be addressed even if Knobs overall are being (eventually) deprecated and replaced by Controls. With identical code and using `display: 'inline-check'` and de-selecting/toggling all options the result is correctly returned as an empty array (`[]`) as one would expect. I would expect the multi-select display config to match behavior.

Is there a compelling reason why this shouldn't be fixed? Is this simply a matter of needing an actual bug ticket and PR fix to be opened and reviewed? If a bug triage results in "expected behavior/won't fix" then could a solution be to document the discrepancy in the README as a known issue?

**Comment by shilman** [comment]
@awreese PRs welcome!
