### ISSUE TITLE
Changing the typescript props does not trigger updates

### ISSUE THREAD

**Issue by Glinkis** [storybookjs/storybook#11982]
When editing the typescript props of a component, the changes does not get applied until I edit something else in the file that is not related to typescript.

```tsx
// button.tsx
// ==========

// changing this does not update the props table
export interface Props {
  label?: string 
}

// changing this updates the component
function Button({ label }: Props) {
  return <button>{label}</button> // changing this updates the component
}

export default Button
```

```tsx
// button.stories.tsx
// ==================

import { Story, Meta } from '@storybook/react'
import React from 'react'

import Button, { Props } from './button'

export default {
  title: 'Button',
  component: Button,
} as Meta

export const Template: Story<Props> = args => <Button {...args} />

Template.args = {
  label: 'Button',
}
```

**Comment by shilman** [comment]
@hipstersmoothie @gaetanmaisse @ndelangen any ideas about this one?

**Comment by hipstersmoothie** [comment]
Things i've found so far. 

1. In a CRA + typescript setup the typescript docgen plugin is loaded twice. Since the `framework-preset-react-docgen` preset is loaded anyway it seems like we don't need the code in the CRA preset
2. The docgen plugin seems to be generating the right docs but storybook isn't updating with the changes


Here I changed the `size` prop to include the string literal `2222`.

![Screen Shot 2020-08-13 at 9 26 36 AM](https://user-images.githubusercontent.com/1192452/90160784-17353180-dd47-11ea-8849-77009e4bdda5.png)

But storybook doesn't update with that.

**Comment by hipstersmoothie** [comment]
If there is someone with more knowledge about what webpack is doing here I would be happy to pair to find the issue. The webpack plugin is pretty simple.

It taps into webpack's `seal` hook and appends the docgen info to the end of the module. You can find the relevant file in `node_modules/react-docgen-typescript-plugin/dist/plugin.js`

**Comment by shilman** [comment]
@ndelangen is our resident webpack expert 😉

**Comment by ndelangen** [comment]
@hipstersmoothie would be happy to pair program on this some time, if you'd be too, let's schedule something!

https://calendly.com/ndelangen/storybook

**Comment by hipstersmoothie** [comment]
Booked for friday!

**Comment by RuudBurger** [comment]
I have the same issue. If I edit the component itself I see the new docgen changes popup.
So please if you find anything, update this ticket 👍

**Comment by Glinkis** [comment]
I believe this is still an issue?

**Comment by yog3sha** [comment]
sb6.1.11, and this issue is still not resolved!
Even use of watch property wont solve it!

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
