### ISSUE TITLE
Angular - TypeError: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by negue** [storybookjs/storybook#12009]
**Describe the bug**

```
Cannot convert undefined or null to object
TypeError: Cannot convert undefined or null to object
    at Function.entries (<anonymous>)
    at http://localhost:6006/vendors~main.628caaa691e17cf9dc97.bundle.js:88535:12
    at Array.reduce (<anonymous>)
    at combineParameters (http://localhost:6006/vendors~main.628caaa691e17cf9dc97.bundle.js:88534:32)
    at enhanceArgTypes (http://localhost:6006/vendors~main.628caaa691e17cf9dc97.bundle.js:81507:55)
    at _this$_argTypesEnhanc._argTypesEnhancers.reduce.Object.assign.__isArgsStory (http://localhost:6006/vendors~main.628caaa691e17cf9dc97.bundle.js:89363:21)
    at Array.reduce (<anonymous>)
    at StoryStore.addStory (http://localhost:6006/vendors~main.628caaa691e17cf9dc97.bundle.js:89361:59)
    at Object.api.add (http://localhost:6006/vendors~main.628caaa691e17cf9dc97.bundle.js:87824:25)
    at http://localhost:6006/vendors~main.628caaa691e17cf9dc97.bundle.js:102757:16
```

**To Reproduce**

1. Clone https://github.com/negue/meme-box/tree/feature/storybook
2. `npm run storybook`
3. See error

**Expected behavior**
To have a running storybook :)

**Screenshots**

**Code snippets**
If applicable, add code samples to help explain your problem.

**System:**
Environment Info:

  System:
    OS: macOS 10.15.4
    CPU: (4) x64 Intel(R) Core(TM) i7-5650U CPU @ 2.20GHz
  Binaries:
    Node: 12.13.1 - /usr/local/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.12.1 - /usr/local/bin/npm
  npmPackages:
    @storybook/addon-actions: 6.0.6 => 6.0.6
    @storybook/addon-essentials: 6.0.6 => 6.0.6
    @storybook/addon-links: 6.0.6 => 6.0.6
    @storybook/angular: 6.0.6 => 6.0.6

**Additional context**
I used the initial `npx sb init` example but removed everything so just have one story / example to reproduce this.

**Comment by Marklb** [comment]
It is a bug in Storybook that happens if you don't have a definition in `documentation.json`. Even though this should be fixed in Storybook, you would have to fix the docs file before things like `addon-controls` will work anyway.

To fix the `compdoc` output file, I created another tsconfig file `tsconfig.stories.ts` that I pass to `compdoc`. So, in `package.json`, my `docs:json` script is `"docs:json": "compodoc -p ./tsconfig.stories.json -e json -d ."`. That is inconvenient and I am considering just changing my base tsconfig file instead. I just haven't got a chance yet to examine my build output, to confirm I am not including extra files in the output.

If it doesn't affect anything, you could fix yours by changing your `tsconfig.base.json` file to use a glob in "includes", instead of the "files" property that only specifies two ts files that compdoc doesn't even attempt to file the imported files of.
The following `tsconfig.base.json` makes your project load Storybook:
```
{
  "compileOnSave": false,
  "compilerOptions": {
    "module": "es2020",
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "baseUrl": ".",
    "rootDir": ".",
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "es2015",
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2018",
      "es2017",
      "es2016",
      "es2015",
      "dom"
    ],
    "paths": {
      "@memebox/contracts": [
        "projects/contracts/src/public-api.ts"
      ]
    }
  },
  "include": [
    "src/**/*.d.ts",
    "src/**/*.ts",
    "projects/**/*.ts"
  ],
  "exclude": [
    "node_modules"
  ]
}
```

From the release notes, it looks like `@schematics/angular@10.0.6` reverted the Typescript "solution" style config, so you may could try running the migration that reverts that change. I have not tried that, so I don't know if it would fix the problem or not.

**Comment by shilman** [comment]
ZOMG!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.0.7 containing PR #12012 that references this issue. Upgrade today to try it out!

Closing this issue. Please re-open if you think there's still more to do.

**Comment by negue** [comment]
Yes its working, thank you!!  @shilman 

@Marklb wow thank you for going through so many layers to find the issue & solutions!
