### ISSUE TITLE
[Typescript] Fields in arguments do not get compiled as fields.

### ISSUE THREAD

**Issue by val-o** [storybookjs/storybook#12019]
I am using @storybook/react@6.0.7

**Describe the bug**
Typescript's fields in constructor feature doesn't get properly compiled, so code like this
```
  constructor(
    private _service: IAuthService,
    private _storage: IStorageManager,
    public readonly withSecondFactor: boolean
  ) { }
```
compiled as just
```
function (_service, _storage, withSecondFactor) {...etc, but nothing to set field values}
```

Although, if you override the config in main.js like so, it will work properly.
```
   config.module.rules[0].use[0].options.plugins = [
      '@babel/plugin-proposal-nullish-coalescing-operator',
      '@babel/plugin-proposal-optional-chaining',
      [
        '@babel/plugin-proposal-decorators/lib/index.js',
        { legacy: true },
      ],
    ];

```
I believe the problem is in plugins, particularly these two:
```
@babel/plugin-proposal-class-properties/lib/index.js
@babel/plugin-transform-classes
```
 not sure which one of them actually causing a problem though

**Comment by shilman** [comment]
cc @gaetanmaisse @mrmckeb

**Comment by Thomvaill** [comment]
I have the same issue with Storybook v6.0.26 on a fresh Next.js install.
However, there is no bug on a fresh create-react-app install.

## Story used to reproduce the issue

TsIssue.stories.tsx:
```tsx
import React from 'react';

class MyClass {
  constructor(public readonly myProp: string) {}
}
const myInstance = new MyClass("test")

export default {
  title: 'TS Issue',
};

export const Test = () => <div>{myInstance.myProp}</div>;
```

The story should print "test". However, it prints nothing when the issue occurs because `myInstance.myProp` is undefined.

## Steps to reproduce on a fresh Next.js install

```
yarn create next-app
cd my-app
touch tsconfig.json # to tell Next.js to set up the project with Typescript
yarn add --dev typescript @types/react @types/node
yarn run dev # Ctrl+c
npx sb init
# copy TsIssue.stories.tsx to stories/
yarn storybook
```

--> `myInstance.myProp` is undefined.

## Steps to reproduce on a fresh CRA install

```
yarn create react-app my-app --template typescript
cd my-app
npx sb init
# copy TsIssue.stories.tsx to stories/
yarn storybook
```

--> it works.


The only difference between the two examples is the presence of the `@storybook/preset-create-react-app` addon for CRA, which seems to fix the issue.
I was not able to investigate more.

PS: Storybook v6.1.0-alphaX also has the issue
PS2: I could not test on Storybook v6.0.27. At the time I am writing, this version crashes totally (blank page)

**Comment by Glavin001** [comment]
@DPros worked for me. Turns out removing the `@babel/plugin-transform-classes` plugin also works:

`.storybook/main.js`:

```javascript
module.exports = {
  //...
  webpackFinal: async (config) => {
    // Storybook bug: https://github.com/storybookjs/storybook/issues/12019#issuecomment-702207045
    const { options } = config.module.rules[0].use[0];
    options.plugins = options.plugins.filter(excludePlugins([
      '@babel/plugin-transform-classes',
    ]));
    return config;
  }
}

function excludePlugins(excludePaths) {
  return plugin => {
    const name = typeof plugin === 'string' ? plugin : plugin[0];
    if (typeof name !== 'string') {
      throw new Error(`Not a string: ${name}`);
    }
    return !excludePaths.some(path => name.includes(path));
  }
}
```

**Comment by gustavohenke** [comment]
👋 still having this issue on 6.1.1, even after filtering out the `@babel/plugin-transform-classes` plugin as suggested above by @Glavin001.

**Comment by maurocolella** [comment]
Filtering out `@babel/plugin-transform-classes` works for me, and the dependency appears in multiple bug reports related to this issue. It's definitely one cause if not _the_ root cause.

**Comment by tobyhinloopen** [comment]
I've posted an example repo + another example in my issue: https://github.com/storybookjs/storybook/issues/14515

**Comment by darkship** [comment]
@Glavin001 and '@babel\\plugin-transform-classes' too for windows

**Comment by joshkel** [comment]
I tried removing `@babel/plugin-transform-classes` but ran into problems; some of my components apparently depend on its functionality.

I instead switched to Storybook's [V7 mode](https://storybook.js.org/docs/react/configure/babel#v7-mode) for Babel configuration (so that Storybook uses the same Babel configuration as the rest of my project), and it seems to work. (I did have to tweak the `config.resolve.fallback` section of my Storyobok's Webpack 5 configuration; apparently requiring Node.js-only modules from the browser is handled slightly differently after switching to V7.)

**Comment by rodrigovive** [comment]
I have a similar issue, I was able to fix it with 

`config.module.rules.push({
      test: /\.(js|jsx|ts|tsx)$/,
      use: {
        loader: 'babel-loader',
        options: {
          // Disable reading babel configuration
          babelrc: false,
          configFile: false,
          presets: [
            '@babel/preset-env',
            '@babel/preset-react',
            '@babel/preset-flow',
            '@babel/preset-typescript',
            {
              plugins: [
                '@babel/plugin-proposal-class-properties',
                '@babel/plugin-proposal-object-rest-spread',
                '@babel/plugin-proposal-optional-chaining',
                '@babel/plugin-proposal-nullish-coalescing-operator'
              ],
            },
          ],
        },
      },
    });`

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
