### ISSUE TITLE
Upgrade badge should be disable-able, non-obstructing

### ISSUE THREAD

**Issue by jodyheavener** [storybookjs/storybook#12027]
**Is your feature request related to a problem? Please describe.**

I've noticed that when there's a new version of Storybook the bottom left shows a little badge to upgrade. That's fine and all, but there are reasons that my team may not want to/can't upgrade. Unfortunately the badge also blocks sidebar links; there are some that can't be reached when the badge is visible.

**Describe the solution you'd like**

- Ideally this badge could be disabled. The CLI notice is enough to remind me that an upgrade is available.
- If not disable-able, extra padding should be added to the bottom of the scrolling sidebar so you can scroll the last item past the badge when it's visible.

**Are you able to assist bring the feature to reality?**

Sure! If there's a defined approach I would be happy to implement it.

**Additional context**

![Screen Shot 2020-08-14 at 10 33 03 AM](https://user-images.githubusercontent.com/6392049/90260735-ed007400-de19-11ea-903e-6a43e86843d2.png)

**Comment by IMH51** [comment]
+1 for making this disable-able. 

This has caused major headaches since being implemented for me and my colleagues. The banner is effectively blocking some of our Webdriver based QA tests from passing in our CircleCI workflows, as the tests can't select components and stories in the bottom left corner of the page, which is now blocking work from being merged and released.

Most of this afternoon has been spent working on fix for this, which still isn't fully complete, so a quick fix for this would be much appreciated!

**Comment by shilman** [comment]
`start-storybook` has a `--no-version-updates` flag. Have you tried that?

**Comment by jodyheavener** [comment]
Boom. My apologies for not seeing this. This flag seems to disable both the CLI notice and the little badge for me. Thank you!
