### ISSUE TITLE
Do not hardcode React v16

### ISSUE THREAD

**Issue by gajus** [storybookjs/storybook#12228]
Currently, Storybook components define React v16 as their direct dependency.

https://github.com/storybookjs/storybook/blob/8851ac1a326efad90df82867f81f1f8d63b32ee4/lib/api/package.json#L45

This causes issues for projects that use others version of React (e.g. v17 or 0.0.0-experimental).

We have to use 0.0.0-experimental because it is hard requirement for [Relay](https://relay.dev/).

This makes Storybooks unusable.

Ideally, this project would just define react dependency as `>= 16 || ^17.0.0-rc.0 || ^0.0.0-experimental`

**Comment by gajus** [comment]
If for whatever reason you do not want to depend on these dependencies, you can use [`acceptDependencies`](https://github.com/npm/rfcs/blob/latest/accepted/0023-acceptDependencies.md#acceptable-acceptdependencies-package-specifiers).

However, this is generally one of the rare cases where using `react: *` as a dependency wouldn't be the worst idea.

**Comment by gajus** [comment]
We ended up switching to yarn using `resolutions`, but this is not ideal.

```json
"resolutions": {
  "**/react": "0.0.0-experimental-94c0244ba",
  "**/react-dom": "0.0.0-experimental-94c0244ba"
},

```

**Comment by ndelangen** [comment]
@gajus Storybook is 2 applications, a manager and a preview.
We bundle the 2 applications separately.
The manager always gets the react version WE specify
The preview always gets the react version the end user specifies in their `package.json`.

yarn resolutions should not be necessary, in fact it might break the manager.

> If for whatever reason you do not want to depend on these dependencies, you can use acceptDependencies.
This link is broken, and seems to be a RFC (looking at the url) rather then a production ready feature?

> Ideally, this project would just define react dependency as >= 16 || ^17.0.0-rc.0 || ^0.0.0-experimental
We can't. We don't ensure we're actually compatible with all those versions.

> We ended up switching to yarn using resolutions, but this is not ideal.
Totally agree with you this is not the best experience. But it is the least bad of all the options I see.
Open to debating this during one of our roadmap meetings for sure!
https://github.com/storybookjs/community

**Comment by gajus** [comment]
We are Okay with the workaround that we are using.

**Comment by bard** [comment]
@ndelangen if `resolutions` should not be necessary, doesn't the fact that it is suggest that there may be a bug? After migrating to React 17, I also had to adopt the workaround due to multiple versions of React being imported, so it seems that "the preview always gets the react version the end user specifies in their `package.json`" may not be the case.

**Comment by ndelangen** [comment]
true, @bard if there's a bug there, We should fix it. Would you be able provide a reproduction repo showcasing this problem?

**Comment by bard** [comment]
@ndelangen this may be yet another case of `node_modules` cruft, because while trying to reduce my complex repo to a minimal case, I deleted `node_modules` entirely and reinstalled, and afterwards Storybook was running fine _without_ a `resolutions` field. So I take that back, it looks like it works as intended and may be just one troubleshooting suggestion to give to other people upgrading to React 17 who face the same issue. Thanks for prompting me to look into this more carefully!

**Comment by ndelangen** [comment]
> `node_modules` cruft
This is our life now
