### ISSUE TITLE
"MDX Reference" link in storybook DocPage README is broken

### ISSUE THREAD

**Issue by bbugh** [storybookjs/storybook#12317]
**Describe the bug**
The title is descriptive of the issue. 

**To Reproduce**

https://www.npmjs.com/package/@storybook/addon-docs#mdx

Click the MDX reference link in the paragraph:

> For more information on MDX, see the MDX reference

Results in a GitHub 404. 

**Expected behavior**
Links to somewhere valid with docs!

**Comment by jonniebigodes** [comment]
@bbugh and sorry for the delay in answering. I've been sidetracked with other aspects of the documentation and your issue was left behind a bit. Nonetheless i would like to thank you for bringing this to our attention and i've just made a pull request that addresses the issue you've encountered. Hopefully once it's merged the links should be working as intended.

Stay safe

**Comment by jonniebigodes** [comment]
Closing this as a pull request was made to address the issue. Feel free to let me know if the issue persists and I'll gladly re-open the issue.

Stay safe
