### ISSUE TITLE
[Angular] Addon-controls: inference issues with enum props

### ISSUE THREAD

**Issue by jordanfonseca-iad** [storybookjs/storybook#12531]
I am not sure that my issue is related to this but I've got this type of behaviour in `"@storybook/vue": "^6.0.21"`:
1. I'm importing enum in the story
2. Using it in `Default.args`
3. Control is appearing as textfield

_Originally posted by @justice47 in https://github.com/storybookjs/storybook/issues/12007#issuecomment-686481342_

----

I'm experiencing the same problem with Angular.
Storybook version : `6.0.21`
Angular version : `8.2.14`

Example given with an avatar component :
```typescript
// avatar.stories.ts

export default {
  title: 'Components/Avatar',
  component: AvatarComponent,
  decorators: [
    moduleMetadata({
      imports: [AvatarModule]
    })
  ]
};

const Template: Story<AvatarComponent> = (args: AvatarComponent) => ({
  component: AvatarComponent,
  props: args
});

export const Small = Template.bind({});
Small.args = {
  size: AvatarSize.SMALL
};
```

```typescript
// avatar.component.ts

@Component({
  // ...
})
export class AvatarComponent {
  @Input() size?: AvatarSize;
  // ...
}
```

The `size` control is displayed as a textfield and not a select.

**Comment by shilman** [comment]
https://github.com/storybookjs/storybook/blob/next/addons/controls/README.md#my-controls-arent-being-auto-generated-what-should-i-do

**Comment by jordanfonseca-iad** [comment]
Thanks @shilman, I've obviously read it before posting this issue 😄 
I'm currently using manual controls with `argTypes` but I would have liked understand why enums aren't auto-generated as select inputs. Is it an issue or a missing feature ? Sorry if I've missed something on enums support in the [README](https://github.com/storybookjs/storybook/blob/next/addons/controls/README.md#my-controls-arent-being-auto-generated-what-should-i-do). 

If my type is not an enum but an union type, it works :
```ts
export class AvatarComponent {
  @Input() size?: 'small' | 'medium' | 'large'; // Auto-generated in select input
}
```

```ts
export class AvatarComponent {
  @Input() size?: AvatarSize; // Auto-generated in text input
}
```

Thanks for your answer and have a good day !

**Comment by shilman** [comment]
We're using `vue-docgen-api` to generate this, so it's a good question for @elevatebart

**Comment by lachieh** [comment]
First of all, I really appreciate the efforts of the Storybook team! The Controls addon is a fantastic addition!

I came across this issue also so I did some digging. This is the relevant function as far as I can tell.

https://github.com/storybookjs/storybook/blob/64846833859af71848ed80abdc3bb530c24a599b/addons/docs/src/frameworks/angular/compodoc.ts#L115-L125

The code below doesn't generate a select input control because the `extractEnumValues` function only checks if it is a union type (checking for a pipe character) because it can't infer the `enum` type from just the type name.

```ts
export class AvatarComponent {
  @Input() size?: AvatarSize; // Auto-generated in text input
}

enum AvatarSize {
  SMALL = 'SMALL',
  MEDIUM = 'MEDIUM',
  LARGE = 'LARGE',
}
```

The same problem exists when using a type alias like this:

```ts
export class AvatarComponent {
  @Input() size?: AvatarSize;
}

type AvatarSize = 'small' | 'medium' | 'large'
```


While `compodoc` does generate the data for enums under `miscellaneous.enumerations`, it doesn't store this information in the same object as the component definition meaning it isn't readily available. I'm not sure where to go from here, but the below is an example of the resulting json from compodoc if someone wants to take a stab at investigating further.

```jsonc
{
  // ...
    "miscellaneous": {
      // ...
        "enumerations": [
            // ...
            {
              "name": "AvatarSize",
              "childs": [
                  {
                      "name": "SMALL"
                  },
                  {
                      "name": "MEDIUM"
                  },
                  {
                      "name": "LARGE"
                  }
              ],
              "ctype": "miscellaneous",
              "subtype": "enum",
              "description": "",
              "file": "src/avatar/avatar.component.ts"
            },
        ]
    }
}
```

**Comment by shilman** [comment]
@lachieh thanks for the research on this. should be pretty easy to add this to `extractArgTypes` for angular. if anybody wants to take this, I'd be happy to help guide.

**Comment by lachieh** [comment]
I would be interested! Point me in the right direction and I'll get started.

**Comment by lachieh** [comment]
@shilman I notice there's a `getCompdocJson` function. Would I use that to get the miscellaneous key and look for the type that matches?

**Comment by shilman** [comment]
Sorry, missed your previous comment. Relevant code is here:

https://github.com/storybookjs/storybook/blob/next/addons/docs/src/frameworks/angular/compodoc.ts#L155

Please be sure to add a test case to `examples/angular-cli` and you can test it out as you develop using the instructions provided in `CONTRIBUTING.md`. LMK if that makes sense!

**Comment by lachieh** [comment]
Thanks, @shilman! PR opened above.

**Comment by graup** [comment]
This isn't just an angular issue, I'm seeing the same on React. And the OP talked about vue. I assume it's for the exact same reason there.

**Comment by lachieh** [comment]
One thing to note for my PR is that even though I have been able extract the values from an enum type, the only version of enums that work are [String Enums](https://www.typescriptlang.org/docs/handbook/enums.html#string-enums). When I got the value to assign to the dropdown control, even though the enum had a name, the control input displays the number value (0, 1, 2, etc).

It's possible that a future iteration of docs and/or controls needs to support enums that have a value and a label, instead of just a list of values.

**Comment by shilman** [comment]
Gadzooks!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.2.0-alpha.0 containing PR #12665 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.

**Comment by paul-request** [comment]
Hi, just tried this out when using a getter/setter for an Input with angular and it does not infer the types.

This works:
`
@Input() variant: Variant = Variant.Generic;
`

This does not:
`
_variant: Variant;

@Input() set variant(variant: Variant) {
    // some custom logic goes here ...

    this._variant = variant;
  }
  get variant(): Variant {
    return this._variant;
  }
`

In this case, I would ignore `_variant`, but would still want `variant` to rendered with a control for the `Variant` enum
