### ISSUE TITLE
when testing with storyshots, args with a null value entry break the story loading chain

### ISSUE THREAD

**Issue by chadi-kazan** [storybookjs/storybook#12540]
**Describe the bug**
using `@storybook/react v6.0.21`
When running image snapshot tests, storybook fails to load a story with a args parameter entry with a null value, even though the component's type for that prop takes null.
The story renders properly in the storybook UI though

**To Reproduce**

1. testing the `ProgressBar` component from kendo ui
2. with the story below
```typescript
import { ProgressBar, ProgressBarProps } from "@progress/kendo-react-progressbars";
import { Story } from "@storybook/react/types-6-0";
import React from "react";

export default {
	title: "Components/Progress Bars/ProgressBar",
	component: ProgressBar,
};

const Example: Story<ProgressBarProps> = (props) => <ProgressBar min={0} max={100} value={66} {...props} />;

/*storybook does not understand the null args.
this breaks the story and therefore storybook ignores all the stories behind it in the pecking order when running snapshot tests*/

export const Indeterminate = Example.bind({});
Indeterminate.args = {
	value: null, // <----------------------------- culprit is this
	style: { height: "4px" },
};
```
Mind you that [ProgressBar declares a `number|null` value prop](https://www.telerik.com/kendo-react-ui/components/progressbars/api/ProgressBarProps/#value)

**Expected behavior**
story to be picked up and test run.

**System:**
Environment Info:
```
  System:
    OS: Windows 10 10.0.17763
    CPU: (8) x64 Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz
  Binaries:
    Node: 12.18.0 - C:\Program Files\nodejs\node.EXE
    npm: 6.14.8 - D:\GIT\vitol-design-system\node_modules\.bin\npm.CMD
  Browsers:
    Chrome: 84.0.4147.125
    Edge: Spartan (44.17763.831.0)
  npmPackages:
    @storybook/addon-actions: 6.0.21 => 6.0.21
    @storybook/addon-essentials: 6.0.21 => 6.0.21
    @storybook/addon-links: 6.0.21 => 6.0.21
    @storybook/addon-storyshots: 6.0.21 => 6.0.21
    @storybook/addon-storyshots-puppeteer: 6.0.21 => 6.0.21
    @storybook/addon-viewport: 6.0.21 => 6.0.21
    @storybook/addons: 6.0.21 => 6.0.21
    @storybook/node-logger: 6.0.21 => 6.0.21
    @storybook/preset-create-react-app: 3.1.4 => 3.1.4
    @storybook/react: 6.0.21 => 6.0.21
```

**Comment by Slioniwe** [comment]
The same issue for `undefined`.

**Comment by bogdanorzea** [comment]
I've been bashing my head against the keyboard for more than a week and just found out that the null and undefined will break the whole jest storyshot generation. After removing the null arg, it started working.

**Comment by thibaudcolas** [comment]
I’m not sure if this is clear enough from the above:

- This affects all Storyshots usage, not just image snapshots
- It’s not just the affected stories that fail to run – as soon as this bug occurs, Storyshots stops running any further tests
- **This all happens silently**. There is no indication from the tests output output that anything is broken

To me the fact that this is all happening while the test suite still passes is much more problematic than those few stories not working as expected.

The error is:

<details>

<summary>Cannot read property 'defaultValue' of undefined</summary>

```
TypeError: Cannot read property 'defaultValue' of undefined
    at storyshots-null-args/node_modules/@storybook/client-api/dist/story_store.js:644:38
    at Array.reduce (<anonymous>)
    at StoryStore.addStory (storyshots-null-args/node_modules/@storybook/client-api/dist/story_store.js:641:50)
    at Object.api.add (storyshots-null-args/node_modules/@storybook/client-api/dist/client_a…/storyshots-null-args/node_modules/jest-jasmine2/build/index.js:60:19)
    at storyshots-null-args/node_modules/jest-runner/build/runTest.js:385:24
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (storyshots-null-args/node_modules/jest-runner/build/runTest.js:161:24)
    at _next (storyshots-null-args/node_modules/jest-runner/build/runTest.js:181:9)
```

</details>

It’s raised here, as part of the array destructuring, because the expected `argType` is `undefined`: https://github.com/storybookjs/storybook/blob/748710ce10a4f16d599f183f215455e450e25d32/lib/client-api/src/story_store.ts#L415

It gets swallowed by the `catch` here: https://github.com/storybookjs/storybook/blob/748710ce10a4f16d599f183f215455e450e25d32/lib/client-api/src/config_api.ts#L18-L20

---

As far as I can see, this `undefined` comes from one of the `_argTypesEnhancers`. It’s not clear to me whether the bug is with one of those enhancers ([`ensureArgTypes`](https://github.com/storybookjs/storybook/blob/748710ce10a4f16d599f183f215455e450e25d32/lib/client-api/src/ensureArgTypes.ts#L9), [`inferArgTypes`](https://github.com/storybookjs/storybook/blob/748710ce10a4f16d599f183f215455e450e25d32/lib/client-api/src/inferArgTypes.ts#L35)), or whether the code above should handle `argType` being undefined.

Without understanding it all, https://github.com/storybookjs/storybook/blob/748710ce10a4f16d599f183f215455e450e25d32/lib/client-api/src/story_store.ts#L412-L418

- This issue seems to be fixed if we check for `argType` before progressing. This seems like it could be appropriate if the whole point of this code is to set a default value for args?
- I think the `if (defaultValue)` check should be more precise, and not conflate all false-y values. 

```diff
const passedArgs: Args = combinedParameters.args;
const defaultArgs: Args = Object.entries(
    argTypes as Record<string, { defaultValue: any }>
-).reduce((acc, [arg, { defaultValue }]) => {
-    if (defaultValue) acc[arg] = defaultValue;
+).reduce((acc, [arg, argType]) => {
+    if (argType && typeof argType.defaultValue !== 'undefined') acc[arg] = defaultValue;
    return acc;
}, {} as Args);
```

**Comment by shilman** [comment]
Thanks @thibaudcolas -- I'll try out your fix and see what it does. I'm very interested in fixing things on the args side of things, don't have the bandwidth to fix the storyshots side.

**Comment by Hypnosphi** [comment]
Related: https://github.com/storybookjs/storybook/issues/12729

**Comment by ChristianIvicevic** [comment]
I was bashing my head against the desk when I found this issue after four hours of experimenting. It'd be awesome if this gets fixed soon as it has been reported in September.

**Comment by thibaudcolas** [comment]
@ChristianIvicevic it’s not clear to me why you checked for `null` as well? Your suggested patch makes it impossible to use `null` as the default value, which is perfectly valid (at least for React projects), and not the same as `undefined`. (`typeof undefined` vs `typeof null`).

**Comment by ChristianIvicevic** [comment]
@thibaudcolas Let me preface this by saying I don't know the codebase of Storybook at all so this was merely trial and error for me and hence I don't know any relations and intricacies here.

I noticed before checking for null that a my stories would have random and inexplicable runtime errors when having props defined either implicitly (by not defining a value for optional props) or explicitly as `undefined`. In fact some props were suddenly `null` even though I explicitly set them in the story. My assumption is that the props got mixed up.

Furthermore due to my code style I never work with `null` at all so I can't say how props behave that you want to allow to be `null` in the first place.

**Comment by ChristianIvicevic** [comment]
I just tested the latest beta of v6.1 and my patch is no longer necessary. Storyshots have been fixed for all occurences of `undefined` and `null` in my project.

**Comment by shilman** [comment]
Hooray! Closing.
