### ISSUE TITLE
Storybook CSS is Overriden by the Application's CSS

### ISSUE THREAD

**Issue by edarioq** [storybookjs/storybook#12573]
**Describe the bug**
Styles are being applied automatically to native Storybook UI elements, such as buttons, tables, and what not. This makes the Storybook UI appear broken, in some cases hard to use.

**To Reproduce**
I have several global styling targeting the HTML elements in my app, such as:
```
button {
  // some styles
}
```

**Expected behavior**
I expect Storybook to have a default non mutable UI for it's layout, controls, buttons, etc. that isn't affected by the apps CSS styles.

**Screenshots**
<img width="1167" alt="Screen Shot 2020-09-24 at 12 51 20 PM" src="https://user-images.githubusercontent.com/1882457/94181467-27bbea00-fe65-11ea-8ba6-7323a039db38.png">

**Comment by shilman** [comment]
@edarioq Storybook in general does. Addon-docs is special in that it renders in the same iframe as the user code, so that's what you're seeing. It does a bunch of CSS reset trickery to try to avoid this issue, but it looks like that's not working.

Do you happen to know whether there is some built-in CSS feature that would allow us to make the styles non-overwritable for certain dom elements?

**Comment by edarioq** [comment]
What I've done to try and fix is, is add `preview-head.html` in `.storybook` directory and target Storybook's UI elements via CSS and use `!important`. This seems to fix it somewhat, although not ideal. So:
```
<style>
  // Overrides goes here
</style>
```
**Do you happen to know whether there is some built-in CSS feature that would allow us to make the styles non-overwritable for certain dom elements?** -- The above should answer your question. By using `important` it makes it non-overwritable.

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
