### ISSUE TITLE
Accessibility addon is not working in Angular based storybook

### ISSUE THREAD

**Issue by kaavya0407** [storybookjs/storybook#12591]
**Describe the bug**
Accessibility addon is not working in Angular based storybook
I am trying to integrate Accessibility add on angular storybook. But its's not working. Always giving message as "Please wait while the accessibility scan is running ..."

Configuration (package.json)
  "@nrwl/storybook": "^9.2.1",
    "@nrwl/workspace": "10.1.0",
    "@storybook/addon-a11y": "^6.0.22",
    "@storybook/addon-knobs": "5.3.9",
    "@storybook/angular": "5.3.9",

![image](https://user-images.githubusercontent.com/72012031/94411444-345a7e00-0196-11eb-81a7-f78e820b239e.png)

![image](https://user-images.githubusercontent.com/72012031/94411480-3de3e600-0196-11eb-918c-e31e87e643ab.png)

**Comment by shilman** [comment]
Do you have a repro repo you can share?

**Comment by jsomsanith** [comment]
Hey @kaavya0407,
I know it's been a while, but do you still experience this issue ?
Based on your screenshot, it may be caused by the same issue as #16232
In short: a11y > element property is not handled well by the addon, treating it the selector as the root element to scan instead of the selector.
Let's close this issue. Feel free to reopen it if needed
