### ISSUE TITLE
Replace compodoc

### ISSUE THREAD

**Issue by klemenoslaj** [storybookjs/storybook#12689]
**Is your feature request related to a problem? Please describe**
Compodoc seems to be unmaintained since a while now and has a number of issues that really hinder the resulting documentation.

**Describe the solution you'd like**
Fork compodoc and fix issues relevant for generating the json (merge back if gets maintained again).

**Describe alternatives you've considered**
- Use typedoc (no Angular specific documentation - inputs, etc.) or
- Implement own solution

**Are you able to assist to bring the feature to reality?**
Yes.

**Comment by shilman** [comment]
Hi @klemenoslaj, Storybook's surface area is too large already so maintaining a Compodoc alternative or fork isn't an option. However, the code that interfaces with compodoc is a single file:

https://github.com/storybookjs/storybook/blob/next/addons/docs/src/frameworks/angular/compodoc.ts

If there were a well-maintained alternative to Compodoc, I'd be open to:
- [ ] Making it an opt-in option in 6.1
- [ ] Deprecating compodoc
- [ ] Making that alternative the default in 7.0

If that alternative is typedoc and it also applies to other frameworks and documentation types (e.g. generic API documentation), I might also be open to that.

What do you think?

**Comment by klemenoslaj** [comment]
Yes, I thought so 🤔 

> If there were a well-maintained alternative to Compodoc

That's the thing, I don't think there is anything else out there.

> If that alternative is typedoc and it also applies to other frameworks and documentation types (e.g. generic API documentation), I might also be open to that.

I guess that is the best solution. It would cover all TS projects which is a nice bonus.

Should I give this PR a spin?

**Comment by shilman** [comment]
@klemenoslaj I can't promise we'll merge a PR without really understanding the extent of what's possible with tsdoc. However, I'm very interested in your proposed direction, and happy to discuss more here OR look at a proof of concept and figure out how we might fit it in.

**Comment by klemenoslaj** [comment]
@shilman yes absolutely. I meant a PR draft as a basis of further discussion - a PoC indeed. Sorry for misunderstanding.
I will try to put something together over the weekend, hope that's fine.

**Comment by shilman** [comment]
@klemenoslaj That's wonderful! Excited to see it 🤩

**Comment by klemenoslaj** [comment]
@shilman I've put together a very rough draft with typedoc.

The problem I am facing is that typedoc seems not to expose the readable string representations of types so I'd have to parse all the types myself.

Example:

From
```json
"type": {
  "type": "union",
  "types": [
    {
      "type": "stringLiteral",
      "value": "primary"
    },
    {
      "type": "stringLiteral",
      "value": "secondary"
    }
  ]
},
```

to
```ts
'primary' | 'secondary'
```

While I did not have the time to turn typedoc apis upside down yet, I do think that by initializing and using typedoc application programmatically we'd gain the ability to serialize and deserialize types using typedoc public API.
This would only be possible in build time I guess.

What do you think?

**Comment by shilman** [comment]
I think rendering structured data to a string shouldn't be hard--we're doing similar things in other parts of the code. What worries me more is what angular-specific info (if any) we lose by moving to Typedoc

**Comment by klemenoslaj** [comment]
> I think rendering structured data to a string shouldn't be hard--we're doing similar things in other parts of the code

Yes, agreed :+1: Would be preferable if documentation tool does that for us to avoid maintenance for syntax changes - which are unlikely tho.

> What worries me more is what angular-specific info (if any) we lose by moving to Typedoc

Yes, I have the same concern. However better something than nothing, as `compodoc` is anyway not working correctly past Angular 8.

P.S. Just submitted the PR. It's a rough draft at best.

**Comment by manuelmeister** [comment]
This would be cool. Currently migrating angular storybook from 5.3 to 6 and knobs to controls and this would solve my problem. No select/radio controls show up for my `type ButtonVariant = 'yellow' | 'white'`

**Comment by Marklb** [comment]
I was trying to think about angular-specific info that may be lost and the only thing that I could think of so far is something that `compodoc` hardly supports, which is `inputs` and `outputs` defined in the `@Component` decorator.

> Using `inputs` and `outputs` like this is not the recommended way to use them, but they are supported and necessary for some reusable feature techniques, such as mixins. Also, I learned about doing this from the `@angular/cdk` and `@angular/material` source code, which in my opinion sort of implies they see it as a valid feature.

I will try to provide a brief example to hopefully explain enough to see if this is something we may be able to add with `typedoc`, instead of trying to fix it in `compodoc`. This has been requested in `compodoc`'s issues, but ignored like everything else it seems.

```ts
This mixin is from Angular Material's source, so the missing details can be found there: https://github.com/angular/components/blob/master/src/material/core/common-behaviors/disabled.ts

export type Constructor<T> = new(...args: any[]) => T

export interface CanDisable {
  /** Whether the component is disabled. */
  disabled: boolean
}

export type CanDisableCtor = Constructor<CanDisable>

/** Mixin to augment a directive with a `disabled` property. */
export function mixinDisabled<T extends Constructor<{}>>(base: T): CanDisableCtor & T {
  return class extends base {
    private _disabled = false

    get disabled() { return this._disabled }
    set disabled(value: any) { this._disabled = coerceBooleanProperty(value) }

    constructor(...args: any[]) { super(...args) }
  }
}

@Component({ template: '' })
class ButtonBase {

}

const _ButtonMixinBase: CanDisableCtor &
    typeof ButtonBase = mixinDisabled(ButtonBase)

const INPUTS = [ 'thingOne', 'thingTwo', 'disabled' ]
const OUTPUTS = [ 'thingMoved', 'thingTalked' ]

@Component({
  selector: 'example-component',
  template: `{{ thingOne }} {{ thingTwo }} {{ disabled }}`,
  inputs: INPUTS,
  outputs: OUTPUTS
})
class ExampleComponent extends _ButtonMixinBase { }
```

> For someone not familiar with Angular, that mixin is useful to add a coerced `disabled` input. In html `<input disabled />` means the input is disabled, but that would pass an empty string to `disabled` in the component input, so this would coerce `''` to `true`.

This is what `compodoc` does:

```json
"components": [
	{
		"name": "AllKnobsComponent",
		"inputs": [
			"INPUTS"
		],
		"outputs": [
			"OUTPUTS"
		],
		...
	}
]
```

This code is typed, but the relation between the `inputs` and `outputs` strings and the type properties in the class isn't something Typescript recognizes, but Angular would validate it in the template and Typescript would validate it in the Typescript code.

----

In the previous example, I didn't provide any way to know the type of all the inputs and outputs. There is a special prefixed property syntax necessary for coerced inputs when using Angular's strictest typechecking and we may be able to use it as a fallback way of checking for types. It isn't meant to represent the actual type, but still better than no type probably. The syntax is `ngAcceptInputType_<property name>` and it is just a hint for Angular's type checker, because a template can't guarantee the input will be passed as the right type in the template, because of various reasons like valid html properties that are loose with their types.

In the following example I am guaranteeing that `disabled` will always be a `boolean` in my component by coercing the input, but the template can't make that same guarantee, so I will use `ngAcceptInputType_disabled` to let the template know what types may be used in the template.

```ts
@Component({ selector: 'example-component' })
class ExampleComponent {
	private _disabled: boolean = false

	@Input()
    get disabled(): boolean { return this._disabled }
    set disabled(value: boolean) { this._disabled = coerceBooleanProperty(value) }

	static ngAcceptInputType_disabled: string | boolean | null | undefined
}
```

So, if we were to use `ngAcceptInputType_` as a fallback, since it is types the input is claiming to know how to handle, then I would expect the following: 

Property: `'disabled'`
Type: `boolean`
```ts
@Component({ selector: 'example-component' })
class ExampleComponent {
	@Input() disabled: boolean
}
```

Property: `'disabled'`
Type: `string | boolean | null | undefined`
```ts
@Component({ selector: 'example-component' })
class ExampleComponent {
	@Input() disabled

	static ngAcceptInputType_disabled: string | boolean | null | undefined
}
```

**Comment by shilman** [comment]
Thanks @klemenoslaj appreciate your hard work and patience on this. @Marklb if you can help get #12736 into a good state, I'd be happy to review and test once you both sign off on it!

**Comment by klemenoslaj** [comment]
@Marklb yes, that sounds perfect! My goal was to get on some kind of parity with compodoc. What you're suggesting is bounds and leaps better than current state with compodoc and I really like that :+1:

**Comment by Marklb** [comment]
Another Angular specific feature that `compodoc` has and I can see being useful is the `--disableLifeCycleHooks` option. I always add `/** @ignore */` above my lifeCycleHooks, because I forgot `compodoc` had the option to exclude them. It isn't too important though, since I think that could probably be managed through an args filter by Storybook and then users could decide if they want them filtered out globally or per story.

---

Also, I do like seeing that alternate tools can be plugged in without too much being changed in Storybook's code. I am still hesitant to say if this could replace `compodoc` yet. I am all for it being supported as an alternative for now though. If more tools are requested, or one of these start having issues that require consistent individual maintenance, then it may be better to just support one with a common interface that others could use though.

I saw where `compodoc` did have some activity a little over a week ago. It looks like he is focusing on a rewrite, which could be good for us if it makes adding features, like watch mode to the json output, easier, but no idea how long it will take or if it is going to be actively updated yet. If issues stop getting ignored, maybe people will start contributing to it though.

**Comment by klemenoslaj** [comment]
> I am still hesitant to say if this could replace compodoc yet. I am all for it being supported as an alternative for now though

I share these thoughts. And even if we'd wanna replace compodoc, we couldn't do it without a major release anyway. So alternative for me sounds great :+1:
That way there is as well more time to iron out some rough edges and give compodoc some time to maybe get back to reasonable state.

**Comment by shilman** [comment]
Rather than trying to be tricky about it, I'd rather make it opt-in.

Here's what we do for React https://storybook.js.org/docs/react/configure/typescript#mainjs-configuration

```js
module.exports = {
  typescript: {
    reactDocgen: 'react-docgen-typescript', // | 'react-docgen'
  }
}
```

We could do the same thing for Angular:

```js
module.exports = {
  typescript: {
    angularDocgen: 'compodoc', // | 'typedoc'
  }
}
```

In 7.0 we could switch the default to `typedoc` if we feel that's the way forward, and deprecate `compodoc`.

**Comment by klemenoslaj** [comment]
Cool :+1: I will look into this. Thanks for the suggestion.

**Comment by manuelmeister** [comment]
I would still be interested in this feature

**Comment by tommyc38** [comment]
It seems currently (6.1) Storybook is only able to display classes in the argsTable despite compodoc parsing types, enums, and interfaces.  Is that accurate?

Moreover, would typedoc be able to parse everything including Angular specific metadata?

**Comment by shilman** [comment]
@tommyc38 PRs welcome!

**Comment by literalpie** [comment]
FYI, Compodoc just made a release for the first time in over a year 🎊

**Comment by vogloblinsky** [comment]
> FYI, Compodoc just made a release for the first time in over a year 🎊

And three more since 😉

Open-source maintainer job can be difficult to manage with personal life etc... but the project is not dead !

**Comment by klemenoslaj** [comment]
> > FYI, Compodoc just made a release for the first time in over a year 🎊
> 
> And three more since 😉
> 
> Open-source maintainer job can be difficult to manage with personal life etc... but the project is not dead !

Yes, 100%. It's a completely selfless thing and one should not expect from maintainer to not have life, so there should absolutely never be any kind of blaming.

At the time when I created an issue there were a lot of problems a
