### ISSUE TITLE
Denial of Service and XSS vulnerabilities reported by Snyk

### ISSUE THREAD

**Issue by dpouliot** [storybookjs/storybook#12720]
✗ Denial of Service [Medium Severity][https://snyk.io/vuln/SNYK-JS-NODEFETCH-674311] in node-fetch@2.6.0
  introduced by @storybook/addon-docs@6.0.26 > @storybook/core@6.0.26 > node-fetch@2.6.0 and 2 other path(s)
This issue was fixed in versions: 2.6.1, 3.0.0-beta.9
✗ Cross-site Scripting (XSS) [High Severity][https://snyk.io/vuln/SNYK-JS-PRISMJS-597628] in prismjs@1.17.1
  introduced by @storybook/addon-a11y@6.0.26 > @storybook/components@6.0.26 > react-syntax-highlighter@12.2.1 > refractor@2.10.1 > prismjs@1.17.1 and 9 other path(s)
This issue was fixed in versions: 1.21.0

**Comment by KSJake** [comment]
react-syntax-highlighter should be upgraded to at least [13.3.1](https://github.com/react-syntax-highlighter/react-syntax-highlighter/blob/master/CHANGELOG.MD#1331--2020-08-08). I assume this hasn't been done yet because of [the breaking changes introduced in v13.0.0](https://github.com/react-syntax-highlighter/react-syntax-highlighter/blob/master/CHANGELOG.MD#breaking-changes).

**Comment by shilman** [comment]
react-syntax-highlighter is 13.5.0 in 6.1

**Comment by tylercraft** [comment]
Doesn't appear that the addons have been updated, for example:
https://github.com/storybookjs/storybook/blob/master/addons/storysource/package.json

**Comment by shilman** [comment]
6.1 is the `next` branch:

https://github.com/storybookjs/storybook/blob/next/addons/storysource/package.json
