### ISSUE TITLE
General Questions about Story creation.

### ISSUE THREAD

**Issue by PaulieScanlon** [storybookjs/storybook#12752]
**Is your feature request related to a problem? Please describe**
This is more of a docs question than a feature but... in the docs you reference the following approach to creating stories

```javascript
export const DocsExample = Template.bind({});

DocsExample.parameters = {
  docs: {
    description: {
      story:
        'This story is created using `Template.bind({})` and uses Storybook to generate the code snippet'
    }
  }
};

DocsExample.args = {
  onClick: (event) => action('onClick')(event)
};
```

**Describe the solution you'd like**
Is there a reason for the `Template.bind({})` approach is recommended beyond the sensible method that it reduces duplicated code. I was wondering if there's a reason behind the docs not showing examples of other ways to acheive this.

**Describe alternatives you've considered**
I prefer this approach, even though it means a few things per story may need to be duplicated

And i'm wondering if there's a reason for using the `Template.bind({})` approach rather than

```javascript
export const AlternativeExample = (args) => (
  <DrButton onClick={(event) => args.handleClick(event.currentTarget)}>
    Click Me
  </DrButton>
);

AlternativeExample.parameters = {
  docs: {
    description: {
      story:
        'This story is created without using `Template.bind({})` with additional args added'
    }
  }
};

AlternativeExample.args = {
  handleClick: (event) => action('handleClick')(event)
};
```

**Are you able to assist to bring the feature to reality?**
I'm happy to create example docs for both methods

**Additional context**
There are also a number of other keys to the `docs` object that to the best of my knowledge can't be found in the docs.

For example, the default story can have a `componentSubtitle`

```javascript
export default {
  title: 'components/DrButton',
  parameters: {
    component: DrButton,
    componentSubtitle:
      'DrButton is a JavaScript component and is of html type button'
  }
};

export const Usage = () => <DrButton>Click me</DrButton>;

```
And perhaps example of decorators attached to stories might also be helpful

```javascript
export const AnotherStory = () => <DrButton>Click me</DrButton>;

AnotherStory.parameters = {
  docs: {
    description: {
      story:
        'This stories decorator is a div with a grey background and 16px padding'
    }
  }
};

AnotherStory.decorators = [
  (Story) => (
    <div style={{ backgroundColor: '#f7f7f7', padding: '16px' }}>
      <Story />
    </div>
  )
];
```

And i think there are options also for hard-coding the code snippet using `docs.source.code` like this

```javascript

const Template = (args) => <DrButton {...args}>Click Me</DrButton>;

export const HardCodedExample = Template.bind({});

HardCodedExample.parameters = {
  docs: {
    description: {
      story:
        'This story is created using `Template.bind({})` and has a hard-coded source code snippet'
    },
    source: {
      code: '<DrButton onClick={() => {}}>Click Me</DrButton>'
    }
  }
};

HardCodedExample.args = {
  onClick: (event) => action('onlick')(event)
};
```

I appreciate there's quite a few ways to do this so it's not a slam on the docs, you know i love you guys! 💛

I'm happy to help coming up with a few more examples if you think it would help users... or perhaps its because you plan to deprecate certain methods in the future?

I'm cool either way, lemme know if i can help!

**Comment by shilman** [comment]
Hi @PaulieScanlon, thanks so much for the question and also offering to help!

The rationale for Template.bind({}) is that we wanted a stylized way to create and copy a story function that was pure JS without requiring additional libraries (one of the goals of CSF).

The current recommendation:
- Shares code between stories when needed, which is esp useful in non-React frameworks
- Works in both CSF and MDX
- Is stylized so that we can write AST transformations that recognize this structure in the future (e.g. if we wanted a codemod to generate https://github.com/storybookjs/storybook/issues/12654)
- Is only slightly weird 😅 

As for addon-docs, the irony of its poor documentation is not lost on me. I started a branch to fix it as part of 6.0 and then got swamped getting the release out.

There's a more general problem here. Here are several versions of the same project that would be super helpful:

**SMALL**: Document the parameters for `addon-docs` and ideally all of the essential addons in markdown tabular reference documents as part of the docs site 

**MEDIUM**: Fix the typescript types as necessary for the parameters for all the essential addons. Use `tsdoc` or some other tool to generate the same tables programmatically

**LARGE**: Same as medium, but also figure out how to integrate it into `addon-docs`, so that this kind of API documentation can be embedded in an MDX Doc block.

Would be incredible to get help on any of these things! cc the amazing @jonniebigodes who's working wonders on our documentation.

**Comment by PaulieScanlon** [comment]
@shilman Hey mate, thanks for the response. Corrr, this sounds like a big ol job! 

Ah yes i was only thinking about React, however, i'd like to write a blog post first and wanted to double check if there were any mega issues with **not** using `Template.bind({})`... sounds like there isn't, and you say it's only slightly weird 😂

I think it might be useful if there is some documentation around this as i've worked on a few new OS projects recently that use Storybook and they are all using `Template.bind({})`, in various ways and even when they don't have to which makes the `.stories` look way more confusing than they have to be. 

Not that its for you to worry about but for a Hacktoberfest project inviting users to contribute and write extra stories its mad how overly complicated `Template.bind({})` can make stories look, i'd like to focus on lowering the barrier to entry and write about how some of the above approaches can be used to make docs and code snippets a really helpful part of any project.

I might throw in some bad examples, particularly really mad looking "Show code" snippets because people have chucked a ton of UI around the thing they want to show instead of using a nice decorator that is hidden in the "Show code" snippet.

Maybe i'll crack on and write it and perhaps ping it back on here for you to read if you're interested. Following on from that i could reach out to @jonniebigodes with some talking points.

How's that sound?

Thanks again!

**Comment by shilman** [comment]
@PaulieScanlon sorry for the slow response on this. I guess this is in your rear view mirror at this point!

**Comment by jonniebigodes** [comment]
Closing this as it's in the rear window as so eloquently put in the comment above. Feel free to reach out to me for any further feedback or improvements.

Stay safe
