### ISSUE TITLE
Storybook Vue components could not be destroyed

### ISSUE THREAD

**Issue by changqingom** [storybookjs/storybook#12944]
**Describe the bug**
I have two stories for my comp.one MDX file does not have a Canvas component, only used as a markdown file. Another MDX file is a vue component story.
 
 If route from vue story to markdown story, the vue story page's component could not execute component Lifecycle Hooks
 
 My component is an animation component. does not destroy it before jumping from it could get some error.

**To Reproduce**
![image](https://user-images.githubusercontent.com/33093289/97540584-cc9a8b80-19fe-11eb-97ba-bbf08cadaff2.png)

**Comment by SebCorbin** [comment]
I would like to know if there is a hook or a way to execute something when a vue component is unmounted too...

**Comment by pocka** [comment]
I (probably) found the root cause but couldn't write a patch because I have no idea how the Storybook core works... hope someone familiar with `app/` takes care of this 🙏 

---

`@storybook/vue` keeps the rendered story when a user switches from Canvas to Docs tab.

<img width="494" alt="Screen Shot 2021-07-19 at 1 37 42" src="https://user-images.githubusercontent.com/13316015/126075190-0cbcaf04-fb30-4eb9-ba6b-c9cfaca8a55c.png">

It seems that `@storybook/react` and `@storybook/angular` unmount the Canvas component at switching (https://github.com/storybookjs/storybook/pull/8625, https://github.com/storybookjs/storybook/pull/15160). Therefore other frameworks may have the same problem (Story emits destroy/unmount event at incorrect timing).

I think the best solution for this is "unmount the story component when `#root[hidden="true"]`", I don't know how though.

**Comment by 01oseluiz** [comment]
up
