### ISSUE TITLE
Manager build caching not working

### ISSUE THREAD

**Issue by tmeasday** [storybookjs/storybook#13076]
**Describe the bug**
Rerunning storybook rebuilds manager each time

**To Reproduce**
Try Chromatic `next` branch.

**Comment by tmeasday** [comment]
False alarm I think

**Comment by ChristianIvicevic** [comment]
Just saw this issue, I have a feeling that Storybook is generally rebuilding more than necessary. Sorry for hijacking this issue but I wanted to share my input.

Ever since upgrading from React 16 to React 17 (to be more specific CRA 3.4 to CRA 4 and Typescript 3.9 to Typescript 4.0.5) my rebuild times have exploded. The same behavior happens with Storybook 6.0.26-28 and 6.1-beta, so I am thinking it has to do with the CRA/Storybook integration. Basically even changing a single SCSS variable caused a rebuild in about 300ms, not every small change causes a longer rebuild of 5-10s. It feels as if my entire project it rebuilt.

How may I help you debug this issue? Are the webpack outputs between rebuilds any help?

**Comment by shilman** [comment]
@ChristianIvicevic can you open a separate issue for this?

**Comment by ChristianIvicevic** [comment]
@shilman Issue is at #13135
