### ISSUE TITLE
Default Vue Webpack config does not support `scoped` styles

### ISSUE THREAD

**Issue by blowsie** [storybookjs/storybook#13087]
**Describe the bug**
vue-loader provides[ scoped css functionality](https://vue-loader.vuejs.org/guide/scoped-css.html#mixing-local-and-global-styles).
The default webpack config for storybook vue does carry over support for scoped styles.

**To Reproduce**
Use scoped styles that have duplicated class names in more than one component
ComponentOne.vue
```vue
<template>
 <p class="example">
 </p>
</template>
<style scoped>
.example {
  color: red;
}
</style>
```
ComponentTwo.vue
```vue
<template>
 <p class="example">
 </p>
</template>
<style scoped>
.example {
  color: blue;
  font-weight:bold;
}
</style>
```

**Expected behaviour**
Scoped styles to work

**Screenshots**

**Code snippets**
as above

**System**
```λ npx sb@next info

Environment Info:

  System:
    OS: Windows 10 10.0.18363
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Binaries:
    Node: 10.16.3 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 86.0.4240.183
    Edge: Spartan (44.18362.449.0)

```

**Additional context**

**Comment by blowsie** [comment]
I tried adding vue-loader manually but had the same error described here.
https://github.com/storybookjs/storybook/issues/6932

**Comment by sebalaini-itm** [comment]
same here when trying to upgrade some other dependencies, I've posted a comment in #6932

**Comment by blowsie** [comment]
Right now, I'm having to nest a lot of classes to prevent this storybook issue. It's a fairly important topic for any vue user using storybook. Can we have this issue added to a priority. roadmap?

**Comment by pocka** [comment]
@blowsie Could you make the issue more specific?

- **To reproduce** ... How you use the components? Any reproduction repo?
- **Expected behaviour** ... ex) each `<p>` tag has different data hash
- What is the actual result? ... ex) both `<p>` tag has same data hash

...and additional Vue specific ones (these would help us diagnose the bug a lot!):
- Do your DOM nodes on Storybook have `data-v-<component hash>`?
- Do the generated CSS rules have `data-v-<component hash>`?

AFAIK, there is no option to disable/modify scoped CSS feature so I believe the problem lies in runtime codes (preview).

If the components are in a parent-child relationship and the parent's style affecting the child's one, it works as intended ("scoped CSS" is not scoped in the way many devs think...)
https://github.com/vuejs/vue-loader/issues/957

**Comment by blowsie** [comment]
@pocka There is no hashes found on the nodes.

I can create a repro on an empty vue/storybook project using the examples above if required.

**Comment by pocka** [comment]
@blowsie 
Thanks for the information! I checked the vue-kitchen-sink but it does not use scoped CSS :/

Reproduction is greatly helpful 👍 Would you create one?

**Comment by pocka** [comment]
Cannot reproduce.

<details>
<summary>What I tried (works fine)</summary>

Modified `vue-kitchen-sink` on `next` branch (6.3.0-beta.4)

```vue
<!-- stories/Child1.vue -->
<template>
  <span class="child">Child1</span>
</template>

<style scoped>
.child {
  font-weight: bold;
}
</style>
```

```vue
<!-- stories/Child2.vue -->
<template>
  <span class="child">Child2</span>
</template>

<style scoped>
.child {
  font-style: italic;
}
</style>
```

```vue
<!-- stories/Button.vue -->
<template>
  <button ...>
    <Child1/>
    <Child2/>
    <slot/>
  </button>
</template>

<!-- Also registered Child components -->
```

Result: both styles and `data-v-*` hash worked fine.

</details>

Please post a comment with both repro and an expected behaviour if you believe the bug still exists.
