### ISSUE TITLE
Not started storybook on existing project

### ISSUE THREAD

**Issue by oleksandrhodzevych** [storybookjs/storybook#13085]
If you are reporting a bug or requesting support, start here:
### Bug or support request summary

Install storybook for exist project and can not run storybook

### Steps to reproduce
main.js :
```
module.exports = {
  "stories": [
    "../src/**/*.stories.@(js|jsx|ts|tsx)"
  ],
  "addons": [
    "@storybook/addon-links",
    "@storybook/addon-essentials"
  ]
}
```

npm run storybook 
Have error:

```
info => Loading presets
WARN   Failed to load preset: "D:\\Projects\\mhc\\....\\node_modules\\@storybook\\vue\\dist\\server\\framework-preset-vue.js"
ERR! Error: Cannot find module 'vue-loader/lib/plugin'
ERR! Require stack:
```

### Please specify which version of Storybook and optionally any affected addons that you're running

- @storybook/vue

**Comment by elevatebart** [comment]
Hello @oleksandrhodzevych 

It could be that the version of vue-loader you are using now is not compatible with your version of storybook.
It might be that you are not even using vue-loader because you are running vite.

Would you please share the complete version number of 3 modules
- `vue`
- `@storybook/vue`
- `vue-loader`

Since storybook is going to rely on your webpack config for building the examples, is it possible you share the contents of your webpack config as well?

**Comment by oleksandrhodzevych** [comment]
> Hello @oleksandrhodzevych
> 
> It could be that the version of vue-loader you are using now is not compatible with your version of storybook.
> It might be that you are not even using vue-loader because you are running vite.
> 
> Would you please share the complete version number of 3 modules
> 
> * `vue`
> * `@storybook/vue`
> * `vue-loader`
> 
> Since storybook is going to rely on your webpack config for building the examples, is it possible you share the contents of your webpack config as well?

Thank You, @elevatebart! 
Main problem with vue-loader version.
It should be "vue-loader": "^15.9.5".
