### ISSUE TITLE
Hash is being removed from iframe URL

### ISSUE THREAD

**Issue by Hypnosphi** [storybookjs/storybook#13273]
It's a regression introduced in 6.1

see https://github.com/storybookjs/storybook/issues/11677#issuecomment-707709420

Open https://next--storybookjs.netlify.app/official-storybook/iframe.html?id=addons-docs-buttongroup--basic&viewMode=story#anchor

Hash should remain there

**Comment by tmeasday** [comment]
@Hypnosphi are you sure this wasn't in 6.0?

**Comment by Hypnosphi** [comment]
Maybe it was, but for some reason it didn't manifest itself in our case cc @andrey-skl

**Comment by andrey-skl** [comment]
Sorry everybody for misleading. I checked again and found that:

Yes, the hash was stripping in 6.0 (6.0.28). But it did not affect our case because it was stripped a little bit after sroty initialization.

For example, if I open `http://localhost:9999/iframe.html?id=components-button--basic#test` with storybook@6.0.28 and log window.location in the first line of the story, it is: `http://localhost:9999/iframe.html?id=components-button--basic#test`

With 6.1.0-rc.0 it logs: `http://localhost:9999/iframe.html?id=components-button--basic&viewMode=story`

**Comment by tmeasday** [comment]
Ahh, ok. My guess is the difference is the new loaders feature which adds a `await` into the story render process (awaiting nothing usually), which probably rearranges the execution of some code.

**Comment by shilman** [comment]
Huzzah!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.1.8 containing PR #13308 that references this issue. Upgrade today to the `@latest` NPM tag to try it out!

```
npx sb upgrade
```

Closing this issue. Please re-open if you think there's still more to do.

**Comment by andrey-skl** [comment]
@shilman @Hypnosphi thanks a lot for a quick fix, our case works perfect so far!
