### ISSUE TITLE
Error following react tutorial instructions

### ISSUE THREAD

**Issue by Oisangui** [storybookjs/storybook#13396]
**Describe the bug**
React not defined error after doing the following from the storybook react tutorial in [here](https://www.learnstorybook.com/intro-to-storybook/react/en/get-started/):

![image](https://user-images.githubusercontent.com/48262842/101432385-7ff07d00-38e7-11eb-93d3-494e28759319.png)

**To Reproduce**

```# Create our application:
npx create-react-app taskbox

cd taskbox

# Add Storybook:
npx -p @storybook/cli sb init

# change versions according to instructions

yarn remove react
yarn add react@16.14.0

yarn remove react-dom
yarn add react-dom@16.14.0

yarn remove react-scripts
yarn add react-scripts@3.4.3

```

To see error, run ```yarn test --watchAll```

See error ```ReferenceError: React is not defined```

**Expected behavior**

All tests should Pass.

**Screenshots**

![image](https://user-images.githubusercontent.com/48262842/101432775-3c4a4300-38e8-11eb-8b02-4c24d7f20506.png)

**System**
Results of `npx sb@next info`:
Environment Info:
```
  System:
    OS: Linux 5.4 Ubuntu 18.04.5 LTS (Bionic Beaver)
    CPU: (4) x64 Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz
  Binaries:
    Node: 12.16.2 - ~/.nvm/versions/node/v12.16.2/bin/node
    Yarn: 1.22.5 - ~/.yarn/bin/yarn
    npm: 6.14.4 - ~/.nvm/versions/node/v12.16.2/bin/npm
  Browsers:
    Chrome: 87.0.4280.66
    Firefox: 83.0```

**Comment by jonniebigodes** [comment]
@Oisangui this is not actually related to Storybook, but rather a React/CRA issue. That note introduced to downgrade React and React-scripts was to allow you to follow the tutorial without getting blocked. As with the release of React 17 it sparked some issues with Storybook (which are now fixed with the latest version). To give you a bit more context when you ran `npx create-react-app taskbox` it created the project with the latest version of the packages, and with React 17 there's a little nuance to it. It infers automatically the imports, more specifically the `import React from 'react' `. As you're now using a previous version you have 2 choices:
- Remove the test file.
- Add the `import React from 'React'` in the test file.

I wasn't able to get around and update the tutorial accordingly because i had to shift my attention to other documentation related tasks. If you don't mind. I'm going to close this issue and if you can open a new issue in the [LearnStorybook tutorial repo](https://github.com/chromaui/learnstorybook.com) and ping me so that we don't lose track of this.

Sounds good? 

Stay safe
