### ISSUE TITLE
Code snippets with material UI children not rendering correctly

### ISSUE THREAD

**Issue by brockwei** [storybookjs/storybook#13391]
**Describe the bug**
When I pass a MaterialUI component to a story as a child, it doesn't generate the code snippet correctly

**To Reproduce**
Import:
```
import Card from '@material-ui/core/Card';
```
Story:
```
import React from 'react';
// also exported from '@storybook/react' if you can deal with breaking changes in 6.1
import { Story, Meta } from '@storybook/react/types-6-0';
import Card from '@material-ui/core/Card';
import { Overlay, IProps } from './Overlay';

export default {
  title: 'Display/Overlay',
  component: Overlay,
  argTypes: {},
  parameters: {
    docs: {
      inlineStories: true,
    }
  },
} as Meta;

const Template: Story<IProps> = (args) => (
  <Overlay {...args}>
    <Card style={{ padding:'12px' }}>
      Dummy Text
    </Card>
  </Overlay>
);

export const Basic = Template.bind({});
Basic.args = {};
```

**Expected behavior**
```
<Overlay>
  <Card
    style={{
      padding: '16px'
    }}
  >
    Dummy Text
  </Card>
</Overlay>
```
**Actual behavior**
```
<Overlay>
  <WithStyles(ForwardRef(Card))
    style={{
      padding: '16px'
    }}
  >
    Dummy Text
  </WithStyles(ForwardRef(Card))>
</Overlay>
```

**System**
    OS: macOS 11.0.1
    CPU: (8) x64 Intel(R) Core(TM) i7-8557U CPU @ 1.70GHz
  Binaries:
    Node: 14.13.0 - /usr/local/bin/node
    Yarn: 1.22.5 - /usr/local/bin/yarn
    npm: 6.13.4 - /usr/local/bin/npm
  Browsers:
    Chrome: 87.0.4280.88
    Firefox: 82.0.3
    Safari: 14.0.1
  npmPackages:
    @storybook/addon-actions: ^6.1.10 => 6.1.10 
    @storybook/addon-essentials: ^6.1.10 => 6.1.10 
    @storybook/addon-links: ^6.1.10 => 6.1.10 
    @storybook/node-logger: ^6.1.10 => 6.1.10 
    @storybook/preset-create-react-app: ^3.1.5 => 3.1.5 
    @storybook/react: ^6.1.10 => 6.1.10

**Comment by nikolaidk** [comment]
Any news on this problem?

**Comment by AdrianSoovary8234** [comment]
Is this being recognized an worked on? This is a major roadblocker for my team using MUI-components with Storybook...

**Comment by maxigarciaf** [comment]
I'm having the same issue? Any news about that?

**Comment by shilman** [comment]
This is the documented behavior of the source block. see the `docs.source.type` parameter here: https://storybook.js.org/docs/react/writing-docs/doc-blocks#source


I think the issue is that `<WithStyles(ForwardRef(IconButton)) color="inherit">` should render as `<IconButton color="inherit" />`, which would be some kind of custom dynamic snippet rendering specifically for MUI. Given MUI's popularity, I'd gladly accept a PR for that.

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
