### ISSUE TITLE
Angular-MDX-Docs:  Only the first five stories in an MDX file are rendering in Docs tab

### ISSUE THREAD

**Issue by tommyc38** [storybookjs/storybook#13537]
**Describe the bug**

Only the first five stories are appearing in Docs. Specifically, if there are more than five stories in a single MDX file, only the first five seem to appear. Also, if you click on a story that didn't render in the side navigation, it won't scroll to that story. Lastly, if you click on the Canvas tab then back to Docs, it will sometimes render stories that did not render before.

**To Reproduce**

Repro: https://github.com/tommyc38/nx-storybook-nest-repro

1.) Install plugins and then `npm run storybook-core`
2.) Navigate to Docs in Storybook for Icon ---> notice only first five components are built.

**Expected behavior**
I would expect all stories in an MDX file to render in Docs.

**System**

```
  System:
    OS: macOS High Sierra 10.13.6
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
  Binaries:
    Node: 10.14.2 - ~/.nvm/versions/node/v10.14.2/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.10 - ~/.nvm/versions/node/v10.14.2/bin/npm
  Browsers:
    Chrome: 87.0.4280.88
    Firefox: 68.0.1
    Safari: 13.1.2
  npmPackages:
    @storybook/addon-docs: ^6.1.11 => 6.1.11 
    @storybook/addon-knobs: ^6.1.11 => 6.1.11 
    @storybook/angular: ^6.1.11 => 6.1.11 
```

**Additional context**
I didn't have this issue in Storybook version 5.3 but do in 6

**Comment by shilman** [comment]
@tommyc38 I suspect this is an issue related to your browser, and not an issue with Storybook 6 per se.

My experience running your repro in Chrome 87.0.4280.88 on MacOS Mojave 10.14.6:
- I opened the page and saw the first five stories loaded
- I went to dev tools to inspect the DOM
- The sixth and seventh stories loaded
- I closed the page and reopened, and all stories loaded

Each instance of Storybook/Angular inside the iframe is heavy. We are actively working on:
- Reducing the bundle size e.g. #13479
- Angular inline rendering support #13525 #11339

Hopefully some combination of these two will fix the problem. Perhaps you can try out 6.2-alpha which already contains more bundle optimizations?

```
npx sb upgrade --prerelease
```

**Comment by tommyc38** [comment]
@shilman I upgraded but had the same result.  I also checked the DOM in dev tools but the stories never loaded--see screenshot.

![Screen Shot 2020-12-29 at 8 38 11 PM](https://user-images.githubusercontent.com/10190567/103328372-ea439b80-4a15-11eb-9be6-c25e7688cfe6.png)

**Comment by tommyc38** [comment]
@shilman It looks like a browser issue.  I just tried Safari and had no issue...load times were much faster as well.

**Comment by daeteck** [comment]
Same issue here. In Safari all the stories are rendered but not in the latest Chrome or Firefox. This issue started in the past 3 or 4 versions of Storybook Essentials, because I remember that when I did the documentation all the stories was rendering properly. Also some time the refresh button in Chrome and Firefox stop working, like the browser is executing an script in the background. 
Sorry that I can't give more information that this because I'm not finding the cause, but I know that it will be hard to debug because it seems related a browser limitation.

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).

FWIW I'm pretty sure this is no longer an issue in 7.0+
