### ISSUE TITLE
Is there a way to asynchronously fill select options in 'controls'?

### ISSUE THREAD

**Issue by slavoroi** [storybookjs/storybook#13574]
We are using the web components storybook:
` "@storybook/web-components": "6.1.10"`

We have a code in a story:
```
export default {
  title: 'Icon',
  component: TAG_NAME,
  argTypes: {
    icon: {
      control: {
        type: 'select',
        options: iconNames
      }
    }
  }
}
```
Can we fill `iconNames` asynchronously?
I tried loaders with no success.

**Comment by shilman** [comment]
Not currently. We could add it without a lot of work but we're not comfortable supporting that API.

**Comment by ghengeveld** [comment]
In 6.2, `control.options` was deprecated in favor of `options` (one level up) and superceded by `control.labels`.

Are you looking to have async `options` or `control.labels`? The latter should be fairly straightforward (like a "lazy" component in React). The former would be more involved because `options` are enforced in Storybook core (specifically the story store). We would have to await the value upon opening your Storybook (regardless of what story is being viewed), making your Storybook slower to load. I don't think we want to go there to be honest.

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
