### ISSUE TITLE
h is not defined - implementing Storybook into React app

### ISSUE THREAD

**Issue by bodenloszt** [storybookjs/storybook#13635]
**Describe the bug**
After playing around with Storybook in a new created project I decided to try and apply it to a bigger project but "h is not defined" stops me right away.

`h is not defined
ReferenceError: h is not defined
    at FirstButton (http://10.96.15.71:6006/main.355e3d622e76c69bbb11.bundle.js:332:3)
    at finalStoryFn (http://10.96.15.71:6006/vendors~main.355e3d622e76c69bbb11.bundle.js:21477:32)
    at http://10.96.15.71:6006/vendors~main.355e3d622e76c69bbb11.bundle.js:17044:21
    at http://10.96.15.71:6006/vendors~main.355e3d622e76c69bbb11.bundle.js:19716:14
    at wrapper (http://10.96.15.71:6006/vendors~main.355e3d622e76c69bbb11.bundle.js:15910:12)
    at http://10.96.15.71:6006/vendors~main.355e3d622e76c69bbb11.bundle.js:17562:14
    at http://10.96.15.71:6006/vendors~main.355e3d622e76c69bbb11.bundle.js:17576:26
    at http://10.96.15.71:6006/vendors~main.355e3d622e76c69bbb11.bundle.js:17044:21
    at http://10.96.15.71:6006/vendors~main.355e3d622e76c69bbb11.bundle.js:19709:12
    at http://10.96.15.71:6006/vendors~main.355e3d622e76c69bbb11.bundle.js:19716:14`

**Code snippets**
**button.js**
```
import { h } from "preact";
import { Link } from "preact-router/match";

const hrefIsValid = href => /^https?:\/\//.test(href);

const ButtonComponent = props => {
    const Element = hrefIsValid(props.href) ?  <a {...props} />: Link;

    const extraProps = {
        href: props.href ? props.href : null,
        target: props.target ? props.target : null
    };

    if (props.onClick) {
        extraProps.onClick = props.onClick;
    }

    return (
        <Element {...extraProps} className={`button ${props.type}`}>
            {props.children}
        </Element>
    );
};

export default ButtonComponent;
```

**button.stories.js**
```
import React from "react";
import ButtonComponent from "./button";

export default {
    title: "Button",
    component: ButtonComponent
};

export const FirstButton = () => (
    <ButtonComponent type="button" href="https://google.com" target="_blank" onClick={null}>
        FirstButton
    </ButtonComponent>
);

export const SecondButton = () => (
    <ButtonComponent type="button" href="https://google.com" target="_blank">
        SecondButton
    </ButtonComponent>
);

export const ThirdButton = () => (
    <ButtonComponent type="button" href="https://google.com" target="_blank">
        ThirdButton
    </ButtonComponent>
);
```

**System**
```
System:
    OS: Windows 10 10.0.18363
    CPU: (8) x64 Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz
  Binaries:
    Node: 12.18.2 - C:\Program Files\nodejs\node.EXE
    npm: 6.14.5 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 86.0.4240.198
    Edge: Spartan (44.18362.449.0)
  npmPackages:
    @storybook/addon-actions: ^6.1.14 => 6.1.14
    @storybook/addon-essentials: ^6.1.14 => 6.1.14
    @storybook/addon-links: ^6.1.14 => 6.1.14
    @storybook/preact: ^6.1.14 => 6.1.14
```

**Additional context**
I pretty much didn't customize Storybook at all. Performed a fresh instalation of it and jumped straight ahead on adding the button.stories.js

This problem could be caused by the complexity of the project I work on and I'm pretty sure I do miss something really obvious.

**Comment by jonniebigodes** [comment]
@bodenloszt i've picked up on your issue and a couple of things jumped right away. Let me go into detail.

In your description you're mentioning preact correct? Then your `button.stories.js` should be something like:
```js

/** @jsx h */
import { h } from "preact"; 
import ButtonComponent from "./button";

export default {
  title: "Example/ButtonComponent",
  component: ButtonComponent,
};

export const FirstButton = () => (
  <ButtonComponent
    type="button"
    href="https://google.com"
    target="_blank"
    onClick={null}
  >
    FirstButton
  </ButtonComponent>
);

export const SecondButton = () => (
  <ButtonComponent type="button" href="https://google.com" target="_blank">
    SecondButton
  </ButtonComponent>
);

export const ThirdButton = () => (
  <ButtonComponent type="button" href="https://google.com" target="_blank">
    ThirdButton
  </ButtonComponent>
);

```
Preact works a bit differently from React and how you setup your stories. See the difference? In your story you're including the React version but in this case you should be using the Preact.

Also something curious about your component implementation, using the code you've supplied i'm facing the following when i start storybook with `npm run storybook` and applying the changes to the appropriate story file:

![storybook-preact-eror-dev](https://user-images.githubusercontent.com/22988955/104649165-30525d80-56ac-11eb-8ada-f159e6ded3f3.png)
![storybook-preact-eror-ui](https://user-images.githubusercontent.com/22988955/104649174-334d4e00-56ac-11eb-93f9-bdbe76de25bd.png)

I was curious and logged what was the value of `Element` and i'm getting the following:

![component-log](https://user-images.githubusercontent.com/22988955/104649458-ac4ca580-56ac-11eb-8f9e-b8ed79908a03.png)

I tinkered with the component's code and i was able to get a working component in Storybook. I've changed `button.js` to the following:
```js
import { h } from "preact";
import { Link } from "preact-router/match";

const hrefIsValid = (href) => /^https?:\/\//.test(href);

const ButtonComponent = (props) => {
    // sets the required props based on what's supplied to the component
  const extraProps = {
    href: props.href ? props.href : null,
    target: props.target ? props.target : null,
    onClick: props.onClick ? props.onClick : null,
    className: `button ${props.type}`,
  };
  // delete after testing
  console.log(hrefIsValid(props.href));
  console.log(Element);
  console.log(props.children);

  //conditionally render the proper element based off the function above.
  return hrefIsValid(props.href) ? (
    <a {...extraProps}>{props.children}</a>
  ) : (
    <Link {...extraProps}>{props.children}</Link>
  );
};

export default ButtonComponent;
```

With this change i get the following in Storybook:

![Working-component](https://user-images.githubusercontent.com/22988955/104649835-34cb4600-56ad-11eb-8fba-c965f37c8cf4.png)


Let me know if the comment helped you with your issue so that we can close it or continue to work on it until we have a solution.

Stay safe

**Comment by bodenloszt** [comment]
@jonniebigodes thanks for your input. Indeed that import of "React" was causing the issue.

Thank you for all the pieces of advice!
