### ISSUE TITLE
Session storage navigation toolbar hidden

### ISSUE THREAD

**Issue by BartJanvanAssen** [storybookjs/storybook#13799]
I was working on a storybook implementation, and somehow the toolbar was hidden, no way i could find in the UI to enable the toolbar again.. So i created new storybook in an new folder.. and still it was hidden! I had no clue how to fix it, but in the end i found my session storage had these options:

![image](https://user-images.githubusercontent.com/4742816/106720049-4ac08c80-6603-11eb-8085-b540a07ac066.png)

Can we please add a toggle for the toolbar?
![image](https://user-images.githubusercontent.com/4742816/106720310-9c691700-6603-11eb-921b-f476fe9d7be5.png)

**Comment by anwalkers** [comment]
Would be a great enhancement to afford the user a way to show the sidebar again without having to search issues on github and find out the shortcut to reopen the sidebar is "S" :) 

Could you use a "hamburger button" or add another icon to the header when the sidebar is closed that allows the user to reopen it?

**Comment by apapadopoulou** [comment]
Hello! Is anyone working on this?

**Comment by shilman** [comment]
@apapadopoulou it's all yours! 🚀

**Comment by apapadopoulou** [comment]
Hello!! I looked a bit into this and I was wandering where in the manager would be a good place to add the button. Some candidate places would be: 

1. The toolbar-However, if the toolbar is disabled or hidden, this would result in the button to be hidden as well.
2. On the right side of the panel where addons are registered. This could, however, cause a problem, if a user has many addons registered or if the orientation is changed.
3. Above the addons panel-if the orientation changes, the button would be moved on top of the addon column as well.
4. On top of the main panel. I think this would be the best place, because it is independent of the addons that the user has configured and it this place, it would also be more discrete and occupy less space, compared to the other options. In this case, we could also add more toggles and buttons for other components, like the toolbar or the addons panel in the future.

I could design some mockups for any of the above cases before implementing them.

Also, as for the button/toggle, I was thinking to design some variants and see what looks better.

**Comment by yannbf** [comment]
@domyen would you mind giving your input on this? ☝️ 
Happy to see more contributions from you @apapadopoulou!

**Comment by domyen** [comment]
Thanks @apapadopoulou, I'm stoked that you're picking this up.

Strawman UX:
1. **Menu**:  Add a link in the dropdown tooltip that shows the state of the Toolbar visibility 
2. **Toolbar**: When the sidebar is collapsed there's no way to see the menu to then  show the Toolbar. Add the `menu` icon to the left hand side of the toolbar when the sidebar is collapsed. (see below)

![image](https://user-images.githubusercontent.com/263385/119743224-68865b80-be57-11eb-98f3-fa96e2ffc1b0.png)

**Comment by yannbf** [comment]
Hey @domyen do I understand correctly that if the user is in full screen mode, the sidebar toggle icon should be present?
Then both the "exit fullscreen" mode and "toggle sidebar" would be present, right?

After #15369 was merged, that's not always the case. The button does not work if you are in fullscreen mode. I've got a fix for that already, however I'm wondering about the actual scenarios in combination with the toggle + fullscreen mode. Shall we define what flows make sense and maybe write a few tests to make sure we get it all right?

**Comment by shilman** [comment]
w00t!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.4.0-alpha.10 containing PR #15369 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.

**Comment by domyen** [comment]
@yannbf thanks for following up. 

**Strawman**
- Remove the full screen mode & its shortcuts in the menu and toolbar
- When the addon panel is hidden, show these icon buttons to open it. 
  - Display icon in the toolbar and swap which one is shown depending on orientation. 
  - ![image](https://user-images.githubusercontent.com/263385/125356082-985fc480-e31a-11eb-9ffa-320fa456f323.png) 
  - ![image](https://user-images.githubusercontent.com/263385/125356123-a4e41d00-e31a-11eb-91c8-4ed42a6af2c7.png)
- Change icon that toggles the sidebar 
  - From ![image](https://user-images.githubusercontent.com/263385/125356384-ff7d7900-e31a-11eb-868e-dc9dea619dd8.png)
  - To ![image](https://user-images.githubusercontent.com/263385/125356372-fbe9f200-e31a-11eb-84c1-12ca08a54942.png)

![outline-addon](https://user-images.githubusercontent.com/263385/125357414-7a935f00-e31c-11eb-933c-b9bdb85b60b6.png)


**Background**
Currently, fullscreen mode adds an extra layer of complexity that we keep running into whenever we make changes to the UI.  

Fullscreen mode is just a shortcut for `hiding sidebar && hiding addons`. It saves you one click when you'd have to do two. The idea behind it is to help developers focus on building the UI without the extra Storybook chrome. 

But the use case for full screen mode and "open canvas in new tab" mode is identical. In many ways, opening the canvas iframe is superior because it eliminates the Storybook DOM entirely.
