### ISSUE TITLE
Determine and set a `h1` element

### ISSUE THREAD

**Issue by adagar** [storybookjs/storybook#13796]
**Is your feature request related to a problem? Please describe**
For users using non-traditional means of navigation through a11y tools, the `h1` element is considered the title of the page. When users open storybook, what is considered the title? Is it the current element that is open? 

Currently, the element that appears as the `h1` header is an invisible error
![Screen Shot 2021-02-02 at 4 06 15 PM](https://user-images.githubusercontent.com/3698858/106663103-421f7600-6571-11eb-8fe9-6b81bf74c205.png)

**Describe the solution you'd like**
I'd like to see a header at the top of the page with the name of the chosen element and/or access tree (ex Basics < Document Formatting < With Markdown) so the purpose/content of the open webpage is immediately apparent.

**Describe alternatives you've considered**
To maintain visual clarity, an `h1` that is only present for screenreader users could be used
https://webaim.org/techniques/css/invisiblecontent/

**Are you able to assist to bring the feature to reality?**
yes, I can

**Additional context**

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid.

Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
