### ISSUE TITLE
Vue documentation has React examples

### ISSUE THREAD

**Issue by jordangunther** [storybookjs/storybook#13852]
**Describe the bug**
Many examples in the Vue documentation show React and not Vue examples

**To Reproduce**

1. Go to 'https://storybook.js.org/docs/vue/writing-docs/docs-page'
2. Scroll down to 'Remixing DocsPage using doc blocks'
3. See example is in React and not Vue. This issue is on many pages in the documentation.

**Expected behavior**
I expected the examples in the documentation to be in Vue as that was the selected framework.

**Screenshots**
Remixing DocsPage using doc blocks
![image](https://user-images.githubusercontent.com/14005131/107414040-b8226080-6ace-11eb-8959-36a430becf85.png)

**Comment by shilman** [comment]
Storybook Docs is implemented in React, so this is the correct way to customize it in Storybook for any framework including Vue. Please let us how we can better clarify that!

**Comment by jonniebigodes** [comment]
Closing this as the documentation covers most of the examples with Vue 2 , Vue 3, and MDX for all of the available code snippets. @jordangunther let me know if you need help or are willing to contribute and expand our documentation. 

Have a great weekend!

Stay safe

**Comment by Nabil-MEDIOUNI** [comment]
Hi there,

I've noticed that many examples in the Vue documentation are written in React instead of Vue, which can be confusing for users like me who are specifically looking for Vue examples.

I've attached a screenshot for reference. Could someone please guide me on how to render blocks in Vue, as the examples provided are in React?

Thank you for your attention to this matter.

![code](https://github.com/storybookjs/storybook/assets/54674189/c845e0ab-ee26-48e2-b416-00749c1e8b22)
