### ISSUE TITLE
What does the warning WARN unable to find package.json for rollup means?

### ISSUE THREAD

**Issue by rhuanbarreto** [storybookjs/storybook#14000]
**Describe the bug**
I receive the warning in the console every time i start a storybook for a library I'm creating:

WARN unable to find package.json for rollup

My dependencies in package.json:

```
"devDependencies": {
    "@babel/core": "^7.12.13",
    "@babel/preset-react": "^7.12.13",
    "@rollup/plugin-babel": "^5.2.3",
    "@rollup/plugin-json": "^4.1.0",
    "@storybook/addon-actions": "^6.1.17",
    "@storybook/addon-essentials": "^6.1.17",
    "@storybook/addon-links": "^6.1.17",
    "@storybook/react": "^6.1.17",
    "@typescript-eslint/eslint-plugin": "^4.15.1",
    "@typescript-eslint/parser": "^4.15.1",
    "babel-eslint": "^10.1.0",
    "babel-loader": "^8.2.2",
    "eslint": "^7.20.0",
    "eslint-config-react-app": "^6.0.0",
    "eslint-plugin-flowtype": "^5.2.0",
    "eslint-plugin-import": "^2.22.1",
    "eslint-plugin-jsx-a11y": "^6.4.1",
    "eslint-plugin-react": "^7.22.0",
    "eslint-plugin-react-hooks": "^4.2.0",
    "rollup": "^2.38.5",
    "rollup-plugin-commonjs": "^10.1.0",
    "rollup-plugin-delete": "^2.0.0",
    "rollup-plugin-generate-package-json": "^3.2.0",
    "rollup-plugin-node-resolve": "^5.2.0",
    "rollup-plugin-peer-deps-external": "^2.2.3"
  },
  "peerDependencies": {
    "lodash.filter": "^4.6.0",
    "lodash.orderby": "^4.6.0",
    "lodash.pickby": "^4.6.0",
    "prop-types": "^15.7.2",
    "react": "^17.0.1",
    "react-dom": "^17.0.1"
  }
```

**Comment by ckaethler** [comment]
^ Having the same error and would love some suggested solutions

**Comment by shilman** [comment]
Do you have a repro repo you can share?

**Comment by tihuan** [comment]
I have the same issue!

Please try: https://github.com/tihuan/components and run `yarn && yarn storybook` 🙏 

Thank you!

**Comment by sagic** [comment]
same here 🙋🏻‍♂️

**Comment by shilman** [comment]
This warning is being printed here: https://github.com/storybookjs/storybook/blob/next/lib/core-server/src/manager/manager-config.ts#L37

Storybook is going through your project's dependencies and trying to read the `package.json` to extract the `storybook` metadata from it in the case of component libraries with published storybook's. I don't know why this code can't find `rollup`'s `package.json`, but the warning can safely be ignored because `rollup` is not a component library and does not have said metadata.

**Comment by tihuan** [comment]
Ahh perfect! Thanks so much, @shilman 🤩 Can confirm that the components work as intended in the storybook even with the warning 👍 Have a wonderful day!

**Comment by zanona** [comment]
related #13099

**Comment by lotyp** [comment]
Problem still exists:

```
WARN unable to find package.json for @wayofdev/ui
```

when I'm running build in my monorepo:

```
turbo run build --filter=storybook --color --parallel

## or
pnpm --filter=storybook build:storybook
```

Repo is located here:

https://github.com/wayofdev/next-starter-tpl

**Comment by rexkenley** [comment]
Maybe related but I am getting 

info => Starting manager..
WARN unable to find package.json for @storybook/react-vite
WARN unable to find package.json for vite

And I don't use vite.

**Comment by musjj** [comment]
Still having this issue in a monorepo setup. Can this issue be reopened?

**Comment by hnrq** [comment]
Same here

**Comment by joshkel** [comment]
For my monorepo, I was able to resolve this by adding `package.json` to the [exports](https://nodejs.org/api/packages.html#subpath-exports) sections of package dependencies. The goal is to ensure that the equivalent of `require('package-storybook-complains-about/package.json')` works.

For example:

* My `@myapp/frontend` package depends on  my `@myapp/lib` package. 
* Storybook was warning, "unable to find package.json for @myapp/lib"
* @myapp/lib's package.json had an exports section similar to the following:
    ```json
    "exports": {
      ".": "./dist/index.js",
      "./*": "./dist/*.js"
    },
    ```
* To fix it, I added package.json, so that Storybook could successfully do the equivalent of `require('@myapp/lib/package.json')`:
     ```json
    "exports": {
      ".": "./dist/index.js",
      "./*": "./dist/*.js",
      "./package.json": "./package.json"
    },
    ```

**Comment by gimwachan-git** [comment]
> "./package.json": "./package.json"
I fixed it!!

**Comment by gimwachan-git** [comment]
> For my monorepo, I was able to resolve this by adding `package.json` to the [exports](https://nodejs.org/api/packages.html#subpath-exports) sections of package dependencies. The goal is to ensure that the equivalent of `require('package-storybook-complains-about/package.json')` works.
> 
> For example:
> 
> * My `@myapp/frontend` package depends on  my `@myapp/lib` package.
> * Storybook was warning, "unable to find package.json for @myapp/lib"
> * @myapp/lib's package.json had an exports section similar to the following:
>   "exports": {
>     ".": "./dist/index.js",
>     "./*": "./dist/*.js"
>   },
> * To fix it, I added package.json, so that Storybook could successfully do the equivalent of `require('@myapp/lib/package.json')`:
>   "exports": {
>    ".": "./dist/index.js",
>    "./*": "./dist/*.js",
>    "./package.json": "./package.json"
>   },

I fixed it!!
