### ISSUE TITLE
Error: "Codegen node is missing for element/if/for node. Apply appropriate transforms first." when using named slots in Vue3

### ISSUE THREAD

**Issue by TheDutchCoder** [storybookjs/storybook#14096]
**Describe the bug**
When using named slots in a Vue3 component, Storybook is unable to process template tags for targeting that slot.

**To Reproduce**
Consider the following story:
```js
export const CloseTemplate = (args) => ({
  components: { ClModal, ClIcon, ClButton },
  setup () {
    return { args }
  },
  template: `
    <cl-modal v-bind="args">
      <div class="relative p-10 bg-white shadow">
        <template #close>
          <cl-icon icon="XIcon" />
        </template>
        <p>hello</p>
      </div>
    </cl-modal>
  `,
})
```

`<template #close>` is what targets the `<slot name="close>` in the component, but I get an `Codegen node is missing for element/if/for node. Apply appropriate transforms first.` error instead.

**Expected behavior**
Template to compile properly.

**Code snippets**
See above

**System**
```
System:
    OS: macOS 11.2.1
    CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
  Binaries:
    Node: 12.19.0 - ~/.nvm/versions/node/v12.19.0/bin/node
    Yarn: 1.22.10 - ~/.nvm/versions/node/v12.19.0/bin/yarn
    npm: 6.14.10 - ~/.nvm/versions/node/v12.19.0/bin/npm
  Browsers:
    Chrome: 88.0.4324.192
    Edge: 88.0.705.81
    Firefox: 81.0.2
    Safari: 14.0.3
  npmPackages:
    @storybook/addon-actions: ^6.2.0-beta.2 => 6.2.0-beta.2
    @storybook/addon-essentials: ^6.2.0-beta.2 => 6.2.0-beta.2
    @storybook/addon-links: ^6.2.0-beta.2 => 6.2.0-beta.2
    @storybook/vue3: ^6.2.0-beta.2 => 6.2.0-beta.2
```

**Comment by TheDutchCoder** [comment]
Ah, apparently this issue appears when the template is in the wrong spot.
Not a very nice error, but was 100% user-error.

**Comment by Oddward** [comment]
I hope it's ok to contribute to this issue since it appeared as a top result for the error, but in case someone stumbled upon this and didn't actually get the solution like me, it's explained in the [Vue docs here](https://vuejs.org/guide/components/slots.html#scoped-slots:~:text=If%20you%20are-,mixing,-named%20slots%20with): 

_If you are mixing named slots with the default scoped slot, you need to use an explicit <template> tag for the default slot. Attempting to place the v-slot directive directly on the component will result in a compilation error. This is to avoid any ambiguity about the scope of the props of the default slot._

Something like
```vue
<cl-modal>
    <div class="">
        <template v-bind="args">
            ...
        </template>

        <template #close>
            ...
        </template>
    </div>
</cl-modal>
```
i.e. slot binding removed from parent element, `args` scoped to the main/default template, and `close` scoped to the other template separately (although the original example might not need nested templates)

**Comment by datsenkoboos** [comment]
@Oddward i've followed your instructions, but still get the same error, am i doing something wrong?

### Component
![изображение](https://github.com/storybookjs/storybook/assets/88643277/2298d846-fde8-4486-97f5-6436339fb138)
### Story
![изображение](https://github.com/storybookjs/storybook/assets/88643277/c7f9823a-4c58-48b0-9a69-27bd91778485)

**Comment by kalnode** [comment]
Just adding my observance.

I got OP's error too simply because I forgot to wrap the template; brain fart:

**FAILS:**
Dunno why I did this, lol.
```
template:
      '<template #icon>' +
        '<div v-html="args.icon" />' +
      '</template>' +
      '<template #default>' +
        '<div v-html="args.default" />' +
      '</template>'
```

**WORKS:**
   ```
 template:
        '<Button>' +
          '<template #icon>' +
            '<div v-html="args.icon" />' +
          '</template>' +
          '<template #default>' +
            '<div v-html="args.default" />' +
          '</template>' +
        '</Button>'
```

**Comment by derwaldgeist** [comment]
I actually had the issue because I did not set up Vuetify correctly, i.e. I did not set `app.use(vuetify);`. This happened because I had copied code from one project to another.
