### ISSUE TITLE
can't get right type

### ISSUE THREAD

**Issue by DuLinRain** [storybookjs/storybook#14093]
**Describe the bug**
just as the  official guides, 

    npx sb init 
    npm run storybook

then, if you write this code in stories:

```javascript
const test = async () => {

}
console.log(test.constructor.name, Object.getPrototypeOf(async function(){}).constructor)
```

you will get this result:

    Function ƒ Function() { [native code] }

but if you run the code directly in chrome console, you get:

    AsyncFunction ƒ AsyncFunction() { [native code] }

is this a bug? or i need to config something like babel?typescript?

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
