### ISSUE TITLE
addon-toolbars: add support for keyboard shortcuts/navigation

### ISSUE THREAD

**Issue by kaelig** [storybookjs/storybook#14239]
**Is your feature request related to a problem? Please describe**
I'd like to be able to switch easily between, say, dark and light mode in a Story (or cycle through multiple themes).

**Describe the solution you'd like**
Not sure how this could work in practice, curious if anyone has ideas on how to make that work.

**Are you able to assist to bring the feature to reality?**
Probably not, sorry!

**Comment by frassinier** [comment]
What do you mean @kaelig? Be able to assign key shortcuts when you register an addon?

**Comment by kaelig** [comment]
I suppose that was just made possible via https://github.com/storybookjs/storybook/pull/14658?

(related: https://github.com/storybookjs/storybook/issues/14401)

**Comment by frassinier** [comment]
@Dschungelabenteuer can you relate? 😊

**Comment by Dschungelabenteuer** [comment]
Yes, as of #14658 this should not be a problem using the extended shortcut API :) I can create a pull request if you guys want, but we should first agree on the different shortcuts (especially cross-OS compatibility) since @kaelig pointed out an unforseen issue in the original PR 😅 I should actually get myself a macOS-powered environment!

**Comment by shilman** [comment]
Jeepers creepers!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.3.0-beta.18 containing PR #15169 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.
