### ISSUE TITLE
storybook not working on microsoft edge.

### ISSUE THREAD

**Issue by danBamikiya** [storybookjs/storybook#14289]
**Describe the bug**
Storybook doesn't work on microsoft edge(latest version, don't know about other versions), but works fine on chrome.
**To Reproduce**

1. Run `npm run storybook`
2. Open microsoft edge
3. Go to localhost:6006
4. check error logging at the browser console `Ctrl+Shift+i`

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/58262528/111888261-30881580-89db-11eb-8b49-1e82823fe615.png)
![image](https://user-images.githubusercontent.com/58262528/111888268-57464c00-89db-11eb-8471-00738eaca438.png)

**The error loggings are currently at 200 errors on the console**

**Comment by danBamikiya** [comment]
I installed storybook two days ago and decided to use it today, so its the latest version.

**Comment by shilman** [comment]
Try upgrading to 6.2-rc:

```
npx sb@next upgrade --prerelease
```

**Comment by danBamikiya** [comment]
Still not working. This is the log file:
[localhost-1616495912721.log](https://github.com/storybookjs/storybook/files/6188810/localhost-1616495912721.log)

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
