### ISSUE TITLE
addons config not persisted when changing screensize

### ISSUE THREAD

**Issue by dexster** [storybookjs/storybook#14337]
**Describe the bug**
This may not be a bug and more a feature. I'm hiding the sidebar but when I go full screen and then back to normal view the sidebar appears. 
 
**To Reproduce**

1. Hide the sidebar in manager.js
```
addons.setConfig({
    showNav: false
});
```
2. Run Storybook and click the fullscreen icon
3. Click the "exit fullscreen" icon
4. The sidenav appears

**Expected behavior**
I would expect that the sidebar hidden state would persist?  

**System**
  System:
    OS: macOS 11.2.3
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Binaries:
    Node: 14.15.5 - ~/.nvm/versions/node/v14.15.5/bin/node
    Yarn: 1.22.10 - ~/.nvm/versions/node/v14.15.5/bin/yarn
    npm: 6.14.11 - ~/.nvm/versions/node/v14.15.5/bin/npm
  Browsers:
    Chrome: 89.0.4389.90
    Edge: 89.0.774.50
    Firefox: 86.0.1
    Safari: 14.0.3
  npmPackages:
    @storybook/addon-actions: ^6.2.0-rc.8 => 6.2.0-rc.8 
    @storybook/addon-essentials: ^6.2.0-rc.8 => 6.2.0-rc.8 
    @storybook/addon-links: ^6.2.0-rc.8 => 6.2.0-rc.8 
    @storybook/angular: ^6.2.0-rc.8 => 6.2.0-rc.8

**Comment by shilman** [comment]
Sounds like a bug to me. @ndelangen @ghengeveld any thoughts?

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
