### ISSUE TITLE
Customize message on rebuild

### ISSUE THREAD

**Issue by zhdanjj** [storybookjs/storybook#14361]
When I run `start-storybook` and start editing files it prints build hash and time it took.
![image](https://user-images.githubusercontent.com/22837399/112724908-8baf9000-8f26-11eb-93c4-bd6725435044.png)

How can I add date when it happend? As far as I know Storybook uses `webpack-dev-middleware` and it should be configured there but I can't see any way to change it

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
