### ISSUE TITLE
Can we add addon-svelte-csf to svelte-kitchen-sink?

### ISSUE THREAD

**Issue by frederikhors** [storybookjs/storybook#14379]
**Describe the solution you'd like**
Can we add https://github.com/storybookjs/addon-svelte-csf to svelte-kitchen-sink?

**Comment by j3rem1e** [comment]
It's not possible today because of dependencies.

this addon has a dependency on storybook. storybook can't have a dependency to the addon.

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
