### ISSUE TITLE
Scroll to specific heading without reloading

### ISSUE THREAD

**Issue by williamliangwl** [storybookjs/storybook#14426]
Is it possible to scroll to specific heading without reloading the Storybook or changing the url ?

I am using Storybook `v6.1.21`
I tried the following mdx

```
[click to go to events](#events)

<br />

<br />

<br />

<br />

<br />

<br />


### Events

No event is supported.
```

When I click on the `click to go to events`, it navigated to http://localhost:9009/iframe.html?id=story-id&viewMode=docs#events (notice the `iframe.html`) and hence a reload happened and the toolbar on the left disappeared.

What I was expecting is that it just scroll to the `Events` heading without moving to `iframe.html` and the toolbars are still there

If there's an addon or documentation about this, I am grateful for that

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1199622255231368/1200143216982026) by [Unito](https://www.unito.io)

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
