### ISSUE TITLE
Is there a way to install storybook version 5 in angular 7?. Whenever i give sb init, its install the latest version. I couldnt find any doc to install storybook in a specific version

### ISSUE THREAD

**Issue by AnandKatta** [storybookjs/storybook#14427]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**
Please paste the results of `npx sb@next info` here.

**Additional context**

**Comment by shilman** [comment]
AFAIK the only way is to edit your package.json by hand.

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
