### ISSUE TITLE
Dynamic preview head not rendering

### ISSUE THREAD

**Issue by stuartizon-x** [storybookjs/storybook#14496]
Not sure if I've misunderstood this feature, but I've tried to add the new `previewHead` config option (https://github.com/storybookjs/storybook/pull/13432) and it seems to not be doing anything.

I've created a small sample repo here based on the way it's described in the docs. https://github.com/stuartizon-x/storybook-example.

I'd expect to see the yellow background I've added to the previewHead, or at least the added preview markup inside the DOM. 

![](https://user-images.githubusercontent.com/79953293/113800220-ea340400-9799-11eb-9909-a0852fc3b3e5.png)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1199622255231368/1200161742581096) by [Unito](https://www.unito.io/learn-more)

**Comment by shilman** [comment]
Turns out the presets got renamed to `xTemplate` (e.g. `previewHeadTemplate`) in commit https://github.com/storybookjs/storybook/commit/2a5895c59e0d988609dc40754a9d430d61becb36

I tested out `previewHeadTemplate` in your repro and it's working as expected.

I'll discuss the change with @ndelangen to see whether we need to update the documentation or revert the changes. Thanks for raising the issue & sorry for the confusion!

**Comment by stuartizon-x** [comment]
Ah good to know I'm not a complete idiot! Thanks

**Comment by shilman** [comment]
ZOMG!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.2.5 containing PR #14500 that references this issue. Upgrade today to the `@latest` NPM tag to try it out!

```
npx sb upgrade
```

Closing this issue. Please re-open if you think there's still more to do.

**Comment by stuartizon-x** [comment]
Amazing. Thanks for your prompt support!
