### ISSUE TITLE
Syntax highlighting for diff code blocks in .mdx not working after 6.1.x+

### ISSUE THREAD

**Issue by malouro** [storybookjs/storybook#14605]
**Describe the bug**
In 6.0.x, the syntax highlighting for diffs was supported in mdx out-of-the-box. After upgrading to 6.1.x or later, this is no longer the case.

**To Reproduce**

1. Clone the [repro repo](https://github.com/malouro/storybook-diff-syntax-repro)
2. Switch to the branch corresponding to the Storybook version to test (`git checkout 6.1.x` or `6.0.x`)
3. Run `yarn install && yarn storybook`
4. View the "Introduction" story in the launched Storybook dev server

**Expected behavior**
Syntax highlighting on diff code blocks should work or be supported

**Screenshots**
Before (6.0.x) 😎
![Screenshot of an example with syntax highlighting working on diffs.](https://i.imgur.com/rZYyWtw.png)

After (6.1.x+) 😢
![Screenshot of an example where syntax highlighting no longer works on diffs.](https://i.imgur.com/aI3gX31.png)

**Additional context**
Not sure if there's a work-around for this currently that I might be missing, but I can dig around the docs and see

**Comment by Mintoo200** [comment]
Hey, any update on this?

**Comment by shilman** [comment]
We removed a bunch of syntax highlighters as part of a performance push in 6.1. The bundle size and build times were both reduced substantially. We might consider adding this one back, or figure out how to make it opt-in.

**Comment by Mintoo200** [comment]
Something pretty weird here:
I didn't add `react-syntax-highlighter` but it's part of my node_modules (I suspect it was automatically added by Storybook?)
so I tried tinkering with it and here's what I found out:
using 
```md
    ```diff
    + My Code
    - Goes Here
    ```
```
on its own does not highlight at all but if you import SyntaxHighlighter, it actually manages to highlight.
E.g.:
![image](https://user-images.githubusercontent.com/25901730/120368036-dcba7680-c311-11eb-8841-c1ed75435162.png)
from the following code:
```javascript
// eslint-disable-next-line import/no-extraneous-dependencies, @typescript-eslint/no-unused-vars
import SyntaxHighlighter from 'react-syntax-highlighter'

const documentation = `
\`\`\`diff
function MyParentComponent(props) {
- const ref = useRef<HTMLElement>()
+ const ref = useRef<FocussableRef>()
\`\`\`
`
```
This seems to work no matter what is imported from `react-syntax-highligher`:
```javascript
import { Prism as SyntaxHighlighter } from 'react-syntax-highlighter'
// and
import 'react-syntax-highlighter'
```
also work.

**Comment by jonniebigodes** [comment]
@Mintoo200, @malouro, @shilman I've been looking at this and it seems the workaround is missing some information. 
Going to detail the steps I took:
- Cloned the [Intro To Storybook template](https://github.com/chromaui/intro-storybook-react-template) to get a minimal working Storybook installation with React.
- Ran `yarn` to install the dependencies.
- Created a file called `ExampleSyntaxHighlight.stories.mdx` within the `stories` directory with the following inside:

```md
import { Meta } from "@storybook/addon-docs";
import { Prism as SyntaxHighlighter } from "react-syntax-highlighter";

<Meta title="Testing Syntax Highlight" />

# Diff example

This is a sample Git diff snippet example with Storybook docs

"diff
- import { OldComponent } from 'my-package'
+ import { NewComponent } from 'my-package'
"
```
The usage of quotes is intentional to allow proper syntax highlighting in here (GH).

- Ran `yarn storybook` and checked the story that was created and it yielded the following:

![Syntax-highlight-not-working](https://user-images.githubusercontent.com/22988955/126833235-23ec27a8-9161-4737-9f4b-86348e2c92e3.png)

Tested with the following import `import SyntaxHighlighter from 'react-syntax-highlighter'` same result.

- Checked the `react-syntax-highlighter` [documentation](https://github.com/react-syntax-highlighter/react-syntax-highlighter) and adjusted my story to the following:
```md

import { Meta } from "@storybook/addon-docs";
import { Prism as SyntaxHighlighter } from "react-syntax-highlighter";
import { dark } from "react-syntax-highlighter/dist/esm/styles/prism";

<Meta title="Testing Syntax Highlight" />

# Diff example

This is a sample Git diff snippet example with Storybook docs

"diff
- import { OldComponent } from 'my-package'
+ import { NewComponent } from 'my-package'
"

export const Component = () => {
  const codeString = "(num) => num + 1";
  return (
    <SyntaxHighlighter language="javascript" style={dark}>
      {codeString}
    </SyntaxHighlighter>
  );
};
```

Now Storybook yields the following:
![Storybook-working-diff](https://user-images.githubusercontent.com/22988955/126834499-03e5d736-79af-43a3-ba66-e465be991bae.png)

As to avoid this being a fluke, restarted Storybook, same result. 
- As I wasn't convinced. I've added [`http-server`](https://www.npmjs.com/package/http-server) to emulate a production server. 
- Adjusted my `scripts` to the run the server with ` "serve-prod": "http-server storybook-static"`
- Ran `yarn build-storybook`, followed by `yarn serve-prod`. 
- Opened up a browser window to `http://localhost:8080` and saw the highlighting working as above.

Why the need for the Component is unknown to me. I'm going to test more and based on this and further testing it's going to make its way into the documentation.

**Comment by jonniebigodes** [comment]
Closing this now as the pr with documentation updates to address this issue was merged and should be published soon. 

Let me know if the issue surfaces back and I'll gladly re-open and we can follow up on it until we have a solution.

Stay safe all
