### ISSUE TITLE
How to develop `vue componet` and `vanilla js lib` togethor?

### ISSUE THREAD

**Issue by BryanAdamss** [storybookjs/storybook#14629]
**Is your feature request related to a problem? Please describe**
No

**Describe the solution you'd like**
Integrate `jsdoc` for `vanilla js lib` 

**Describe alternatives you've considered**
Hi,Im  trying develop `vue compoent` and `vanilla js lib` togethor. 
I am useing `@storybook/vue` to generate `vue` document，I alos have some `vanilla js lib`  need to doc it.
Im trying use `jsdoc`，but how can i integrate it to storybook?Is there any examples?

**Are you able to assist to bring the feature to reality?**
No

**Additional context**
No

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
