### ISSUE TITLE
Placeholder and value are not centered vertically in Firefox

### ISSUE THREAD

**Issue by JB1905** [storybookjs/storybook#14642]
**Describe the bug**
Placeholder and value are not centered vertically in Firefox in text input from `@storybook/addon-controls`

**To Reproduce**
Open Storybook playground in Firefox

**System**
```
  System:
    OS: macOS 11.3
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
  Binaries:
    Node: 12.10.0 - /usr/local/bin/node
    Yarn: 1.22.5 - /usr/local/bin/yarn
    npm: 6.14.11 - ~/gh/jb/react-figma-ui/node_modules/.bin/npm
  Browsers:
    Chrome: 91.0.4472.10
    Safari: 14.1
  npmPackages:
    @storybook/addon-controls: ^6.2.8 => 6.2.8
    @storybook/addon-docs: ^6.2.8 => 6.2.8
    @storybook/addon-storysource: ^6.2.8 => 6.2.8
    @storybook/addons: ^6.2.8 => 6.2.8
    @storybook/react: ^6.2.8 => 6.2.8
    @storybook/storybook-deployer: ^2.8.7 => 2.8.7
```

![Zrzut ekranu 2021-04-17 o 19 58 33](https://user-images.githubusercontent.com/28870390/115143919-25f88480-a04a-11eb-889c-759a4590f094.png)
![Zrzut ekranu 2021-04-17 o 19 58 43](https://user-images.githubusercontent.com/28870390/115143925-2b55cf00-a04a-11eb-993b-9a0073db9fac.png)

**Comment by JB1905** [comment]
Issue is visible e.g. here https://5ccbc373887ca40020446347-fmqyskzoof.chromatic.com/?path=/story/forms-input--template

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid.

Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
