### ISSUE TITLE
Args Table dropdown does not working with more than 15 options 

### ISSUE THREAD

**Issue by gauravverma029** [storybookjs/storybook#14676]
Some click options also not working  **.. 11 more ...**

![Screen Shot 2021-04-21 at 13 06 41](https://user-images.githubusercontent.com/4488516/115544248-a44f6380-a2a2-11eb-9eaf-faf66aca17c5.png)

Storybook version Storybook 6.2.8

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid.

Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
