### ISSUE TITLE
Is SB, because it uses emotion,  breaking the compilation of a Typescript + styled-components project expected?

### ISSUE THREAD

**Issue by thomasmery** [storybookjs/storybook#14675]
SB seems to break the compilation of a create-react-app with _Typescript_ and _styled-components_ 

this is caused by the cssprop ts definition from the _emotion_ lib overrides the _styled-components_ one

see https://github.com/DefinitelyTyped/DefinitelyTyped/issues/31245#issuecomment-759730109 

which seems to be a fix in most cases

Creating this issue here as I don't think this is documented anywhere

Thanks for any enlighting feedback

**Comment by hydrosquall** [comment]
We were running into typescript compiler issues issues related to the `emotion` library when we tried to use the storybook `Story` and `Meta` typescript types in our stories, so we stopped using them (this has been true since at least version 6.0). Our project wasn't using `styled-components` or any form of CSS-in-JS at all, in case that helps with debugging.

**Comment by ndelangen** [comment]
This is fixed in storybook 7.0 beta.
