### ISSUE TITLE
How to properly debug SCSS?

### ISSUE THREAD

**Issue by fabpico** [storybookjs/storybook#14719]
**What's the problem?**
When I inspect an element that is styled in an SCSS file, the browser devtool does not say where the SCSS file is located. It only links to a `<style>` tag which by klicking on it, shows an implementation in the DOM, containing the compiled CSS code that differs from the SCSS. 

See screenshot:

![style](https://user-images.githubusercontent.com/4472725/116052267-bf8eea00-a679-11eb-9e90-cc576908086e.png)

**Is there documentation on this?**
I tought it could be something wrong with the source mapping, so I debugged the webpack config as [documented](https://storybook.js.org/docs/react/configure/webpack) with `yarn storybook --debug-webpack`. It showed me `devtool: '#cheap-module-source-map',`

**Additional context**
I tried to replace the sourcemap configuration with `source-map` and `inline-source-map`.
```
// .storybook/main.js
module.exports = {
    // ...
    webpackFinal: async (config, {configType}) => {
        config.devtool = 'source-map';
        return config;
    },
};
```
The webpack debug showed me the changed devtool value, but the result on inspection remained unchanged.

What should I do to link the inspected CSS to a pseudo SCSS file in the browser, that reflects the SCSS file from the project?
Thanks in advance.

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
