### ISSUE TITLE
Why dependencies storybook v6 affect the require(path) in project?

### ISSUE THREAD

**Issue by happy-tourist** [storybookjs/storybook#14720]
**What's the problem?**
Dependencies storybook v6 affect the `require(path)` in project. 

After install, my `require(path)` return Module obj although i expect string. In Storybook v5 all ok

**Is there documentation on this?**
I did not find.

**Additional context**
I'm use vue and laravel mix, yarn

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
