### ISSUE TITLE
Args parameter of the Story template has undefined properties when first load (Angular)

### ISSUE THREAD

**Issue by VolAndriienko** [storybookjs/storybook#14732]
Hi.
Just updated from the version 6.1.1 to the newest version 6.2.9

Faced with the problem in image below:

args has ALL of components properties with undefined value, not only for @Input or @Output decorators, and the component is broken because all functions are undefined.

![image](https://user-images.githubusercontent.com/28803006/116239021-d2351c00-a76a-11eb-994a-1bde28386e2f.png)

When I am clicking on the another story everything is OK and args contains only passed parameters or default values.
![image](https://user-images.githubusercontent.com/28803006/116239189-09a3c880-a76b-11eb-9751-b4835ee7520e.png)

If I open first welcome page -  then open the story - everything is OK.

I made temporary workaround (see on the image),  just to make it work, but it's not cool to have this in the code.

Can somebody give me advise? Can't find similliar problem is others topics.

**Comment by shilman** [comment]
I believe this is a duplicate issue, right @ThibaudAV? We are looking into a solution in 6.3!

**Comment by ThibaudAV** [comment]
yes again and again ^^

---
it is necessary to control the args before adding them to angular (for the moment 🤞 )
I know 3 ways to do it :

### Prefer a "destructuring" to control them :

```
const Template: Story<SampleComp> = (args) => ({
  props: {
  input1: args.input1
  },
});
```

### Use compodoc `@ignore` comment
like : 
Add /** @ignore */ to the other properties so that compodoc ignores them

### Disable doc for some kind props in compodoc 
like: 
"docs:json": "compodoc -p ./src/app/tsconfig.app.json -e json -d . --disablePrivate --disableProtected --disableLifeCycleHooks --disableInternal",

**Comment by shilman** [comment]
closing as dupe to #11613

**Comment by shilman** [comment]
Yee-haw!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.3.0-alpha.18 containing PR #14769 that references this issue. Upgrade today to the @next NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.
