### ISSUE TITLE
How to import component the external storybook in other reactjs project

### ISSUE THREAD

**Issue by Ruchi-agrawal** [storybookjs/storybook#14731]
Hi, 

**What's the problem?**
I have created a component and added it on chromatic, Now I want to use that component in my other Reactjs project, So I am using this documentation - 
https://storybook.js.org/tutorials/intro-to-storybook/react/en/deploy/
https://www.chromatic.com/docs/composition

According to this, I am able to see the external storybook that fetched from the chromatic given URL, But I am not able to get any document related to how I **import that external storybook component in my web page** and use it accordingly. Please provide me document related to this, so I will import that composition ( **External** ) storybook's component.

**Comment by shilman** [comment]
That's not something Storybook handles for you per se. We have a chapter on distributing your components here, which could help https://storybook.js.org/tutorials/design-systems-for-developers/react/en/distribute/

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
