### ISSUE TITLE
SharedArrayBuffer usage is restricted to cross-origin isolated sites

### ISSUE THREAD

**Issue by Frikki** [storybookjs/storybook#14757]
**What's the problem?**
When running `storybook` (only in dev, not build), the following warning is presented in the console in Chrome Version 90.0.4430.85 (Official Build) (x86_64):

> SharedArrayBuffer usage is restricted to cross-origin isolated sites
SharedArrayBuffers (SABs) can be used to construct high-resolution timers. High-resolution timers simplify Spectre attacks on cross-origin resources.
To mitigate security risks across browsers, SharedArrayBuffers are gated behind cross-origin isolated contexts starting with Chrome 91 (May 2021). To continue using SharedArrayBuffers, please ensure that this page opts-into cross-origin isolation by setting Cross-Origin-Opener-Policy and Cross-Origin-Embedder-Policy appropriately.
Note that for each iframe, only the first issue is reported for performance reasons.

**Additional context**
The warning comes from React and has been [resolved in React 17.0.2](https://github.com/facebook/react/issues/20829#issuecomment-804424954)

Since `storybook` depends on React, I believe that this issue is relevant.

**Comment by sibelius** [comment]
is this fixed?

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
