### ISSUE TITLE
Typescript can't generate a defined interface in 6.2.9 version

### ISSUE THREAD

**Issue by linxianxi** [storybookjs/storybook#14750]
**Describe the bug**
![image](https://user-images.githubusercontent.com/47104575/116495206-0a586e00-a8d5-11eb-8335-caa411082aab.png)
![image](https://user-images.githubusercontent.com/47104575/116495248-20662e80-a8d5-11eb-8333-670a572a89d2.png)
![image](https://user-images.githubusercontent.com/47104575/116495334-47246500-a8d5-11eb-989a-6cc0209afc88.png)

**To Reproduce**
Link to a reproduction repo that demonstrates the bug, plus instructions on how to trigger it.

**System**
Please paste the results of `npx sb@next info` here.

**Additional context**

**Comment by YozhEzhi** [comment]
Isn't this an expected behaviour?
I mean, if `ContentButtonProps` should have lot of `extends`: should all of interface props be printed out?

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid.

Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
