### ISSUE TITLE
REM units not based on body style

### ISSUE THREAD

**Issue by jwlh** [storybookjs/storybook#14760]
**What's the problem?**
I've followed the documentation to use a preview-body.html file to add a font-size to the body which according to the docs should make the rem units in my component respect the font-size I set (in this case 16px)

But the rem units are actually  basing themselves on a 10px value on the html tag wrapping the head and the body (see screenshot)
![Screenshot 2021-04-29 at 16 08 27](https://user-images.githubusercontent.com/30984190/116574521-b4e88500-a905-11eb-9d09-b584d6f61fc6.png)

**Is there documentation on this?**
This is a link to documentation I mention above https://storybook.js.org/docs/react/configure/story-rendering#adding-to-body

**Additional context**
Disabling the 10px font-size rule in the dev tools leaves me with the sizing I would expect from my Rem values within the components

**Comment by leesgithub2019** [comment]
>I alse have this problem.
>Have you solved this problem?

**Comment by leesgithub2019** [comment]
@jwlh
 Have you solved the problem？

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
