### ISSUE TITLE
using storybook addon-docs with `.md` files

### ISSUE THREAD

**Issue by TheKnarf** [storybookjs/storybook#14787]
**What's the problem?**
I have a project with a lot of documentation as markdown files, would it be possible to configure addon-docs to import them into Storybook without renaming them from `.md` to `.mdx`?

**Is there documentation on this?**
Can't find any documentation 

**Additional context**
Relates to #14786

**Comment by YozhEzhi** [comment]
As workaround you can do this:

Create `stories.mdx` with content:

```
import { Description, Meta } from '@storybook/addon-docs/blocks';

import readme from '../README.md';

<Meta title="Readme" />

<Description>
  { readme }
</Description>
```

**Comment by TheKnarf** [comment]
This seems to work, but ends up with me having duplicate files (one `.mdx` file pr `.md` file), is there any way for me to loop over files? Like have one `.stories.*` file that outputs multiple stories. That way I can have only one story file that outputs one story for each markdown file.

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
