### ISSUE TITLE
Storybook could not resolve image imports

### ISSUE THREAD

**Issue by sudobhat** [storybookjs/storybook#14815]
**Could not resolve image imports in Storybook**
In my react components library built with microbundle-crl, I am importing the image like so:
 
`import CompanyLogo from '/../images/logo.svg'`

normal imports starting with ../ was not working, so had to add / in the beginning. That worked.
More info on the above issue in the link: https://github.com/transitive-bullshit/create-react-library/issues/285

Rest of the modules that are importing these components display the logo. But, Storybook throws the error:

`Module not found: Error: Can't resolve '/../images/logo.svg'`

Any extra config needed in main.js or something? please help!

**Additional context**
Package versions:
```
"@babel/core": "^7.13.16",
"@storybook/addon-actions": "^6.2.9",
"@storybook/addon-essentials": "^6.2.9",
"@storybook/addon-links": "^6.2.9",
"@storybook/react": "^6.2.9",
```

**Comment by leesgithub2019** [comment]
Maybe you should give your directory structure.

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
