### ISSUE TITLE
[angular]: forceReRender does nothing

### ISSUE THREAD

**Issue by nickbullock** [storybookjs/storybook#14823]
**Describe the bug**
`forceReRender` method doen't rerender story for angular applications

What I'm trying to achieve: destroy and init root angular component or application in general, but `forceRerender` doesn't do that.

**To Reproduce**
Can be easily reproduced with clean project like
```
npx ng new app;
cd app;
npx sb init;
```

**System**
Environment Info:

  System:
    OS: macOS 10.15.7
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
  Binaries:
    Node: 12.21.0 - ~/.nvm/versions/node/v12.21.0/bin/node
    npm: 6.14.11 - ~/.nvm/versions/node/v12.21.0/bin/npm
  Browsers:
    Chrome: 90.0.4430.93
    Firefox: 86.0.1
    Safari: 13.1.3
  npmPackages:
    @storybook/addon-actions: 6.2.8 => 6.2.8 
    @storybook/addon-essentials: 6.2.8 => 6.2.8 
    @storybook/addon-links: 6.2.8 => 6.2.8 
    @storybook/angular: 6.2.8 => 6.2.8 
    @storybook/theming: 6.2.8 => 6.2.8

**Comment by nickbullock** [comment]
I think the problem is on [this line](https://github.com/storybookjs/storybook/blob/643e7eb011a880e2b4b8d82ad360752aa9461dd6/app/angular/src/client/preview/angular-beta/RendererService.ts#L72) (at least for angular)
Storybook decides that if you called `forceReRender` manually it can do not full rerender cycle.
So I guess [this function](https://github.com/storybookjs/storybook/blob/643e7eb011a880e2b4b8d82ad360752aa9461dd6/app/angular/src/client/preview/angular-beta/RendererService.ts#L138) must be changed to fix this behavior.

**Comment by ThibaudAV** [comment]
I have already tried to use `forceReRender` but it doesn't do what we want because it sets the `forceRender=true` [link](https://github.com/storybookjs/storybook/blob/next/app/angular/src/client/preview/render.ts#L12) (if I am not mistaken)
and angular uses it to not completely reload :/

Why do you need to force the rendering again?

[here](https://github.com/storybookjs/storybook/pull/14226/commits/d64e49ba1a715db73a3d6c697517fe6a85a8f8ef) I added an additional check to force a new rendering if the angular metadata changes

**Comment by nickbullock** [comment]
@ThibaudAV 
We have some really big components that interact with CodeMirror and in real life they can't be changed using inputs (props) during application lifetime, they can be initialized only. So to restart them in storybook after controls changes I need some API to `forceForceReRender`. Basically this is our code problem, but it would be cool if there is public API for doing this.
Right now I've achieved it with `RendererService.prototype.fullRendererRequired` monkey patching, but this is an awful solution.

**Comment by ThibaudAV** [comment]
I understand the request I have already [discussed](https://github.com/storybookjs/storybook/pull/14226#discussion_r593728500) with @shilman 

I wanted to add a story flag only for angular to disable the optimization on some story. 
But it seems better to make a generic mechanism for all frameworks 

I also thought of adding a boolean in the `forceReRender()` method to change the value of the `forceRender` sent to the story. but 🤷‍♂️

**Comment by nickbullock** [comment]
Hey @shilman @ThibaudAV, any news on this?

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
