### ISSUE TITLE
How to use redux in storybook???

### ISSUE THREAD

**Issue by ooo2003003v2** [storybookjs/storybook#14824]
Hello there. I've created a component for my login. It works fine in storybook until I add redux into the component.
Any example that I can follow for it to work?

**Comment by yannbf** [comment]
Hey @ooo2003003v2, thanks for using Storybook 🎉 
When components need support for more complex things, you need to create a decorator that wraps the stories in order to provide support for those. There is a good explanation at the "Supplying context with decorators" section in one of the Storybook tutorial sections at https://storybook.js.org/tutorials/intro-to-storybook/react/en/screen/, that should help you out!

I have a project with a more scalable example, in case you would like to take a peak as well: https://github.com/yannbf/mealdrop/blob/master/.storybook/decorators.tsx#L107

**Comment by ooo2003003v2** [comment]
> Hey @ooo2003003v2, thanks for using Storybook 🎉
> When components need support for more complex things, you need to create a decorator that wraps the stories in order to provide support for those. There is a good explanation at the "Supplying context with decorators" section in one of the Storybook tutorial sections at https://storybook.js.org/tutorials/intro-to-storybook/react/en/screen/, that should help you out!
> 
> I have a project with a more scalable example, in case you would like to take a peak as well: https://github.com/yannbf/mealdrop/blob/master/.storybook/decorators.tsx#L107

Thank you for the reply. I managed to make my component works with redux. However my dispatch actions didnt show up in the "Actions" session of the storybook panel. Should I change the pattern of how I write my dispatch?

loginCard.stories.tsx
```
import React from "react";
import { Provider } from "react-redux";
import { Meta } from "@storybook/react";
import LoginCard, { mapStateToProps, mapDispatchToProps } from "./index";
import { createBrowserHistory } from "history";
import configureStore from "../../configureStore";

const initialState: any = { ...mapDispatchToProps, ...mapStateToProps };
const history = createBrowserHistory();
const store = configureStore(history, initialState);
export default {
  title: "Components/Login Card",
  decorators: [(story) => <Provider store={store}>{story()}</Provider>],
  component: LoginCard,
} as Meta;

interface propsFromComponent {
  user: any;
}

interface propsFromDispatch {
  login: (input: any) => any;
  getAccount: () => any;
}

type Props = propsFromComponent & propsFromDispatch;

const Template = () => <LoginCard />;

export const Default = Template.bind({});
```

loginCard/index.tsx
```

interface propsFromComponent {
  user: any;
}

interface propsFromDispatch {
  login: (input: any) => any;
  getAccount: () => any;
}

type Props = propsFromComponent & propsFromDispatch;
type LoginState = {
  email: string;
  pass: string;
};

class LoginPage extends Component<Props, LoginState> {
  state: LoginState = {
    email: "",
    pass: "",
  };

 render() {
    return (
      ...
    );
  }

}


export const mapStateToProps = ({ userStore }: ApplicationState) => {
  return { user: userStore.user };
};

export const mapDispatchToProps = (
  dispatch: ThunkDispatch<any, any, AnyAction>
) => {
  return {
    login: (item: any) => dispatch(Login(item)),
    getAccount: () => {
      console.log("dispatch get ac");
      dispatch(GetAccount());
    },
  };
};

export default connect(mapStateToProps, mapDispatchToProps)(LoginPage);

```

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).

**Comment by johnemau** [comment]
> orybook has changed a lot since this issue was created an

I am in the same situation, in redux the pattern is to dispatch actions through the store, so I am not sure how to make storybook's Actions plugin aware of them.
