### ISSUE TITLE
Minification not disabled when running build-storybook with Node_env development as well as setting mode development in preset

### ISSUE THREAD

**Issue by sunilsurana** [storybookjs/storybook#15068]
**Describe the bug**
Minification not disabled when running build-storybook with Node_env development as well as setting mode development in presets js

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid.

Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
