### ISSUE TITLE
Cannot resoslve tsconfig.json paths props in storybook

### ISSUE THREAD

**Issue by ooo2003003v2** [storybookjs/storybook#15101]
Hello there. I've set a path for accessing src folder in component. However when I build my components in storybook it shows "Module not found: Can't resolve '@/components/xxx' in 'D:\Documents\reactApp\~' src/components/~"
Any idea how to solve it?

tsconfig.json
```
~
 "extends": "./tsconfig.paths.json",
~
```

tsconfig.paths.json
```
{
    "compilerOptions": {
      "baseUrl": ".",
      "paths": {
        "@/*": [
            "src/*"
          ]
      }
    }
  }
```

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
