### ISSUE TITLE
Next.js 10  webpack5 + Storybook 6.2.9 + Tailwind / Not loading CSS 

### ISSUE THREAD

**Issue by vousys** [storybookjs/storybook#15206]
Hi, I've installed storybook on Next.js 10  with webpack5 + Storybook 6.2.9 + Tailwind,  but I can't see the CSS styles, as you can see in this image:

![image](https://user-images.githubusercontent.com/12813221/121705833-6fde7380-caab-11eb-9931-1bbebb58df75.png)

main.js 

```
module.exports = {
  stories: [
    '../components/**/*.stories.mdx',
    '../components/**/*.stories.@(js|jsx|ts|tsx)',
    '../components/stories/*.stories.@(js|jsx|ts|tsx)',
  ],
  addons: [
    '@storybook/addon-links',
    '@storybook/addon-essentials',
    '@storybook/preset-create-react-app',

    {
      name: '@storybook/addon-postcss',
      options: {
        postcssLoaderOptions: {
          implementation: require('postcss'),
        },
      },
    },
  ],

  webpackFinal: (config) => {
    config.module.rules.push({
      test: /\.scss$/,
      sideEffects: true,
      use: ['react-style-loader', 'css-loader', 'sass-loader'],
    })

    return config
  },
}

```

I check all github related issues, but I don't want to downgrade Tailwind to use Storybook, is there anything I can do?

Thanks in advance!

**Comment by frmysantana** [comment]
I'm seeing something similar. We have an experimental branch to try out Next.js 11 (with webpack 5 by default) + storybook 6.2.9 + tailwind. Tailwind is working fine on our next.js pages, but is not loading in our stories.

On our main branch (Next.js 10 + Webpack 4 + Storybook 6.2.9 + Tailwind), we have no problems loading tailwind in our stories.

**Comment by diegoaguilar** [comment]
@frmysantana did you figure this out? Starting a brand new tailwind project on Next 11 and would love to use storybook

**Comment by frmysantana** [comment]
@diegoaguilar I believe we fixed it by installing `@storybook/builder-webpack5` in our devDependencies, and configuring the `.storybook/main.js` to use postcss and tailwind by adding this  key-value pair into `module.exports`:

```
webpackFinal: async (config) => {
    config.module.rules.push({
      test: /\.css$/,
      use: [
        {
          loader: "postcss-loader",
          options: {
            postcssOptions: {
              plugins: [require("tailwindcss"), require("autoprefixer")],
            },
          },
        },
      ],
      include: path.resolve(__dirname, "../"),
    });
    return config;
  },
```

**Comment by diegoaguilar** [comment]
Hi @frmysantana  thanks for answer. Yeah I got it working too. I got a quite similar configuration that made the job:

```javascript
module.exports = {
  stories: [
    "../components/**/*.stories.mdx",
    "../components/**/*.stories.tsx"
  ],
  addons: [
    "@storybook/addon-essentials"
  ],
  core: {
    builder: "webpack5"
  },
  webpackFinal: async (config) => {
    config.module.rules.push({
      test: /\.scss$/,
      use: [
        "style-loader",
        "css-loader",
        "postcss-loader",
        "sass-loader",
      ],
      include: path.resolve(__dirname, "../"),
    });
    return config;
  }
}
```

Also, I had to make sure to include this on top of `preview.js` file `import "!style-loader!css-loader!postcss-loader!sass-loader!../styles/main.scss"` where `main.scss` is loading Tailwind.

**Comment by diegoaguilar** [comment]
@frmysantana taking the chance I ask, did you have to include any additional configs on `next.config.js` or a custom `.babelrc` in order to get Next working along with Tailwind and sass?

When I run either `npm run dev` or `npm run build` I'l get a variety of errs:

For example:

```
./components/form/form.module.scss.webpack[javascript/auto]!=!./node_modules/next/dist/compiled/css-loader/cjs.js??ruleSet[1].rules[3].oneOf[3].use[1]!./node_modules/next/dist/compiled/postcss-loader/cjs.js??ruleSet[1].rules[3].oneOf[3].use[2]!./node_modules/next/dist/compiled/resolve-url-loader/index.js??ruleSet[1].rules[3].oneOf[3].use[3]!./node_modules/next/dist/compiled/sass-loader/cjs.js??ruleSet[1].rules[3].oneOf[3].use[4]!./components/form/form.module.scss
Error: resolve-url-loader: CSS error
```

Where of course `Error: resolve-url-loader: CSS error` is the key.

Also I've been getting some missing semicolon errs.

This all while storybook is already working appropriately

**Comment by frmysantana** [comment]
@diegoaguilar No, we didn't need any extra configs. But we're not using Sass, we just use tailwind out-of-the-box so that may be why.

**Comment by eric-burel** [comment]
Is there something specific to Next+Storybook in your question? It seems to me that you basically need to setup Tailwind again in Storybook, which is expected because there is no "automatic" connection between your Next.js webpack config and your Storybook config. You can avoid duplication as much as possible by simply having a common Webpack config that you import in both next.config.js and Storybook main.

There is the same question for CSS modules, they are supported out of the box in Next, but you simply need to add the relevant preset to Storybook to make them work there.

I haven't found a Tailwind preset for storybook btw, this could simplify the setup.

**Comment by w3bdesign** [comment]
Just in case anyone is still having similar issues, here is how I managed to get Storybook working with Tailwind 3 and Next 12:

- Install `@storybook/addon-postcss` as a dev dependency
- Make sure you add it to your .storybook/main.js:
`addons: [
    "@storybook/addon-links",
    "@storybook/addon-essentials",
    {
      name: "@storybook/addon-postcss",
      options: {
        postcssLoaderOptions: {
          implementation: require("postcss")
        }
      }
    }
  ],`
- Import the CSS file (import "../styles/globals.css";)  with Tailwind in preview.js

![bilde](https://user-images.githubusercontent.com/45217974/147864041-d5404515-7b09-4856-907b-0927f629c0bc.png)

**Comment by sshquack** [comment]
After following the [addon-postcss](https://storybook.js.org/addons/@storybook/addon-postcss) I'm seeing this error too. SB fails to build with CRA TW and SB with this error:

```
99% done plugins webpack-hot-middlewarewebpack built preview 5f7ac74125465130ad66 in 4135ms
ModuleBuildError: Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
SyntaxError

(1:1) /Users/ayemacair/Desktop/code/js/react-ts-tw-sb-01/src/index.css Unknown word

> 1 | var api = require("!../node_modules/@storybook/addon-postcss/node_modules/style-loader/dist/runtime/injectStylesIntoStyleTag.js");
...
```

Deps:
- Storybook 6.4.9
- @storybook/addon-postcss 2.0.0

Full repro:
https://github.com/sshquack/react-ts-tw-sb-01

Any idea on how to get past this issue?

**Comment by as-zlynn-philipps** [comment]
I'm seeing the same thing @sshquack. Did you ever find a fix?

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
