### ISSUE TITLE
After compiling the .vue file into a js file component and adding it to the storybook, the props and events on the docs are not displayed

### ISSUE THREAD

**Issue by DtStorm** [storybookjs/storybook#15274]
why?
![image](https://user-images.githubusercontent.com/56500428/122367602-27352780-cf8f-11eb-8962-21451b588438.png)
![image](https://user-images.githubusercontent.com/56500428/122367654-31efbc80-cf8f-11eb-90d3-a8dda1b1d034.png)

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid.

Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
