### ISSUE TITLE
Upgrading from 6.2 to 6.3 seeing significant slow down

### ISSUE THREAD

**Issue by lifeiscontent** [storybookjs/storybook#15380]
**Describe the bug**
After upgrading in a TypeScript Monorepo  when trying to reload storybook it's taking 10+ seconds to reload. Previously it was 1 to 2 seconds.

**To Reproduce**
@bebraw I added you to my lifetime repo, you can check it out there, just run the following:

```
npm install -g pnpm
pnpm i
pnpm build
pnpm dev 
```
pnpm dev will start storybook from the `/website` folder
all stories are in `/packages/react-ui` and `/packages/react-components` feel free to change one in testing to see how slow it is when modifying source code from these packages and how long it takes to reload the code.

**System**
Please paste the results of `npx sb@next info` here.

**Additional context**

**Comment by bebraw** [comment]
I noticed that in your 6.3 update (commit `3fb0f69ddb89a`), `react-docgen-typescript-plugin` was bumped from 0.6.3 to the current one. The difference between these two is that the former doesn't support webpack 5 so most likely it wasn't extracting documentation for you (I didn't test but that's the reason why we did the work on the plugin to add the support).

For a reason I don't understand, when testing it's not even reloading the components for me so there may be some difference in how we're using the dev version.

That said, I would expect 6.3 to be slower due to this reason. It's doing more work so it should be slower as well.

In case you don't need the type information (the `Docs` tab) during development, I would suggest disabling it during development and enabling it only for production. I believe doing this would match the earlier performance of your project quite closely. Would that work for you for now?

**Comment by shilman** [comment]
Boo-yah!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.4.0-alpha.8 containing PR #15431 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.
