### ISSUE TITLE
Decorator unmounted when switching stories

### ISSUE THREAD

**Issue by y-nk** [storybookjs/storybook#15416]
**Additional Context**

I'm trying to create a storybook addon for my company. We're looking to create a decorator which will hold a stateful object (our company's sdk) via the react's context api. After that we'll have stories which will make use of this context to load some data.

This addon is part of our web solution, and we work in a yarn workspaces environment with boilerplates made with tsdx. Don't worry I've provided a clonable repro repo :)

**Describe the bug**

The decorator works fine when clicking on the toolbar's button, we can see the color changing from green to red. **The problem** is that the decorator gets unmounted/remounted when you visit another story. I've added `console.log` statement to help debug.

**To Reproduce**

1. `git clone https://github.com/y-nk/storybook-decorator-unmounted-repro`
2. `cd storybook-decorator-unmounted-repro`
3. `yarn`
4. `cd addon`
5. `yarn build`
6. `cd ../demo-app`
7. `yarn storybook` (or `yarn build-storybook` and `npx http-server storybook-static`)

or 

**System**

```
Environment Info:

  System:
    OS: macOS 11.4
    CPU: (8) x64 Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz
  Binaries:
    Node: 16.4.0 - ~/.nvm/versions/node/v16.4.0/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 7.18.1 - ~/.nvm/versions/node/v16.4.0/bin/npm
  Browsers:
    Chrome: 91.0.4472.114
    Firefox: 88.0.1
    Safari: 14.1.1

```

---

**EDIT**: I forgot to mention but you can tinker around by running `yarn watch` in the addon side, and `yarn storybook` in the demo-app side.

**Comment by y-nk** [comment]
( @shilman no offense but it seems like a bug except if it's expected behavior from decorators )

**Comment by shilman** [comment]
Yes, it's the expected behavior. @tmeasday can give more detail, but this issue has been done to death in previous discussions.

**Comment by tmeasday** [comment]
This is a slightly different issue to the one discussed before;

We don't make any guarantees about decorators being retained as you move between stories. The mechanism to render a set of decorators and a story creates a series of "decorated story" SFCs that are unique to the story. It's something like this:

```js
// In vaguely mathematical language
decorateStory([], story) = story
decorateStory([d, ...ds], story) = () => d(decorateStory(ds, story))
```

You can see that `decorateStory(decorators, story)` creates a *new* function that is unique to the story. So there's no way for react to reconcile that with the same decorator applied to a second story. Thus the remounting.

---

I think instead of trying to ensure the decorator doesn't remount, you should look at options to make your functionality work without a remount. Is that possible @y-nk?

**Comment by y-nk** [comment]
Thanks for the explanation @tmeasday it somehow makes sense.

I kinda managed a temporary workaround by storing my sdk instance in a global var outside of the decorator component and reusing the instance on remount based on some criterias ; but it definitely feels like a hack (...but it does work) and has few caveats as well : our sdk has to reinit itself since it disposes itself at unmount (and this is expected behavior by spec, so there's a limit to what we can pull as workaround)


I've tried to wrap my decorator in a `React.memo` as well but it didn't end so well.

Another way which would work is for me to register my decorator as the 1st one, so hopefully it wouldn't have to be remounted?

If the goal is to have a stack of decorators, wouldn't it be possible to so something like:

```
const DecoratorStack = registeredDecorators.reduce((Parent, Child) => (
  <Parent><Child /></Parent>
), React.Fragment)

return <DecoratorStack><Story /></DecoratorStack>
```

then you don't need the intermediate anonymous function. or am i missing something obvious there?

---

if the conversation is not useful feel free to close/terminate the ticket (i understand you're busy guys!). as said i've a workaround but i definitely feels weird.

**Comment by tmeasday** [comment]
Without thinking too deeply about it yet, the problem there is the set of decorators differs between different stories, so the `DecoratorStack` "component" will be different as you change stories, and so React will see `<DecoratorStack>` as a new component that it needs to remount (along with its rendered subcomponents) each time you change story.

It would be nice to be able to produce something like:

```jsx
<DecoratorOne>
  <DecoratorTwo>
     <Story />
  </DecoratorTwo>
</DecoratorOne>
```

But the issue is that the decorator API allows `DecoratorOne` to pass updated context to `DecoratorTwo`, so it need to take it unrendered as an prop, rather than as a child.

**Comment by y-nk** [comment]
@tmeasday Would that be too far fetched to give different treatment to story level decorators from global level decorators? It's unlikely that a global level decorator would be dependent on the story, so it'd make sense it should be considered as persistent?

**Comment by tmeasday** [comment]
@y-nk I guess so, but I do wonder if that would be confusing in other situations..
