### ISSUE TITLE
Storybook / Chart.js - Bug when interacting with controls when datasets is included

### ISSUE THREAD

**Issue by dmoxon-ent** [storybookjs/storybook#15441]
**Describe the bug**
When interacting with controls in Storybook for an Angular component,  Chart.js will append a _meta object to the objects as part of the datasets prop. The _meta object contains circular references and Storybook attempts to JSON.stringify() props in the controls tab. This causes a circular reference bug and causes the whole page to go blank.

**To Reproduce**
Configure Storybook and Angular. Use Chart.js or ng2-charts and build an Angular component consisting of a line-chart or radar chart with data passed to the datasets prop in the baseChart directive. 

Alternatively, attach meta data to any prop of a component that contains circular references. Storybook will attempt to JSON.stringify() props when interacting with controls in the Controls pane.

**System**
N/A

**Additional context**
This bug is a particular interaction between Storybook and Chart.js, however any other projects that may update prop data with circular references would have similar issues.

Perhaps adding some error handling around JSON.stringify() when controls are being adjusted would help?

**Comment by shilman** [comment]
Can you provide a repro using `npx sb@next repro` and/or isolate which line of code is causing the problem?

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid.

Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
