### ISSUE TITLE
Should @storybook/builder-webpack4 be included in @storybook#addon-docs

### ISSUE THREAD

**Issue by alanquigley-toast** [storybookjs/storybook#15474]
https://github.com/storybookjs/storybook/blob/4bd2fc9b0677190c59e60fd63841294ab88e80c5/addons/docs/package.json#L68

When creating a webpack 5 storybook instance in a typescript project, this installs webpack 4 along with the @types/webpack package, which can intermittently cause typescript compile issues. 

is there advice on dealing with this - should this be included in the @storybook#addon-essentials package, or should there be a webpack 5 @storybook#addon-essentials version.

**Comment by shilman** [comment]
This is intentional. Webpack4 is the default builder for Storybook 6.x. Not including it would be a breaking change. Starting in 7.0, we'll make the builder opt-in and this won't be an issue anymore.

In the meantime, if you're using `yarn` you can use [resolutions](https://classic.yarnpkg.com/en/docs/selective-version-resolutions/) to force a specific version of webpack.

**Comment by ndelangen** [comment]
This is fixed in storybook 7.0 beta.
