### ISSUE TITLE
MDX story crashes when name prop is wrapped in curly brackets {}

### ISSUE THREAD

**Issue by R-Bower** [storybookjs/storybook#15471]
**Describe the bug**
MDX stories crash when name prop is wrapped in curly brackets {}

**To Reproduce**
In a project with `@storybook/addon-docs`, create an MDX story and attempt the following:

```
import {Canvas, Meta, Story} from "@storybook/addon-docs"

<Meta title="Components/Test" />

export const Template = (args) => <div />

<Canvas>
  <Story name={"example"}>
    {Template.bind({})}
  </Story>
</Canvas>
```

**System**
```
System:
    OS: macOS 11.4
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
  Binaries:
    Node: 14.17.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.13 - /usr/local/bin/npm
  Browsers:
    Chrome: 91.0.4472.114
    Firefox: 78.11.0
    Safari: 14.1.1
```

**Comment by shilman** [comment]
That's expected. Like in vanilla CSF, story exports should be statically analyzable, and therefore we only consider stories with string names. If you replace this expression with a string literal, it will work as desired:

```
<Canvas>
  <Story name="example">
    {Template.bind({})}
  </Story>
</Canvas>
```

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
