### ISSUE TITLE
Sidebar duplicate entries if `title` starts with `/`

### ISSUE THREAD

**Issue by xseman** [storybookjs/storybook#15506]
**Describe the bug**

Sidebar duplicate entries per story if `title` starts with `/`

![2021-07-07-134427_694x500_scrot](https://user-images.githubusercontent.com/9111485/124754103-1b9fa580-df2a-11eb-8178-baa1384d03d4.png)

**To Reproduce**

Set start of `title` to `/`

```tsx
// foo.story.tsx

export default {
    title: '/foo/bar/Foobar'
    ...
}

...
```

**System**

```
System:
    OS: Linux 5.10 Debian GNU/Linux 11 (bullseye) 11 (bullseye)
    CPU: (8) x64 Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
Binaries:
    Node: 14.17.2 - /bin/node
    npm: 6.14.13 - /bin/npm
Browsers:
    Chrome: 91.0.4472.114
    Firefox: 87.0
```

**Additional context**

I found this bug bacause i'm using tip from <https://storybook.js.org/docs/riot/configure/sidebar-and-urls>.
Which recomends to use `path.macro` in `Generating titles based on __dirname` section.

```tsx
import base from 'paths.macro';

export default {
    title: `${base}/Component`
    ...
}

...
```

`base` will start with `/`

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
