### ISSUE TITLE
Question: What's the roadmap/timeline for Controls support in HTML Storybooks?

### ISSUE THREAD

**Issue by stephenhmarsh** [storybookjs/storybook#15525]
I don't see Controls in the [support table](https://storybook.js.org/docs/react/api/frameworks-feature-support) for `@storybook/html`.  I'm wondering how long my team will have to keep using the deprecated package before we can migrate to Controls?

**Comment by shilman** [comment]
The support table is misleading cc @jonniebigodes 

Controls work for all frameworks, but in some cases they can be inferred automatically an in other cases they can't. The "supported" frameworks are the ones where we're doing that inference for you. And the unsupported frameworks are ones where we're not.

In pure HTML there is no way to infer a component's input because the HTML snippets are not components (unless we're talking about web components, in which case it's a slightly different conversation).

But it's not as bad as it sounds. If you define `args` for your component/story, Storybook can do inference on the args for you. Consider this simple example:

```js
export default {
  title: 'demo',
  args: { a: 1, b: 'hello', c: '#fff' }
}

export const First = ({ a, b, c }) => `...`;
export const Second = ...;
Second.args = { a: 2, b: 'bye', c: '#000' };
```

It will infer `a` as a number type, and `b`/`c` as string types. But maybe `c` is actually a color. Then you can augment the definition like so:

export default {
  title: 'demo',
  args: { a: 1, b: 'hello', c: '#fff' },
  argTypes: {
    c: { control: 'color' }
  },
}
```

There are a lot more examples in the docs: https://storybook.js.org/docs/react/essentials/controls

**Comment by stephenhmarsh** [comment]
Thank you!
