### ISSUE TITLE
Angular: validateDOMNesting(...): <p> cannot appear as a descendant of <p>

### ISSUE THREAD

**Issue by amnambiar** [storybookjs/storybook#15521]
**Bug:**

After upgrading storybook from v6.2.9 to **6.3.3**(latest), and runnning the storybook build and preview, below error is displayed in the browser console:
![image](https://user-images.githubusercontent.com/11058223/124941962-d4e4a500-e028-11eb-90d5-4ac563285f95.png)

This was not present at any point in the earlier version.

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid.

Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
