### ISSUE TITLE
Unable to generate docs version

### ISSUE THREAD

**Issue by 544076724** [storybookjs/storybook#15596]
The docs version cannot be built in vue3.0. The use of --docs is invalid. My command configuration is: build-storybook --quiet --docs -o build, why is this?

Is my configuration wrong? I configured it according to the official website manual。

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid.

Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
