### ISSUE TITLE
Show Code under Docs Broken Styling

### ISSUE THREAD

**Issue by yaldram** [storybookjs/storybook#15655]
**Describe the bug**
Hello Community, I am facing a weird issue the show code under docs has broken styles for me. When expanded the text is blurry and the colors are light not visible, hard to read.

**To Reproduce**
Image : - 
![image](https://user-images.githubusercontent.com/13429535/126656118-fa8bc841-9afa-4512-b78b-2179069d64e4.png)

**System**
Environment Info:

  System:
    OS: Windows 10 10.0.19041
    CPU: (8) x64 Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz
  Binaries:
    Node: 14.5.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.5 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.964.0), Chromium (91.0.864.71)
  npmPackages:
    @storybook/addon-a11y: ^6.3.2 => 6.3.3
    @storybook/addon-actions: ^6.3.2 => 6.3.3
    @storybook/addon-essentials: ^6.3.2 => 6.3.3
    @storybook/addon-knobs: ^6.3.0 => 6.3.0
    @storybook/addon-links: ^6.3.2 => 6.3.3
    @storybook/addon-viewport: ^6.3.2 => 6.3.3
    @storybook/react: ^6.3.2 => 6.3.3

**Comment by alk-mandrianarijaona** [comment]
I believe this is related to https://github.com/storybookjs/storybook/issues/15598 as well

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid.

Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
