### ISSUE TITLE
Show code not display right with dot notation component in Template section

### ISSUE THREAD

**Issue by JokerDang** [storybookjs/storybook#15662]
**Describe the bug**
 Example my code:
```
<DropdownList {..props}>
  <DropdownList.Item label="1" value="1" />
  <DropdownList.Item label="2" value="2" />
</DropdownList>

```
In template section, when I click Show code button and it show:

```
<DropdownList {..props}>
  <[object Object] label="1" value="1" />
  <[object Object] label="1" value="1" />
</DropdownList>
```

**Expected**

Display correct with my code without [object Object].

**System**
- "typescript": "4.0.3"
- "storybook/react": "^6.1.19"
- "storybook/addons": "^6.2.8"
- "storybook/essentials: "^6.1.19"

**Comment by enableds** [comment]
This is still a thing. The output of this is completely wrong. Create any react component with a dot notation, go to docs, and click show code. If your component is `<Ico.Button icon="bi-gear-fill" {...args} />` the output will be `<Button ...  />`. Any fix planed for this?

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).

**Comment by melanie-l-cb** [comment]
I have Storybook 7 and this is still an issue.
