### ISSUE TITLE
doc comments hidden in Storybook for deprecated props

### ISSUE THREAD

**Issue by scottwpage** [storybookjs/storybook#15686]
Hello, on Storybook 6.3, using Typescript,  a React component's deprecated props will not include the doc string message in Storybook if the @deprecated annotation is _above_ the message.  As an example, the `DEPRECATED. Use foo instead` message will not show up in the resulting story: 

```
type Props = {
  /**
   * @deprecated
   * DEPRECATED. Use `foo` instead.
   */
  bar: boolean;
};
```

The message will show up, however, if @deprecated is below the message.

The message is also hidden if on the same line (e.g. `@deprecated Use foo instead.` ) which matches the spec here: https://tsdoc.org/pages/tags/deprecated/

**Comment by rdevries** [comment]
So, any plans for this Issue?

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
