### ISSUE TITLE
LocationProvider issue

### ISSUE THREAD

**Issue by Musuel** [storybookjs/storybook#15688]
**Describe the bug**

When you have an Angular application with Storybook already installed and some community addons installed, some errors related to LocationProvider are popping as soon as you remove your node_modules folder and package-lock.json file, and do a fresh npm install.

**To Reproduce**

Remove your node_modules folder and package-lock.json file, then run npm install.
After that, you may see some warnings popping in console about reach/router depending on react@^16.14.0.

**Temporary Solution**

Install manually react@^16.14.0 as a dev dependency.

This issue is related to reach/router which seems to be an abandonned package and should be migrated to react router 6. Some issues have already been opened related to this migration and npm 7 issues.

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid.

Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
