### ISSUE TITLE
Stories aren't discovered outside project root

### ISSUE THREAD

**Issue by gsouquet** [storybookjs/storybook#15694]
**Describe the bug**

Stories aren't discovered in a sibling directory, or by referencing a locally symlinked package

**To Reproduce**

Given the following directory structure

```
project1/
├── .storybook/
│   └── main.js

project2/
├── src/
│   └── component.stories.js

```

Where `project2` is installed as a symlinked package in `project1` (using `yarn link`)

```
module.exports = {
  "stories": [
    "../../project2/src/**/*.stories.mdx",
    "../../project2/src/**/*.stories.@(js|jsx|ts|tsx)"
  ],
  "addons": [
    "@storybook/addon-links",
    "@storybook/addon-essentials"
  ]
}
```

Referencing  `../node_modules/project2/....` fails in the same manner

**System**

All

**Additional context**

The project setup might be slightly unconventional, but I would rather keep the Storybook setup in `project1/` as it is where the webpack configuration for this multi-repo project exists and would be better to not create cross dependencies.

I am not sure whether there is a reason why Storybook behaves this way or whether it is a defect

**Comment by bukharov** [comment]
I may have the same issue. 
`stories: ['../../../applications/**/*.stories.tsx', '../../../shared/**/*.stories.tsx']` yields `Oh no! Your Storybook is empty`

I suspect it's because of this in the `main.iframe.bundle.js`:
`[__webpack_require__("./applications sync recursive ^\\.(?:(?:^|\\/|(?:(?:(?%21(?:^|\\/)\\.).)*?)\\/)(?%21\\.)(?=.)[^/]*?\\.stories\\.tsx)$"), __webpack_require__("./shared sync recursive ^\\.(?:(?:^|\\/|(?:(?:(?%21(?:^|\\/)\\.).)*?)\\/)(?%21\\.)(?=.)[^/]*?\\.stories\\.tsx)$")]`

notice `%21`? that should be just `!`

in the `generated-stories-entry.js` it looks fine though:

`(0, _frameworkImportPath.configure)([require.context('../../../applications', true, /^\\.(?:(?:^|\\/|(?:(?:(?!(?:^|\\/)\\.).)*?)\\/)(?!\\.)(?=.)[^/]*?\\.stories\\.tsx)$/),require.context('../../../shared', true, /^\\.(?:(?:^|\\/|(?:(?:(?!(?:^|\\/)\\.).)*?)\\/)(?!\\.)(?=.)[^/]*?\\.stories\\.tsx)$/)], module, false);`

i suppose somehow it gets escaped in the `VirtualModulesPlugin` 🤔

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
