### ISSUE TITLE
angular: ModuleNotFoundError: Module not found: Error: Can't resolve with typescript declaration import .d.ts

### ISSUE THREAD

**Issue by peterpeterparker** [storybookjs/storybook#15750]
**Describe the bug**
Adding an import on a Typescript declaration file (`.d.ts`) in an Angular component breaks `npm run storybook`. The command results in following error:

> 99% done plugins webpack-hot-middlewarewebpack built preview a6ea4c93ebb5591a07da in 12786ms
> ModuleNotFoundError: Module not found: Error: Can't resolve './my-lib' in '/Users/projects/lab/my-storybook-workspace/projects/my-lib/src/lib'

**To Reproduce**
```
git clone https://github.com/peterpeterparker/my-storybook-workspace
cd my-storybook-workspace
npm ci
npm run storybook
```

If you remove the `import` and `console.log` in the demo [component](https://github.com/peterpeterparker/my-storybook-workspace/blob/main/projects/my-lib/src/lib/my-lib.component.ts), you will be able to start successfully Storybook.

**Additional context**
The sample repo narrows the error. Renaming the declaration file to `.ts` would solve the issue but, in the real use case I have  to apply, I have to import the declaration file from a third party library dependencies, therefore would be happy if there would be another solution.

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
