### ISSUE TITLE
workspaces config expects an Array

### ISSUE THREAD

**Issue by DimiMikadze** [storybookjs/storybook#15765]
**Describe the bug**

Installation of the `storybook` with `npx sb init` command fails within Monorepo because of having workspaces property as an object in the `package.json` file instead of an array.

```
"workspaces": {
    "nohoist": [
        "react-scripts"
    ]
}
```

Although, an object is a valid type for workspaces property as per Yarn [documentation](https://classic.yarnpkg.com/blog/2018/02/15/nohoist).

```
// flow type definition:
export type WorkspacesConfig = {
  packages?: Array<string>,
  nohoist?: Array<string>,
};
```

**To Reproduce**

Just ad ann `workspaces` property to `package.json` as an object, and try to install or upgrade Storybook with "npx sb".

**System**

```
Environment Info:

  System:
    OS: macOS 11.3.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Binaries:
    Node: 12.20.0 - ~/.nvm/versions/node/v12.20.0/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.15.0 - ~/.nvm/versions/node/v12.20.0/bin/npm
  Browsers:
    Chrome: 92.0.4515.131
    Safari: 14.1
```

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
