### ISSUE TITLE
Missing script: "start-storybook"

### ISSUE THREAD

**Issue by lucilecoutouly** [storybookjs/storybook#15843]
```
npm run storybook

> frontend@0.0.1 storybook
> start-storybook -p 6006

sh: 1: start-storybook: not found
```
when ever i choose npx sb init --type .... react or web-component
i can't start server

**Comment by shilman** [comment]
What happens when you do the following?

```sh
ls node_modules/.bin | grep storybook
```

**Comment by lucilecoutouly** [comment]
```
ls node_modules/.bin | grep storybook
getstorybook
```

**Comment by shilman** [comment]
This is what it should look like:

```sh
$ ls node_modules/.bin | grep storybook
build-storybook
start-storybook
storybook-server
```

Perhaps try reinstalling?

**Comment by lucilecoutouly** [comment]
hello,
when inside docker 
FROM node:buster

I try 
`npm install @storybook/cli@latest --save-exact`
it didn't install start-storybook

Which command should install start-storybook ?
thanks

**Comment by alk-mandrianarijaona** [comment]
@lucilecoutouly did you find any solution for this issue?

**Comment by nhoizey** [comment]
With Storybook 6.5.16, `start-storybook` and `build-storybook` are also missing:

```shell
$ ls node_modules/.bin | grep storybook
getstorybook
storybook
```

**Comment by penkin** [comment]
Found the issue, need to use `sb start` and `sb build` respectively. Not sure why the script used the old cli commands.

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
