### ISSUE TITLE
Ability to pass micromatch options when configuring story loading

### ISSUE THREAD

**Issue by brandonferrua** [storybookjs/storybook#15913]
**Is your feature request related to a problem? Please describe**
I have a need to parse out documentation stories within a monorepo. Due to our monorepo structure, matching the glob pattern is adding complexity to parse the stories I want to showcase in our documentation. Per https://storybook.js.org/docs/react/configure/overview#configure-story-loading it does not seem possible to pass in [micromatch options](https://github.com/micromatch/micromatch#options) into the configuration, even though it's using micromatch to parse the files behind the scenes.

**Describe the solution you'd like**
The ability to pass in an object with micromatch options to the `stories` key.

```js
module.exports = {
  stories: {['../src/**/*.stories.@(js|mdx)'], options},
}
```

**Describe alternatives you've considered**
I can get the paths of all story files and then build my own filtered array using https://github.com/storybookjs/storybook/issues/11181#issuecomment-674844736. Though it seems like I'm just recreating this feature request at that point?

**Are you able to assist to bring the feature to reality?**
no

**Comment by shilman** [comment]
what options do you want to provide?

**Comment by brandonferrua** [comment]
We currently have a need for the `ignore` option to be passed into micromatch. Could it just accept an object with any of the micromatch options? Would be happy with just `ignore` though.

**Comment by dannyhw** [comment]
By chance I was looking at this today and from what I can tell micromatch is only used to generate a regex that is used in a `require.context`.  I don't think passing micromatch options would work unless the options are specific to the makeRe function (the makeRe function doesn't have the ignore option). 

I could be wrong but the only reference I found to micromatch is this one, so that's what I based this observation on.
https://github.com/storybookjs/storybook/blob/1143d6933fe9b6e8ca742a594cc515f2cebed61a/lib/core-common/src/utils/to-require-context.ts

**Comment by shilman** [comment]
Partially addressed by https://github.com/storybookjs/storybook/pull/22873

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if this is still relevant in SB 7.x.
