### ISSUE TITLE
Please add support for FormGroups, FormArrays & FormControls in Angular

### ISSUE THREAD

**Issue by andykono** [storybookjs/storybook#15950]
**Storybook not useful for Angular without FormGroups, FormArrays & FormControls.**

**Comment by shilman** [comment]
@andykono what would that entail?

**Comment by Marklb** [comment]
My assumption is that this means using Angular FormControls as args. Sort of like the POC I did a while ago, https://github.com/storybookjs/storybook/issues/12308#issuecomment-683956199.

I was waiting for custom controls support before trying that again, but it may be possible to partially support them with the addon api. If the arg could be altered before being serialized, then the FormControl instance could be moved to a reference map in the preview and replaced with the value before the args are sent to the manager. Then when it comes back, the arg could be set as the FormControl instance's value when it returns to the preview and the FormControl instance placed in props before get is passed to the story.

That is the basic idea for what my POC did, but I had added a new Storybook Control and was serializing the FormControl into a json object with multiple states of the FormControl instance, such as `value`, `disabled`, `touched`, `dirty` and allowed each one to be tweaked from a Control that contained multiple inputs.

Right now my workaround is to initialize a new FormControl instance each time `props` update, but that causes all the change FormControl's state to be reset. At the momenet when I need to maintain the state and use controls I create the FormControl instance in the global scope and try to keep it updated by resetting it when the story selected even is fired. It doesn't look good doing that, but maybe it could be done more accurately with the current addon api.

**Comment by andykono** [comment]
> @andykono what would that entail?

It make storybook useful for angular components with input prop [formControl].

**Comment by andykono** [comment]
Thanks @Marklb.
I have seen it in discord (if I have not mistaken).

I mean something like this :)
```
import {moduleMetadata, Meta, Story} from '@storybook/angular';
import {CommonModule} from '@angular/common';
import {SwitcherComponent} from '../src/app/components/switcher/switcher.component';
import {FormControl, FormsModule, ReactiveFormsModule} from '@angular/forms';


// data mock
const switcherOptions = [
  {id: '1', title: 'Cardiff'},
  {id: '2', title: 'Halifax'},
  {id: '3', title: 'London'}
];

const fcSelected = new FormControl(switcherOptions[1]);

// STORY ----
export default {
  title: 'Switcher',
  component: SwitcherComponent,
  decorators: [
    moduleMetadata({
      declarations: [SwitcherComponent],
      imports: [CommonModule, FormsModule, ReactiveFormsModule]
    })
  ],
  excludeStories: /.*Data$/
} as Meta;

const Template: Story<SwitcherComponent> = (args) => ({
  props: {
    ...args,
  },
});

export const Default = Template.bind({});

Default.args = {
    name: 'testSwitcher',
    options: switcherOptions,
    formControl: fcSelected
};
```

**Comment by Marklb** [comment]
@andykono If you are initializing the `FormControl` in the global scope like that then you can pass it into props directly, since there isn't a Control for a `FormControl` type anyway. It isn't ideal, but is an ok work around, because it would just pass in the same instance each time props update. The instance won't reset unless you refresh the page though, unless you listen for the the story selected or changed events and reset the FormControl yourself.

By passing the FormControl instance directly to `props`, instead of `args`, it avoids the serialization/deserialization that happens when args get sent from the preview to the manager for addons, like the controls, to interact with them.

Example:
```ts
import {moduleMetadata, Meta, Story} from '@storybook/angular';
import {CommonModule} from '@angular/common';
import {SwitcherComponent} from '../src/app/components/switcher/switcher.component';
import {FormControl, FormsModule, ReactiveFormsModule} from '@angular/forms';


// data mock
const switcherOptions = [
  {id: '1', title: 'Cardiff'},
  {id: '2', title: 'Halifax'},
  {id: '3', title: 'London'}
];

const fcSelected = new FormControl(switcherOptions[1]);

// STORY ----
export default {
  title: 'Switcher',
  component: SwitcherComponent,
  decorators: [
    moduleMetadata({
      declarations: [SwitcherComponent],
      imports: [CommonModule, FormsModule, ReactiveFormsModule]
    })
  ],
  excludeStories: /.*Data$/
} as Meta;

const Template: Story<SwitcherComponent> = (args) => ({
  props: {
    ...args,
    formControl: fcSelected
  },
});

export const Default = Template.bind({});

Default.args = {
    name: 'testSwitcher',
    options: switcherOptions,
    // formControl: fcSelected // Since there isn't a control for `FormControl` type, I moved it to props as a workaround.
};
```

**Comment by andykono** [comment]
Thanks, but it hot working for me :( I not see console.log in
```
  writeValue(value: SwitcherItem): void {
    console.log('>>>', value);
    if (!value) {
      this.selected = {id: '', title: ''};
    } else {
      this.selected = value;
    }
  }
```

Hm...

**Comment by Marklb** [comment]
@andykono That is correct that `writeValue` would not be called. I hadn't noticed it, because I rarely define a story without providing a `template` and I would always add the directive in my template, since I knew it wasn't an input. In your example, `writeValue` isn't called because Angular only supports adding directives from a template. So, Storybook is just setting the `formControl` property on the component instance from js.

Until Storybook has a way to add directives to stories that don't return a `template`, the following are the only workarounds I can think of at the moment:
1. Return a `template` in your Story.
2. (*This would work for the previously posted example, but requires an odd change in your component's code.*) Make Storybook think `formControl` is an input of your component. The `Component` decorator supports a string array of input names, so you can tell your component it has an input without adding an input property. By doing that, when Storybook is generating a `template` for your component it will recognize the prop `formControl` as an input to your component, even though it is really an input to a directive, and the `formControl` will get added as an input to the component. 

Example for workaround 2:
```ts
@Component({
	selector: 'ex-comp',
	template: '',
	inputs: [ 'formControl' ]
})
class ExComponent implements ControlValueAccessor {
	...
}
```

**Comment by andykono** [comment]
@Marklb Thank you very much. And sorry about delay ;((
Yes, it works, but IMHO it not so good (no-inputs-metadata-property). As for dev time maybe it possible to do some like this. But this changes in component will be not desirable :(

**Comment by brambooo** [comment]
Any progress on this?

**Comment by ndelangen** [comment]
@storybookjs/angular is this something we want to support / do at some point?

**Comment by Marklb** [comment]
@ndelangen This has been requested multiple times, so I think we mostly know what is wanted. I don't consider this a high priority, but do think better support for form controls would be useful.

**Comment by tabassumt1** [comment]
import { cloneDeep } from 'lodash';

const deleteReference = (formGroup: FormGroup) => {
  const clonedFormGroup = cloneDeep(formGroup);
  delete clonedFormGroup['controls']['name']['_parent'];
  delete clonedFormGroup['controls']['age']['_parent'];
  return clonedFormGroup;
};

const Template: Story = (args: any) => ({
  props: {
    ...args,
    fg: deleteReference(originalFormGroup)
  }
});

Though this is really an old issue. But this bunch of code worked perfectly.

**Comment by nightisyang** [comment]
> Some updates? waiting for this as well

This worked out for me https://github.com/storybookjs/storybook/discussions/15602#discussioncomment-6290582
