### ISSUE TITLE
[Documentation] Migration guide has a deadlink

### ISSUE THREAD

**Issue by realestninja** [storybookjs/storybook#15968]
**Describe the bug**
A link in the documentation leads to a page not found.

**To Reproduce**
https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#deprecated-addparameters-and-adddecorator
The "Preview Entries" in this paragraph points to this page: https://github.com/storybookjs/storybook/blob/next/docs/api/writing-presets.md#preview-entries

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
