### ISSUE TITLE
dotenv-webpack ^7.0.0 in webpack5 config has dangerous defaults

### ISSUE THREAD

**Issue by anilanar** [storybookjs/storybook#16086]
Please read https://github.com/mrsteele/dotenv-webpack, specifically warnings about `ignoreStub`. 

`ignoreStub: false` is a dangerous setting that won't work for many projects by default. It basically replaces all occurences of standalone `process.env` (not just `process.env.{X}`) with `MISSING_ENV_VAR` which breaks at least our codebase.

So I suggest that `ignoreStub: true` is passed to dotenv plugin options.

**Comment by shilman** [comment]
Related: #16067

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
