### ISSUE TITLE
Full Screen iFrame Not Scrolling in iOS

### ISSUE THREAD

**Issue by sheby2** [storybookjs/storybook#16125]
I am embedding a link with full-screen iframe but that is not scrolling in ios. How can I solve it? I need without scrollbar.

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
