### ISSUE TITLE
storybook : set-value vulnerabilities of around 1k

### ISSUE THREAD

**Issue by achhranitesh** [storybookjs/storybook#16227]
storybook : set-value vulnerabilities of around 1k

Hi I have setup storybook inside CRA, on latest npm i. I get a set of 1k + vulnerabilities for only react-storybook, any fix around this which can reduce the number

**Comment by jahanner** [comment]
And if you're using npm instead of yarn, this seems to work https://www.npmjs.com/package/npm-force-resolutions. Then you can do "resolutions": ... like @fernandopasik mentioned

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
