### ISSUE TITLE
Addon-a11y: Remove `story-root` reference

### ISSUE THREAD

**Issue by shilman** [storybookjs/storybook#16232]
_Originally posted by @kaelig in https://github.com/storybookjs/storybook/issues/16129#issuecomment-926951565_

By the way, what's this code supposed to do?

https://github.com/storybookjs/storybook/blob/4750c6bfbcc340330c905071574a511153231d7c/addons/a11y/src/a11yRunner.ts#L20

Is `#story-root` a thing?

If this is only related to this addon, should it be documented?

**Comment by jam-awake** [comment]
I believe this was supposed to look up the [`element` parameter value](https://github.com/storybookjs/storybook/blob/main/addons/a11y/README.md?plain=1#L175-L176), if it is provided. I just specified the `element` parameter on Storybook 6.3.12 and I get "The scan encountered an error: {}` in the panel. When I dropped the `element` parameter, the addon works fine. So, I explored the source code to see the control flow:

1. [`axe` is run on the `element` identifier](https://github.com/storybookjs/storybook/blob/main/addons/a11y/src/a11yRunner.ts#L50)
1. [the `element` identifier refers to the element specified in input or the return of `getElement` if it isn't provided](https://github.com/storybookjs/storybook/blob/main/addons/a11y/src/a11yRunner.ts#L44)
1. [`getElement`](https://github.com/storybookjs/storybook/blob/main/addons/a11y/src/a11yRunner.ts#L19-L22) refers to an HTML element, either `#root`, the top-level div that contains a story by default when no decorators are used, or `#story-root`, a mysterious value.
1. [`input` is the value returned by `getParams`](https://github.com/storybookjs/storybook/blob/main/addons/a11y/src/a11yRunner.ts#L38)
1. [`getParams`](https://github.com/storybookjs/storybook/blob/main/addons/a11y/src/a11yRunner.ts#L69-L80) either returns the `element` parameter if specified or null.

So, your real problem is that the `element` parameter's docs are incorrect. That parameter currently seems to do nothing.

**Comment by jsomsanith** [comment]
Hi 👋 
Fixed proposed here: #17989 
Thanks @jam-awake for the investigation

**Comment by jsomsanith** [comment]
PR merged

**Comment by shilman** [comment]
w00t!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.5.0-beta.4 containing PR #17989 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```
