### ISSUE TITLE
Typescript - Export an enum

### ISSUE THREAD

**Issue by BiancaArtola** [storybookjs/storybook#16249]
**Describe the bug**
I am using Storybook, React, and Typescript on their last versions. I have a components library on Storybook that I use on other front-ends. I would like to export an enum from the library to the front-end that is using it. 
I am exporting the enum like this on the Storybook side:
![image](https://user-images.githubusercontent.com/21174759/136082275-b7c81712-4196-466a-8ad3-e62c9b4b8dae.png)

I am trying to use it on the front-ends as:
`import { ExportEnum } from "@library/build/table/enums/enums";`

And the result is:
`Module not found: Can't resolve '@library/build/table/enums/enums' in 'file'
`

Any help with this, please? I am already exporting interfaces and they work fine. I only have issues with enums

**Comment by shilman** [comment]
What does it mean to export enums from Storybook?

**Comment by Tim-arts** [comment]
Hello @BiancaArtola , could you try to enable `isolatedModules` in the tsconfig of your project where you declare this enum?

```
"compilerOptions": {
  "isolatedModules": true
},
```

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
