### ISSUE TITLE
Angular - argTypes works only when defined on the export default Meta level (ignored when defined on the individual named exported stories)

### ISSUE THREAD

**Issue by distributev** [storybookjs/storybook#16283]
Storybook version: 6.3.10
Angular version: 12.2.8

**Describe the bug**

When I define the argTypes declaration in the export default Meta section it works fine (but it applies to all my stories, which I don't want)

When I copy-paste (move) the same argTypes declaration on individual named export stories, it is ignored and no controls appear in the story where I defined the argTypes (as per my intention) and no controls appear anywhere because I argTypes was removed from the export default Meta section (this is fine, this was my intention).

I intend to define the argTypes individually per story, but because of this bug it is currently not possible.

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
