### ISSUE TITLE
Core: Full iframe reload loses globals

### ISSUE THREAD

**Issue by yannbf** [storybookjs/storybook#16383]
**Describe the bug**

As title says.

Steps:
1 - [Select a story with interactions](https://next--storybookjs.netlify.app/official-storybook/?path=/story/addons-interactions-accountform--standard-email-success)
2 - Set globals, such as theme
3 - Go to debug mode in addon-interactions
4 - Switch stories

You will see that the theme will reset:

![Kapture 2021-10-18 at 12 28 44](https://user-images.githubusercontent.com/1671563/137715353-2a90ebd5-f010-4317-adc3-3772b1373b2f.gif)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200510412866230/1201277457121900) by [Unito](https://www.unito.io)

**Comment by MBelniak** [comment]
Hi, I'm still experiencing this issue when I reload the IFrame programmatically via window.location.reload(). I set the URL of my design package in browser's local storage to read it in preview-head.html where I add a script with mentioned URL as src. 

I tried with `setTimeout(() => window.location.reload(), 1000);` and IT WORKS! 
Is there a way to wait with the reload until the globals are saved in manager? 

Anyway, my code:
```export const globalTypes = {
    theme: {
        name: 'THEME',
        description: 'Theme package to use for components',
        defaultValue: 'neutral',
        toolbar: {
            icon: 'paintbrush',
            items: themeNames
        }
    }
};

const themeResourceUrl = 'theme-resource-url';
const withThemeReload = (Story, context) => {
    React.useEffect(() => {
        const newThemeResourceUrl = `./theme/${context.globals.theme}.js`;
        if (localStorage.getItem(themeResourceUrl) !== newThemeResourceUrl) {
            localStorage.setItem(themeResourceUrl, newThemeResourceUrl);
            window.location.reload();
        }
    }, [context.globals.theme]);
    return <Story {...context} />;
    export const decorators = [withThemeReload];
```

**Comment by ghengeveld** [comment]
Need to investigate. Might be related to the manager <> preview sync which takes a moment because it involves sending events over the channel.

**Comment by shilman** [comment]
@MBelniak @ghengeveld I'd propose we simply don't support the use case of immediately reloading the page before the globals get synced.

**Comment by MBelniak** [comment]
@ghengeveld That's right. I can live with it. That 1 second timeout hack seems to be sufficient and stable.

**Comment by shilman** [comment]
Fixed in  #16469

@MBelniak reported a separate issue

**Comment by amccloud** [comment]
Is anyone else running into a similar issue where args are not persisted when calling `reload` from the iframe? My args are optional and initially unset. I have a hunch the reload is briefly rendering the default (unset) vs. what is in the args query param. My args eventually update to match query params, but the brief gap in consistency makes it hard to distinguish a never used arg from an arg that is just reloading.

I'd expect the first render after reload to be consistent with the current global/arg/etc state. @shilman was this essentially the same issue here but with globals instead of args? Thinking of spinning up a similar PR for args too.

**Comment by shilman** [comment]
@amccloud According to https://github.com/storybookjs/storybook/pull/16469, it should fix the issue for both args & globals. Perhaps @ghengeveld can weigh in on your comment, since he is more familiar with the guts of what's going on here

**Comment by ghengeveld** [comment]
It's been a year since I worked on that, so I don't have that much familiarity anymore. Judging by my own description on that PR, I would expect a reload to just work. What I'd do is check the `window.location.href` of the iframe before the reload, to check whether the correct args/globals are in the querystring. If not then that's a bug, or your args/globals are deemed insecure and therefore don't serialize to the URL (in which case the main Storybook URL wouldn't have them either).
