### ISSUE TITLE
Code block in Docs page doesn't work properly with decorators in 6.4.0 beta

### ISSUE THREAD

**Issue by kovavka** [storybookjs/storybook#16482]
**Describe the bug**
Code block are not generated properly anymore if you have global decorators:

https://user-images.githubusercontent.com/34582631/138944327-4874d8d7-7bab-4dff-bead-a8420faeda49.mov

If I remove decorators, everything works fine. I personally can afford it, I don't need decorators anymore, but seems like it's a pretty important functionality.

**To Reproduce**
I built an example to reproduce in codesandbox:
https://codesandbox.io/s/broken-code-block-w90j6

**Additional context**
Also it worked fine before in my repo with: 
```
"@storybook/addon-actions": "6.4.0-alpha.41",
"@storybook/addon-essentials": "6.4.0-alpha.41",
"@storybook/addon-links": "6.4.0-alpha.41",
"@storybook/builder-webpack5": "6.4.0-alpha.35",
"@storybook/manager-webpack5": "6.4.0-alpha.35",
"@storybook/react": "6.4.0-alpha.40",
```

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
