### ISSUE TITLE
Consistent error handling for addon-interactions

### ISSUE THREAD

**Issue by shilman** [storybookjs/storybook#16585]
Currently we handle errors differently between errors thrown on instrumented functions and errors thrown on non-instrumented functions:

```js
const Instrumented = Template.bind({});
Instrumented.play = async ({ canvasElement }) => {
  const taskInput = await findByRole(canvas, 'textbox');
  await fireEvent.change(taskInput, {
    target: { value: 'Fix bug in the textarea error state' },
  });
}

const NonInstrumented = Template.bind({});
NonInstrumented.play = async ({ canvasElement }) => {
  throw new Error('hahaha');
};
```

The former shows an error in the interactions tab:

<img width="770" alt="InboxScreen_-_Default_⋅_Storybook" src="https://user-images.githubusercontent.com/488689/140257583-7ee889d0-93dc-4fca-90f2-8f111be7fa7f.png">

The latter shows a typical storybook error:

<img width="923" alt="InboxScreen_-_Default_⋅_Storybook" src="https://user-images.githubusercontent.com/488689/140257518-4134e617-33c4-4dc9-9d92-2a8e1e8edc25.png">

Should this handling be consistent?

**Comment by ghengeveld** [comment]
Preferably we wouldn't show a red box for simple errors at all, but rather something like the interactions panel. However, the interactions addon might not be installed, even when using the play function and instrumented libraries. That means we can't simply catch everything thrown in the play function, because doing so would gobble it up and go nowhere.

We could simply catch it, log the error to console and call it a day.
We could detect whether the Interactions addon is installed an only catch if it is.
We could introduce a bespoke UI component in the Storybook manager to surface exceptions. Basically a nicer version of the redbox, somewhere in a modal or something. This could tie in nicely with a render phase indicator.

**Comment by tmeasday** [comment]
I think @ghengeveld's ideas make sense; I would just say that for now whatever we do I think we should be consistent between normal and intercepted errors. For 6.4 that probably means logging to the console and showing in the interactions panel.

**Comment by shilman** [comment]
Huzzah!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.4.0-beta.29 containing PR #16590 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.

**Comment by ghengeveld** [comment]
Reopening because the PR that handles this is still pending: #16592

**Comment by tmeasday** [comment]
Sorry not sure why I referenced this issue

**Comment by shilman** [comment]
Ta-da!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.0-alpha.11 containing PR #16592 that references this issue. Upgrade today to the `@future` NPM tag to try it out!

```
npx sb upgrade --prerelease
```
