### ISSUE TITLE
Button next section for the docs

### ISSUE THREAD

**Issue by judicaelandria** [storybookjs/storybook#16654]
**Is your feature request related to a problem? Please describe**
I'm always frustrated when I go the docs, read a section for example the introduction and scroll till the bottom, but when I need to scroll to the top to be able to go to the next section
![Menu Introduction](https://user-images.githubusercontent.com/46365844/141065117-e8a384cd-6583-4011-ab87-8ffb44bc2761.png)
**Describe the solution you'd like**
What would you like to see added to Storybook to solve problem?
I would be really cool if you can add a menu on the bottom page to go to the next tutorials,
for example after the introduction we have Args, adding the button to go the args tuts like so

**Describe alternatives you've considered**
Any alternative solutions or features you've considered.
![menu](https://user-images.githubusercontent.com/46365844/141066101-b15ad794-5c6f-4873-858c-b6d5b1571715.png)

**Are you able to assist to bring the feature to reality?**
yes, I can...

And BTW, thanks for all the works you do here,

**Comment by yannbf** [comment]
Hey @judicaelandria thanks for your feedback! This is a feature we already have in the Get Started section:
![image](https://user-images.githubusercontent.com/1671563/150676687-ccae70d4-ce61-467e-8b75-93eb72b34e60.png)

@jonniebigodes @domyen we could apply that to other sections like suggested

**Comment by Pepijnk12** [comment]
@yannbf this can be done easily by adding a description and changing everything to a bullet-list item. https://github.com/storybookjs/storybook/blob/next/docs/toc.js.

**See storybookjs frontpage:** https://github.com/storybookjs/frontpage/blob/e867387da7255691b931f89ba3f3cff3cc692de7/gatsby-node.js#L176

Is this preferred because the sidebar UI will change as well? We could also change 'storybookjs frontpage' because every page will get the next button at the bottom of the page, instead of only bullet-link items.

<img width="257" alt="storybook-bullet-list" src="https://user-images.githubusercontent.com/33691272/159138559-299e64d2-a1bf-4dc8-9d1c-b51b00021edf.png">

**Comment by yannbf** [comment]
Great question! cc @domyen @MichaelArestad @jonniebigodes

**Comment by MichaelArestad** [comment]
As long as it makes sense to go through those sections in that order, the change in the sidebar design works. It needs to read like chapters in a story. I don't have the bandwidth to go through it now. Could one of you confirm that it has a nice flow?

**Comment by domyen** [comment]
Only the get started guide has a "flow". The rest are individual docs pages.
