### ISSUE TITLE
storybook not work for nebular radio and checkbox

### ISSUE THREAD

**Issue by soloraid** [storybookjs/storybook#16712]
my angular project support nebular package but some modules not working in storybook
they has error like the image uploaded
my nb-radio and nb-checkbox has this error.
pls help me !
![image](https://user-images.githubusercontent.com/46398811/142183829-8b80773d-7a00-41b9-8686-2fa61531abd4.png)

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
