### ISSUE TITLE
Using wildcards for directories doesn't seem to be working

### ISSUE THREAD

**Issue by dep** [storybookjs/storybook#16826]
**Describe the bug**

This is working:

```
module.exports = {
  stories: [
    "../node_modules/@foo/titan-template/src/stories/app.stories.mdx",
  ],
  addons: ["@storybook/addon-docs"],
};
```

However this is not:

```
module.exports = {
  stories: [
    "../node_modules/@foo/titan-*/src/**/*.stories.mdx"
  ],
  addons: ["@storybook/addon-docs"],
};
```

Even though an `ls` test on the same pattern finds matches 🤔

```
▶ ls ../node_modules/@foo/titan-*/src/**/*.stories.mdx
../node_modules/@foo/titan-template/src/stories/app.stories.mdx
```

**Comment by shilman** [comment]
@tmeasday any comments on this glob pattern?

**Comment by tmeasday** [comment]
Hmm, I'm no expert on `picomatch`. Does it work with that pattern @dep?

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
