### ISSUE TITLE
Canvas withSource prop in @storybook/addon-docs has conflicting types

### ISSUE THREAD

**Issue by billietaylor2** [storybookjs/storybook#17018]
**Describe the bug**
`withSource` prop has conflicting intersection types that are `SourceState` and `SourceProps`.

**To Reproduce**
- import and use the `Canvas` from `@storybook/addon-docs`
- import the `SourceState` enum from `@storybook/addon-docs`
- try to set `withSource` prop to be enum `SourceState.NONE`
- TS error

**System**
Please paste the results of `npx sb@next info` here.

**Additional context**

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
