### ISSUE TITLE
Mdx ArgsTable does not get props from TypeScript type

### ISSUE THREAD

**Issue by GlebUrentsev** [storybookjs/storybook#17029]
**Describe the bug**

The bug connected with ArgsTable when properties are described through an interface or a type in .ts file that is imported from another module.

**To Reproduce**
The project uses the 6.4 version of storybook.

I published test repo to reproduce the bug 
https://github.com/GlebUrentsev/TestMdxArgsTable

Just run storybook and there will be two stories of button.
The difference is that the first Button has type in the exact same file as the component, the Button2 uses type from .ts file with the same type.

Current behavior  - Button2 does not have ArgsTable.

Expected behavior - Button2 has ArgsTable as Button.

**Comment by joeycozza** [comment]
I am digging into a similar issue, and I saw this comment on react-docgen's README. https://github.com/reactjs/react-docgen#flow-and-typescript-support

> Note: react-docgen will not be able to grab the type definition if the type is imported or declared in a different file.

So for your example, I wonder if maybe react-docgen is being used instead of react-docgen-typescript. (or maybe react-docgen-typescript has the same limitation).

The [ArgTypes docs here](https://storybook.js.org/docs/react/api/argtypes#automatic-argtype-inference) make it seem like it would infer the typescript and use react-docgen-typescript, but it isn't explicitly stated that it is smart enough to do so...

**Comment by GlebUrentsev** [comment]
@joeycozza Thank you for advice! For my example the problem was fixed by installing typescript.
`npm i typescript`
But, digging into the problem, I found the weird case:

If you have multiple components with displayName in the file, it breaks the ArgsTable, for example

```tsx
const ButtonIcon = () => <img />;
ButtonIcon.displayName = "ButtonIcon"

const Button = () => <button><ButtonIcon  /></button>
Button.displayName = "Button"
```


ArgsTable for Button will have unknown in description column. Like in that issue [15303](https://github.com/storybookjs/storybook/issues/15303)

The problem can be solved by splitting components with displayName in different files.
