### ISSUE TITLE
"Select" control does not support string with extra spaces as an option

### ISSUE THREAD

**Issue by daniel-stoian-lgp** [storybookjs/storybook#17051]
**Describe the bug**
Recently, we migrated from knobs to controls using storybook 6.3.12 and we have usecases where a component must be tested with strings with extra spaces
When selecting a string with extra spaces( example "Hello            there" with extra spaces between the 2 words) in a select control, the selected value is rendered as undefined and the text is not displayed in our components.

When we used knobs, the generated HTML select had each option with a value attribute. and there was no issue in using strings with extra spaces

![image](https://user-images.githubusercontent.com/63335068/146896571-3e448141-43fb-4e31-9dc9-9c33cb8f06d5.png)

With controls, the options don't have a value attribute.

![image](https://user-images.githubusercontent.com/63335068/146897231-62a6769f-b594-40e0-9475-5647b4a7d13f.png)

When trying to select an option, the string with extra spaces appears with only 1 space
![image](https://user-images.githubusercontent.com/63335068/146897159-7075690b-f520-43f3-9c97-551f8b777a6e.png)

After selecting it, the dropdown looks as if no option is selected and the url is appended with this string: **_&value:!undefined_**

![image](https://user-images.githubusercontent.com/63335068/146897461-fdd2c9e7-add1-44d9-a679-60dc42d83d4b.png)

**To Reproduce**
In any select control, put a string with extra spaces or a string which starts with a space as an option and select it

**Comment by megbailey** [comment]
I have experienced this same issue when converting knobs to controls. Adding the additional space allowed us to bypass the sorting of numbered options as numbers allowing the options to show in the correct order when the label differed from the number value. Now, if the option has a different label, it is placed last in the list rather than in string order.
<img width="1212" alt="Screen Shot 2023-04-13 at 12 56 02 PM" src="https://user-images.githubusercontent.com/32280319/231869075-9b08d213-2267-444f-ac71-6404712c44ed.png">

**Comment by oxcened** [comment]
I've submitted a pull request that fixes this 🎉

**Comment by anniepauline** [comment]
is it up for grabs?
