### ISSUE TITLE
Webpack 5 build fails with type:module and main.cjs

### ISSUE THREAD

**Issue by angrycat9000** [storybookjs/storybook#17050]
**Describe the bug**

Trying to use webpack 5 with a `type:module` package fails to build.

**To Reproduce**
See reproduction at https://github.com/angrycat9000/storybook-webpack5-mjs

**System**
```
  System:
    OS: macOS 11.5.2
    CPU: (8) x64 Intel(R) Core(TM) i5-8279U CPU @ 2.40GHz
  Binaries:
    Node: 12.18.3 - /usr/local/bin/node
    Yarn: 3.1.1 - ~/.yarn/bin/yarn
    npm: 6.14.6 - /usr/local/bin/npm
  Browsers:
    Chrome: 96.0.4664.110
    Firefox: 88.0.1
    Safari: 14.1.2
  npmPackages:
    @storybook/addon-actions: ^6.5.0-alpha.4 => 6.5.0-alpha.4 
    @storybook/addon-docs: ^6.5.0-alpha.4 => 6.5.0-alpha.4 
    @storybook/addon-essentials: ^6.5.0-alpha.4 => 6.5.0-alpha.4 
    @storybook/addon-links: ^6.5.0-alpha.4 => 6.5.0-alpha.4 
    @storybook/builder-webpack5: ^6.4.9 => 6.4.9 
    @storybook/manager-webpack5: ^6.4.9 => 6.4.9 
    @storybook/web-components: ^6.5.0-alpha.4 => 6.5.0-alpha.4 
```
**Additional context**

I renamed `main.js` to `main.cjs` to work around the `Error [ERR_REQUIRE_ESM]: Must use import to load ES Module` ( https://github.com/storybookjs/storybook/issues/11587 ). That fix worked using webpack 4.  It now breaks when trying to use webpack 5

**Comment by IanVS** [comment]
I updated the reproduction to the latest 6.5.0-beta.0, and I'm seeing this error when attempting to run `yarn build-storybook`:

```
ERR! => Failed to build the preview
ERR! Module not found: Error: Can't resolve '/Users/ianvs/code/experiments/storybook-webpack5-mjs/node_modules/@storybook/client-api' in '/Users/ianvs/code/experiments/storybook-webpack5-mjs/.storybook'
ERR! Did you mean 'index.js'?
ERR! BREAKING CHANGE: The request '/Users/ianvs/code/experiments/storybook-webpack5-mjs/node_modules/@storybook/client-api' failed to resolve only because it was resolved as fully specified
ERR! (probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
ERR! The extension in the request is mandatory for it to be fully specified.
ERR! Add the extension to the request.
ERR! ModuleNotFoundError: Module not found: Error: Can't resolve '/Users/ianvs/code/experiments/storybook-webpack5-mjs/node_modules/@storybook/client-api' in '/Users/ianvs/code/experiments/storybook-webpack5-mjs/.storybook'
ERR! Did you mean 'index.js'?
```

**Comment by Merri** [comment]
I'm having a different kind of error message with out component library but I'll update on that once I'm at work again tomorrow. Regardless the gist of the error I'm having seems to be that for whatever reason Webpack 5 possibly does not get all transpilation config and errors when encountering TSX, JSX, or maybe TypeScript syntax.

**Comment by Merri** [comment]
Okay, the error I'm getting seems to be related into TypeScript not getting processed:

```
ERR! => Failed to build the preview
ERR! Module parse failed: Unexpected token (29:1)
ERR! File was processed with these loaders:
ERR!  * ./node_modules/babel-loader/lib/index.js
ERR!  * ./node_modules/@storybook/source-loader/dist/cjs/index.js
ERR! You may need an additional loader to handle the result of these loaders.
ERR! |   color,
ERR! |   ...props
ERR! > }: React.ComponentProps<typeof Button>) => (
ERR! |   <Button {...props} {...color} {...as}>
ERR! |     {children}
```

I'll continue debugging and experimenting with `babelModeV7: true`. There is also a production specific Babel config for a non-Storybook build so maybe that causes issues.

**Comment by Merri** [comment]
Alright, this was the config that made the production build fail for me. A notable thing is that this config was NOT intended for Storybook:

```ts
  env: {
    production: {
      comments: false,
      minified: true,
      sourceMaps: true,
      presets: [
        [
          '@babel/preset-env',
          {
            bugfixes: true,
            browserslistEnv: process.env.BABEL_ENV || process.env.NODE_ENV,
            modules: false,
            shippedProposals: true,
          },
        ],
        '@babel/preset-react',
        '@babel/preset-typescript',
      ],
      ignore: [
        '**/*.d.ts',
        '**/*.docs.ts',
        '**/*.docs.tsx',
        '**/*.spec.ts',
        '**/*.spec.tsx',
        '**/*.stories.tsx',
        '**/*.stories.style.ts',
        '**/GlobalFonts.ts',
      ],
    },
  },
};
```

I resolved the issue by changing `BABEL_ENV` to something else than `production` when building the non-Storybook production build. So I think I now have a fully working main.cjs + Webpack 5 + type: module build :)

The upcoming changes to v7 with Babel sound like a good idea as partially this issue was due to it not being obvious (from code alone) that Storybook makes use of Babel, too. If there existed a visible Babel configuration for Storybook I might've never ended up having the problems I had.

While this is unrelated issue to the sample project above I hope maybe someone else happens to have a similar setup where they're using Babel for non-Storybook purposes.

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
