### ISSUE TITLE
Cannot step through debugger with skip button (interaction addon)

### ISSUE THREAD

**Issue by nebbles** [storybookjs/storybook#17167]
**Bug**
When using the experimental step debugger toolbar UI, I skip back to start and then step through using the `>` step button. However, the button becomes disabled before the last step. 

You can see the issues encountered with clicking through the debugger in the video:

https://user-images.githubusercontent.com/12599555/148567154-a93b4c46-fb5b-4269-9ad1-e0bf3b738fb3.mp4

**To Reproduce**

**System**
```
Environment Info:

  System:
    OS: macOS 10.15.7
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
  Binaries:
    Node: 14.17.0 - ~/.nvm/versions/node/v14.17.0/bin/node
    Yarn: 1.22.17 - ~//code/app/node_modules/.bin/yarn
    npm: 6.14.13 - ~/.nvm/versions/node/v14.17.0/bin/npm
  Browsers:
    Chrome: 96.0.4664.110
    Safari: 15.1
  npmPackages:
    @storybook/addon-actions: ^6.4.9 => 6.4.9 
    @storybook/addon-essentials: ^6.4.9 => 6.4.9 
    @storybook/addon-interactions: ^6.4.9 => 6.4.9 
    @storybook/addon-links: ^6.4.9 => 6.4.9 
    @storybook/builder-webpack5: ^6.4.9 => 6.4.9 
    @storybook/manager-webpack5: ^6.4.9 => 6.4.9 
    @storybook/node-logger: ^6.4.9 => 6.4.9 
    @storybook/preset-create-react-app: ^4.0.0 => 4.0.0 
    @storybook/react: ^6.4.9 => 6.4.9 
    @storybook/testing-library: ^0.0.7 => 0.0.7 
```

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
