### ISSUE TITLE
Storybook overrides component calculated values

### ISSUE THREAD

**Issue by jacobdab** [storybookjs/storybook#17218]
**Describe the bug**
Today I updated storybook to newest version to support angular 12. Now component values that aren't inputs are overriden by storybook. This causes strange behaviours. For example component calculates pages that will be available, but storybook overrides it and set it to 1.

**System**
Environment Info:

  System:
    OS: Windows 10 10.0.19043
    CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
  Binaries:
    Node: 14.17.6 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.13 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.15 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (97.0.1072.55)
  npmPackages:
    @storybook/addon-actions: ^6.4.12 => 6.4.12
    @storybook/addon-docs: ^6.4.12 => 6.4.12
    @storybook/addon-essentials: ^6.4.12 => 6.4.12
    @storybook/addon-links: ^6.4.12 => 6.4.12
    @storybook/addon-storysource: ^6.4.12 => 6.4.12
    @storybook/angular: ^6.4.12 => 6.4.12
    @storybook/builder-webpack5: ^6.4.12 => 6.4.12
    @storybook/manager-webpack5: ^6.4.12 => 6.4.12
    @storybook/theming: ^6.4.12 => 6.4.12

**Additional context**

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
