### ISSUE TITLE
Including global styles in preview.js is ignored in 6.5.0-alpha.16

### ISSUE THREAD

**Issue by artaommahe** [storybookjs/storybook#17234]
**Describe the bug**

Including global styles in preview.js is ignored in 6.5.0-alpha.16.

```js
// preview.(j|t)s
import '!style-loader!css-loader!sass-loader!./global.scss';
```
```scss
body {
  background-color: #ffe4c4;
}
```

Can't check with 6.4.x cause it's broken with angular (see https://github.com/storybookjs/storybook/issues/17039#issuecomment-1012217050).

**To Reproduce**

- `git clone https://github.com/artaommahe/storybook-issues`
- `yarn install`
- `yarn storybook`
- see no applied body styles for stories

**System**

```
Environment Info:

  System:
    OS: macOS 12.1
    CPU: (10) arm64 Apple M1 Max
  Binaries:
    Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
    Yarn: 1.22.17 - ~/.nvm/versions/node/v16.13.0/bin/yarn
    npm: 8.1.0 - ~/.nvm/versions/node/v16.13.0/bin/npm
  Browsers:
    Chrome: 97.0.4692.71
    Safari: 15.2
  npmPackages:
    @storybook/addon-actions: 6.5.0-alpha.16 => 6.5.0-alpha.16 
    @storybook/addon-essentials: 6.5.0-alpha.16 => 6.5.0-alpha.16 
    @storybook/addon-links: 6.5.0-alpha.16 => 6.5.0-alpha.16 
    @storybook/angular: 6.5.0-alpha.16 => 6.5.0-alpha.16 
    @storybook/builder-webpack5: 6.5.0-alpha.16 => 6.5.0-alpha.16 
    @storybook/manager-webpack5: 6.5.0-alpha.16 => 6.5.0-alpha.16 
```

**Additional context**

Worked fine with `6.4.0-alpha.28` (it's used in our real apps with such global styles imports).

**Comment by ThibaudAV** [comment]
This topic has already appeared here is the summary :
The functionality is no longer supported by angular so either there is a feature made on the storybook side to take this case into account. Or use the new storybook builder provided for that.
It is perhaps feasible with a webpack config that does not conflict with that of angular

https://github.com/angular/angular-cli/issues/21893
https://github.com/angular/angular-cli/issues/21747
some others ...


IMHO : I don't know how to do it. And I also think it's not a good solution for sb angular users.

In angular we configure the global style scss via the angular-cli builder and angular.json otherwise you have to do your own webpack configuration. Storybook allows the same thing

**Comment by shilman** [comment]
closing as dupe to #16256
