### ISSUE TITLE
Play function does not run on re-render

### ISSUE THREAD

**Issue by Bilge** [storybookjs/storybook#17264]
**Describe the bug**
Although the play function runs on initial load, it does not run on subsequent renders when interacting with the interactive controls that trigger re-rendering.

**To Reproduce**
```ts
import {StoryObj} from '@storybook/html';

export const Test: StoryObj = {
    storyName: 'Test',
    render: (args) => args.foo,
    args: {
        foo: 'Foo',
    },
    play: context => {
        console.log(context.args);
    },
};
```

Observe that the console is only written to once; changing the value of `foo` re-renders the control but does not retrigger the play function.

**System**
```
  System:
    OS: Windows 10 10.0.19042
    CPU: (8) x64 Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz
  Binaries:
    Node: 14.15.3 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.9 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 97.0.4692.71
    Edge: Spartan (44.19041.1266.0), Chromium (97.0.1072.62)
  npmPackages:
    @storybook/addon-actions: ^6.4.13 => 6.4.13
    @storybook/addon-essentials: ^6.4.13 => 6.4.13
    @storybook/addon-links: ^6.4.13 => 6.4.13
    @storybook/html: ^6.4.13 => 6.4.13
```

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
