### ISSUE TITLE
Babel errors not rendered in browser

### ISSUE THREAD

**Issue by mbezgin** [storybookjs/storybook#17272]
**Describe the bug**

When component JSX has a syntax error, storybook does not display the error in the UI and can't find the story. Please check screenshot below. CRA project example

![image](https://user-images.githubusercontent.com/13313136/149947228-eb4586c7-715b-4634-94d1-fa147bb0646a.png)

![image](https://user-images.githubusercontent.com/13313136/149947375-c55c3cff-f9b2-46a4-932e-459cee6e2fa9.png)

**System**
Environment Info:
  System:
    OS: macOS 11.6
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
  Binaries:
    Node: 14.18.0 - ~/.nvm/versions/node/v14.18.0/bin/node
    Yarn: 1.22.17 - ~/.nvm/versions/node/v14.18.0/bin/yarn
    npm: 6.14.15 - ~/.nvm/versions/node/v14.18.0/bin/npm
  Browsers:
    Chrome: 97.0.4692.71
    Safari: 14.1.2

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
