### ISSUE TITLE
Storybook Composition not showing anything

### ISSUE THREAD

**Issue by ma-jahn** [storybookjs/storybook#17299]
Hi

in our monorepo we want to have a storybook per package and a "global" storybook for composition. In theory this should give us all the flexibility we need.
But it turns out, this is not so easy. Each single Storybook (2 x Nuxt, 1 x Vue) is working by itself. But when trying to show these storybook in our "global" storybook we're stuck in an infinite loading state. No Errors are being thrown.

I've managed to reproduce it within a minimal setup.

Create multiple Storybooks using `npx sb@next init --type html`.
Use one of them for composition by adding `refs` to `main.js`.

```
refs: {
  test1: {
    title: 'Storybook 1',
    url: 'http://localhost/storybook-1
  },
},
```

Run `yarn build-storybook && npx sb extract` for each storybook

The global storybook is running on 
`http://localhost/storybook`

Another Storybook is running on
`http://localhost/storybook-1`

Storybook-1 can be accessed directly and works as expected. Accessing /storybook is just showing a loading state.

Is my configuration wrong? Am i missing somethnig?

Thank you!

**Comment by ma-jahn** [comment]
It's working when switch from absolute to relativ urls for `refs`.

```
refs: {
  test1: {
    title: 'Storybook 1',
    url: '/storybook-1
  },
},
```

Is this intended?

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
