### ISSUE TITLE
External linking inside an mdx story results in incorrect URL

### ISSUE THREAD

**Issue by openscript** [storybookjs/storybook#17308]
**Describe the bug**
Inside an mdx story `Start.stories.mdx` the README.md file is rendered:

```
import { Meta, Description } from '@storybook/addon-docs';
import Readme from '../README.md';

<Meta title="Start" parameters={{ previewTabs: { canvas: { hidden: true } } }} />

<Readme />
```

The README.md file contains external links like:

```
## Resources
...
  - [**Storybook**](https://storybook.js.org/): Storybook is an open source tool for building UI components and pages in isolation. It streamlines UI development, testing, and documentation.
...
```

When one of this links is clicked inside the storybooks iFrame, the URLis append to the current URL:

![image](https://user-images.githubusercontent.com/1105080/150483388-dc332cd1-bcab-439d-b2c6-cabd3754fe7c.png)

**To Reproduce**
Repository: https://github.com/openscript-ch/react-collapsible-timeline
Deployment: https://openscript-ch.github.io/react-collapsible-timeline

**System**
Unfortunately the script to collect the data fails:
`sh: 1: sb: Permission denied` (with root permissions)

```
    "@storybook/addon-actions": "^6.4.13",
    "@storybook/addon-docs": "^6.4.13",
    "@storybook/addon-essentials": "^6.4.13",
    "@storybook/addon-links": "^6.4.13",
    "@storybook/addon-storysource": "^6.4.13",
    "@storybook/react": "^6.4.13",
```

Inside a devcontainer:

```
Distributor ID: Debian
Description:    Debian GNU/Linux 10 (buster)
Release:        10
Codename:       buster
```

**Additional context**
The setup is special, because I use vite, but this shouldn't affect this issue. When I did research I've found #9302, but I'm on a much newer version.

**Comment by GuilleDF** [comment]
I'm running into this issue as well, it seems to be related to how storybook changes link components to handle internal links. 
https://github.com/storybookjs/storybook/blob/4750c6bfbcc340330c905071574a511153231d7c/addons/docs/src/blocks/mdx.tsx#L94
As a workaround, changing the markdown-style link to an `<a>` element with `target="_blank"` solves this.

However, it's kind of weird to have to change all external links to html-style instead of markdown-style. Maybe as a feature request, I would love storybook to figure out on its own if a link is internal or external and do that automatically 😇

**Comment by shilman** [comment]
Great Caesar's ghost!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.5.0-alpha.57 containing PR #17819 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.

**Comment by openscript** [comment]
@MaiLeeTR That seems to be true, that it only got fixed for `https` urls.
