### ISSUE TITLE
Arrow up/down doesn't work in addon panels

### ISSUE THREAD

**Issue by nihgwu** [storybookjs/storybook#17442]
**Describe the bug**
Can't move cursor in textarea if it's in addon panels

I suspect it's caused by the shortcuts for story navigation, as if we are focusing on the panels, arrow up/down with change the current story

**To Reproduce**
https://5ccbc373887ca40020446347-vphrpuyumo.chromatic.com/?path=/story/button--basic, input some multiline content in the children control, then try to move cursor using keyboard, only arrow left/right works but not for arrow up/down

**System**
SB V6

**Additional context**

**Comment by alanorozco** [comment]
This is how I fixed this on my own addon. `onKeyDownCapture` on JSX does not work likely due to synthetic events, so I set it on the DOM directly.

```js
  useEffect(() => {
    textareaRef.current.addEventListener(
      "keydown",
      (e) => {
        e.stopPropagation();
        e.stopImmediatePropagation();
      },
      /* capture */ true
    );
  }, []);
```

(The problem is unfortunately still present on the official Controls addon.)

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
