### ISSUE TITLE
Storybook Error: ENOENT: no such file or directory, open 'vue/dist/vue.esm-bundler.js'

### ISSUE THREAD

**Issue by welschoff** [storybookjs/storybook#17443]
Hi, I'm working on a react-app and when I try to start stroybook I always get this error (see title)...

I've already tried to delete node_modules and package-lock.js, but still not working :/

Anybody have an idea how to solve this issue?

**Comment by alessandro-aglietti** [comment]
hi @welschoff take a look here seems the same issue https://github.com/storybookjs/storybook/issues/16180#issuecomment-1122718772

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
