### ISSUE TITLE
Switching to an unexpected component

### ISSUE THREAD

**Issue by Paqura** [storybookjs/storybook#17449]
**Describe the bug**
After clicking on any control in a component (e.g. Button), another component opens.
See in "To Reproduce"

**To Reproduce**
https://paqura.github.io/bug-storybook

Switch to "Button", click to any control

**System**

```
Environment Info:

  System:
    OS: Linux 5.13 Ubuntu 20.04.3 LTS (Focal Fossa)
    CPU: (12) x64 AMD Ryzen 5 3600X 6-Core Processor
  Binaries:
    Node: 16.13.2 - ~/.nvm/versions/node/v16.13.2/bin/node
    Yarn: 1.22.17 - ~/.nvm/versions/node/v16.13.2/bin/yarn
    npm: 8.1.2 - ~/.nvm/versions/node/v16.13.2/bin/npm
  Browsers:
    Chrome: 98.0.4758.80
    Firefox: 96.0
  npmPackages:
    @storybook/addon-actions: ^6.4.18 => 6.4.18 
    @storybook/addon-essentials: ^6.4.18 => 6.4.18 
    @storybook/addon-links: ^6.4.18 => 6.4.18 
    @storybook/builder-webpack5: ^6.4.18 => 6.4.18 
    @storybook/manager-webpack5: ^6.4.18 => 6.4.18 
    @storybook/node-logger: ^6.4.18 => 6.4.18 
    @storybook/preset-create-react-app: ^3.2.0 => 3.2.0 
    @storybook/react: ^6.4.18 => 6.4.18 
```

**Additional context**
features `storyStoreV7` enabled

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
