### ISSUE TITLE
Anchor/Hash links do not work as expected

### ISSUE THREAD

**Issue by VilleMiekkoja** [storybookjs/storybook#17472]
**Describe the bug**
Hash link opens a new iframe.html window, instead of scrolling the user to the content. This happens in the latest version (6.4.18) of storybook/react.

**To Reproduce**

Just put this into your component and try press it. You will notice a new window will appear instead of expected behaviour
`<a href="#field1">Please enter your first name</a>`

**System**
Environment Info:

  System:
    OS: macOS 11.6
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
  Binaries:
    Node: 12.18.3 - ~/.nvm/versions/node/v12.18.3/bin/node
    Yarn: 1.16.0 - /usr/local/bin/yarn
    npm: 6.14.6 - ~/.nvm/versions/node/v12.18.3/bin/npm
  Browsers:
    Chrome: 98.0.4758.80
    Firefox: 96.0.3
    Safari: 15.0
  npmPackages:
    @storybook/addon-a11y: 6.4.18 => 6.4.18
    @storybook/addon-backgrounds: 6.4.18 => 6.4.18
    @storybook/addon-viewport: 6.4.18 => 6.4.18

**Additional context**
Storybook/react version: 6.4.18

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
