### ISSUE TITLE
Story book build fails with Angular and Angular Material 13.x.x versions

### ISSUE THREAD

**Issue by SaiCharan-CN** [storybookjs/storybook#17503]
I recently migrated Angular and Material from 11.x.x to 13.2.2 version and while I am trying to build the storybook and then follwing error occurs.

<img width="1769" alt="image" src="https://user-images.githubusercontent.com/79690667/153886727-afbb3b20-becf-4f43-afc5-7653fb0bcf69.png">

**System**

Environment Info:

  System:
    OS: macOS 12.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Binaries:
    Node: 14.15.5 - ~/.nvm/versions/node/v14.15.5/bin/node
    Yarn: 1.21.1 - /usr/local/bin/yarn
    npm: 6.14.11 - ~/.nvm/versions/node/v14.15.5/bin/npm
  Browsers:
    Chrome: 98.0.4758.80
    Edge: 98.0.1108.51
    Firefox: 96.0.3
    Safari: 15.2
  npmPackages:
    @storybook/addon-actions: ^6.4.18 => 6.4.18 
    @storybook/addon-essentials: ^6.4.18 => 6.4.18 
    @storybook/addon-links: ^6.4.18 => 6.4.18 
    @storybook/addon-postcss: ^2.0.0 => 2.0.0 
    @storybook/angular: ^6.4.18 => 6.4.18 
    @storybook/builder-webpack5: ^6.4.18 => 6.4.18 
    @storybook/manager-webpack5: ^6.4.18 => 6.4.18 
    @storybook/react: ^6.4.19 => 6.4.19 

**Additional context**
Upgraded from Angular 11 to Angular 13 with material dependencies.

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
