### ISSUE TITLE
ArgTypes data type returning `unknown` despite being defined as prop-types and argTypes

### ISSUE THREAD

**Issue by alexastef** [storybookjs/storybook#17522]
**Describe the bug**
ArgTypes data type returning `unknown` for all props, both from the component-defined prop-types and from story-defined argTypes

**Story**
```
export default {
  title: 'Icon Button Menu',
  component: IconButtonMenu,
  argTypes: {
    menuOptions: {
      control: null,
      description: 'Array of objects that will be mapped into `MenuItem` elements'
      type: { summary: 'array' }
    },
    iconElement: {
      control: null,
      description: 'Entire `Icon` element to be used as the menu trigger'
      type: { summary: 'element' }
    },
    variant: {
      description: 'Icon button variant style, defaults to `textGrey` if not specified',
      control: 'select',
      options: ['primary', 'secondary', 'text']
      type: {
        summary: 'string'
      }
    },
    ariaLabel: {
      description: 'Accessibility label for the icon menu'
      type: { summary: 'string' }
    },
    menuListWidth: {
      description: 'Width of the menu list. Defaults to 120px or auto, whichever is greater.'
    },
    width: {
      description: 'Width for the button'
    },
    size: {
      description: 'Button size. defaults to `md`',
      control: 'select',
      options: ['xs', 'sm', 'md', 'lg']
    }
  }
};
```
<img width="1027" alt="Screen Shot 2022-02-16 at 9 26 03 AM" src="https://user-images.githubusercontent.com/62451633/154321447-35327f9b-c7a4-4c27-80c4-96d8b1e96bc4.png">

The props are also defined in the component prop-types.

**Additional context**
All other stories are formatted exactly the same and work fine. It is just this one story where the argTypes don't work. I am not using addon-info, just addon-docs. Control, description, options, etc. are also working fine.

**Comment by Tim-arts** [comment]
Hello @alexastef, as shown [here](https://storybook.js.org/docs/react/api/argtypes), an argType is structured like this:

`
label: {
    name: 'label',
    type: { name: 'string', required: false },
    defaultValue: 'Hello',
    description: 'demo description',
    table: {
      type: { summary: 'string' },
      defaultValue: { summary: 'Hello' },
    },
    control: {
      type: 'text'
    }
  }
`

So for example your first argument should be:

```
menuOptions: {
  control: null,
  description: 'Array of objects that will be mapped into `MenuItem` elements'
  table: {
    type: {
      summary: 'array' 
    }
  }
}
```

And I'm going to quote @kylegach for something he said recently about argtypes:

![image](https://user-images.githubusercontent.com/10064887/154398484-ff10bd48-c86a-4845-a2f3-f3ce69b925c2.png)
As well as some [documentation ](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#no-longer-inferring-default-values-of-args) about it that could help you

Also, you may prefer to use 'radio' instead of the 'select' control type since it might be easier for the user to switch between values

**Comment by alexastef** [comment]
I figured that out after I made this issue :) Thanks, @Tim-arts !

**Comment by kylegach** [comment]
Given that you figured this out, I'm going to close this issue.

Thanks for helping out, @Tim-arts!
