### ISSUE TITLE
Uncaught (in promise) Error: No `docs.container` set

### ISSUE THREAD

**Issue by belforto** [storybookjs/storybook#17527]
Why I get this error?
**//storybook/main.tsx**

stories: ["../src/components/**/*.stories.@(tsx|mdx)", "../src/styles/*.stories.@(tsx|mdx)",],

  addons: [
    "@storybook/addon-essentials",
    "@storybook/addon-actions/register",
    "@storybook/addon-controls",
    "@storybook/addon-viewport",
    {
      name: '@storybook/addon-docs',
      options: {
        configureJSX: true,
        babelOptions: {},
        sourceLoaderOptions: null,
        transcludeMarkdown: true,
      },
    },
  ],

and this is my mdx file
**//BlogCard.stories.mdx**

import { Meta, Story } from '@storybook/addon-docs/blocks';
import * as stories from './BlogCard.stories.tsx';
import  BlogCard  from "./index";

<Meta title="Components/Blog Card" component={BlogCard} />

<Story story={stories.BlogCardPlayground} />

...some random markdown here

**Comment by blowsie** [comment]
I get a similar issue, reproduction is available here
https://github.com/blowsie/vue3-vitesse-storybook-pnpm/tree/master/packages/ui

![image](https://user-images.githubusercontent.com/308572/160837426-29368400-13ce-4aa8-a7ff-eb016103810c.png)

**Comment by charleshimmer** [comment]
I'm getting this error after upgrading from storybook 6.4 to 6.5 using react. Every figure out what was going on?

**Comment by shilman** [comment]
@charleshimmer Do you a have a reproduction repo you can share? If not, can you create one? See [how to create a repro](https://storybook.js.org/docs/react/contribute/how-to-reproduce). Thank you! 🙏

**Comment by codesman** [comment]
I got this error today when I had accidentally installed `@storybook/addon-docs": "6.5.5"`, when the rest of the storybook deps were at `6.4.22`.  The Docs tab was missing as well and the markdown in my `.mdx` was not rendered. This is in an NX `13.4.6` repo.

**Comment by charleshimmer** [comment]
I found my issue was the path for the `addon-docs` needed to be changed from `'@storybook/addon-docs/preset'` to `   '@storybook/addon-docs'` in `.storybook/main.js`.

**Comment by charleshimmer** [comment]
Hot reloading does seem to not be working though now :(.

**Comment by konsalex** [comment]
Hey folks, any update regarding this issue?

**Comment by dagjomar** [comment]
Also had the same problem with version 6.5.9
Downgraded to the following set of versions and everything works fine again:

    "@storybook/addon-actions": "~6.4.22",
    "@storybook/addon-essentials": "~6.4.22",
    "@storybook/addon-interactions": "~6.4.22",
    "@storybook/addon-links": "~6.4.22",
    "@storybook/builder-webpack5": "~6.4.22",
    "@storybook/manager-webpack5": "~6.4.22",
    "@storybook/react": "~6.4.22",
    "@storybook/testing-library": "^0.0.11",

Would love for someone to figure out what the problem is

**Comment by kherock** [comment]
@shilman I don't have time to create a full repro, but I believe I was able track this regression to #17755.

I have two storybooks with this problem, and it seems like the only ingredient for this to occur is to have a custom `.storybook/preview.js`. The error is thrown due to some refactoring of `getContainer()` and `getPage()` parameters in the default addon-docs preset. In 6.4, they were configured in [config.ts](https://github.com/storybookjs/storybook/blob/v6.4.22/addons/docs/src/frameworks/common/config.ts), loaded in the common-preset module:

https://github.com/storybookjs/storybook/blob/8dd4fa6ef42f803ec276be18fb78644a827d5b74/addons/docs/preset.js#L10-L16

6.5 seems to have completely rewritten the preset entrypoint and I'm still investigating what needs to be done in order to fix this. In the meantime, I can get docs working again by including this in my `.storybook/preview.js` file:


```js
export const parameters = {
  docs: {
    ...require('@storybook/addon-docs/preview').parameters.docs,
    // other config
  }
}

**Comment by bartaz** [comment]
> I found my issue was the path for the `addon-docs` needed to be changed from `'@storybook/addon-docs/preset'` to ` '@storybook/addon-docs'` in `.storybook/main.js`.

Thanks @charleshimmer this has been an issue in our case as well.

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
