### ISSUE TITLE
When using MDX with Web Components, the Canvas always shows "No code available"

### ISSUE THREAD

**Issue by vmadman** [storybookjs/storybook#17567]
**Describe the bug**
When using MDX with Web Components, the Canvas always shows "No code available" when running StoryBook in dev/watch mode.

**System**
```
  System:
    OS: Linux 5.11 Ubuntu 21.04 (Hirsute Hippo)
    CPU: (6) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
  Binaries:
    Node: 15.11.0 - ~/.nvm/versions/node/v15.11.0/bin/node
    npm: 7.6.0 - ~/.nvm/versions/node/v15.11.0/bin/npm
  Browsers:
    Firefox: 96.0
  npmPackages:
    @storybook/addon-actions: ^6.4.19 => 6.4.19 
    @storybook/addon-docs: 6.4.19 => 6.4.19 
    @storybook/addon-essentials: ^6.4.19 => 6.4.19 
    @storybook/addon-links: ^6.4.19 => 6.4.19 
    @storybook/web-components: ^6.4.19 => 6.4.19 
```

**Repro**
**Repo:** https://github.com/vmadman/storybook-vite-tests
**Chromatic:** https://master--62172139aa1486003a0af480.chromatic.com/

**Additional context**
The bug does not manifest in Chromatic or in the StoryBook static build. It only affects dev/watch mode.

![image](https://user-images.githubusercontent.com/1026490/155471216-095281f1-db61-4e5e-bb74-449a63709caf.png)

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
