### ISSUE TITLE
jsx lint on Vue3.0 template? 

### ISSUE THREAD

**Issue by mxm-web-develop** [storybookjs/storybook#17576]
**Describe the bug**
  I started the project with vite + vue3 + typescript+tailwind , then npx sb init to install storybook to this project.  every things seems work fine, However the storybook changed how the syntax in vue3, its ask use className in vue template? this confuse me a lot 
![Screen Shot 2022-02-25 at 5 55 01 PM](https://user-images.githubusercontent.com/84134484/155694646-762e0019-622a-4f98-9d70-ae4b3d54da36.png)

**Comment by MrAnyx** [comment]
Hello ! I had the same problem with approximately the same configuration. I use `Storybook 6.4` with `Vite 2.8.6` and `Vue 3.2.31`. I also use Visual Studio Code. 

After installing Storybook with the following command
```bash
npx sb init --builder storybook-builder-vite --type vue3
```

I found out that my editor is linting the `class` attribut within my vue components as if there were en error.
![image](https://user-images.githubusercontent.com/44176707/156541175-4853f1a1-5cee-493e-804f-2bf72f0a14ba.png)

When I hover over the error, it says that it's a JSX error, not a vue error which is a bit confising
```
(JSX attribute) class: {
    button: boolean;
    outline: boolean;
}
Type '{ class: { button: boolean; outline: boolean; }; }' is not assignable to type 'DetailedHTMLProps<ButtonHTMLAttributes<HTMLButtonElement>, HTMLButtonElement>'.
  Property 'class' does not exist on type 'DetailedHTMLProps<ButtonHTMLAttributes<HTMLButtonElement>, HTMLButtonElement>'. Did you mean 'className'?ts(2322)
```

After further research, I discovered that this warning is caused by the following packages:
- @storybook/vue3
- @storybook/addon-links
- @storybook/addon-essentials
- @storybook/addon-actions

When I remove all the other packages, the error is still there, but when I remove these specific packages, the error disappears.

**Comment by mxm-web-develop** [comment]
any solutions?

**Comment by mxm-web-develop** [comment]
> Hello ! I had the same problem with approximately the same configuration. I use `Storybook 6.4` with `Vite 2.8.6` and `Vue 3.2.31`. I also use Visual Studio Code.
> 
> After installing Storybook with the following command
> 
> ```shell
> npx sb init --builder storybook-builder-vite --type vue3
> ```
> 
> I found out that my editor is linting the `class` attribut within my vue components as if there were en error. ![image](https://user-images.githubusercontent.com/44176707/156541175-4853f1a1-5cee-493e-804f-2bf72f0a14ba.png)
> 
> When I hover over the error, it says that it's a JSX error, not a vue error which is a bit confising
> 
> ```
> (JSX attribute) class: {
>     button: boolean;
>     outline: boolean;
> }
> Type '{ class: { button: boolean; outline: boolean; }; }' is not assignable to type 'DetailedHTMLProps<ButtonHTMLAttributes<HTMLButtonElement>, HTMLButtonElement>'.
>   Property 'class' does not exist on type 'DetailedHTMLProps<ButtonHTMLAttributes<HTMLButtonElement>, HTMLButtonElement>'. Did you mean 'className'?ts(2322)
> ```
> 
> After further research, I discovered that this warning is caused by the following packages:
> 
> * @storybook/vue3
> * @storybook/addon-links
> * @storybook/addon-essentials
> * @storybook/addon-actions
> 
> When I remove all the other packages, the error is still there, but when I remove these specific packages, the error disappears.

Create stub/types__react/index.d.ts
// stub/types__react/index.d.ts
export { }
Setting react module alias in tsconfig
// tsconfig.json
{
  "compilerOptions": {
    // ...
    "types": [
      // whitelist to include modules type from node_modules/@types
    ],
    "paths": {
      "react": ["./stub/types__react"]
    }
  },
}

fixed, check detail here 👍 https://github.com/johnsoncodehk/volar/discussions/592

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).

**Comment by dstuessy** [comment]
Mentioned [here](https://github.com/storybookjs/storybook/discussions/17091) I'm also having the same issue as reported above with version 7.2.1. Having used 6.5 for 8 months, I upgraded using `npx storybook@latest upgrade`. Like @mxm-web-develop, I was able to suppress the JSX type errors by removing all storybook addons: "storybook/addon-links", "@storybook/addon-essentials", and "@storybook/addon-actions"
