### ISSUE TITLE
Angular inline  styles using scss maps, does not work on story book.

### ISSUE THREAD

**Issue by SunilManthenaG01** [storybookjs/storybook#17632]
**Describe the bug**
In Angular when using inline styles with in the same component file with scss support. Story book does not compile them to css

**To Reproduce**
Here is repo where you can reproduce the issue. I just have one app component here we have inline style template inside the component. When you do ng serve you can see the scss maps works fine but when you run story book that styles are not applied to the app component. 

https://github.com/SunilManthenaG01/storybook-inline-scss-angular-

**System**
Environment Info:
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (98.0.1108.62)
  npmPackages:
    @storybook/addon-actions: ^6.4.19 => 6.4.19
    @storybook/addon-essentials: ^6.4.19 => 6.4.19
    @storybook/addon-interactions: ^6.4.19 => 6.4.19
    @storybook/addon-links: ^6.4.19 => 6.4.19
    @storybook/angular: ^6.4.19 => 6.4.19
    @storybook/builder-webpack5: ^6.4.19 => 6.4.19
    @storybook/manager-webpack5: ^6.4.19 => 6.4.19
    @storybook/testing-library: ^0.0.9 => 0.0.9
  npmGlobalPackages:
    @storybook/cli: 6.4.19

**Additional context**

**Comment by ThibaudAV** [comment]
I try to reproduce but I did not succeed

for me this is not good even in an Angular application (i've `SassError: Undefined variable.`):
```
  styles: [
    `
    @use 'sass:map';
      h1{
        color: red;
        font-weight: map-get($weights , 'light' );
      }
    `
  ],
```
https://github.com/SunilManthenaG01/storybook-inline-scss-angular-/blob/main/src/app/app.component.ts#L6

because $weights not exist. 
when you use `app.component.scss` is well added 

or I am making a mistake somewhere 🤔

**Comment by SunilManthenaG01** [comment]
@ThibaudAV my bad on this one for testing purpose i moved the variable to the global styles i think that might be causing the issue for you. Try it now.

**Comment by ThibaudAV** [comment]
Ok I have seen other error on your example project for this to work.
You seem to have wanted to configure storybook with the angular builder. but it is not correctly configured
<img width="1149" alt="image" src="https://user-images.githubusercontent.com/4974420/157550626-56fe45b6-4077-4ecd-a66f-e292f5aa713f.png">
> `inlineStyleLanguage` is not a known option. And the browserTarget should exist as for extract-i18n or serve. 

And you do not use the builder because is not configured in package.json > scripts 
<img width="1136" alt="image" src="https://user-images.githubusercontent.com/4974420/157551072-061cac5c-211c-469f-bb54-a44aedbfc875.png">

And so if you use angular 12.0 upper and the builder it will work

**Comment by SunilManthenaG01** [comment]
I see that is working with the angular builder. Thank you for taking a look at this one.
Maybe not related to this issue but if you can help I have one question.

I see when we run " ng run jasmine-test:storybook ", the first thing it runs is the compodoc with the below command.

compodoc -p .storybook\tsconfig.json -d C:\Users\JISAQBX\play\own\jasmine-test -e json

Is there a way we can pass in additional flags to how we want to run compodoc like the command below 
compodoc -p .storybook\tsconfig.json **--disableRoutesGraph** -d C:\Users\JISAQBX\play\own\jasmine-test -e json

The reason I ask is I am having an issue when we run compodoc with routes. Below is the issue, so it would be nice to utilize the compodoc's options to run before the story book.

https://github.com/compodoc/compodoc/issues/1208

**Comment by ThibaudAV** [comment]
You can see all storybook angular builder options [here](https://github.com/storybookjs/storybook/blob/next/app/angular/src/builders/start-storybook/schema.json#L74).
Maybe you could try to add `disableRoutesGraph` with option `compodocArgs` ?

**Comment by SunilManthenaG01** [comment]
@ThibaudAV Thank you for the above that works. Here is my angular json for storybook.

` "storybook": {
          "builder": "@storybook/angular:start-storybook",
          "options": {
            "browserTarget": "app-operationsexecution-load-workflow-ui:build:local",
            "port": 3000,
            "compodocArgs": ["-e","json",  "--disableRoutesGraph"]

          }
        },`
