### ISSUE TITLE
[@storybook/angular] hoists webpack 4 dependency breaking Angular apps using webpack 5

### ISSUE THREAD

**Issue by Coly010** [storybookjs/storybook#17672]
**Describe the bug**
The `@storybook/angular` package depends on `webpack@4`.  
Angular now depends on `webpack@5`.

Installing `@storybook/angular` with yarn after creating an Angular app forces the `webpack@4` dependency of Storybook Angular to be hoisted, causing erroneous behaviour.

https://github.com/storybookjs/storybook/blob/next/app/angular/package.json#L80

**To Reproduce**
 - Create a new Angular app (or clone an existing one (https://github.com/Coly010/nx-mfe-deploy-netlify))
 - Add storybook/angular (or run `yarn nx g @nrwl/angular:storybook-configuration --name=login`)
 - Run `yarn why webpack` or `npm ls webpack`
 
**Additional context**
Storybook Angular should likely now depend on webpack 5, in line with Angular 13+ apps. Backwards compatibility can be maintained by having Angular <13 users use an older version of the package.

**Comment by Coly010** [comment]
An additional issue reporting this behaviour on the Nx Repo:
https://github.com/nrwl/nx/issues/9154

**Comment by jornare** [comment]
Related: https://github.com/storybookjs/storybook/issues/17436

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
