### ISSUE TITLE
React components remount on docs page

### ISSUE THREAD

**Issue by penx** [storybookjs/storybook#17693]
**Describe the bug**

When changing an argument on a React component on the docs page, the component remounts.

**To Reproduce**

https://github.com/penx/repro-remount

- Open button story
- Change 'test' arg up and down
- Notice in console, 'new' is logged every time the component remounts in Docs tab, but this doesn't happen in 'Canvas' tab

**System**

Environment Info:

  System:
    OS: macOS 11.6
  Binaries:
    Node: 16.13.2 - ~/.nvm/versions/node/v16.13.2/bin/node
    Yarn: 3.2.0 - ~/.nvm/versions/node/v16.13.2/bin/yarn
    npm: 8.1.2 - ~/.nvm/versions/node/v16.13.2/bin/npm
  Browsers:

[Chromium: 99.0.4844.51 (Official Build) (x86_64)]

  npmPackages:
    @storybook/addon-actions: ^6.5.0-alpha.47 => 6.5.0-alpha.47 
    @storybook/addon-docs: ^6.5.0-alpha.47 => 6.5.0-alpha.47 
    @storybook/addon-essentials: ^6.5.0-alpha.47 => 6.5.0-alpha.47 
    @storybook/addon-interactions: ^6.5.0-alpha.47 => 6.5.0-alpha.47 
    @storybook/addon-links: ^6.5.0-alpha.47 => 6.5.0-alpha.47 
    @storybook/react: ^6.5.0-alpha.47 => 6.5.0-alpha.47 
    @storybook/testing-library: ^0.0.9 => 0.0.9

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
