### ISSUE TITLE
Running yarn during setup fails

### ISSUE THREAD

**Issue by nicu-chiciuc** [storybookjs/storybook#17719]
**Describe the bug**
I'm following the tutorial about [setting up storybook](https://storybook.js.org/docs/react/contribute/code#initial-setup) and I fail on the `yarn` step.

**To Reproduce**
Run:
```sh
git clone https://github.com/your-username/storybook.git
cd storybook
yarn
yarn bootstrap --core
```

**System**
```
Environment Info:

  System:
    OS: macOS 12.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Binaries:
    Node: 14.18.1 - ~/.local/share/nvm/v14.18.1/bin/node
    Yarn: 3.1.1 - ~/.local/share/nvm/v14.18.1/bin/yarn
    npm: 8.2.0 - ~/.local/share/nvm/v14.18.1/bin/npm
  Browsers:
    Chrome: 99.0.4844.51
    Firefox: 98.0.1
    Safari: 15.2
```

**Comment by nicu-chiciuc** [comment]
This is the main error:
```
➤ YN0013: │ @lerna/import@npm:3.22.0 can't be found in the cache and will be fetched from the remote registry
➤ YN0035: │ @lerna/import@npm:3.22.0: The remote server failed to provide the requested resource
➤ YN0035: │   Response Code: 404 (Not Found)
➤ YN0035: │   Request Method: GET
➤ YN0035: │   Request URL: https://registry.yarnpkg.com/@lerna/import/-/import-3.22.0.tgz
➤ YN0000: └ Completed in 3s 446ms
```

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
