### ISSUE TITLE
Vulnerability due to storybook#components using out-of-date version of react-syntax-highlighter

### ISSUE THREAD

**Issue by kdw2126** [storybookjs/storybook#17721]
**Describe the bug**
We got a Dependabot security alert due to [this issue](https://github.com/PrismJS/prism/pull/3341) in PrismJS.  

Tracing the origin of this dependency yielded:
  └─┬ @storybook/components@6.4.19
    └─┬ react-syntax-highlighter@13.5.3
      ├── prismjs@1.26.0
      └─┬ refractor@3.5.0
        └── prismjs@1.25.0

The newest version of react-syntax-highlighter -- 15.5.0 -- [now fixes this dependency](https://github.com/react-syntax-highlighter/react-syntax-highlighter/releases/tag/15.5.0) on a non-patched version of prismsjs.   Wanted to flag this because I didn't see an open ticket on this issue.

**Additional context**
I'm very new to Storybook but I do try to keep up on npm/yarn security issues so please let me know if there is anything about this issue that should have been phrased/presented differently.  Also searched through the issues and found a bunch of older security bugs but no mention of this issue.

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
