### ISSUE TITLE
Props not loading in Canvas tab of .MDX stories

### ISSUE THREAD

**Issue by jeredsloof** [storybookjs/storybook#17754]
**Describe the bug**
Props passed by .MDX stories are succesfully loaded in the Docs tab, but are not loaded in the Canvas tab.

**To Reproduce**
Repro: https://www.chromatic.com/library?appId=623432469a808c003aec445c
Repository: https://github.com/jeredsloof/storybook-repro

**System**
Environment Info:

  System:
    OS: macOS 11.6.4
    CPU: (4) x64 Intel(R) Core(TM) i3-8100B CPU @ 3.60GHz
  Binaries:
    Node: 16.14.0 - /usr/local/bin/node
    Yarn: 3.2.0 - /usr/local/bin/yarn
    npm: 8.3.1 - /usr/local/bin/npm
  Browsers:
    Firefox: 98.0.1
    Safari: 14.1.2
  npmPackages:
    @storybook/addon-actions: ^6.5.0-alpha.49 => 6.5.0-alpha.49 
    @storybook/addon-docs: ^6.5.0-alpha.49 => 6.5.0-alpha.49 
    @storybook/addon-essentials: ^6.5.0-alpha.49 => 6.5.0-alpha.49 
    @storybook/addon-links: ^6.5.0-alpha.49 => 6.5.0-alpha.49 
    @storybook/vue3: ^6.5.0-alpha.49 => 6.5.0-alpha.49

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
