### ISSUE TITLE
Possible bug: Fatal error due to missing user during bootstrap `Run local registry`

### ISSUE THREAD

**Issue by binomialstew** [storybookjs/storybook#17797]
I’m using the bootstrap “run registry” function, but I ran into a fatal error because no user has been added to the local registry that was created by storybook. Upon trying to publish the first package:

```
npm ERR! code ENEEDAUTH
npm ERR! need auth This command requires you to be logged in to http://localhost:54445/
npm ERR! need auth You need to authorize this machine using `npm adduser`
```

I’m familiar with the need to add a user to a registry to allow publish, but since this registry is opened dynamically by the script, how can I add a user before it is needed? I found the `verdaccio.yaml` in the scripts directory, but it seems much of the config is used for other purposes. I tried adding a user which resulted in a successful login alongside the running run-registry script, but I still got the same message when the first package was attempted to be published via the other process.

**System**
```
System:
    OS: macOS 12.3
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Binaries:
    Node: 16.14.1 - ~/.nvm/versions/node/v16.14.1/bin/node
    Yarn: 3.1.1 - /usr/local/bin/yarn
    npm: 8.5.0 - ~/.nvm/versions/node/v16.14.1/bin/npm
  Browsers:
    Chrome: 99.0.4844.83
    Firefox: 88.0
    Safari: 15.4
```

**Comment by TefDesign** [comment]
Hi @binomialstew , 
Have you found a solution to your problem ? Or is it still relevant ? I opened a similar ticket in the help requests because I don't know if it's a bug or a misuse on my part :(
https://github.com/storybookjs/storybook/discussions/17863

In any case I'm interested in the answer :)

Thanks !

**Comment by binomialstew** [comment]
@TefDesign, this is still relevant for me. I've set up Verdaccio for myself locally in the meantime and published there to test what I need in a registry.

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
