### ISSUE TITLE
we use storybook beside our main repo as a separate project and storybook parse and bundle all our main files ,while it should only parse the files we imported

### ISSUE THREAD

**Issue by neginpashmakian** [storybookjs/storybook#17821]
When I run storybook, it builds completely, but when I load the page, it stays at the loading stage and does not load stories, and when I check Console, it shows errors that are not related to our stories and related to other parts of our project.
Firstly I customize Webpack in main.js, but  it doesn't work
then I create a separate config for the storybook, bu still face loading and face new error

**Comment by AmirAsghary** [comment]
More context:
```
   Packages: 
    "@storybook/builder-webpack5": "^6.5.0-alpha.41",
    "@storybook/manager-webpack5": "^6.5.0-alpha.41",
    "@mui/material": "^5.0.4",
    "react": "^17.0.1",
    "react-router": "^6.2.2"
```

```
 Storybook main.js: 
  stories: ['../src/**/*.stories.mdx', '../src/**/*.stories.@(js|jsx|ts|tsx)'],
  addons: [
    '@storybook/preset-create-react-app',
    'storybook-addon-performance/register',
  ],
  framework: '@storybook/react',
  core: {
    builder: 'webpack5',
  },
  staticDirs: ['../public/assets'],
```

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
