### ISSUE TITLE
Strict mode not applied for addon-docs

### ISSUE THREAD

**Issue by flippidippi** [storybookjs/storybook#17880]
**Describe the bug**
When specifying react `strictMode`, it seems like this isn't being applied to inline stories in doc pages.

**To Reproduce**
- https://github.com/flippidippi/storybook-repo-17880
- Not deployed because `StrictMode` is only in development

**System**
```bash
Environment Info:

  System:
    OS: Linux 5.10 Ubuntu 20.04.3 LTS (Focal Fossa)
    CPU: (16) x64 Intel(R) Core(TM) i7-10875H CPU @ 2.30GHz
  Binaries:
    Node: 16.6.2 - ~/.nvm/versions/node/v16.6.2/bin/node
    npm: 8.1.0 - ~/.nvm/versions/node/v16.6.2/bin/npm
```

**Additional context**
Strict mode is **NOT** enabled in dev on the "Docs" tab.
![image](https://user-images.githubusercontent.com/1396568/161628251-aeee3460-e1a3-4d23-94e7-cc32dd91bf38.png)

Strict mode **IS** enabled in dev on the "Canvas" tab.
![image](https://user-images.githubusercontent.com/1396568/161628423-41b12b38-c9ef-4892-ac92-04fcfee50a69.png)

**Comment by m7kvqbe1** [comment]
Also experiencing problems with this.

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
