### ISSUE TITLE
Warning: validateDOMNesting(...): <div> cannot appear as a descendant of <p>.

### ISSUE THREAD

**Issue by yashi3112** [storybookjs/storybook#17948]
On angular 9 application
Getting console` Warning: validateDOMNesting(...): <div> cannot appear as a descendant of <p>` after upgrading to v6.0.0

Earlier not facing this issue on version v5.2.3
<img width="871" alt="image" src="https://user-images.githubusercontent.com/63290846/163144496-7a92234b-da80-4169-a74f-47343715e877.png">

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
