### ISSUE TITLE
Unexpected token default

### ISSUE THREAD

**Issue by its-ratikant** [storybookjs/storybook#17958]
**Describe the bug**
Getting unexpected token default:

```
"@babel/core": "^7.17.9",
"@storybook/addon-actions": "^6.4.21",
"@storybook/addon-essentials": "^6.4.21",
"@storybook/addon-links": "^6.4.21",
"@storybook/react": "^6.4.21",
"react-is": "^18.0.0",
```

**To Reproduce**
Run `npx sb init` for a monorepo

**Additional context**
![image](https://user-images.githubusercontent.com/77279630/163290435-84167b60-a6e3-4ce6-937c-44ed3d78098a.png)
![image](https://user-images.githubusercontent.com/77279630/163290445-c4d33e3e-69e5-4535-a653-8f3023e19570.png)

**Comment by MarkPolivchuk** [comment]
I'm encountering this after doing an `npx storybook upgrade` to `6.5.10` as well.

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
