### ISSUE TITLE
Canvas Controls not displaying for TPara story

### ISSUE THREAD

**Issue by OxyTJ** [storybookjs/storybook#18030]
We have written a story for our `TPara` component with the following default export configuration:

```
export default {
    title: 'atoms/TextComponents/TPara'
}
```

This story has a bunch of control arguments setup, however, we get the "**No inputs found for this component**" message. However, when changing `atoms/TextComponents/TPara` to `atoms/TextComponents/_TPara`, the controls appear as expected. I then changed the `TPara` portion of the title to variations like `TParams`, `TParasdasdfasd`, etc, and the controls disappear with every variation that starts with `TPara`. The `_TPara` is fine as a workaround, but we'd really like to use `TPara` to keep our stories' naming convention consistent.

**Comment by burhanuday** [comment]
not able to reproduce this. can you provide a repo with that can reproduce this bug?
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/25934701/164879214-e08c551c-31a3-420d-9e82-dd35d8ec02f4.png">

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
