### ISSUE TITLE
Vulnerability in @storybook/addon-essentials dependencies related with clean-css

### ISSUE THREAD

**Issue by Sonadi1** [storybookjs/storybook#18050]
**Describe the bug**
Not exactly a bug but we got an Xray report saying there's a vulnerable version of [clean-css](https://github.com/clean-css/clean-css) in @storybook/addon-essentials that comes through dependencies.

```
├─┬ @storybook/addon-essentials@6.4.22
│ └─┬ @storybook/addon-docs@6.4.22
│   └─┬ @storybook/builder-webpack4@6.4.22
│     └─┬ html-webpack-plugin@4.5.2
│       └─┬ html-minifier-terser@5.1.1
│         └── clean-css@4.2.4
```
The [vulnerability](https://huntr.dev/bounties/6937a4ed-e41f-4fff-8f9b-8bcbed0f616e/) has been fixed and updating [html-webpack-plugin](https://github.com/jantimon/html-webpack-plugin) would also fix the issue in Storybook. Is it possible to update the plugin to the latest version?

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
