### ISSUE TITLE
CORS errors when referencing storybook that is only accessible internally

### ISSUE THREAD

**Issue by leander-karp** [storybookjs/storybook#18115]
**Describe the bug**
When configuring a reference to another storybook that can be accessed only within an internal network, the storybook assumes that only access with credentials is possible. But that is not the case and requesting `https://www.example.com/stories.json` fails with `Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at 'site'`.

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
