### ISSUE TITLE
Unncessecary unmet `peerDependencies` warning

### ISSUE THREAD

**Issue by emattias** [storybookjs/storybook#18147]
<img width="800" alt="CleanShot 2022-05-05 at 13 06 09@2x" src="https://user-images.githubusercontent.com/351537/166911153-eb52c2c4-d6f1-4403-9e6a-4577c3784024.png">

We get those from other packages that we use. Could the be set as optional [like react is](https://github.com/storybookjs/storybook/blob/next/addons/a11y/package.json#L73-L80)?

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
