### ISSUE TITLE
Home and End buttons don't work inside the sidebar search input

### ISSUE THREAD

**Issue by kaiyoma** [storybookjs/storybook#18142]
**Describe the bug**
The Home and End buttons don't work inside the sidebar search input. (I often use Shift + Home to select all the text in an input.)

**To Reproduce**
Press Home or End while focused inside the sidebar search input.

**System**
Can be seen on any version.

**Additional context**
Tested on a PC keyboard.

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
