### ISSUE TITLE
Docs are not generated for React.VFC

### ISSUE THREAD

**Issue by gaurav5430** [storybookjs/storybook#18238]
**Describe the bug**
It seems that the docgen plugin does not automatically generate docs for React.VFC

**To Reproduce**
Create a component with React.VFC type, create a story for it. Docs do not show up in Docs pane.
Change React.VFC to React.FC , does show up

**System**
Environment Info:

  System:
    OS: macOS 12.0.1
    CPU: (10) x64 Apple M1 Pro
  Binaries:
    Node: 12.22.8 - ~/.nvm/versions/node/v12.22.8/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.15 - ~/.nvm/versions/node/v12.22.8/bin/npm
  Browsers:
    Chrome: 101.0.4951.64
    Firefox: 99.0.1
    Safari: 15.1
  npmPackages:
    @storybook/addon-a11y: ^6.3.3 => 6.4.19 
    @storybook/addon-actions: ^6.3.3 => 6.4.19 
    @storybook/addon-essentials: ^6.3.3 => 6.4.19 
    @storybook/addon-links: ^6.3.3 => 6.4.19 
    @storybook/builder-webpack5: ^6.3.12 => 6.4.19 
    @storybook/manager-webpack5: ^6.3.12 => 6.4.19 
    @storybook/react: ^6.3.3 => 6.4.19

**Additional context**
it seems there is a open bug on docgen repo, which might be the cause of it. There is a workaround where you can add React.VFC in customComponentTypes, i couldn't find that option on storybook
https://github.com/styleguidist/react-docgen-typescript/issues/402

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
