### ISSUE TITLE
Story height is translated to min-height instead of height

### ISSUE THREAD

**Issue by Yogu** [storybookjs/storybook#18311]
**Describe the bug**

If you set the height of a story with the `height` attribute

```<Story name="test" height="600px">...</Story>```

and have `inlineStories` set to `true` in the docs configuration, the height is applied as min-height, and no max height is in place. Additional, it sets the "height" attribute of a `div` which looks like it would work in an `iframe`, but obivously it does not on a div.

Is it intentional that `height` translates to `min-height`? It's a bit confusing because it also sets `overflow: auto`, which does not really make sense with only a min height. If it's intended, is there a way to restrict the height?

**To Reproduce**

https://github.com/Yogu/storybook-repro-story-height

**System**

```
Environment Info:

  System:
    OS: Linux 5.10 Ubuntu 20.04.4 LTS (Focal Fossa)
    CPU: (8) x64 Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz
  Binaries:
    Node: 14.19.1 - ~/.nvm/versions/node/v14.19.1/bin/node
    Yarn: 1.22.18 - ~/.nvm/versions/node/v14.19.1/bin/yarn
    npm: 6.14.16 - ~/.nvm/versions/node/v14.19.1/bin/npm
  Browsers:
    Firefox: 100.0.2
```

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
