### ISSUE TITLE
 Restored webpack dependency breaks my builds

### ISSUE THREAD

**Issue by thomasmattheussen** [storybookjs/storybook#18374]
**Describe the bug**
I get the same errors as described in https://github.com/storybookjs/storybook/issues/14497

I've tracked it back to this commit (introduced in 6.5.0-alpha.15) https://github.com/storybookjs/storybook/commit/29c46278fc7c38b3f9c68e91de056419b9735680

I've tried to fix this by using yarn resolutions trying to pin the webpack version to `4` but leads to other errors.

**System**
System:
    OS: macOS 11.6.5
    CPU: (8) arm64 Apple M1
  Binaries:
    Node: 16.14.2 - ~/.nvm/versions/node/v16.14.2/bin/node
    Yarn: 1.22.18 - ~/.nvm/versions/node/v16.14.2/bin/yarn
    npm: 8.5.0 - ~/.nvm/versions/node/v16.14.2/bin/npm
  Browsers:
    Chrome: 101.0.4951.64
    Edge: 101.0.1210.53
    Firefox: 100.0.2
    Safari: 15.4

**Additional context**

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
