### ISSUE TITLE
Not getting the reset value for input-type 'number' 

### ISSUE THREAD

**Issue by PranabanandaJana2022** [storybookjs/storybook#18398]
**Describe the bug**
I'm always frustrated when I work with controls. Not getting the reset value in type 'number' input-box. After reset the change effect is happening fine but the value in the input-box is not changing. 
**To Reproduce**
1. Choose the story with input type 'number in control. 
2. I change number in control.
3. Click on the 'Reset' button
4. I still see the changed value

![image](https://user-images.githubusercontent.com/106813355/171846024-0ead7e50-6681-4d70-80c0-afcb62a60f40.png)

**Additional context**
For other input type(like: boolean, object, string) the reset function is happening fine.

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
