### ISSUE TITLE
why @storybook/vue3 has react as it dependencies?

### ISSUE THREAD

**Issue by l1shu** [storybookjs/storybook#18404]
<img width="381" alt="image" src="https://user-images.githubusercontent.com/48285873/171995791-624be4cd-be5f-4c5e-b95e-8b79067a1ac4.png">

can it be removed?

**Comment by l1shu** [comment]
I figured out that vue3 + jsx declaration has been covered by @types/react which is imported by storybook

and the solution is : 
https://github.com/storybookjs/storybook/issues/17576
https://github.com/johnsoncodehk/volar/discussions/592

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
