### ISSUE TITLE
Attempt to load story for storybook pages

### ISSUE THREAD

**Issue by xxxKOTxxx** [storybookjs/storybook#18424]
**Describe the bug**
On Storybook pages like `About`, `Release notes`, `Keyboard shortcuts`, etc. console error like: 
```
Unable to load story '{page_name}':
Couldn't find story matching '{page_name}'.
- Are you sure a story with that id exists?
- Please check your stories field of your main.js config.
- Also check the browser console and terminal for error messages.
```
**To Reproduce**
Just open one of mentioned pages, open console and reload page.

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
