### ISSUE TITLE
Missing install directions for web components in docs

### ISSUE THREAD

**Issue by jared-christensen** [storybookjs/storybook#18438]
There are no install directions for web components in the docs.

https://storybook.js.org/docs/web-components/get-started/install

Here is an example of what I see for the docus under HTML. 

<img width="876" alt="image" src="https://user-images.githubusercontent.com/1406482/172672060-4775903e-5de0-4af8-8f67-9a7a661abd21.png">

When I change the framework to web componets the directions are gone.

<img width="1249" alt="image" src="https://user-images.githubusercontent.com/1406482/172672394-bbd1e587-36fa-40ad-874b-c742a2cec022.png">

**Comment by jonniebigodes** [comment]
@jared-christensen thanks for opening up this issue and following up with us on this. To give you some context, this is a known issue raised [here](https://github.com/storybookjs/frontpage/issues/228). In all fairness, this is being addressed, but rather slowly as I hadn't had the time to fully commit myself to address it as I've been working on some other parts of the documentation that required attention. I plan on circling back to it in the upcoming weeks and solve it so that not only you but the other community members can also benefit from it as well.

Hope you have a great week. 

Stay safe

**Comment by kylegach** [comment]
This has been fixed.
