### ISSUE TITLE
args suddenly stopped being spread in the story

### ISSUE THREAD

**Issue by dominikabieder** [storybookjs/storybook#18486]
I have following story

```
export default {
  title: "Misc/Offers/AgentMessage",
  component: AgentMessage,
  decorators: [withRouterDecorator()],
  args: {
    areSavingsAboveZero: true,
    offer: {
      category: "ELECTRICITY",
    },
  },
};
```

However, despite areSavingsAboveZero are set to true, which is a condition to showing some text in a component, when I spread args, they don't get spread anymore like they used to
`export const VOffer = ({ args }) => <AgentMessage {...args} />;`

When I console.log `areSavingsAboveZero`, they are undefined. 

Any idea why this has suddenly stopped working?

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
