### ISSUE TITLE
Exit process when specified directory doesn't exist 

### ISSUE THREAD

**Issue by rwu823** [storybookjs/storybook#18481]
**Describe the bug**

If the specified directory that doesn't exist will get errors

> ModuleNotFoundError: Module not found: Error: Can't resolve

But no exit of build process.

**To Reproduce**

Please create a `.storybook/main.js` config and put any directory that doesn't exist.

```js
module.exports = {
 stories: ['../foo/**/*.stories.js'],
}
```

And then run:
```sh
yarn build-storybook
```

**System**
Please paste the results of `npx sb@next info` here.

```
Environment Info:

  System:
    OS: macOS 12.4
    CPU: (8) arm64 Apple M1
  Binaries:
    Node: 16.14.2 - /var/folders/kw/h6hm37453zgb915l08ln8f1h0000gn/T/fnm_multishells/15631_1655249271477/bin/node
    Yarn: 1.22.18 - /opt/homebrew/bin/yarn
    npm: 8.5.0 - /var/folders/kw/h6hm37453zgb915l08ln8f1h0000gn/T/fnm_multishells/15631_1655249271477/bin/npm
  Browsers:
    Chrome: 102.0.5005.115
    Firefox: 100.0.2
    Safari: 15.5
  npmPackages:
    @storybook/addon-essentials: 6.5.9 => 6.5.9 
    @storybook/addon-links: 6.5.9 => 6.5.9 
    @storybook/addons: 6.5.9 => 6.5.9 
    @storybook/core-common: 6.5.9 => 6.5.9 
    @storybook/react: 6.5.9 => 6.5.9 
    @storybook/theming: 6.5.9 => 6.5.9 
```

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
