### ISSUE TITLE
Static deployment from internal repository on Github CORS error in Composition

### ISSUE THREAD

**Issue by gabriel-brotas** [storybookjs/storybook#18517]
Hi guys, I have 2 instances of storybook hosted in 2 different internal repositories and when I try the composition ex:
```
	"refs": {
		"angular": {
		  title: 'Angular Internal',
		  url: 'https://<another-internal-repo-url>.pages.github.io/',
		  expanded: true
		}
	}
```
it gives me an CORS error when try to access the <url>/stories.json (I have the stories.json file in both repositories).

Do you guys know how to solve this? github doesn't allow cors settings and the storybook-static doesn't have an option to setup cors either.

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
