### ISSUE TITLE
Please publish version 5.3.22 to fix colors@1.4.2 being absent from npm

### ISSUE THREAD

**Issue by collinstommy** [storybookjs/storybook#18533]
**Describe the bug**
`5.3.21` cannot be installed due to a missing dependency down the tree (colors@1.4.2). The dependency is brought in by `cli-table3@0.5.1`.

Colors v1.4.2 was removed from npm.

Version`5.3.22` will fix the issue as it includes this commit:

5.3.22 is missing on npm for these packages:
@storybook/addon-a11y
@storybook/addon-actions
@storybook/addon-centered
@storybook/addon-info
@storybook/addon-jest
@storybook/addon-knobs
@storybook/addon-links
@storybook/addon-viewport
@storybook/addons
@storybook/react

Cli was published for 5.3.22.
https://www.npmjs.com/package/@storybook/cli

Thanks for all your good work!

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
