### ISSUE TITLE
Various DependaBot security vulnerabilities

### ISSUE THREAD

**Issue by developerdizzle** [storybookjs/storybook#18541]
**Describe the bug**

While triaging our own repo's DependaBot security vulnerabilities, we noticed a lot of them were coming from sub-dependencies within Storybook.  It would be great if Storybook was able to resolve these vulnerabilities to prevent them from being present in repos that use it.

**To Reproduce**

Not a traditional repro instruction set, but you can see these vulnerabilities by forking Storybook (skip this if you're a Storybook admin), enabling DependaBot alerts, then viewing them.  You'll see this (taken today):

![image](https://user-images.githubusercontent.com/1398136/175051350-647fb7fb-641a-4008-9e80-d3193d98fe4f.png)

**Comment by TomasSlama** [comment]
We have the same issue, the storybook is using a lot of out-of-date packages with vulnerabilities, it would be great to fix them, the only solution we have right now is to fix it locally with `resolutions`.

**Comment by denieler** [comment]
yeah, we have the same issue 👍 hate using resolutions for that purpose 🤯

**Comment by dmaklygin** [comment]
this one https://github.com/storybookjs/storybook/issues/14603 seems, is an old one

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).

AFAIK we've cleared the decks on security violations in 7.0 and will be doing major releases more frequently to keep it that way
