### ISSUE TITLE
Unable to build story book

### ISSUE THREAD

**Issue by redfer13** [storybookjs/storybook#18584]
**To Reproduce**
npx create-react-app dnd
npx storybook 
yarn install // Using yarn 3.2.2
yarn build-storybook
**System**

![image](https://user-images.githubusercontent.com/62601155/176084239-7aa2a396-4da6-4cf2-97c5-6b7d155240e1.png)

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
