### ISSUE TITLE
Unable to run storybook after upgrading to latest version

### ISSUE THREAD

**Issue by aakashsardana** [storybookjs/storybook#18590]
**Describe the bug**
Hi, earlier we were using version 5..2.4 of storybook but now we want to upgrade it to 6.5.9. We have also upgraded webpack to version 5. 
Our storybook configuration is present in webpack.config.babel.js file.
But after running storybook I get an import error of package 'globby'. Syntax Error: Cannot use import statement outside a module
We are using globby inside webpack.config.babel.js  to get the storybook indexes.

`globby.sync('*/storybook.index.js', {cwd, absolute: true})`

**To Reproduce**
Please create a reproduction by running `npx sb@next repro` and following the instructions. Read our [documentation](https://storybook.js.org/docs/react/contribute/how-to-reproduce) to learn more about creating reproductions.
Paste your repository and deployed reproduction here. We prioritize issues with reproductions over those without.

**System**
Please paste the results of `npx sb@next info` here.

**Additional context**

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
