### ISSUE TITLE
Storybook starts without the default (pre-built) fonts

### ISSUE THREAD

**Issue by raul1991** [storybookjs/storybook#18707]
**Describe the bug**
I just upgraded from 5.3.21 to 6.5.9 and it seems that newer version doesn't applies the fonts correctly.

![version 6.5.x](https://user-images.githubusercontent.com/1281636/178894533-0d25e72b-c02d-48cc-8025-cf0b43ccdd7c.png)
![version 5.3.x](https://user-images.githubusercontent.com/1281636/178895009-a8e32fb4-29a3-4025-b669-86c48128642f.png)

**To Reproduce**
Ran npx storybook init and then yarn storybook

**System**
```bash
Environment Info:

  System:
    OS: macOS 11.6.7
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Binaries:
    Node: 16.10.0 - /usr/local/bin/node
    Yarn: 3.2.1 - ~/.yarn/bin/yarn
    npm: 7.24.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 103.0.5060.114
    Firefox: 97.0
    Safari: 15.5
```

**Additional context**
I am not loading any external fonts, I expect the default fonts that showed up in the last version shows up in this newer version too.

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
