### ISSUE TITLE
storybook 6.5.9  show code  show story not  templete

### ISSUE THREAD

**Issue by JOYCEQL** [storybookjs/storybook#18721]
**Describe the bug**
storybook 6.5  show code  show story not  templete

![image](https://user-images.githubusercontent.com/34961949/179191343-68186530-8ee4-40e8-b059-0b6d92f47bc0.png)

**System**
     windows
  Binaries:
    Node: 14.17.0
  Browsers:
    edge 103.0.1264.49 (正式版本) (64 位)

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
