### ISSUE TITLE
Integration with ant design

### ISSUE THREAD

**Issue by michalgrzegorczyk-dev** [storybookjs/storybook#18797]
**Describe the bug**
In Angular application I would like to display nz-badge (from ant design) but it's not displayed properly.

**To Reproduce**
Create component with `<nz-badge [nzCount]="10">Test</nz-badge>`

Test will be displayed but without badge count.

**System**

Environment Info:

  System:
    OS: macOS 12.4
    CPU: (8) arm64 Apple M1
  Binaries:
    Node: 16.14.0 - /usr/local/bin/node
    Yarn: 1.22.18 - /usr/local/bin/yarn
    npm: 8.3.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 103.0.5060.134
    Firefox: 102.0.1
    Safari: 15.5
  npmPackages:
    @storybook/addon-essentials: ~6.5.9 => 6.5.9 
    @storybook/angular: ~6.5.9 => 6.5.9 
    @storybook/builder-webpack5: ~6.5.9 => 6.5.9 
    @storybook/core-server: ~6.5.9 => 6.5.9 
    @storybook/manager-webpack5: ~6.5.9 => 6.5.9 
  npmGlobalPackages:
    @storybook/cli: 6.5.9

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
