### ISSUE TITLE
Links in migration guide are broken/outdated

### ISSUE THREAD

**Issue by DerZyklop** [storybookjs/storybook#18939]
**Describe the bug**
I try to start my storybook. It tells me

```
WARN Your Storybook startup uses a solution that will not be supported in version 7.0. 
WARN You must use angular builder to have an explicit configuration on the project used in angular.json
WARN Read more at:
WARN - https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#sb-angular-builder)
WARN - https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#angular13)
```
 
I took a look at https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#sb-angular-builder. It tells me that »The full builder documentation will be shown in the [main documentation page](https://storybook.js.org/docs/angular) soon«. Which does not seem to be the case yet. I searched the docs for angular.json and could not find any entry.

There are at least links to examples and schemas for `start-storybook` and `build-storybook`. But sadly both lead to a 404.

I’m lost.

**To Reproduce**
Visit https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#sb-angular-builder; try all the links.

**System**
Please paste the results of `npx sb@next info` here.

```
Environment Info:

  System:
    OS: macOS 12.2
    CPU: (10) arm64 Apple M1 Pro
  Binaries:
    Node: 16.13.2 - ~/.nvm/versions/node/v16.13.2/bin/node
    npm: 8.1.2 - ~/.nvm/versions/node/v16.13.2/bin/npm
  Browsers:
    Chrome: 104.0.5112.79
    Firefox: 103.0.2
    Safari: 15.3
  npmPackages:
    @storybook/addon-actions: 6.5.10 => 6.5.10 
    @storybook/addon-docs: 6.5.10 => 6.5.10 
    @storybook/addon-essentials: 6.5.10 => 6.5.10 
    @storybook/addon-interactions: 6.5.10 => 6.5.10 
    @storybook/addon-links: 6.5.10 => 6.5.10 
    @storybook/addon-viewport: 6.5.10 => 6.5.10 
    @storybook/angular: 6.5.10 => 6.5.10 
    @storybook/builder-webpack5: 6.5.10 => 6.5.10 
    @storybook/cli: 6.5.10 => 6.5.10 
    @storybook/manager-webpack5: 6.5.10 => 6.5.10 
    @storybook/testing-library: 0.0.13 => 0.0.13 
```

**Additional context**

Not sure if this belongs here, but the warning is followed by an error 
`Error: Requested locale 'en' is not defined for the project.` (which I think is not true)

**Comment by jonniebigodes** [comment]
@DerZyklop, thanks for taking the time to reach out to us with your issue. For an overview on how to set up Storybook's builder, we have some documentation [here](https://storybook.js.org/docs/angular/get-started/install). Also, if you scroll down that page into the "Troubleshooting" section, you'll see that there's an overview mentioning all the available options to further customize the builder.

I'm more than ok with making a small pull request fixing the links, but looking at this issue, probably a better path moving forward would be to link to the installation instructions instead of the migration guide to be a bit more explicit as the migration guide, and the repo's code can get out of sync as Storybook grows.

What do you think @shilman and @yannbf ?

**Comment by jonniebigodes** [comment]
Closing this as it was already addressed with earlier pull requests.
