### ISSUE TITLE
Bad Link for Storybook Test Runner Add-on

### ISSUE THREAD

**Issue by MichaelrMentele** [storybookjs/storybook#18957]
I love storybook. Great work with the package. Thought'd I'd drop this minor issue here:

**Describe the bug**
![image](https://user-images.githubusercontent.com/9519712/185445629-d75cecdc-cb37-4ee4-8c00-8d7b829ad056.png)

**To Reproduce**
click link with add-on

![image](https://user-images.githubusercontent.com/9519712/185445736-dfcffaf0-895e-4fec-ad2d-84c32a53be41.png)

**System**
Please paste the results of `npx sb@next info` here.
```
Environment Info:

  System:
    OS: macOS 12.4
    CPU: (10) x64 Apple M1 Max
  Binaries:
    Node: 16.14.0 - ~/.nvm/versions/node/v16.14.0/bin/node
    Yarn: 3.2.0 - ~/.nvm/versions/node/v16.14.0/bin/yarn
    npm: 8.3.1 - ~/.nvm/versions/node/v16.14.0/bin/npm
  Browsers:
    Chrome: 104.0.5112.101
    Firefox: 101.0
    Safari: 15.5

```

**Comment by zhyd1997** [comment]
Recently all the source code has been moved to `code` folder: https://github.com/storybookjs/storybook/blob/next/code/addons/interactions/README.md

The website has many places need to sync with the major change.

**Comment by jonniebigodes** [comment]
@MichaelrMentele, thanks for reaching out to us and letting us know of that issue. As @zhyd1997 mentioned correctly the monorepo recently went through a change, and with that, some addons might still be affected as the addon-interactions. On that note, @zhyd1997 can you provide a bit more context on this:

> The website has many places need to sync with the major change.

I've recently updated the documentation in light of this change, and probably hasn't been patched up, but if you found any other broken links, please do let me know, and I'll gladly update them. Or, if you're willing, feel free to submit a pull request addressing it and ping me so that it can be looked at and help not only you but the rest of our community.

**Comment by zhyd1997** [comment]
@jonniebigodes 

Okay, only find one here:https://github.com/storybookjs/storybook/blob/65e222d6191e4b269afbadded8646c2afbe10e0b/docs/contribute/code.md?plain=1#L15-L20

not related to user experience, but to developer experience.

for now, `storybook` folder is not correct, `yarn` will not work because the source code has been moved to `code` folder, and `yarn bootstrap` will not work either because we need to install `node_modules` in `scripts` folder firstly using `yarn` to prevent some `node_modules` not found error.

all the changes should be also made in the [gitpod.yml](https://github.com/storybookjs/storybook/blob/next/.gitpod.yml) file, but not sure the process above is correct.

_I am a new contributor to the project and lack some engineering knowledge about it._

**Comment by jonniebigodes** [comment]
@zhyd1997, yes, indeed you're correct. To provide you a bit more context, as with this shift in the monorepo, that part of the documentation will require some updates to reflect the changes introduced. A pull request should be up soon addressing it and hopefully will get you unblocked and provide you with the necessary information to start contributing to Storybook.

**Comment by zhyd1997** [comment]
@jonniebigodes 

A PR is here: #18998

**Comment by jonniebigodes** [comment]
@MichaelrMentele  wanted to let you know that a pull request is already up addressing and closing this issue. Sorry for the delay in getting it pushed.

Once it's merged, the issue will be closed. Thanks for reaching out with this small but rather crucial issue. Appreciate it 🙏 !


Hope you have a great weekend.

Stay safe
