### ISSUE TITLE
CLI: `sb init` should not initialize with the deprecated `-s` option for static folders

### ISSUE THREAD

**Issue by shilman** [storybookjs/storybook#19420]

**Comment by LBBO** [comment]
If possible, I would like to work on this.

I think the cause for this lies in `code/lib/cli/src/generators/baseGenerator.ts:242` where the staticDir is passed to the package scripts in order to then be included in the default scripts in the package.json. Instead, I would suggest passing a `staticDirs` array to `configureMain` that is set to `[staticDir]` if it is set.

Are there any issues with my suggestions? And are there any special edge cases I should consider during testing? This would be my first contribution to storybook, just in case that's a factor.

**Comment by LBBO** [comment]
Alright, I hope to have fixed the issue. However, I can't figure out how to test the CLI locally. I've tried running `yarn build cli` successfully (after some problems that I was able to solve) and it produces a `dist/generate.js`, but I haven't managed to execute it (via the `bin/index.js` file) because dependencies can't be found. Any pointers?

**Comment by shilman** [comment]
Jeepers creepers!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.0-alpha.48 containing PR #19585 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.
