### ISSUE TITLE
[Bug]: newFrameworks automigration should respect builder

### ISSUE THREAD

**Issue by shilman** [storybookjs/storybook#19727]
### Describe the bug

From [discord](https://discord.com/channels/486522875931656193/915642585761075280/1037393201620852756):

> newFrameworks migration updated me from builder-vite to react-webpack5 for some reason, I would've expected that it updates me to react-vite.

**Comment by yannbf** [comment]
I tried my best to replicate that specific user's `main.ts` and the migration ran successfully:

![Image](https://user-images.githubusercontent.com/1671563/204877912-3abda28f-a56a-46d9-9d6a-7c5c2ac15a18.png)

 I'm missing something, so hopefully the user will answer on discord and I'll be able to replicate this

**Comment by mihkeleidast** [comment]
I tried the migration again with the latest version, and it seems this issue has been fixed by something in the time that has passed. One difference I did notice from before was that before it ran both `mainjsFramework` and `newFrameworks` migrations, now the first one did not run at all anymore - maybe that borked something up before? Either way, I think this can be closed now, seems to work as expected with latest.
