### ISSUE TITLE
[Bug]: 6.5->7 migration failed for CRA reproduction

### ISSUE THREAD

**Issue by tmeasday** [storybookjs/storybook#20040]
### Describe the bug

I ran `npx sb@next upgrade --prerelease` on this reproduction from https://github.com/storybookjs/storybook/issues/18258: https://github.com/reinertisa/my-example-reproduction

The migration did not:

1. Upgrade to webpack5
2. change the framework field
3. Add the CRA preset (not sure why it wasn't there already).

**Comment by yannbf** [comment]
Hey @tmeasday I ran the same command in the repro and I had a successful migration (related to our current fixes):

- webpack4 deps got removed
- @storybook/react-webpack5 was added
- storybook scripts were updated correctly
<img width="1108" alt="image" src="https://user-images.githubusercontent.com/1671563/207022356-eb893c8c-5923-40b4-ba73-b230bdf77010.png">

The framework field already existed in the repro, and it got changed to the correct package too:
<img width="897" alt="image" src="https://user-images.githubusercontent.com/1671563/207022417-8695b467-b751-4e7a-8072-3a6f076af6f2.png">

The preset didn't get added because we do not have an automigration for that.

**Comment by tmeasday** [comment]
That looks pretty good @yannbf. I'm not sure why it didn't happen to me, but maybe we fixed something in the meantime. I think we can close this.
