### ISSUE TITLE
[Bug]: Slot content displayed with double quotes

### ISSUE THREAD

**Issue by oliviervanbulck** [storybookjs/storybook#20670]
### Describe the bug

When you add default to args for using the default slot, you can give a string, but that string is displayed with quotes around it.

Ex. **"String"** displayed instead of **String**

**Comment by emersonbottero** [comment]
workaround..

```js
 render: (args) => ({
    components: { Button },
    setup() {
      return { args };
    },
    template: '<Button v-bind="args">{{args.default}}</Button>',
  }),
```

**Comment by shilman** [comment]
@chakAs3 is this something you've seen before?

**Comment by chakAs3** [comment]
> @chakAs3 is this something you've seen before?

i know what is happening, actually we should not be passing slot with default anymore as we have now slot control.
normaly Typescript won't allow you `args.default` as it is not a prop of the component, but since is it javascript i guess so no type checking it passes with the value, I will find a fix.
