### ISSUE TITLE
[Bug]: Storybook-Next v7 build for web-components isn't static

### ISSUE THREAD

**Issue by ARuzek** [storybookjs/storybook#20816]
### Describe the bug

v6 storybook static build folder opened without any server. I could double click the index and it opened in the browser with everything working. 

v7 storybook static build folder only works when opening via a server service on an open port for example. 

![image](https://user-images.githubusercontent.com/6900736/215219499-76d53c45-4467-4994-a9ab-ee06293c71ae.png)

### To Reproduce

```shell
Latest storybook with web-components-webpack5 and then build. Try to open index in a browser without running a server. It's a blank screen for me. 
```

### System

```shell
Environment Info:

  System:
    OS: Windows 10 10.0.19044
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz
  Binaries:
    Node: 18.13.0 - C:\Program Files\nodejs\node.EXE
    npm: 9.3.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (109.0.1518.61)
  npmPackages:
    @storybook/addon-actions: ^7.0.0-beta.35 => 7.0.0-beta.35
    @storybook/addon-docs: ^7.0.0-beta.35 => 7.0.0-beta.35
    @storybook/addon-essentials: ^7.0.0-beta.35 => 7.0.0-beta.35
    @storybook/addon-links: ^7.0.0-beta.35 => 7.0.0-beta.35
    @storybook/cli: ^7.0.0-beta.35 => 7.0.0-beta.35
    @storybook/mdx2-csf: ^1.0.0-next.4 => 1.0.0-next.5
    @storybook/web-components: ^7.0.0-beta.35 => 7.0.0-beta.35
    @storybook/web-components-webpack5: ^7.0.0-beta.35 => 7.0.0-beta.35
```

**Comment by ARuzek** [comment]
I think maybe it's a CORS issue with the index.html module script of the storybook-static folder: `<script type="module">
      import './sb-addons/links-0/manager-bundle.mjs';`

**Comment by shilman** [comment]
@valentinpalkovic can you please verify the reproduction on windows when you have a minute?

**Comment by shilman** [comment]
I believe this is a known issue and we require an HTTP server for static content, such as `npx http-server storybook-static`.

@ndelangen @IanVS can either of you please elaborate on this?

**Comment by ndelangen** [comment]
Ow, I haven't tried this in a while, but I do remember this being at a point where it broke, and we decided it wasn't too terribly important to fix?

It's possibly due to one or more of these issues:
- pathing, references to assets being broken (though they really should all be relative!)
- mime-types, using extensions like `.mjs` might not get proper mime-types or something, thus not run as JavaScript.

I'm personally not convinced it's a feature worth having.

If we are going to bring it back, I wonder how we're going to assure it won't break again in the future, and we'd have to assure this on both unix and non-unix systems i guess.

I'm advocating for dropping support for this because it's extremely hard to test, and running a quick `npx` command isn't too much trouble?

**Comment by IanVS** [comment]
I agree.  I have also advocated in the past for adding a command into the Storybook cli like `storybook serve` or `storybook preview`, similar to other tools like Vite, Astro, Docusaurus, etc.  Most modern tools require a server and will not open directly from files, and so far I haven't heard a use case for needing to avoid a server.
