### ISSUE TITLE
[Bug]: Crash with @storybook/react under ts 5.0.0-beta

### ISSUE THREAD

**Issue by Jack-Works** [storybookjs/storybook#20826]
### Describe the bug

please upgrade [react-docgen-typescript-plugin](https://github.com/hipstersmoothie/react-docgen-typescript-plugin) to 1.0.2

https://github.com/storybookjs/storybook/blob/f86883940bc436b9028231ca406d99c742bef178/code/presets/react-webpack/package.json#L78

**Comment by Jack-Works** [comment]
see: https://github.com/hipstersmoothie/react-docgen-typescript-plugin/issues/78

wait for a new release on npm of @storybook/react-docgen-typescript-plugin

**Comment by JReinhold** [comment]
@shilman it seems like people are blocked on trying out TS 5.0 beta because we've forked `react-docgen-typescript-plugin` and are running on an old version of that. We already have a PR ready to bring us up-to-date with upstream: https://github.com/storybookjs/react-docgen-typescript-plugin/pull/8

But I'm curious why we're on a fork?

**Comment by shilman** [comment]
closing as dupe to [#19055](https://github.com/storybookjs/storybook/issues/19055)
