### ISSUE TITLE
Take the default name for MDX files from the filename, rather than the `docsOptions.defaultName`

### ISSUE THREAD

**Issue by tmeasday** [storybookjs/storybook#20863]
When you create an attached MDX file without an explicit name:

```mdx
<Meta of={SomeStories} />
```

The file will end up with :
 - `SomeStories`'s title (good)
 - name: `"Docs"` (or whatever the `docsOptions.defaultName` is).

Contrast with an unattached MDX file, using autotitle, which ends up with:
 - the name of the MDX file as title (e.g. `Introduction`)
 - name: `"Docs"` also, but with a crucial difference which is due to single-story hoisting, you cannot actually see the name.

So it appears in the UI with an entry corresponding to the file name.

Should we change the logic for unnamed attached MDX files to use the file name as name also?

**Comment by shilman** [comment]
@tmeasday can you expand on your single-story hoisting point above? I thought we only applied SSH when the story name is the same as the title?

Otherwise I generally like the proposal to use autotitle for attached MDX files. There are probably two cases to consider:

Case 1, which maps cleanly to the existing behavior
```
Button/
 - index.js
 - index.stories.js
 - docs.mdx
``` 

Case 2, which does not:

```
atoms/
  - Button.js
  - Button.stories.js
  - Button.mdx
```

Would Case 2's docs get the title "Button"? Or would we expect them to add a `title` in the MDX? Or would we need some kind of special case when the autotitle of the MDX matches the autotitle of the component?

**Comment by tmeasday** [comment]
>  I thought we only applied SSH when the story name is the same as the title?

Or when the only entry is a docs file.

**Comment by shilman** [comment]
Yowza!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.0-beta.40 containing PR #20867 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb@next upgrade --prerelease
```
