### ISSUE TITLE
[Bug]: Sidebar sorting is inconsistent with Webpack project when StoryStoreV7 is disabled

### ISSUE THREAD

**Issue by yannbf** [storybookjs/storybook#20941]
### Describe the bug

Context can be found here: https://github.com/storybookjs/storybook/pull/20892#issuecomment-1416335728

### To Reproduce

```shell
yarn task --task sandbox --template internal/ssv6-webpack --no-link --start-from=install
```

### Additional context

Once fixed, please re-enable the tests for ssv6-webpack in `code/e2e-tests/addon-docs.spec.ts`

**Comment by tmeasday** [comment]
This is a webpack export ordering problem: 
<img width="334" alt="image" src="https://user-images.githubusercontent.com/132554/216851285-0a01f58a-9751-4523-a6ae-fb51d8d452b2.png">

I'm pretty sure we've solved this issue before, need to find the old solution..

**Comment by tmeasday** [comment]
OK, so our fix for the above issue is a babel loader: https://github.com/storybookjs/storybook/blob/1623d0cdabfef6bd569d34c6ba672f64a483bf56/code/lib/builder-webpack5/src/presets/preview-preset.ts#L27

That doesn't apply to our test stories, because we use `esbuild-loader` to process stories in the `template-stories` directory.

I'm not sure we can fix this (easily at least). Shall we just leave the test disabled do you think @yannbf?

**Comment by yannbf** [comment]
@tmeasday that could make sense, but what about the fact that the other Webpack5 projects had the correct ordering? Shouldn't that problem affect all Webpack sandboxes? Why would it affect only ssv6?

**Comment by tmeasday** [comment]
Because in v7 the order is provided by the index, which processes the file statically. In v6, there is no index, it all happens at runtime in the browser.

**Comment by yannbf** [comment]
Got it! Then it makes sense that this is not a problem. Thanks for explaining!
