### ISSUE TITLE
[Bug]: autodocs pages that only contain a single story show the same story twice

### ISSUE THREAD

**Issue by yannbf** [storybookjs/storybook#20969]
### Describe the bug

<img width="1278" alt="image" src="https://user-images.githubusercontent.com/1671563/217089217-264b41ec-6a84-40d8-bb7b-4584cae35018.png">

### To Reproduce

Access a Storybook 7 project with autodocs, and create a single story for a component. Look at the docs entry and you will see two component, which seems redundant.

One would assume that there should be no need to display the same component twice, while others might argue the top one is a playground, and the bottom one is the fixed story (with original looks). Providing the story at the bottom when there are multiple stories does seem to make more sense, it just feels weird when there is a single story.

**Comment by chantastic** [comment]
this seems like the "least magical" option to me.

i'd be inclined to leave it as is and see if it bothers anyone. it's a very logical default.
if other use-cases emerge, does the autodocs feature have the ability to accept user configuration?

**Comment by JReinhold** [comment]
I tend to agree with @chantastic on this - keeping it is less magical than removing it, but I also get why you'd think that it's a bit weird to see.


> if other use-cases emerge, does the autodocs feature have the ability to accept user configuration?

@chantastic yes we have plenty of configurations under `parameters.docs.X`, so we could add another one for this if we wanted.

### Background info

This is caused by the recent decision to also show the primary story in the list below (before, the primary story was always omitted).

Which was caused by the question _"where do we show the description for the primary story (which is NOT the same as the component description)?"_ to which the answer was _"for consistency, we'll render the primary story in the list below, so it has a place for its description"_.

So if we wanted to get rid of the second story below in this one-story scenario, a question we'd need to answer is _"where do we show the description for the story then, while also making it distinguishable from the component description?"_.

**Comment by JReinhold** [comment]
More feedback here: https://discord.com/channels/486522875931656193/1072612950747132004/1072688449037025350

And here: https://github.com/storybookjs/storybook/pull/20604#issuecomment-1422226240

**Comment by shilman** [comment]
I vote hiding the stories section when there's just a single story. It doesn't make sense and looks like a bug.

**Comment by shilman** [comment]
Ermahgerd!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.0-beta.54 containing PR #21178 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb@next upgrade --prerelease
```

**Comment by adirzoari** [comment]
@yannbf Hi, what props I need to add in preview.ts to show only docs and not stories?

**Comment by yannbf** [comment]
> @yannbf @JReinhold @shilman Hi, what configuration I need to add to show only docs and not stories?

Do you mean [--docs](https://storybook.js.org/docs/writing-docs/build-documentation#preview-storybooks-documentation)?

**Comment by adirzoari** [comment]
@yannbf  exactly!!! can I build a storybook with only docs and deploy it?

**Comment by yannbf** [comment]
> @yannbf exactly!!! can I build a storybook with only docs and deploy it?

Yes, please read the docs that I shared, it covers that. Also, you please use the https://discord.gg/storybook discord community for more questions, you will probably get better help there!

**Comment by carlos22** [comment]
This is still a problem if you hide the stories from that page via `tags: ["!autodocs"]`.
