### ISSUE TITLE
[Bug]: Next13xStorybook7 "addons__default.setChannel is not a function" when importing stories in tests

### ISSUE THREAD

**Issue by hajimism** [storybookjs/storybook#20971]
### Describe the bug

Thank you for the best product. This tool is essential to my work, but I am having trouble setting up a new project.

Here is what I want to do.
- Develop using Next.js 13 app directory
- Test components using jest, React Testing Library
- Reuse Component Story for those tests

I was able to get the second item without any problems. I mean, I was able to run the following tests as intended.

```ts
import { render } from "@testing-library/react";

describe("test", () => {
  test("First test", async () => {
    const { getByText } = render(<MyComponent />);

    expect(getByText("Hello")).toBeVisible();
  });
});
```

However, the third one caused the bug I am reporting here.

```bash
  Test suite failed to run

    TypeError: addons__default.setChannel is not a function

      3 | setGlobalConfig
      4 | setGlobalConfig(globalStorybookConfig);
    > 5 |
        | ^

      at Object.setChannel (node_modules/@storybook/testing-react/src/index.ts:10:8)
      at Object.<anonymous> (node_modules/@storybook/testing-react/dist/index.js:7:20)
      at Object.<anonymous> (setupSb.ts:5:23)
```

The official docs showed the following workaround, but unfortunately it didn't work for me this time.

> ```js
> import { addons, mockChannel } from '@storybook/addons';
> addons.setChannel(mockChannel());
> ```

### To Reproduce

```shell
This is the very repository that is making the error. Some code is written using Tailwind CSS className, but at this stage I have not installed Tailwind CSS or any other dependencies.

https://github.com/hajimism/next13-storybook7-jest-test
```

### System

```shell
Environment Info:

  System:
    OS: macOS 13.2
    CPU: (10) arm64 Apple M1 Pro
  Binaries:
    Node: 18.12.1 - ~/.volta/tools/image/node/18.12.1/bin/node
    Yarn: 3.3.0 - ~/.volta/tools/image/yarn/3.3.0/bin/yarn
    npm: 8.19.2 - ~/.volta/tools/image/node/18.12.1/bin/npm
  Browsers:
    Chrome: 109.0.5414.119
    Safari: 16.3
  npmPackages:
    @storybook/addon-essentials: ^7.0.0-beta.43 => 7.0.0-beta.43 
    @storybook/addon-interactions: ^7.0.0-beta.43 => 7.0.0-beta.43 
    @storybook/addon-links: ^7.0.0-beta.43 => 7.0.0-beta.43 
    @storybook/blocks: ^7.0.0-beta.43 => 7.0.0-beta.43 
    @storybook/jest: 0.0.11-next.0 => 0.0.11-next.0 
    @storybook/nextjs: ^7.0.0-beta.43 => 7.0.0-beta.43 
    @storybook/react: ^7.0.0-beta.43 => 7.0.0-beta.43 
    @storybook/testing-library: ^0.0.14-next.1 => 0.0.14-next.1 
    @storybook/testing-react: ^1.3.0 => 1.3.0
```

**Comment by zhyd1997** [comment]
the reason is here: 

https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#no-more-default-export-from-storybookaddons

<img width="1048" alt="Screenshot 2023-02-07 at 13 09 49" src="https://user-images.githubusercontent.com/31362988/217153840-7711ccb1-e06b-4988-ad57-da932957bd9e.png">

I have tested that it works on the repro repo above:

<img width="1077" alt="Screenshot 2023-02-07 at 13 11 57" src="https://user-images.githubusercontent.com/31362988/217154114-07902aec-e68a-453f-98be-795502e49041.png">

and submitted a patch PR to [testing-react](https://github.com/storybookjs/testing-react) repo.

but the issue affected other repos: 

https://github.com/search?q=%22import+addons%22+user%3Astorybookjs&type=code&ref=advsearch

<img width="1423" alt="Screenshot 2023-02-07 at 13 15 03" src="https://user-images.githubusercontent.com/31362988/217154542-e72f6546-6c05-4bf7-b993-16aca42664c4.png">

**Comment by hajimism** [comment]
Hi @zhyd1997, thanks for your helpfu comment! I understand the problem. 
I greatly appreciate you showing me the documentation, trying it out on repro, and even creating a PR!

**Comment by zhyd1997** [comment]
Hi @hajimism 

To solve the issue, you need to upgrade your `@storybook/testing-react` library to [v2.0.0-next.0](https://github.com/storybookjs/testing-react/releases/tag/v2.0.0-next.0) Pre-release.

Thanks @IanVS's explanation on Discord.

**Comment by IanVS** [comment]
Thanks @zhyd1997!
