### ISSUE TITLE
[Feature Request]: Add Svelte CSF stories to the template stories in Svelte sandboxes

### ISSUE THREAD

**Issue by JReinhold** [storybookjs/storybook#21043]
### Is your feature request related to a problem? Please describe

Svelte templates doesn't include Svelte CSF stories, which means that isn't tested regularly.

### Describe the solution you'd like

We should add a set of Svelte CSF stories to the sandbox templates.

It will require some mangling of the template (installing the addon, adding the addon to the main.js) but it should be doable.

### Are you able to assist to bring the feature to reality?

yes, I can

**Comment by benmccann** [comment]
It would be really nice if `storybook init` setup `@storybook/addon-svelte-csf`

**Comment by benmccann** [comment]
It looks like `storybook init` has been restructured quite a bit since I last looked at it, but it looks to me like the code now live here:

- https://github.com/storybookjs/storybook/tree/next/code/frameworks/sveltekit/template
- https://github.com/storybookjs/storybook/tree/next/code/frameworks/svelte-vite/template

**Comment by JReinhold** [comment]
I agree @benmccann .

I'm working on a larger Svelte+Storybook RFC that touches on this among other things.
Should be able to publish it later this week.

**Comment by JReinhold** [comment]
Closing in favor of a more holistic discussion at https://github.com/storybookjs/storybook/discussions/27092
