### ISSUE TITLE
[Bug]: Thrown errors unreported

### ISSUE THREAD

**Issue by shilman** [storybookjs/storybook#21318]
### Describe the bug

The following errors are not reported to telemetry even when crash reporting is enabled
- [x] Preview.js syntax errors in builder-webpack 
- [ ] Inside webpackFinal
- [x] Top level of main.js in builder-vite

**Comment by tmeasday** [comment]
@valentinpalkovic I cannot reproduce the issue with `webpackFinal` throwing. In fact that's what I've been doing in the past to check telemetry stuff! Can you share reproduction steps?

**Comment by valentinpalkovic** [comment]
@tmeasday Reproduction is a bit tricky, because of some remaining Storybook bugs, I have to adjust the selected Angular project by hand to make it work first with SB 7.0.

Nevertheless, I have rechecked it and the error got reported when Storybook is being built, but not if the dev server runs. Is this intended?

**Comment by tmeasday** [comment]
> Nevertheless, I have rechecked it and the error got reported when Storybook is being built, but not if the dev server runs. Is this intended?

No, it isn't.

**Comment by shilman** [comment]
Jeepers creepers!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.0-beta.62 containing PR #21416 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb@next upgrade --prerelease
```
