### ISSUE TITLE
[Bug]: Preact - pragma and pragmaFrag cannot be set when runtime is automatic.

### ISSUE THREAD

**Issue by wmonecke** [storybookjs/storybook#21362]
### Describe the bug

Added storybook to a fresh **_preact_** app.

Got the following error after running `yarn storybook`

```bash
[vite] Internal server error: /Users/wmonecke/Documents/Code/fabled/src/stories/Button.stories.jsx: 
pragma and pragmaFrag cannot be set when runtime is automatic.
> 1 |
    | ^
  2 |     /* eslint-disable */
  3 |     // @ts-nocheck
  4 |     // @ts-ignore
  Plugin: vite:preact-jsx
  File: /Users/wmonecke/Documents/Code/fabled/src/stories/Button.stories.jsx
```

**Comment by shilman** [comment]
Do you a have a reproduction repo you can share? If not, can you create one? See [how to create a repro](https://storybook.js.org/docs/react/contribute/how-to-reproduce). I wasn't able to repro with a fresh install. Thank you! 🙏

**Comment by jishidaaaaa** [comment]
I was able to reproduce the same thing by specifying `@storybook/preact-webpack5` in the `framework` of main.js.

Probably because @babel/plugin-transform-react-jsx has `runtime: 'automatic'` enabled in `@storybook/presets-preact-webpack`. 
https://github.com/storybookjs/storybook/blob/ccd32b57deafd8422567b82f8ddbeca68efeda37/code/presets/preact-webpack/src/index.ts#L 14

Would it be better to put the default setting `runtime: 'classic'` and only override the setting if necessary by extending the webpack config?
https://babeljs.io/docs/babel-plugin-transform-react-jsx#:~:text=%22runtime%22%3A%20%22automatic%22%2C%20//%20defaults%20to%20classic
