### ISSUE TITLE
[Bug]: Changes in `preview-head.html` and `preview-body.html` using webpack do not trigger HMR

### ISSUE THREAD

**Issue by valentinpalkovic** [storybookjs/storybook#21445]
### Describe the bug

Reported by @yannbf 

Making changes to preview-head.html and preview-body.html do not trigger HMR. In the same project using Vite builder, they do. Vite also has HMR for manager-head.html 

### To Reproduce

The reporter used this repo: https://github.com/yannbf/mealdrop

**Comment by tmeasday** [comment]
AFAIK, these files have never been HMR-ed by webpack, as they are inlined in the `iframe.html`.

It looks like maybe it works in vite because we invalidate the whole process on every file change (just a guess): 
https://github.com/storybookjs/storybook/blob/0c7d7cc7772f9e7387a19c4ea42de3370bcb60c2/code/lib/builder-vite/src/plugins/code-generator-plugin.ts#L29-L32

To fix this in WP we'd need to setup some kind of file watcher (we have one for the index 🤷) on these files. Feels out of scope for 7.0 if we think it's important.

**Comment by ndelangen** [comment]
Sending HMR updates for preview-head.html is not an intended feature.

If inside there's some `<script />` tag, which is unmanaged, there's no way to undo that work.

**Comment by tmeasday** [comment]
OK! Closing as `WONTFIX`. Not sure if we consider it a bug that Vite updates, but probably an edge case anyways.
