### ISSUE TITLE
[Bug]: The reset controls button appears to be resetting the value back to undefined

### ISSUE THREAD

**Issue by dkrutsko** [storybookjs/storybook#21470]
### Describe the bug

Hello, I'm currently using Storybook `7.0.0-beta.62` with SvelteKit and I'm running into this problem again: https://github.com/storybookjs/storybook/issues/11976. Which occasionally leads to this error in the console: `A component is changing a controlled input to be uncontrolled. This is likely caused by the value changing from a defined to undefined`. Instead of going back to `undefined`, the value should go back to the default specified in `args` or by the `props`.

### To Reproduce

A short example to help illustrate the issue:

### test.svelte
```svelte
<script lang="ts">
	export let prop = 'prop';
</script>

<p>{prop}</p>
```

### test.stories.ts
```ts
import type { Meta, StoryObj } from '@storybook/svelte';

import Test from './test.svelte';

const meta = {
	title: 'Effects/Test',
	tags: [
		'autodocs',
	],

	component: Test,

} satisfies Meta<Test>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Default: Story = {
};
```

### System

```shell
System:
  OS: macOS 12.6
  CPU: (10) arm64 Apple M1 Max
Binaries:
  Node: 18.14.1 - ~/.nvm/versions/node/v18.14.1/bin/node
  Yarn: 1.22.19 - ~/.nvm/versions/node/v18.14.1/bin/yarn
  npm: 9.6.0 - ~/.nvm/versions/node/v18.14.1/bin/npm
Browsers:
  Chrome: 110.0.5481.177
  Firefox: 110.0.1
  Safari: 16.0
npmPackages:
  @storybook/addon-a11y: ^7.0.0-beta.62 => 7.0.0-beta.62
  @storybook/addon-essentials: ^7.0.0-beta.62 => 7.0.0-beta.62
  @storybook/addon-interactions: ^7.0.0-beta.62 => 7.0.0-beta.62
  @storybook/addon-links: ^7.0.0-beta.62 => 7.0.0-beta.62
  @storybook/blocks: ^7.0.0-alpha.8 => 7.0.0-beta.62
  @storybook/manager-api: ^7.0.0-beta.62 => 7.0.0-beta.62
  @storybook/svelte: ^7.0.0-beta.62 => 7.0.0-beta.62
  @storybook/sveltekit: ^7.0.0-beta.62 => 7.0.0-beta.62
  @storybook/testing-library: ^0.0.14-next.1 => 0.0.14-next.1
  @storybook/theming: ^7.0.0-beta.62 => 7.0.0-beta.62
```

**Comment by tmeasday** [comment]
Is there some way we can tell Svelte to go back to the default without needing to know the prop's default value? 

Previously we auto-set the default value of the arg (from the prop) by inferring it ourselves, but that was unreliable and (in most frameworks) if you just reset the arg back to `undefined` it falls back to the component's default. That would be ideal here.

If you set an arg for the story, resetting will go back to that.

**Comment by dkrutsko** [comment]
Yes @tmeasday, this is what I have done. In fact, I went a step beyond, I am storing all the props and their default value in an object which I can import in both the Svelte component itself as well as Storybook. That way I can call my `getDefaultProps` function and destructure it. For me this solution provides more flexibility than just having Svelte define the default values.

However, doing this actually breaks the automatic docs generation of Storybook, meaning that I have to manually add types and default values for each property I'm documenting. It's no problem for me because I prefer to annotate the types manually, however, this is something to be aware of when using my approach.

### props.ts
```ts
export interface Props
{
	role: string;
	ariaLabel: string;
}

export const getDefaultProps = function(): Props
{
	return {
		role: 'img',
		ariaLabel: '',
	};
};
```

### component.svelte
```ts
<script lang="ts">
	import { getDefaultProps } from './props.js';

	const defaults = getDefaultProps();

	export let role = defaults.role;
	export let ariaLabel = defaults.ariaLabel;

...
```

I am investigating to see if I can have those Svelte exported values generated automatically.

**Comment by tmeasday** [comment]
Right, that makes sense, but I agree it has some major drawbacks.

What I was meaning (as someone who knows little to nothing about Svelte) is does Svelte provide APIs to say to a component "revert this prop to it's default". In React you can do this by passing `undefined` to the prop, and following this is why SB does what it does.

Alternatively, is there a way for the Svelte renderer to read the default value off the component class (`Test`)? Because although we've been burnt setting `argType.defaultValue` from *inferred* defaults (inferred by static tooling that runs on your source code), it might be OK to set a default value for an arg from a *runtime* component default (e.g. `Test.defaultProps.prop` in React).

cc @JReinhold who might know some of these answers.

**Comment by JReinhold** [comment]
AFAIK there's no API to "revert to default props" in Svelte, we use the `$set` API to set props, and it doesn't expose such a functionality.
There's also no way to read it from the client-side Component class, as it's not part of that. You can see in this minimal REPL what a Svelte component compiles to:
https://svelte.dev/repl/36d4663297de4dd88e564098a11615f2?version=3.56.0
If you open the "JS Output" tab on the right and go to line 46 you'll see that the default prop is not part of the class but rather inlined in the initialisation function.

The only solution I can think of here is to make the Svelte renderer do a full remount when args are reset. Given that "revert to default" is not even possible in a real Svelte use case, I think that's a fine option. A user would never need to test "what happens if my component gets props reset to defaults but still maintains state" because that's not a possible scenario in Svelte.
I made a REPL to demonstrate this: https://svelte.dev/repl/36d4663297de4dd88e564098a11615f2?version=3.56.0
Resetting the "name" prop to default "world" is only possible by remounting the `Greeter` component via changing the key (similar to React's concept of keys).

However I'm not sure how to remount on reset args in the renderer. From what I can tell in the code, the renderer doesn't know if `renderToCanvas` was called as a result of the `RESET_STORY_ARGS` event, so it would have to listen for that event manually and then trigger a forced remount on it self?

**Comment by tmeasday** [comment]
I think your analysis is right @JReinhold. Perhaps we should patch something like that in for now and work towards a proper `renderToCanvas` API so it's not necessary later? Or we could just wait to fix this properly (via the second method) in 7.1? I'm not sure we should be changing/adding fundamental preview APIs this late in the release cycle.

**Comment by JReinhold** [comment]
Agree, let's do a workaround for now.

In the broader perspective I'm wondering if reseting args should just be always be a force remount, in all renderers. I'm not sure what the case is for "what happens if my component gets props reset to defaults but still maintains state" in any renderer, irregardless of it being possible or not. Except it would be slightly more performant to not remount the whole tree.

**Comment by tmeasday** [comment]
Yeah that makes sense!

**Comment by shilman** [comment]
¡Ay Caramba!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.0-rc.7 containing PR #21659 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb@next upgrade --prerelease
```
