### ISSUE TITLE
Blocks: Fix consistency of `sourceState` in components Canvas and Source

### ISSUE THREAD

**Issue by jrencz** [storybookjs/storybook#21554]
### Is your feature request related to a problem? Please describe

I noticed that components `Canvas` and `Source` from `@storybook/blocks` both have common functionality of controlling how source is shown (props named `sourceState` and `state`), but accepted values are incoherent event though they have essentially the same meaning

`Source` has enum `SourceState`

https://github.com/storybookjs/storybook/blob/8670e1f51e73be15d23640cdb06dc1a57211ca06/code/ui/blocks/src/blocks/Source.tsx#L18-L22

https://github.com/storybookjs/storybook/blob/8670e1f51e73be15d23640cdb06dc1a57211ca06/code/ui/blocks/src/blocks/Source.tsx#L116

while `Canvas` has inline type:

https://github.com/storybookjs/storybook/blob/8670e1f51e73be15d23640cdb06dc1a57211ca06/code/ui/blocks/src/blocks/Canvas.tsx#L69-L76

### Describe the solution you'd like

I think `Canvas` should ultimately adopt `SourceState` enum.

`Canvas` should still accept `shown` and `hidden` - it's already too late to ship such change in sb7, but for sb8 they should IMO have the same api.

### Are you able to assist to bring the feature to reality?

yes, I can

### Additional context

`SourceState is already exported from `@storybook/blocks`, it's descriptive and it's handy to use MDX, to a point where I already used it several times writing:

```mdx
<Canvas of={Stories.SomeStory} sourceState={SourceState.NONE} />
```

which is clearly a coincidence it works - just because both types (enum and inline type) happen to have common `'none'`. 

Just now I tried to set `SourceState.OPEN` on `Canvas` and that's how I found out they are actually different types.

**Comment by JReinhold** [comment]
Thanks Jarek!

I think there's a misunderstanding though. While the `SourceState` enum exists in the `Source` block's file, it's actually not directly used by `Source`, it's only there for the `Canvas` block to use it. That's at least what I can tell from reading the code, the docs and the stories we have for the blocks - but maybe you're seeing something I'm not?

The move from the `SourceState` enum to string-based options in `Canvas` was an intentional, in an effort to simplify the API (and it has been changed from `OPEN|CLOSED|NONE` to `"shown"|"hidden"|"none"` to match the UI wording). The strings are simpler to pass in (you don't have to import anything), and they are still strongly typed for users that care about that.
`SourceState` is still a part of the code because the change is a deprecation and not a breaking one, it will be completely removed in 8.0

**Comment by shilman** [comment]
@JReinhold I'm ok with your solution here. Closing this!
