### ISSUE TITLE
[Bug]: Cannot destructure property 'legacyRootApi' of '(intermediate value)' as it is undefined.

### ISSUE THREAD

**Issue by shilman** [storybookjs/storybook#21632]
### Describe the bug

Vite RC users are reporting the error:

> Cannot destructure property 'legacyRootApi' of '(intermediate value)' as it is undefined.

### To Reproduce

No reproduction available, we'll need to read through the code paths & reverse engineer it.

**Comment by tmeasday** [comment]
@shilman which frameworks? `vite-react` only?

**Comment by tmeasday** [comment]
OK, it was easy to repro in the sandbox:
<img width="326" alt="image" src="https://user-images.githubusercontent.com/132554/225769733-a9e635a7-18df-42ec-8f92-32cb96685ff3.png">

I think it's only happening in vite because `react-webpack5` sets a value for `frameworkOptions`:

https://github.com/storybookjs/storybook/blob/fc28c951e454b1fa1acf81fa9e06b217d265968c/code/frameworks/react-webpack5/src/preset.ts#L15

**Comment by shilman** [comment]
Ooh-la-la!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.0-rc.4 containing PR #21644 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb@next upgrade --prerelease
```

**Comment by kylesuss** [comment]
Thanks @tmeasday -- just ran into this 😄
