### ISSUE TITLE
[Bug]: Decorators causes source snippets in docs to show `<No Display Name />`

### ISSUE THREAD

**Issue by JReinhold** [storybookjs/storybook#21649]
### Describe the bug

If you have a decorator, the source snippet in docs mode will not show the story's source, but instead the decorator with a `<No Display Name />` child.

This bug was likely introduced by https://github.com/storybookjs/storybook/pull/21182, as applying

```
features: {
  legacyDecoratorFileOrder: true,
}
```

makes it work again.

### Additional context

https://chromaticqa.slack.com/archives/C03BNCJ8C7K/p1679047287634789

## v7.0.0-rc.3 - Vite
<img width="1059" alt="image (5)" src="https://user-images.githubusercontent.com/5678122/225904401-89931237-3d34-4632-8ef0-bffaded4486d.png">

## v7.0.0-beta.54 - Vite
<img width="942" alt="image (6)" src="https://user-images.githubusercontent.com/5678122/225904523-321ee51b-ef67-4e20-a372-7fc76fcb515f.png">

## v6.5.9 - CRA
https://5f84c5baa35bdd0022a7684f-mvszeeebuw.chromatic.com/?path=/docs/components-restaurantcard--default
<img width="1023" alt="image (4)" src="https://user-images.githubusercontent.com/5678122/225904276-7b95725b-fee1-46a0-8cd4-f77957ba7415.png">

**Comment by JReinhold** [comment]
We agreed to default `excludeDecorators` to `true` in all renderers (or more likely in the core implementation?), but that wouldn't actually fix this issue, so we'll keep this open, but most likely not Required for GA.

**Comment by tmeasday** [comment]
Here's the PR to do that: https://github.com/storybookjs/storybook/pull/21722

Do we have any idea where this actual issue stems from? It's not correct to say

> This bug was likely introduced by https://github.com/storybookjs/storybook/pull/21182

as I mentioned on #21722, that change actually fixed a bug that you *couldn't* previously see decorators you'd added in `preview.js`, such as the `<Provider>` from Mealdrop above.

The real bug here is why you can't see any deeper inside the provider, and it says `<No Display Name />`. Do we have any idea where that comes from?

In any case, I agree this should be dropped from Required from GA now.

**Comment by tmeasday** [comment]
>  Do we have any idea where that comes from?

Ok, I think the reason is that the decorator in question does something like:

```js
(Story) => <div><Story /></div>
```

I guess React sees the `<Story />` and can't figure out a display name, for whatever reason. But the deeper issue here is that I suppose our JSX decorator doesn't go any further into the element tree than one level. That's fundamentally incompatible with showing decorators isn't it?

If you change the decorator to 
```js
(Story) => <div>{Story()}</div>
```

<img width="433" alt="image" src="https://user-images.githubusercontent.com/132554/226783380-0e2fcc77-8711-4232-a983-42bcbac6d400.png">


It works, but that's not really an idiomatic React decorator.

**Comment by shilman** [comment]
@tmeasday I'm not sure how [react-element-to-jsx-string](https://www.npmjs.com/package/react-element-to-jsx-string) works under the hood & how easy it would be to add recursion support, but it's not a library option so it would be a project to get it working

**Comment by tmeasday** [comment]
OK. I wonder if we should consider dropping the option entirely for React then, given the value of "showing decorators and not the story itself" seems pretty low..

**Comment by tmeasday** [comment]
I think realistically we are not going to update the library to look "inside" React elements, so I would close this as WONTFIX, unless there is a simper fix we can do to change `<No Display Name />` to `<Storybook Decorator />` or something. Thoughts @shilman @JReinhold ?

**Comment by vanessayuenn** [comment]
Closing this as per ☝🏼 , but please let me know if this should be reopened!
