### ISSUE TITLE
[Bug]: Missing `.svelte-kit` directory when starting Storybook in StackBlitz

### ISSUE THREAD

**Issue by tony19** [storybookjs/storybook#21869]
### Describe the bug

When starting up Storybook 7 in StackBlitz, several errors appear, and then it just stops loading. To proceed any further, you have to hit the refresh button within the preview window (not the browser's native refresh button).

*Terminal log*
```
attention => Storybook now collects completely anonymous telemetry regarding usage.
This information is used to shape Storybook's roadmap and prioritize features.
You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
https://storybook.js.org/telemetry

info => Starting manager..
▲ [WARNING] Cannot find base config file "./.svelte-kit/tsconfig.json" [tsconfig.json]

    tsconfig.json:2:12:
      2 │   "extends": "./.svelte-kit/tsconfig.json",
        ╵              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

The following Vite config options will be overridden by SvelteKit:
  - base

 (x2)
Forced re-optimization of dependencies
╭────────────────────────────────────────────────────╮
│                                                    │
│   Storybook 7.0.0 for sveltekit started            │
│   3.46 s for manager and 22 s for preview          │
│                                                    │
│    Local:            http://localhost:6006/        │
│    On your network:  http://192.168.1.104:6006/    │
│                                                    │
╰────────────────────────────────────────────────────╯
12:08:26 PM [vite-plugin-svelte] prebundle libraries in progress ...
12:08:31 PM [vite-plugin-svelte] prebundle libraries done.
package                 files     time     avg
@storybook/svelte           2   99.3ms  49.7ms
12:12:34 PM [vite] Internal server error: failed to resolve "extends":"./.svelte-kit/tsconfig.json" in /home/projects/sveltekit-storybook-bug/tsconfig.json
  Plugin: vite:esbuild
  File: /home/projects/sveltekit-storybook-bug/.storybook/preview.ts
      at resolveExtends (file://file:///home/projects/sveltekit-storybook-bug/node_modules/vite/dist/node/chunks/dep-79892de8.js:13348:9)
      at parseExtends (file://file:///home/projects/sveltekit-storybook-bug/node_modules/vite/dist/node/chunks/dep-79892de8.js:13302:28)
      at parse$f (file://file:///home/projects/sveltekit-storybook-bug/node_modules/vite/dist/node/chunks/dep-79892de8.js:13240:24)
      at async loadTsconfigJsonForFile (file://file:///home/projects/sveltekit-storybook-bug/node_modules/vite/dist/node/chunks/dep-79892de8.js:13800:24)
      at async transformWithEsbuild (file://file:///home/projects/sveltekit-storybook-bug/node_modules/vite/dist/node/chunks/dep-79892de8.js:13487:36)
      at async TransformContext.transform (file://file:///home/projects/sveltekit-storybook-bug/node_modules/vite/dist/node/chunks/dep-79892de8.js:13619:32)
      at async Object.transform (file://file:///home/projects/sveltekit-storybook-bug/node_modules/vite/dist/node/chunks/dep-79892de8.js:43436:30)
      at async loadAndTransform (file://file:///home/projects/sveltekit-storybook-bug/node_modules/vite/dist/node/chunks/dep-79892de8.js:41154:29)
12:12:36 PM [vite-plugin-svelte] prebundle libraries in progress ...
12:12:41 PM [vite-plugin-svelte] prebundle libraries done.
package                 files     time     avg
@storybook/svelte           2   66.5ms  33.2ms
```

*Browser console error*
```
TypeError: Failed to fetch dynamically imported module: https://sveltekitstorybookbug-ggji--6006.local-credentialless.webcontainer.io/.storybook/preview.ts
```

### To Reproduce

See https://stackblitz.com/edit/storybook-7-poor-startup-ux

Steps to reproduce:

 1. Scaffold new SvelteKit project (with TypeScript and no other prompted features):

    ```sh
    npm create svelte@latest my-app
    cd my-app
    npm install
    ```

 2. Add Storybook:

    ```sh
    npx storybook@next init
    ```

 3. Check it into GitHub.
 4. [Import](https://developer.stackblitz.com/guides/user-guide/importing-projects#import-from-github) that repo into StackBlitz.
 5. Start Storybook in StackBlitz terminal.
 6. Observe the errors at startup and then loading stops.
 7. Click the preview window's refresh button.
 8. Observe Storybook starts successfully.

### System

```shell
Environment Info:

  System:
    OS: macOS 12.6.3
    CPU: (8) x64 Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
  Binaries:
    Node: 18.14.2 - ~/n/bin/node
    Yarn: 1.22.19 - ~/n/bin/yarn
    npm: 9.5.0 - ~/n/bin/npm
  Browsers:
    Chrome: 111.0.5563.146
    Safari: 16.3
  npmPackages:
    @storybook/addon-essentials: ^7.0.0 => 7.0.0 
    @storybook/addon-interactions: ^7.0.0 => 7.0.0 
    @storybook/addon-links: ^7.0.0 => 7.0.0 
    @storybook/blocks: ^7.0.0 => 7.0.0 
    @storybook/svelte: ^7.0.0 => 7.0.0 
    @storybook/sveltekit: ^7.0.0 => 7.0.0 
    @storybook/testing-library: ^0.0.14-next.2 => 0.0.14-next.2
```

**Comment by JReinhold** [comment]
Thanks for the detailed bug report.
This is actually strictly not related to StackBlitz, I can recreate it locally too.

What happens is:

1. The SvelteKit starter generates a `tsconfig.json` that extends a `./.svelte-kit/tsconfig.json`
2. This extended file doesn't actually exist, but is generated when the SvelteKit app is "synced", which happens continuously as the app runs and **as part of SvelteKit's `postinstall` script**.
3. However if you start Storybook first, without starting your app, that file might not have been generated, so it's missing.

I think the reason why this is experienced in StackBlitz and not locally, is [because StackBlitz doesn't run `postinstall` scripts after installing dependencies](https://developer.stackblitz.com/platform/webcontainers/turbo-package-manager#install-scripts), so the file won't be generated as it would locally.

StackBlitz own recommendation is to set your `startCommand` to run whatever script you need to run before starting your app, so in this case that would be:

```
// .stackblitzrc
{
  "startCommand": "svelte-kit sync && npm run storybook"
}

```
as implemented successfully in this fork: https://stackblitz.com/edit/storybook-7-poor-startup-ux-v8biht?file=.stackblitzrc


An interesting discussion to have here, is whether Storybook should sync SvelteKit similar to to how the SvelteKit app does it, when it starts and continuously as it changes. I'm not sure if that is even possible, and I'd be afraid if it would create conflicts if the SvelteKit app is running simultaneously with Storybook, a development workflow that is pretty common. I'm curious if @benmccann has any thoughts on this?

**Comment by JReinhold** [comment]
Closing this as there's a workaround for StackBlitz and it's mostly unrelated to Storybook.
