### ISSUE TITLE
[Bug]: ESM imports incompatible with script redirection (circleCI)

### ISSUE THREAD

**Issue by jlowcs** [storybookjs/storybook#21897]
### Describe the bug

We are currently deploying our generated storybook files as a artifacts on circleCI so we can test our doc.

It is working well with storybook 6.x, but it is not working with storybook 7.x anymore.

The reason is the following:
- when loading a script from the generated `index.html` page from the `output.circle-artifacts.com` domain, we are being redirected to a AWS domain (e.g. `circleci-tasks-prod.s3.us-east-1.amazonaws.com`), using a url containing a bunch of query parameters so that the query can return the actual script without an actual authentication
- some of those scripts are ESM scripts being [copied as-is](https://github.com/storybookjs/storybook/blob/4a37372f649e85e7a0c35b0493da016dbb5dee17/code/lib/builder-manager/src/index.ts#L234) from the @storybook dependency files
- since some of the storybook files are importing in a relative manner (e.g. `import xyz from './some-path.mjs`), it results in trying to import from that same AWS domain, but without the necessary query parameters, so we're getting a 403

A solution would be to actually compile those ESM files and transform those paths and rely on webpack's [automatic public path](https://webpack.js.org/guides/public-path/#automatic-publicpath) handling to use the initial url of the script instead of the one after redirection.

### To Reproduce

Hard to reproduce I guess... unless you have access to circleCI.

**Comment by jlowcs** [comment]
I ended up deploying the doc to our own S3 bucket for now, which fixes the issue for us at least.

**Comment by GreenGremlin** [comment]
This is a problem for us because we link to storybook builds in Circle artifacts in our pull requests, upgrading to Storybook breaks this. To fix this Storybook doesn't need to support query params or authentication, they just need to support processing the manager files through webpack, rather than just copying them over as is.

**Comment by ndelangen** [comment]
>  they just need to support processing the manager files through webpack, rather than just copying them over as is

yeah.. that's not happening, because:

- webpack is slow, we want to depend as little on it as we can.
- webpack is no longer the default, newer faster builders/bundlers are now gaining more traction.
- a lot of storybook users never use webpack.

I'd be happy to listen to your ideas to bring this feature back to storybook 7.0 in some way.

I've also forwarded this issue's link to some fine folks at CircleCI support.

**Comment by ndelangen** [comment]
I also reported here:
https://discuss.circleci.com/t/storybook-7-wont-work-as-a-circleci-artifact/47977

**Comment by jerdog** [comment]
We have added proxying of Javascript artifacts, and everything should be good now!
https://discuss.circleci.com/t/storybook-7-wont-work-as-a-circleci-artifact/47977/6?u=jerdog

https://output.circle-artifacts.com/output/job/4f1c0e54-94ef-47cd-9a39-d802471dc12f/artifacts/0/storybook-static/index.html

**Comment by ndelangen** [comment]
@jlowcs I will close this issue as this is fixed upstream in CircleCI.

A big thank you to the CircleCI team! 🎉
