### ISSUE TITLE
[Bug]: Storybook command not found

### ISSUE THREAD

**Issue by rishabhmehta** [storybookjs/storybook#22002]
### Describe the bug

I installed storybook in both react and next.js project using yarn & npm package manager. But when I run yarn storybook or npm run storybook I get this error 

> my-app@0.1.0 storybook
> start-storybook -p 6006 -s public

sh: start-storybook: command not found

I tried installing storybook separately as a global module. 
I also tried to run the script as npx start-storybook -p 6006 -s public

and I keep getting the same error mentioned above. 

Is it the issue in the latest version@7?

**Comment by KarafiziArtur** [comment]
Now they removed `start-storybook` and added `storybook dev` so you can use `storybook dev -p 6006 -s public`

**Comment by KarafiziArtur** [comment]
Please double check [Migration guide](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

**Comment by godzzo** [comment]
I have installed storybook with `npx storybook init` command as the [Install Storybook](https://storybook.js.org/docs/react/get-started/install/) stated. 

But you should install with `npx storybook@latest init`, then you have the proper scripts in your package.json file.

Should be fixed in the documentation.

**Comment by rishabhmehta** [comment]
It works! thanks @godzzo @KarafiziArtur
