### ISSUE TITLE
[Bug]: Angular services used before constructor (DI) not working in Storybook 7

### ISSUE THREAD

**Issue by Yanduz** [storybookjs/storybook#22185]
### Describe the bug

Angular 15.2.6
NX 15.9.2
NX Storybook 15.9.2
Storybook 7.0.6

Error...
<img width="1511" alt="image" src="https://user-images.githubusercontent.com/27006337/233379524-50d0582f-e20e-4606-9cc5-12f32d9a3317.png">
<img width="1547" alt="image" src="https://user-images.githubusercontent.com/27006337/233382985-12e8a248-aa7e-4520-93fb-425d4c0cabee.png">

Working
<img width="1524" alt="image" src="https://user-images.githubusercontent.com/27006337/233382723-a05f2b18-f638-407b-9753-ff4b8914ac77.png">

### System

```shell
Environment Info:

  System:
    OS: macOS 12.4
    CPU: (8) arm64 Apple M1 Pro
  Binaries:
    Node: 16.18.1 - /usr/local/bin/node
    Yarn: 3.3.1 - /usr/local/bin/yarn
    npm: 8.19.2 - /usr/local/bin/npm
  npmPackages:
    @storybook/addon-docs: 7.0.6 => 7.0.6 
    @storybook/addon-essentials: 7.0.6 => 7.0.6 
    @storybook/addon-mdx-gfm: 7.0.6 => 7.0.6 
    @storybook/addon-postcss: ^2.0.0 => 2.0.0 
    @storybook/angular: 7.0.6 => 7.0.6 
    @storybook/blocks: 7.0.6 => 7.0.6 
    @storybook/core: ^6.5.16 => 6.5.16 
    @storybook/theming: ~7.0.6 => 7.0.6
```

**Comment by valentinpalkovic** [comment]
Hi @Yanduz,

please provide a minimal production, either by sharing a repro or by creating a stackblitz repro: https://new-storybook.netlify.app/

**Comment by Marklb** [comment]
I haven't looked at how to fix this, but a workaround is to set the `module` or `target` to `ES2020` in `.storybook/tsconfig.json` or whichever tsconfig is getting used for your Storybook. I had this problem in my library, but not my apps.

My understanding is that the way constructor props are hoisted, Typescript used to move them to the top and before the `super` call, but now follow how js does it. I will try to find where I read an explanation of the change, because I should have it somewhere. I am not sure why Storybook has the problem, since we are using the Angular builder though.

**Comment by Adrii77** [comment]
Hey, same issue here (Angular 15.2.8 / Storybook: 7.0.10).

I tried @Marklb 's solution and it worked.
