### ISSUE TITLE
[Feature Request]: Re-allow or ease hosting of static build

### ISSUE THREAD

**Issue by mat100payette** [storybookjs/storybook#22564]
### Is your feature request related to a problem? Please describe

As of v7, it seems to be no longer possible to host the static build output as a a regular html file. The reasons mentioned are that it's a consequence of the usage of esm files. Correct me if I'm wrong there.

In our ci/cd, each branch generates and publishes its own static build so that non-devs can easily view the resulting changes online and compare between branches. Now, from what I understood, we are required to host the new output as an app. This has pretty big implications in terms of infrastructure work for us and really isn't justified by any significant advantage from the upgrade to v7.

### Describe the solution you'd like

Optimally, we would like to not have to change anything to how our builds are made available online. Any way to transform the current output to some plain static files like v6 had would be great.

### Describe alternatives you've considered

The only alternative we have at the moment is not upgrading Storybook.

### Are you able to assist to bring the feature to reality?

no

**Comment by shilman** [comment]
When we released SB7 we generated `.mjs` ESM files for our Storybook UI code. This caused issues with hosting on a variety of platforms including Nginx, S3, Github pages, and so forth. Starting in https://github.com/storybookjs/storybook/releases/tag/v7.0.8 we updated those files so they now have the `.js` extension, and I believe that problem has been solved completely.

There is a second issue, which is whether you can open Storybook's `index.html` file directly in a browser from the file system. This hasn't been fixed and we don't plan to fix it. We are using `<script type="module">` in our HTML now, and this works fine when the URL is an `http`/`https`. However, when the URL is `file://` then browsers refuse to load these scripts. I don't know the rationale for why the browsers don't load ESM for file URLs, but presumably there are security concerns which don't happen in HTTP. We don't plan to step away from ESM.

Hopefully you are concerned about the former problem and it is fixed in the latest versions of SB7!

**Comment by shilman** [comment]
Closing this for now. Please reopen if we need to do any followup here!
