### ISSUE TITLE
[Feature Request]: Add tags to postRender context

### ISSUE THREAD

**Issue by unional** [storybookjs/storybook#22775]
### Is your feature request related to a problem? Please describe

Currently, when using snapshot testing,
for stories that I would like to skip,
I have to use an ID hack:

```ts
// story
export const SomeStory_SkipSnap = ...

// .storybook/test-runner.ts
export default {
  async postRender(page, context) {
    if(!/-skip-snap$/.test(context.id) {
      // snapshot test
    }
  }
}
```

### Describe the solution you'd like

Adding `tags` to `context`:

```ts
// story
export const SomeStory = {
  tags: ['skip-snapshot'],
  ...
}

// .storybook/test-runner.ts
export default {
  async postRender(page, context) {
    if (!context.tags.includes('skip-snapshot')) {
      // snapshot test
    }
  }
}
```

This allows cascade config

```ts
// preview.tsx
export const tags = ['skip-snapshot'] // skip snapshot by default

// story meta
export default {
  tags: [] // enable snapshot for all stories in this file
}

// story
export const Story = {
  tags: ['skip-snapshot'] // except this one
}
```

### Describe alternatives you've considered

Continue to use the current workaround

### Are you able to assist to bring the feature to reality?

yes, I can

**Comment by shilman** [comment]
This sounds great. Any interest in opening a PR on the Test Runner to add it? https://github.com/storybookjs/test-runner

There's a little bit of work to do to wire up tags since the test runner works by either (1) statically transforming the CSF source, which has tags, or (2) running off the story index (index.json), which also has tags.

Happy to review the PR if you make it or give help in the `#contributing` channel on the Storybook Discord https://discord.gg/storybook

**Comment by unional** [comment]
This is now supported:

```js
import { getStoryContext } from '@storybook/test-runner'

export async postRender(page, context) {
  const storyContext = await getStoryContext(page, context)
  
  if (storyContext.tags.every(t => t !== 'skip-snapshot') {
    // test snapshot
  }
}
```

```ts
const StoryToSkipSnapshot = {
  tags: ['skip-snapshot']
  ...
}
```
