### ISSUE TITLE
[Bug]: Stories are not sorted by their exports when Webpack is v5.76.0

### ISSUE THREAD

**Issue by dkilgore-eightfold** [storybookjs/storybook#22804]
### Describe the bug

Upgrade from Webpack 5.64.4 to 5.76.0 causes stories to be sorted alphabetically, rather than by order exported.

### To Reproduce

Repro branch via Dependabot PR --> https://github.com/EightfoldAI/octuple/pull/564

- Launch Terminal or CMD
- Ensure you're using Node 16.14.2
- Clone the PR branch
- run `yarn`, and `yarn storybook`
- Visit localhost port 2022

**Comment by dkilgore-eightfold** [comment]
@tmeasday Repro above, logged from https://github.com/storybookjs/storybook/issues/15574#issuecomment-1552279664.

**Comment by tmeasday** [comment]
@dkilgore-eightfold this project is on 6.5 so I would encourage you to try it out on 7.0, where the babel handling has changed quite a bit.

The issue comes from the lack of `babel-plugin-named-exports-order`. When I run `yarn storybook --debug-webpack` in the project I don't see that babel plugin which I would have expected.

**Comment by dkilgore-eightfold** [comment]
@tmeasday I'll add this babel dep and push an update to this dependabot PR branch.

**Comment by dkilgore-eightfold** [comment]
@tmeasday I've updated the Dependabot PR using the recommended exports plugin. Works a treat.

**Comment by shilman** [comment]
Glad to hear you got it sorted! 🎉 Closing this for now. Please let me know if there's more to be done.
