### ISSUE TITLE
[Bug]: `args` types incorrectly make `() => void` properties optional

### ISSUE THREAD

**Issue by aaronadamsCA** [storybookjs/storybook#23068]
### Describe the bug

In this example, the second story should complain that property `onClick` is missing, but this doesn't happen. The types change the required `onClick` method to an optional method.

```tsx
import { action } from "@storybook/addon-actions";
import type { Meta, StoryObj } from "@storybook/react";
import type { ReactElement } from "react";
import * as React from "react";

interface BoxProps {
  className: string;
  onClick: () => void;
}

export function Box(props: BoxProps): ReactElement {
  return <div {...props}>Test</div>;
}

const meta = {
  component: Box,
} satisfies Meta<typeof Box>;

export default meta;

type Story = StoryObj<typeof meta>;

export const ThisWorksAsExpected: Story = {
  // @ts-expect-error -- Property `className` is missing
  args: {
    onClick: () => action("Box click")(),
  },
};

export const ThisDoesNot: Story = {
  // @ts-expect-error -- Property `onClick` is missing
  args: {
    className: "box",
  },
};
```

### To Reproduce

Here you can see the second `@ts-expect-error` flagged as unused:

https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgQwMY2BAdnAvnAMyghDgCIABAZxmgE8AjCCAawHpkATT7AWjQzYqZANwAoUJFhwYdMAFNEcALLyYyADRwAyrSh0A8gwBWeQsVKUa9JqzZR5A0RPDR4shUoBKj9AFEAG3kQeSx4fCIScgcncUk3OAAqFCo4HwFzKLIY9GcJMPkoAjRFACEIAA8ABWIwVIQxODhUAOQqKgA5ZBCALjgaKGAsAHNxJuwAYQDgVBY+gAoASjgAXgA+OAA3CGBOcVwxMXkKqXgCAFcsdEwccor5sFqqPruaiDrFvvT-IJCwxEacAcMHOUBwAB5OMBNogAHTwx7vKi4NYAFXkNHBbChmzW+0OqCE8BC6lWAKahNcWFCMBelQ0YnwVGQGCoBGAGJUamQ4I88ggBDgdzxh2OpzgnHkxXOAWJ3PEYj5Oj0dDJunoRmMvLk-MFJOQIqOJwShKwNDgqIAFsAqAB1aAsKgAQSofhO8nQ8k4fXV+jJDSabDYcAoMCovDFHpgEagxCgcF4vDgbwUsFVAAMWm1Ot15Om4Da4CAbVQhsNAcgoMNnuSmnBJtNZgtlusUNdsPMyHdmo2WGRFksGU1cAzcAqxSaiRbrVQACIQDEdCC05X0f2AoMhsMR93oGNxhNJlOFWRwdMNmYsfOF4vtMsVqs1gN1rPtLq9chMCpkId4UfiIA

### System

```shell
$ pnpm exec tsc -v        
Version 5.1.3
$ pnpm exec storybook info

Environment Info:

  System:
    OS: Linux 5.15 Ubuntu 22.04.2 LTS 22.04.2 LTS (Jammy Jellyfish)
    CPU: (4) x64 Intel(R) Xeon(R) Platinum 8370C CPU @ 2.80GHz
  Binaries:
    Node: 18.16.0 - /usr/local/share/nvm/versions/node/v18.16.0/bin/node
    npm: 9.5.1 - /usr/local/share/nvm/versions/node/v18.16.0/bin/npm
  npmPackages:
    @storybook/addon-a11y: 7.0.20 => 7.0.20 
    @storybook/addon-actions: 7.0.20 => 7.0.20 
    @storybook/addon-essentials: 7.0.20 => 7.0.20 
    @storybook/addon-styling: 1.1.0 => 1.1.0 
    @storybook/blocks: 7.0.20 => 7.0.20 
    @storybook/react: 7.0.20 => 7.0.20 
    @storybook/react-webpack5: 7.0.20 => 7.0.20
```

**Comment by sookmax** [comment]
It seems like a provided prop only becomes optional if the prop is a function with the signature `() => void`. Any other function signature such as `() => string` or `() => number[]` seems not affected (i.e., not made optional) inside `args` prop of `Story` type. [(TS Playground)](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgQwMY2BAdnAvnAMyghDgCIABAZxmgE8AjCCAawHpkATT7AWjQzYqZANwAoUJFhwYdMAFNEcALLyYyADRwAyrSh0A8gwBWeQsVKUa9JqzZR5A0RPDR4shUoBKj9AFEAG3kQeSx4fCIScgcncUk3OAAqFCo4HwFzKLIY9GcJMPkoAjRFACEIAA8ABWIwVIQxODhUAOQqKgA5ZBCALjgaKGAsAHNxJuwAYQDgVBYARj6ACgBKOABeAD44ADcIYE4xuEnp2YAmJdXNuCwAVxAGQsPjmZYAZgv1rYGh0cajrCmLwALB8rrYgsgsE8AScWABWUFbW73QoAbQAutDAbMAGyIxC4MSEsTyCpSeAEG5YdCYHDlCqLMC1Kh9ek1CB1ZZ9dL+IIhMKIP4OGA3KA4AA8nGA20QADp5UyOVRcBsACryGjithS7YbcTE1BCeAhdTrQVNQ2uLChGCsyoaIn9ZAYKgEYAalRqZDijzyCAEOD0vViElkhKceTFG4BY1e8RiX06PR0M26ehGYw+uR+gMm5DB0Pk5pGuCqgAWwCoAHVoCwqABBKh+MnydDyTh9NP6M0NJrIKDDFnmprNVrtLq9chMCpkP64B24eOkouGrA0UsVqgAEQgGo6EFtSfoPb+-cHfV7I5abU63XkfTI07IDqa86JIiAA)

I don't know much about the underlying `StoryAnnotations` type, but a quick inspection got me thinking that `SetOptional` and `ActionArgs` might be the cause here. Specifically, it seems like a provided prop `P` gets made optional if `((...args: any[]) => void) extends TArgs[P]` is true? 

@kasperpeulen, hey sorry for alpha-mentioning you, but I see you worked on this part the latest (through GitLens) so maybe you could shed some lights on this issue?

**Comment by kasperpeulen** [comment]
@sookmax and @sookmax 
Yes, this is by design!

```ts
type ActionArgs<TArgs> = {
  // This can be read as: filter TArgs on functions where we can assign a void function to that function.
  // The docs addon argsEnhancers can only safely provide a default value for void functions.
  // Other kind of required functions should be provided by the user.
  [P in keyof TArgs as TArgs[P] extends (...args: any[]) => any
    ? ((...args: any[]) => void) extends TArgs[P]
      ? P
      : never
    : never]: TArgs[P];
};
```

So it is marked optional, because we provide a default value (that logs to the action panel) for those actions, so that you don't have to do that yourself.

If the function is not void, our default function mock, will be not be typesafe, so therefore, they are still required.

**Comment by kasperpeulen** [comment]
> This feels like the kind of thing Storybook has moved away from lately in favour of more consistent explicit behaviours.

@aaronadamsCA Agreed, we are working on a RFC to address those concerns, I will post it here, when it is done!

**Comment by aaronadamsCA** [comment]
Awesome, thanks. In the meantime I'm closing this, since it's not a bug, just a little surprise.

**Comment by kasperpeulen** [comment]
RFC is out @aaronadamsCA @sookmax :
https://github.com/storybookjs/storybook/discussions/23649
