### ISSUE TITLE
[Bug]: Not working with Transloco (Angular)

### ISSUE THREAD

**Issue by MickL** [storybookjs/storybook#23130]
### Describe the bug

Storybook doesn't seem to work with Transloco anymore. I created a new repo with Angular, Transloco and Storybook on latest version and I always get the error:

>  NullInjectorError: No provider for InjectionToken TRANSLOCO_TRANSPILER!

My story:

```
import type {Meta, StoryObj} from '@storybook/angular';
import {SomeComponent} from '../app/some/some.component';
import {moduleMetadata} from '@storybook/angular';
import {TranslocoRootModule} from '../app/transloco-root.module';

const meta: Meta<SomeComponent> = {
  component: SomeComponent,
  decorators: [
    moduleMetadata({
      imports: [TranslocoRootModule],
    }),
  ],
};

export default meta;
type Story = StoryObj<SomeComponent>;

export const Some: Story = {
  render: () => ({
    props: {
      label: 'SomeComponent',
      primary: true,
    },
  }),
};
```

### To Reproduce

Minimal reproduction repository:
https://github.com/MickL/transloco-issues

### System

```shell
Environment Info:

  System:
    OS: macOS 13.3.1
    CPU: (12) arm64 Apple M2 Max
  Binaries:
    Node: 20.3.0 - ~/.nvm/versions/node/v20.3.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v20.3.0/bin/yarn
    npm: 9.6.7 - ~/.nvm/versions/node/v20.3.0/bin/npm
  Browsers:
    Chrome: 113.0.5672.92
    Firefox: 113.0.2
    Safari: 16.4
  npmPackages:
    @storybook/addon-essentials: ^7.0.22 => 7.0.22 
    @storybook/addon-interactions: ^7.0.22 => 7.0.22 
    @storybook/addon-links: ^7.0.22 => 7.0.22 
    @storybook/angular: ^7.0.22 => 7.0.22 
    @storybook/blocks: ^7.0.22 => 7.0.22 
    @storybook/testing-library: ^0.0.14-next.2 => 0.0.14-next.2
```

**Comment by valentinpalkovic** [comment]
@MickL Have you followed the migration guide around `applicationProvider`, which is described [here](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#angular-application-providers-and-modulewithproviders)?

**Comment by valentinpalkovic** [comment]
Hi @MickL,

Thank you for providing the reproduction. I have tweaked it a bit but before jumping into the changes, I would like to explain, what I did.

In Storybook we use the new [bootstrapApplication API](https://angular.io/api/platform-browser/bootstrapApplication) to mount your component to the DOM. Because of this, application-wide providers has to be registered differently in comparison to how you would do it with `NgModules`. Application-wide/Environment-wide providers have to be passed to the bootstrapApplication function like this:

```ts
await [bootstrapApplication](https://angular.io/api/platform-browser/bootstrapApplication)(RootComponent, {
  providers: [
    {provide: BACKEND_URL, useValue: 'https://yourdomain.com/api'}
  ]
});
```

As you might read it in the migration docs, you can pass your provider to the `bootstrapApplication` function by using the `applicationConfig` helper function from `@storybook/angular`:

```tsx
import { applicationConfig } from '@storybook/angular';

const meta: Meta<SomeComponent> = {
  component: SomeComponent,
  decorators: [
    applicationConfig({
      providers: [
        ...
      ],
    }),
  ],
};
```

Angular itself provides a helper method ([importProvidersFrom](https://angular.io/api/core/importProvidersFrom)) to extract all providers from a NgModule. What you have to know is, that registered modules of your `TranslocoRootModule` are NOT registered. Only the providers are extracted. Because of that, `TranslocoModule` is not available in the Storybook environment, if you just do something like this:

```tsx
import type {Meta, StoryObj} from '@storybook/angular';
import {SomeComponent} from '../app/some/some.component';
import {applicationConfig} from '@storybook/angular';
import {TranslocoRootModule} from '../app/transloco-root.module';
import {importProvidersFrom} from '@angular/core';

const meta: Meta<SomeComponent> = {
  component: SomeComponent,
  decorators: [
    applicationConfig({
      providers: [
        // Only providers are extracted. TranslocoModule itself doesn't get registered.
        importProvidersFrom(TranslocoRootModule),
      ],
    }),
  ],
};

export default meta;
type Story = StoryObj<SomeComponent>;

export const Some: Story = {...};

```

Luckily, we can fix this. As far as I can see, your application doesn't use the new Standalone API to bootstrap your Angular component to the DOM. Instead, your application still relies on NgModules. And that's fine. You don't have to change this. But what you have to keep in mind is that Storybook uses the Standalone API to mount your component to the DOM. Therefore, you have to follow this guide: https://ngneat.github.io/transloco/docs/getting-started/installation#standalone-setup to setup Transloco for Storybook.

1. First of all make sure to install the latest version of `@ngneat/transloco` (4.3.0)
2. Follow the linked standalone-setup guide for Transloco. Your `Some.stories.ts` should look like this:

```tsx
// Some.stories.ts
import { Meta, StoryObj, moduleMetadata } from '@storybook/angular';
import { SomeComponent } from '../app/some/some.component';
import { applicationConfig } from '@storybook/angular';
import {
  TranslocoHttpLoader,
  translocoConf,
} from '../app/transloco-root.module';
import { provideHttpClient } from '@angular/common/http';
import { TranslocoModule, provideTransloco } from '@ngneat/transloco';

const meta: Meta<SomeComponent> = {
  component: SomeComponent,
  decorators: [
    moduleMetadata({
      imports: [TranslocoModule],
    }),
    applicationConfig({
      providers: [
        provideHttpClient(),
        provideTransloco({
          config: translocoConf,
          loader: TranslocoHttpLoader,
        }),
      ],
    }),
  ],
};

export default meta;
type Story = StoryObj<SomeComponent>;

export const Some: Story = {
  render: () => ({
    props: {
      label: 'SomeComponent',
      primary: true,
    },
  }),
};
```

I have also adjusted `transloco-root.module.ts` to reuse the configuration of Transloco in Storybook and to avoid duplicate code:

```tsx
// transloco-root.module.ts
import { HttpClient } from '@angular/common/http';
import {
  TRANSLOCO_LOADER,
  Translation,
  TranslocoLoader,
  TRANSLOCO_CONFIG,
  translocoConfig,
  TranslocoModule,
} from '@ngneat/transloco';
import { Injectable, isDevMode, NgModule } from '@angular/core';

@Injectable({ providedIn: 'root' })
export class TranslocoHttpLoader implements TranslocoLoader {
  constructor(private http: HttpClient) {}

  getTranslation(lang: string) {
    return this.http.get<Translation>(`/assets/i18n/${lang}.json`);
  }
}

export const translocoConf = translocoConfig({
  availableLangs: ['en', 'de'],
  defaultLang: 'en',
  // Remove this option if your application doesn't support changing language in runtime.
  reRenderOnLangChange: true,
  prodMode: !isDevMode(),
});

@NgModule({
  exports: [TranslocoModule],
  providers: [
    {
      provide: TRANSLOCO_CONFIG,
      useValue: translocoConf,
    },
    { provide: TRANSLOCO_LOADER, useClass: TranslocoHttpLoader },
  ],
})
export class TranslocoRootModule {}
```

Then we are almost there. Let's fix the typo in `src/assets/i18n/en.json`:

```json
// en.json
{
  "text2": "Text 2 in English",
  "text1": "Text 1 in English"
}
```

And finally we have to tell storybook to make the assets folder public:

```json
// angular.json
{
  ...
  "projects": {
         ...
        "storybook": {
          "options": {
             ...
            "assets": [
              "src/favicon.ico",
              "src/assets"
            ],
          }
        },
        "build-storybook": {
           ...
          "options": {
             ...
            "assets": [
              "src/favicon.ico",
              "src/assets"
            ],
          }
        }
      }
    }
  }
}
```

After following all the steps you are able to run the example as expected. I have also created a PR with all the described changes: https://github.com/MickL/transloco-issues/pull/1

Hopefully, this helps :)

**Comment by MickL** [comment]
@valentinpalkovic Thanks for your very detailed answer! All this things make sense now. I still have another issue, tho and a few notes:

- I feel like the Storybook Angular docs are still missing out tons of informations. For example that Storybook is now using the new standalone feature is not described [here](https://storybook.js.org/docs/angular/writing-stories/introduction), instead it showcases how to import modules the NgModule way. Personally I would have appreciated an information directly on the [introduction](https://storybook.js.org/docs/angular/writing-stories/introduction) page.
- Further I am not sure if it was too early to go over to standalone apps? For example Transloco still has an [open issue ](https://github.com/ngneat/transloco/issues/614) to support standalone apps.

Anyhow I do have another issue that is not documented by Transloco: I also need to add the Transloco Locale Module which doesnt have a standalone doc. How may I do that? `importProvidersFrom(TranslocoLocaleModule)` doesnt seem to work and I also need to set options into the .forRoot function:

```
imports: [
    ...
    TranslocoLocaleModule.forRoot({
      langToLocaleMapping: {
        en: 'en-US',
        de: 'de-DE'
      }
    }),
  ],
```

**Comment by valentinpalkovic** [comment]
Hey @MickL,

Thank you for your feedback. I appreciate it. You are totally right. The angular docs are currently not in good shape, but currently, we are updating them. @jonniebigodes Can we add more information to the introduction page, like mentioned above?

> Further I am not sure if it was too early to go over to standalone apps?

That's indeed a valid question. Switching to the standalone apps API not only allowed us to keep up to date with how Angular wants to proceed in the future, but switching from ngModules to standalone components internally made it possible fix some crucial bugs, especially which occurred on docs pages.

To address the Transloco Locale Module issue. I think the right thing to do would be to pass the whole `TranslocoLocaleModule.forRoot({...}) to `importProvidersFrom`:

```tsx
applicationConfig({
  providers: [
    importProvidersFrom(
      TranslocoLocaleModule.forRoot({
        langToLocaleMapping: {
          en: 'en-US',
          de: 'de-DE'
        }
      })
    )
  ]
})
```

**Comment by MickL** [comment]
importProvidersFrom() + importing the module worked
