### ISSUE TITLE
[Bug]: Parameter docs.autodocs = false not working

### ISSUE THREAD

**Issue by stevus** [storybookjs/storybook#23769]
### Describe the bug

**NOTE:** This is an additional repro of this closed bug report:

https://github.com/storybookjs/storybook/issues/21920

FYI @stefano24

### Packages

```
"dependencies": {
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "vite": "^4.4.7"
  },
  "devDependencies": {
    "@storybook/addon-a11y": "^7.1.0",
    "@storybook/addon-essentials": "^7.1.0",
    "@storybook/addon-interactions": "^7.1.0",
    "@storybook/addon-links": "^7.1.0",
    "@storybook/blocks": "^7.1.0",
    "@storybook/builder-vite": "^7.1.0",
    "@storybook/react": "^7.1.0",
    "@storybook/react-vite": "^7.1.0",
    "@storybook/testing-library": "^0.2.0",
    "storybook": "^7.1.0"
  }
```

### Expected

I want to hide all the "Docs" autogenerated files on the sidebar.

From the [documentation](https://storybook.js.org/docs/react/writing-docs/autodocs#configure) I can set:

```
docs: {
       autodocs: false,
},
```

### Unexpected

But It's not working. The docs files always exists.

### To Reproduce

https://github.com/stevus/storybook-autodocs-false-repro

```
npm i
npm run storybook
```

![image](https://github.com/storybookjs/storybook/assets/1261603/4451199e-772b-404d-9ce2-28bcb71f9265)

This is the single story:

https://github.com/stevus/storybook-autodocs-false-repro/blob/master/jsx/SampleStory.stories.mdx

```
import { Meta, Story } from '@storybook/addon-docs'
import App from './App'

<Meta title='App' component={App} />

<Story
  name='App'>
  <App />
</Story>
```

main.js file:

https://github.com/stevus/storybook-autodocs-false-repro/blob/master/%40storybook/main.js

```
module.exports = {
  addons: [
    '@storybook/addon-links',
    '@storybook/addon-controls',
    '@storybook/addon-a11y',
    '@storybook/addon-essentials',
    '@storybook/addon-interactions',
  ],
  docs: {
    autodocs: 'false',
  },
  features: {
    postcss: false,
  },
  framework: {
    name: '@storybook/react-vite',
    options: {},
  },
  stories: ['../jsx/**/*.stories.mdx', '../stories/**/*.stories.mdx'],
}
```

### System

```shell
Environment Info:

  System:
    OS: Linux 5.15 Ubuntu 22.04.3 LTS 22.04.3 LTS (Jammy Jellyfish)
    CPU: (16) x64 Intel(R) Core(TM) i9-10885H CPU @ 2.40GHz
  Binaries:
    Node: 16.20.1 - /usr/bin/node
    npm: 8.19.4 - /usr/bin/npm
  npmPackages:
    @storybook/addon-a11y: ^7.2.1 => 7.2.1
    @storybook/addon-essentials: ^7.2.1 => 7.2.1
    @storybook/addon-interactions: ^7.2.1 => 7.2.1
    @storybook/addon-links: ^7.2.1 => 7.2.1
    @storybook/blocks: ^7.2.1 => 7.2.1
    @storybook/builder-vite: ^7.2.1 => 7.2.1
    @storybook/react: ^7.2.1 => 7.2.1
    @storybook/react-vite: ^7.2.1 => 7.2.1
    @storybook/testing-library: ^0.2.0 => 0.2.0
```
```


### Additional context

_No response_

**Comment by stevus** [comment]
has anyone seen this?

**Comment by stilt0n** [comment]
I think this has to do with the story being `.mdx`.

[There's some code in StoryIndexGenerator (in `@storybook/core-server`) that decides if a docs entry should be created:](https://github.com/storybookjs/storybook/blob/next/code/lib/core-server/src/utils/StoryIndexGenerator.ts#L337)
```ts
/* Lines 330 - 338 */
const { autodocs } = this.options.docs;
// We need a docs entry attached to the CSF file if either:
//  a) autodocs is globally enabled
//  b) we have autodocs enabled for this file
//  c) it is a stories.mdx transpiled to CSF
const hasAutodocsTag = entries.some((entry) => entry.tags.includes(AUTODOCS_TAG));
const isStoriesMdx = entries.some((entry) => entry.tags.includes(STORIES_MDX_TAG));
const createDocEntry =
  autodocs === true || (autodocs === 'tag' && hasAutodocsTag) || isStoriesMdx;
```
Assuming this is a bug, the last check should be `|| isStoriesMdx && autodocs !== false`.
  
I haven't looked into if there would be other places to change.
  
If it's intentional it might be worth documenting somewhere that setting autodocs to false is intended to have no effect in this situation. The closest I can see is in this section in the MIGRATION.md, but I'm not sure.

**Comment by JReinhold** [comment]
@stilt0n is right, this is because the stories are defined in a `*.stories.mdx` file, and not `*.stories.js`. It's intentional that `*.stories.mdx` always generate docs entries, so changing it would be a breaking change.

If you wish to have stories without Docs entries I suggest you write them in CSF instead of MDX.

We could document this here: https://storybook.js.org/docs/react/writing-docs/autodocs#configure but given that Stories MDX is deprecated and AFAIK not documented anywhere anymore, I'm not sure it would make sense. Thoughts @kylegach ?

**Comment by stevus** [comment]
is there a MDX to CSF codemod? it’s unfortunate because I have a ton of MDX stories that will need to be converted.

**Comment by shilman** [comment]
@stevus yes there is. we describe it in the upgrade guide here: https://storybook.js.org/docs/react/migration-guide#storiesmdx-to-mdxcsf

**Comment by kylegach** [comment]
> We could document this here: [storybook.js.org/docs/react/writing-docs/autodocs#configure](https://storybook.js.org/docs/react/writing-docs/autodocs#configure) but given that Stories MDX is deprecated and AFAIK not documented anywhere anymore, I'm not sure it would make sense. Thoughts @kylegach ?

Agreed that doesn't make sense, @JReinhold.
