### ISSUE TITLE
[Bug]: TypeError: _storybook_addons__WEBPACK_IMPORTED_MODULE_0__.addons.setConfig is not a function

### ISSUE THREAD

**Issue by ashrah38** [storybookjs/storybook#24048]
### Describe the bug

After upgrading to Storybook v7 and running the auto migrate tool, I have come across the following error,
`TypeError: _storybook_addons__WEBPACK_IMPORTED_MODULE_0__.addons.setConfig is not a function`

I have seen some other people run into a similar error for `addons.setChannel` but that was due to no more default exports from `@storybook/addons`.

These are my import statements:
![image](https://github.com/storybookjs/storybook/assets/66855296/f68d43d3-c463-4eba-9f26-baa9b37a4d44)
![image](https://github.com/storybookjs/storybook/assets/66855296/fa949666-82bd-4fab-aa33-e56fa94cf8df)

### System

```bash
Environment Info:

  System:
    OS: Linux 6.2 Ubuntu 22.04.3 LTS 22.04.3 LTS (Jammy Jellyfish)
    CPU: (8) x64 Intel(R) Xeon(R) Platinum 8272CL CPU @ 2.60GHz
  Binaries:
    Node: 16.20.0 - ~/.nvm/versions/node/v16.20.0/bin/node
    npm: 8.19.4 - ~/.nvm/versions/node/v16.20.0/bin/npm
  npmPackages:
    @storybook/addon-actions: ^7.4.0 => 7.4.0 
    @storybook/addon-essentials: ^7.4.0 => 7.4.0 
    @storybook/addon-links: ^7.4.0 => 7.4.0 
    @storybook/addon-mdx-gfm: ^7.4.0 => 7.4.0 
    @storybook/addons: ^7.4.0 => 7.4.0 
    @storybook/react: ^7.4.0 => 7.4.0 
    @storybook/react-webpack5: ^7.4.0 => 7.4.0
```

**Comment by dealvz** [comment]
I'm also running into this

**Comment by SchwJ** [comment]
I have the same proplem.

**Comment by shilman** [comment]
This must be due to multiple versions of Storybook packages installed. Things you can try:

1. `npm ls @storybook/addons`, `yarn why @storybook/addons`, etc. (depending on your package manager)
2. Remove your `node_modules` and reinstall
3. Remove your lock file and reinstall
4. Remove all your addons from `.storybook/main.js`. If that solves the problem, add them back one by one to see whether one of the addons is using the outdated API.
