### ISSUE TITLE
Fix unclear snippets for Highlight addon docs

### ISSUE THREAD

**Issue by kylegach** [storybookjs/storybook#24050]
Related discussion: https://github.com/storybookjs/storybook/discussions/23951#discussioncomment-6822345

https://storybook.js.org/docs/react/essentials/highlight

Clarify where `emit` comes from.

**Comment by ATREAY** [comment]
Hey @kylegach, can I work on this issue?
Also, if you assign me this task, I've got a quick question: where should I put the info about that "emit()" function?

**Comment by ATREAY** [comment]
Hey @kylegach,

I would like to inquire about the status of this issue. Is this issue still open?

**Comment by jonniebigodes** [comment]
@ATREAY thanks for your interest in helping us improve our documentation. We appreciate it 🙏 ! If you're still interested, please go ahead and submit a contribution.

If you have questions about contributing, check out our [documentation](https://storybook.js.org/docs/web-components/contribute/how-to-contribute) or ask us here so that we're able to help you get unblocked.


Looking forward to seeing the pull request up.

Hope you have a fantastic rest of the weekend.

Stay safe

**Comment by ATREAY** [comment]
Hey @jonniebigodes, I've made the necessary changes. Please take a look when you get a chance!

**Comment by ATREAY** [comment]
Hey @jonniebigodes, could you take a look at the changes I've made? 
Thanks!
