### ISSUE TITLE
[Bug]: Unwanted Emotion classNames added to components

### ISSUE THREAD

**Issue by 0mitch** [storybookjs/storybook#24949]
### Describe the bug

When trying to render a story that is using React Native Web and NativeWindV4 for styles I am finding the Tailwind styles applied are getting overwritten and replaced with something like `css-text-146c3p1` by Emotion. 

Tailwind on a normal `<div>` works fine and so does `<View style={{ $$css: true, test: "w-10 h-10 bg-blue-500" }} />` as well as manually applying the Tailwind styles. So currently I think the issue is how to stop Emotion from trying to process these Tailwind classNames when added to a React Native Web component using NativeWind V4. 

### To Reproduce

Add NativeWind V4 to this [example](https://github.com/expo/examples/tree/master/with-storybook) and see that the components do not render the Tailwind styles. 

### System

```bash
Storybook Environment Info:

  System:
    OS: macOS 13.6
    CPU: (10) arm64 Apple M1 Pro
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.17.0 - ~/.nvm/versions/node/v16.17.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.17.0/bin/yarn
    npm: 8.15.0 - ~/.nvm/versions/node/v16.17.0/bin/npm
    pnpm: 8.9.2 - ~/Library/pnpm/pnpm <----- active
  Browsers:
    Chrome: 119.0.6045.159
    Safari: 17.0
  npmPackages:
    @storybook/addon-essentials: ^7.5.3 => 7.5.3
    @storybook/addon-interactions: ^7.5.3 => 7.5.3
    @storybook/blocks: ^7.5.3 => 7.5.3
```

**Comment by shilman** [comment]
Do you a have a reproduction repo you can share? If not, can you create one? Go to https://storybook.new or see [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce). Thank you! 🙏

**Comment by panzacoder** [comment]
@0mitch did you solve your problem? I'm seeing pretty much the same behavior, except I am actually able to render the components into my NextJS project fine, and they _also_ have the emotion class there, which comes from the React Native Stylesheet that's being loaded somewhere.

So odd that the classes aren't stripped from standard html or from style props.

I did notice a not in the Solito docs that suggests that we need to use babel to transpile if we use `className` directly, but I don't think that's the case anymore since v4 uses SWC.

I'm new to the space though so having a hard time figuring out where one tool stops and the next starts.
