### ISSUE TITLE
[Bug]: Onboarding broken in SB8

### ISSUE THREAD

**Issue by shilman** [storybookjs/storybook#25288]
### Describe the bug

The onboarding addon fails to render properly and blocks user interaction. Probably due to some React version mismatch -- 8.0 manager UI is based on React18, 7.x is React16. Probably just need to create a `next` branch of the addon & externalize React on it? Or just bump a major?

**NOTE: This isn't an issue in 7.x.**

<img width="1389" alt="image" src="https://github.com/storybookjs/storybook/assets/488689/c099f11e-6057-40b7-a65b-51cbf96dd70e">

### To Reproduce

In an empty directory:

```
npx storybook@next init
```

Then choose react-vite.

**Comment by yannbf** [comment]
There are two reasons for this failure, both unrelated to versions of React:
- The elements are not properly visible (fixed [here](https://github.com/storybookjs/addon-onboarding/pull/78))
- One of the steps of the walkthrough will not select the right element, and the users will be stuck. This happens because in Storybook 8 the UI changed, and it's tricky to keep the addon working for both structures of Storybook 7 and 8

**Comment by yannbf** [comment]
There is a fix proposed here:
https://github.com/storybookjs/addon-onboarding/pull/81

**Comment by shilman** [comment]
Still broken. Reproduction:

```sh
mkdir nextjs-empty
cd nextjs-empty
npx storybook@latest init
```

Finally, choose the NextJS option
