### ISSUE TITLE
Determine whether to remove unstable TAB addon type

### ISSUE THREAD

**Issue by yannbf** [storybookjs/storybook#25376]
It's unclear whether to remove the TAB type for addons in Storybook 8:
https://github.com/storybookjs/storybook/blob/975ad7604b8236bad273d6498362b50af40975ee/code/lib/types/src/modules/addons.ts#L532

@ndelangen @shilman please let us know whenever you can, and what can be done migration-wise 🙏 

I'm looping in @cdedreuille and @MichaelArestad too because I have seen the tab being quite useful for certain addons, especially [addon-designs](https://github.com/storybookjs/addon-designs/blob/master/packages/examples-tab/.storybook/main.js#L14)

**Comment by shilman** [comment]
Seems like people are still using this but that it's buggy. I think I proposed getting rid of it in 7.0 but @MichaelArestad  proposed to keep it since we hadn't designed an alternative (this is the tab UI where you can have a full page that sits in a tab next to canvas, rather than in an addon panel). @MichaelArestad @cdedreuille do you have opinions on whether we can drop this feature in 8.0?

**Comment by shilman** [comment]
Oops sorry just saw you already looped them in. AFAIK this is not a technical issue just trying to reduce surface area.

**Comment by ndelangen** [comment]
Probably not really popular to remove it, but likely the right direction for maintenance.

**Comment by shilman** [comment]
Let's keep it for now to give ourselves another release cycle to figure out a better solution. We've got our hands full enough as is.

**Comment by cdedreuille** [comment]
I would be happy to check it if needed. I think I'm missing a bit some contexts on it though.
