### ISSUE TITLE
[Bug]: Cannot use Bun with storybook init

### ISSUE THREAD

**Issue by Polygons1** [storybookjs/storybook#25389]
### Describe the bug

trying to init a Vue project with Bun

### To Reproduce

bunx storybook init in a Vite + Vue (TS) project

### System

```bash
Error
```

**Comment by valentinpalkovic** [comment]
Adding official support for another Javascript runtime besides Node.js would mean we had to commit long-term supporting a runtime like bun. Currently, we are still waiting for a broader adoption of bun to satisfy official support since we have to juggle with the limited resources we have and use them wisely. 

On the other hand, I have already seen posts and mentions, that bun seems to work with Storybook, at least in some circumstances.

If you want to drive and accelerate Storybook's support of Bun, I would suggest creating an RFC or create a tracking issue where we can track missing pieces which are required to fully support bun. Then other contributors might participate, and supporting Bun might be driven by the community in the first place. This issue though is not very helpful, because it doesn't provide any meaningful error message or shows a path of how to support Bun.

Therefore, I am closing this for now as not planned.

**Comment by Polygons1** [comment]
just the package manager like pnpm or yarn, not the whole runtime

**Comment by UnknownH** [comment]
Also potentially as builder/bundler like swc
