### ISSUE TITLE
Storybooks support for next/navigation is broken in monorepo where different versions of nextjs are used

### ISSUE THREAD

**Issue by magnusriga** [storybookjs/storybook#25783]
### Describe the bug

Different versions of nextjs in a monorepo causes storybooks `nextjs/navigation` support to break.

### To Reproduce

Here is a minimal repo: https://github.com/magnusriga/turbo-tailwind

To reproduce the bug:

1. Run `pnpm i` in the root folder
2. Run `pnpm storybook` from the `apps/foo` folder

As seen, `pathname` from the external package is `null` (go to the console in dev tools and see the printout).

To fix the issue, just change the `next` dependency in `bar`'s package.json from `^13.5.6` to `latest`. Now do the first two steps above again (running `pnpm i` again is crucial), and voila it works.

### System

Storybook Environment Info:
(node:48496) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)

  System:
    OS: Linux 5.15 Ubuntu 22.04.3 LTS 22.04.3 LTS (Jammy Jellyfish)
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 21.5.0 - ~/.nvm/versions/node/v21.5.0/bin/node
    Yarn: 1.22.21 - ~/.nvm/versions/node/v21.5.0/bin/yarn
    npm: 10.2.4 - ~/.nvm/versions/node/v21.5.0/bin/npm
    pnpm: 8.15.0 - ~/.local/share/pnpm/pnpm <----- active
  npmPackages:
    @storybook/addon-essentials: 8.0.0-alpha.15 => 8.0.0-alpha.15 
    @storybook/addon-interactions: 8.0.0-alpha.15 => 8.0.0-alpha.15 
    @storybook/addon-links: 8.0.0-alpha.15 => 8.0.0-alpha.15 
    @storybook/addon-onboarding: ^1.0.11 => 1.0.11 
    @storybook/blocks: 8.0.0-alpha.15 => 8.0.0-alpha.15 
    @storybook/nextjs: 8.0.0-alpha.15 => 8.0.0-alpha.15 
    @storybook/react: 8.0.0-alpha.15 => 8.0.0-alpha.15 
    @storybook/test: 8.0.0-alpha.15 => 8.0.0-alpha.15 
    eslint-plugin-storybook: ^0.6.15 => 0.6.15 
    storybook: 8.0.0-alpha.15 => 8.0.0-alpha.15

**Comment by magnusriga** [comment]
I found the issue.

If the monorepo has three packages, one `packages/ui`, and two application packages (`apps/foo` and `apps/bar`), and the latter two use different nextjs versions (nextjs: 13 and 14, respectively), storybook's usePathname() when used from a component in `packages/ui` no longer works.

**Comment by valentinpalkovic** [comment]
## Why is Storybook breaking with different versions of Next.js?

Storybook sets up some necessary React Context Providers. These providers are imported from `next/<some-path>`. So whatever Next.js version is installed besides Storybook, it will take this version to import the necessary providers.

In your particular repo, `next/<subpath>` will be resolved to `apps/foo/node_modules/next/<subpath>`.

In `apps/bar`, a different Next.js version is installed. This leads to a problem. The `useContext` hook will be used from one version of `Next.js`, whereas the Context Provider, which Storybook sets up, uses a different version of Next.js. Therefore, the "instances" are not matching and the error occurs.

## Possible solutions to this problem

**1. Avoid multiple versions of Next.js**

It's dangerous to have a Next.js component library that uses one version while the application uses another. In the end, there will be one Next.js server running and importing your components with exactly one version. These components hopefully don't use unsupported API's of the Next.js version, which is running on the server. So, within the mono-repository, make sure that throughout the whole repo, one Next.js version is used, especially if your applications/libraries require each other. Then, the Next.js dependency should be properly hoisted and the error should be gone.

**2. Tell Storybook to only use one version of Next.js**

If you think that it is necessary to have different versions of Next.js in your mono-repo, you could tell Storybook to just use exactly one version. This should fix your issue:

```diff
//apps/foo/.storybook/main.ts
import type { StorybookConfig } from "@storybook/nextjs";

import path, { join, dirname } from "path";

/**
 * This function is used to resolve the absolute path of a package.
 * It is needed in projects that use Yarn PnP or are set up within a monorepo.
 */
function getAbsolutePath(value: string): any {
  return dirname(require.resolve(join(value, "package.json")));
}
const config: StorybookConfig = {
  stories: ["../src/**/*.mdx", "../src/**/*.stories.@(js|jsx|mjs|ts|tsx)"],
  addons: [
    getAbsolutePath("@storybook/addon-links"),
    getAbsolutePath("@storybook/addon-essentials"),
    getAbsolutePath("@storybook/addon-onboarding"),
    getAbsolutePath("@storybook/addon-interactions"),
  ],
  framework: {
    name: getAbsolutePath("@storybook/nextjs"),
    options: {},
  },
+  webpackFinal: async (config) => {
+    // alias next.js to the version which is installed here
+    config.resolve = {
+      ...config.resolve,
+      alias: {
+        ...(config.resolve?.alias ?? {}),
+        next: path.resolve(__dirname, "../node_modules/next"),
+      },
+    };
+    return config;
+  },
  docs: {
    autodocs: "tag",
  },
  staticDirs: ["../public"],
};
export default config;
```

This issue isn't really easily fixable, because there is a wide range of how people can set up mono-repos. A generic solution, which could be applicable to all mono-repos, is not available at this time.

**Comment by valentinpalkovic** [comment]
@magnusriga I will close this for now. Please let me know if you have general ideas on how to fix this issue.

**Comment by magnusriga** [comment]
Thanks for chiming in @valentinpalkovic . I decided to set up tooling to prevent different versions of packages across the monorepo. A bit clumsy, but works well now that it has been configured.
