### ISSUE TITLE
[Bug]: Local stories not working when loading external refs

### ISSUE THREAD

**Issue by nilpaco** [storybookjs/storybook#25957]
### Describe the bug

I'm encountering an issue where the main documentation section of our Storybook project remains indefinitely in the loading state, despite the content having completely loaded. In the video you can see that deleting the `preview-loader` container the content is shown.

https://github.com/storybookjs/storybook/assets/12384231/951c53da-574a-49ff-8dfe-44bcc9c0a4d8

The issue appears to be with how Storybook handles the loading of external references that share the same base URL with the stories loaded externally.

Example of conflicting URLs:

- External ref URL: https://example-storybook.com/components/button/master/
- Storybook base URL: https://example-storybook.com/

The previewInitialized state doesn't get properly updated because the URL matching logic incorrectly impacts the state of an external reference instead of the local story. (see [findRef source code](https://github.com/storybookjs/storybook/blob/44ed235bf675d5b1a0b11706e0f780fdc61e3951/code/lib/manager-api/src/modules/refs.ts#L166)):

``` 
findRef: (source): any => {
      const refs = api.getRefs();
      return Object.values(refs).find(({ url }: any) => url.match(source));
}
```

### To Reproduce

Not the most elegant way but I've prepared a StackBlitz project that mimics a similar configuration. In this example, you can see that the external references match with the same URL, as previously mentioned.

https://stackblitz.com/edit/github-j9db22?file=.storybook%2Fmain.js

note: You may need to update the base url of the ref object.

**Comment by ndelangen** [comment]
Hello @nilpaco I'm looking into this, however the video cannot be played or downloaded, it seems.

I'm looking at the stackblitz (thank you for including that!), however it's looking different for me:
![Screenshot 2024-03-04 at 14 59 41](https://github.com/storybookjs/storybook/assets/3070389/f40bef89-2421-4f25-b168-0ae35b5d09e7)

It's likely because I don't have access to the [composed storybook](https://githubj9db22-jbij--6006--6f234770.local-credentialless.webcontainer.io/test-component/master).
Maybe it's switched off due to inactivity, or it's private?

I tried following through to get access, but ran into trouble
![Screenshot 2024-03-04 at 15 02 09](https://github.com/storybookjs/storybook/assets/3070389/a6f5e41b-e98e-453a-8a48-7a7e1f64f69f)
![Screenshot 2024-03-04 at 15 02 15](https://github.com/storybookjs/storybook/assets/3070389/03982945-47f3-4e80-a0fd-f46b81015586)

Can you assist me in getting this reproduced reliably?

**Comment by nilpaco** [comment]
Thank you, @ndelangen! Sorry for the oversight. Let me know if you need anything from me. I've tried different fixes, but any attempt seems to either break something else or fall short.

**Comment by ndelangen** [comment]
I'm on the case!

**Comment by ndelangen** [comment]
I have found a solution/fix and will open a PR soon! 🎉

**Comment by nilpaco** [comment]
thank you @ndelangen for the work!
