### ISSUE TITLE
"What's new" modal changes

### ISSUE THREAD

**Issue by vanessayuenn** [storybookjs/storybook#26133]
1. **Modal title**: Can we use the blogpost title instead of the excerpt property (which we currently show)? The problem is that to optimize a changelog for appearing in Storybook and on the web blog, we have to write two titles (one as the page title and another as the excerpt used by the modal). That can be pretty awkward. Annotated screenshot attached 
![image](https://github.com/storybookjs/storybook/assets/6842965/718ce523-0a0d-43c6-867f-e722f1266487)
![image](https://github.com/storybookjs/storybook/assets/6842965/24437f37-7d5b-4d9d-84de-f5a0bed74dec)

2. **Modal call to action**: Can we remove ‘Click to’? Instead, simplify it to be ‘Learn what’s new in Storybook’

3. **Modal symbol**: Is there a reason why we use a heart? There may be a better symbol to represent that this is a Storybook update. Maybe a newspaper symbol, or even the Storybook S itself?

**Comment by joevaugh4n** [comment]
thank youuu @vanessayuenn !

**Comment by joevaugh4n** [comment]
cc @winkerVSbecks – @kasperpeulen that’s an interesting idea re. changing the What’s New endpoint.

As a short-term fix (even if just for the SB8 release), could we change this so that rather than the excerpt being a dynamic value (as that’s the part that SB shows), we instead hard-code it to replicate whatever we make the SB8 byline/subheading? 

e.g. if the SB8 blogpost title ‘Storybook 8’ and the byline is ‘Major compatibility and testing improvements’, could we just change the excerpt value to be ‘Major compatibility and testing improvements’?

If I understand correctly, that would surface irrespective of a user’s Storybook version, right? And it means we don’t need to do more work on this in the short term.
