### ISSUE TITLE
[Bug]: flaky tests on HMR

### ISSUE THREAD

**Issue by FilipePfluck** [storybookjs/storybook#26217]
### Describe the bug

I am getting flaky tests when I update my file and the storybook updates with HMR. It seems like the tests are running in an unclean state. 
![Screenshot from 2024-02-22 09-23-31](https://github.com/storybookjs/storybook/assets/62773200/0ff8d037-58cb-4a1e-9c2e-0dbcd52fa571)
![Screenshot from 2024-02-22 09-23-40](https://github.com/storybookjs/storybook/assets/62773200/f0c6cbe8-018e-40a5-b1a8-8fbaa8f09ee2)

### Additional context

@kasperpeulen asked me to create this issue on a discord conversation

**Comment by shilman** [comment]
cc @kasperpeulen

**Comment by kasperpeulen** [comment]
@vanessayuenn I think we should fix this as part of the module mock project.
I think that on HMR loaders are not rerun but the play function is.

@yannbf @JReinhold  We should either:
* not rerun the play function on HMR
* or rerun both loaders and the play function on HMR

**Comment by JReinhold** [comment]
Agree. If we want to be consistent with test runners like Vitest, I think we should rerun the whole pipeline on HMR.

**Comment by yannbf** [comment]
I agree as well. @kasperpeulen can you add this to the project?

Before we even do anything, @tmeasday @shilman do you know why loaders are not rerun on HMR? Is there some important information we're missing somehow?

**Comment by ghengeveld** [comment]
In my recollection, we decided to not rerun loaders on HMR because these operations may be relatively slow (since they're async).

I'm not sure about rerunning the play function on HMR. HMR shouldn't cause a component to remount (render from scratch), and so it isn't safe to run the play function again (or we'd have applied it twice). The effects of the 1st run would still be there, and that's preferable. However, if the HMR affects the play function itself then we probably should remount and replay, otherwise you'll get into an invalid state. I suppose we could detect an interaction error after HMR and force-remount in this case. That would defeat the benefit of HMR but that's better than getting into an invalid state.

**Comment by JReinhold** [comment]
Findings from testing the behaviour out in a simple sandbox:

| Reruns on | Story-file HMR | Component-file HMR | Args change | Globals change |
|---|---|---|---|---|
| Loaders | ✅ | ❌ | ✅ | ✅ |
| Story Render | ✅ | ❌ | ✅ | ✅ |
| Component Render | ✅ | ✅ | ✅ | ✅ |
| Play | ✅ | ❌ | ❌ | ❌ |

This is consistent between Vite and Webpack (Next.js).

I think this matches what @tmeasday and @ghengeveld expresses, and after trying it out I'm okay with this current behavior.

This does lead to the slight confusing scenario where your assertions could be failing, then you change your _component_ to fix it, but the assertions still shows as failed because the `play`-function didn't rerun, you'd have to manually trigger it again. This might be what @FilipePfluck ran into, I can't tell without a minimal reproduction.

However the trade-off as @ghengeveld mentions is that if we did choose to rerun the whole pipeline on component-changes, we could make the development-loop a lot slower than it needs to be.

> However, if the HMR affects the play function itself then we probably should remount and replay, otherwise you'll get into an invalid state.

As the table suggests this is actually what happens today with the difference between story- and component HMR, but it's not fool proof.

**Comment by kasperpeulen** [comment]
I think @IanVS also encountered this issue.

**Comment by tmeasday** [comment]
@JReinhold once we've agreed the behaviour is what we want, we should update the preview tests to ensure all cases are covered. And we might consider refactoring the (large) `PreviewWeb.test.ts` file to make it easier for someone to infer the correct behaviour by reading them.
