### ISSUE TITLE
CLI: `github-flavored-markdown-mdx automigration` shouldn't run if you're upgrading from 8.x

### ISSUE THREAD

**Issue by shilman** [storybookjs/storybook#26249]
### Describe the bug

I upgraded Storyblok's design system from `7.6.10` to `8.0-beta.6`. Along the way it prompted me if I wanted to install Github-flavored MDX and I declined. Then after the upgrade I ran `npx storybook automigrate` and it prompted me again.

It should only prompt me when upgrading from 7.x or below. Once a user is on 8.x they are already on MDX3 and GFM is not supported. We shouldn't bug users to add support, especially when the support is just a transitional measure.

**Comment by valentinpalkovic** [comment]
I think we have to clarify here some things.

The `github-flavored-markdown-mdx` shouldn't be triggered during upgrading Storybook from 7.6 to 8.x, because the version conditions are defined currently as:

- before version: `<7`
- after version: `>=7`

It gets triggered, though, because we have a bug (very likely introduced by resolving a merge conflict). I have fixed this here:
https://github.com/storybookjs/storybook/pull/26293

The second point you mention is that `github-flavored-markdown-mdx` shouldn't be triggered when the `automigrate` CLI is used. While using `automigrate`, the version checks aren't applied, since we don't know from which previous versions the user has upgraded because we don't save the previous Storybook version while `upgrade`. The `check` function of `github-flavored-markdown-mdx` only checks whether for example `mdx` is defined as a glob for the `stories` property, or whether `@storybook/addon-mdx-gfm` is already installed. It doesn't have a "current version" check, though. The automigrations also don't remember, whether they were declined at some point.

What I could do is to check the current version in the `check` function and if it is later than `8.0`, we don't trigger it. @shilman WDYT?

**Comment by shilman** [comment]
Fantastic @valentinpalkovic !! Sounds good to me
