### ISSUE TITLE
[Bug]: Story#of always use the first exported component as fallback instead of given one (8.0.0-rc.0)

### ISSUE THREAD

**Issue by codeart1st** [storybookjs/storybook#26272]
### Describe the bug

In my .mdx file in both cases the first exported component from Formular.stories.tsx gets rendered instead of the provided one by "of"-prop

```
import { Canvas, ArgTypes, Story, Meta } from '@storybook/blocks'
import * as FormularStories from './Formular.stories'
import { Formular } from '@/components/Formular/Formular'

<Meta of={FormularStories} />

#### All Components
<Canvas withSource='open'>
  <Story of={FormularStories.AllComponents} />
</Canvas>

#### Listen Form
<Canvas withSource='open'>
  <Story of={FormularStories.ListenForm} />
</Canvas>
```

### To Reproduce

[https://stackblitz.com/edit/github-xlavar?file=src%2Fstories%2FButton.mdx](https://stackblitz.com/edit/github-xlavar?file=src%2Fstories%2FButton.mdx)

### System

```bash
Storybook Environment Info:

  System:
    OS: Linux 5.15 Ubuntu 20.04.6 LTS (Focal Fossa)
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 20.11.1 - /usr/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn <----- active # i know it's not officially supported anymore
    npm: 8.19.4 - ~/Projects/form-interpreter/node_modules/.bin/npm
  Browsers:
    Chrome: 122.0.6261.94
  npmPackages:
    @storybook/addon-essentials: next => 8.0.0-rc.0 
    @storybook/addon-links: next => 8.0.0-rc.0 
    @storybook/react: next => 8.0.0-rc.0 
    @storybook/react-vite: next => 8.0.0-rc.0 
    storybook: next => 8.0.0-rc.0
```

**Comment by codeart1st** [comment]
I added https://stackblitz.com/edit/github-xlavar?file=src%2Fstories%2FButton.mdx

**Comment by JReinhold** [comment]
The [doc blocks' API changed in 7.0](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#doc-blocks), deprecating the old props API, and [in 8.0 the old props are now completely ignored](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#canvas-doc-block-properties). For the `Canvas` block this specifically means that it doesn't accept `<Story />` children but instead requires the use of `of={MyStory}` prop - [see the migration notes on that here](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#canvas-block), and [the API docs here](https://storybook.js.org/docs/8.0/api/doc-block-canvas).

What's happening for you here is that because you're not passing the `of` prop, it basically functions as `<Canvas />` (`children` are ignored), which defaults to showing a canvas with the primary story.

Here's a fork of your StackBlitz with the necessary changes:

https://stackblitz.com/edit/github-xlavar-bkumbh?file=src%2Fstories%2FButton.mdx

**Comment by codeart1st** [comment]
Missed that part. Thanks for the clarification 👍
