### ISSUE TITLE
[Bug]: AddOn - TooltipLinkList "left" does not render (8.0.0-beta.2)

### ISSUE THREAD

**Issue by stevensacks** [storybookjs/storybook#26310]
### Describe the bug

If you put something in "left", it does not render.

"title" and "right" still work

### To Reproduce

Put anything into "left" in the TooltipLinkList links prop.

### System

```bash
System:
    OS: macOS 14.3.1
    CPU: (12) arm64 Apple M2 Pro
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.11.0 - ~/.nvm/versions/node/v20.11.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v20.11.0/bin/yarn
    npm: 10.4.0 - ~/.nvm/versions/node/v20.11.0/bin/npm <----- active
    pnpm: 8.1.0 - ~/.nvm/versions/node/v20.11.0/bin/pnpm
  Browsers:
    Chrome: 122.0.6261.94
    Safari: 17.3.1
  npmPackages:
    @storybook/addon-essentials: 8.0.0-beta.2 => 8.0.0-beta.2 
    @storybook/addon-interactions: 8.0.0-beta.2 => 8.0.0-beta.2 
    @storybook/addon-links: 8.0.0-beta.2 => 8.0.0-beta.2 
    @storybook/blocks: 8.0.0-beta.2 => 8.0.0-beta.2 
    @storybook/components: 8.0.0-beta.2 => 8.0.0-beta.2 
    @storybook/core-events: 8.0.0-beta.2 => 8.0.0-beta.2 
    @storybook/manager: 8.0.0-beta.2 => 8.0.0-beta.2 
    @storybook/manager-api: 8.0.0-beta.2 => 8.0.0-beta.2 
    @storybook/preview: 8.0.0-beta.2 => 8.0.0-beta.2 
    @storybook/preview-api: 8.0.0-beta.2 => 8.0.0-beta.2 
    @storybook/react: 8.0.0-beta.2 => 8.0.0-beta.2 
    @storybook/react-vite: 8.0.0-beta.2 => 8.0.0-beta.2 
    @storybook/testing-library: ^0.2.2 => 0.2.2 
    @storybook/theming: 8.0.0-beta.2 => 8.0.0-beta.2 
    @storybook/types: 8.0.0-beta.2 => 8.0.0-beta.2 
    storybook: 8.0.0-beta.2 => 8.0.0-beta.2
```

### Additional context

```ts
// pseudo-code example

[ 
  {title: 'English', right: '🇺🇸'},
  {title: 'English', right: 'GB'},
  {title: 'Français', left: '🇫🇷'},
  {left: '🇯🇵'},
  {right: '🇩🇪'},
  'Spain',
  '🇮🇹 Italiano',
],
```

![Screenshot 2024-03-05 at 15 17 22](https://github.com/storybookjs/storybook/assets/162252/77a30b62-a851-431f-bd6a-6b7c8abfa8bd)

**Comment by shilman** [comment]
@JReinhold @cdedreuille is this an intentional 8.0 change?

**Comment by valentinpalkovic** [comment]
This was already an intentional change for Storybook 7. See https://github.com/storybookjs/storybook/pull/20898 and https://github.com/storybookjs/storybook/issues/20897

A `left` property doesn't exist. You must use `icon` if you want to place an icon on the left. See the property definition here: https://github.com/storybookjs/storybook/blob/next/code/ui/components/src/components/tooltip/ListItem.tsx#L175

@stevensacks Where did you find the information that the `left` property can be configured? Have we documented it somewhere wrongly?

**Comment by stevensacks** [comment]
Ok. I see in the code you linked that even though there is a component called `<Left>` you removed the “left” prop in favor of an “icon” prop. I noticed there are two props for the center called “center” and “title”, and a “right” prop for the `<Right>` component.

The “icon” prop is not technically an icon, it’s a ReactNode. It could be text. It could be an emoji (like my usage). I assume that’s why it was named “left” all these years.

I’ll change my addon to use the new name, but this is a breaking change for all addons that use the TooltipListLink component, and it should be clearly stated in the migration docs.

**Comment by valentinpalkovic** [comment]
@stevensacks I have added an entry to the migration docs here:
https://github.com/storybookjs/storybook/pull/26324

Please reach out if you need some further help. And don't get confused about the `icon` property in `globalTypes`, because before we pass the icon further to the `ToolTipListLink` component, we will pass the string into the `Icon` component from `@storybook/components` (which is deprecated).

And I agree. The API of the TooltipListLink is pretty messy. I hope, at some point, we can clean it up! Thanks for pointing it out.
