### ISSUE TITLE
[Bug]:  ECONNRESET error when running html storybook

### ISSUE THREAD

**Issue by Tallyb** [storybookjs/storybook#26369]
### Describe the bug

when serving html storybook the following error constantly shows up: 
<w> [LazyCompilationBackend] Error: read ECONNRESET
<w>     at __node_internal_captureLargerStackTrace (node:internal/errors:563:5)
<w>     at __node_internal_errnoException (node:internal/errors:690:12)
<w>     at TCP.onStreamRead (node:internal/stream_base_commons:217:20) {
<w>   errno: -54,
<w>   code: 'ECONNRESET',
<w>   syscall: 'read' 

### To Reproduce

not sure how to, as I do not understand the root cause. 

### System

```bash
Storybook Environment Info:

  System:
    OS: macOS 14.2.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.11.1 - ~/.nvm/versions/node/v20.11.1/bin/node
    Yarn: 1.22.21 - /usr/local/bin/yarn
    npm: 7.24.2 - ~/yoobic/yoobic-ng-6/node_modules/.bin/npm <----- active
    pnpm: 8.15.2 - /usr/local/bin/pnpm
  Browsers:
    Chrome: 122.0.6261.112
    Safari: 17.2.1
  npmPackages:
    @storybook/addon-coverage: 1.0.0 => 1.0.0
    @storybook/addon-designs: 7.0.9 => 7.0.9
    @storybook/addon-essentials: 7.6.17 => 7.6.17
    @storybook/addon-interactions: 7.6.17 => 7.6.17
    @storybook/angular: 7.6.17 => 7.6.17
    @storybook/cli: 7.6.17 => 7.6.17
    @storybook/html-webpack5: 7.6.17 => 7.6.17
    @storybook/manager-api: 7.6.17 => 7.6.17
    @storybook/preview-api: 7.6.17 => 7.6.17
    @storybook/test: 7.6.17 => 7.6.17
    @storybook/theming: 7.6.17 => 7.6.17
    chromatic: 10.9.6 => 10.9.6
    storybook: 7.6.17 => 7.6.17
```

### Additional context

HTML is used to run a stencil based storybook. 
Hovering over the stories trigger a rebuild, and occasionally the error.

**Comment by vanessayuenn** [comment]
@Tallyb thanks for reporting this. However, without a consistent repro, there is no where for us to start investigating. I will leave this open and see if others are also running into this and can give some insights.

**Comment by michaelfaith** [comment]
We're seeing this as well in v8.2.6

**Comment by Igna312** [comment]
here the solution:

add in  app.modules.ts in secction imports (db):

ssl: {
    rejectUnauthorized: false,

**Comment by Igna312** [comment]
ssl: {
        rejectUnauthorized: false, 
      },

**Comment by BrendanThysse** [comment]
Also experiencing this storybook 8.3.4...

@Igna312 can you better explain where to set the ssl option, I do not have an app.module.ts as I am running a mono repo within storybook?

**Comment by Igna312** [comment]
"Hey @Tallyb  and @BrendanThysse , sorry for the confusion. The solution I mentioned applies to environments where SSL/TLS connections are used, specifically when dealing with connections that might reject unauthorized certificates.

If you're working with a Node.js or similar backend that connects to a database or service using SSL, you might need to add this ssl: { rejectUnauthorized: false } setting in the relevant configuration (like database connection settings or environment files).

Since Storybook itself doesn’t have an app.module.ts, the setting might not apply directly to Storybook’s config but to any backend or service Storybook interacts with. If you're not using SSL in your setup, this might not be relevant.

**Comment by Igna312** [comment]
and this was gpt, hope it helps:

The ECONNRESET error usually happens when a connection is unexpectedly closed by the server or client. For Storybook, this could be related to how HTTP connections are being handled, especially since you mentioned it occurs when hovering over stories, triggering rebuilds.

Here are a few things you can try:

Disable Lazy Compilation: Since the issue seems tied to rebuilds on hover, you can try disabling lazy compilation in your Webpack config. Add this to your webpack.config.js:

js
Copiar código
module.exports = {
  experiments: {
    lazyCompilation: false,
  },
};
SSL/TLS Config: If your Storybook setup is interacting with services requiring SSL, the issue might be related to unauthorized certificates. For connections where SSL is required, you could try adding this:

js
Copiar código
ssl: {
  rejectUnauthorized: false,
},
This applies to backend services or APIs Storybook might be communicating with. It won't directly apply to Storybook config unless you’re making secure connections.

Increase Connection Limits: It might also be worth increasing connection limits or adjusting timeout values if the server is closing connections too quickly.

Node.js Version: Some recent versions of Node.js (like 20.x) have introduced changes that might be causing this. Try switching to a stable LTS version like 18.x to see if the issue persists.

Handle Errors Gracefully: If it’s occurring on the frontend, you can also handle connection errors gracefully with something like:

js
Copiar código
process.on('uncaughtException', (err) => {
  if (err.code === 'ECONNRESET') {
    console.warn('Connection reset by peer');
  } else {
    throw err;
  }
});
It seems others have reported similar issues, so this could also be related to certain Storybook or Webpack versions.

**Comment by mimifuwacc** [comment]
This discussion might be helpful for resolving this issue:
https://github.com/storybookjs/storybook/discussions/34795

The error `[LazyCompilationBackend] ECONNRESET` is often caused by a flood of network requests when `lazyCompilation.imports` is enabled. Switching to `entries: true` reduces the request overhead and stabilizes the connection.
