### ISSUE TITLE
[Bug]: Unable to install storybook (_d.toLowerCase is not a function)

### ISSUE THREAD

**Issue by masterprompt** [storybookjs/storybook#26483]
### Describe the bug

1. Did a fresh install of storybook into our new app (create_react_app with typescript) via `npx storybook@latest init`

```
Node v20.9.0

"dependencies": {
    "@auth0/auth0-react": "^2.2.4",
    "@tanstack/react-query": "^4.36.1",
    "@testing-library/jest-dom": "^5.17.0",
    "@testing-library/react": "^13.4.0",
    "@testing-library/user-event": "^13.5.0",
    "@types/jest": "^27.5.2",
    "@types/node": "^16.18.58",
    "@types/react": "^18.2.28",
    "@types/react-dom": "^18.2.13",
    "axios": "^1.6.0",
    "jmespath": "^0.16.0",
    "lodash": "^4.17.21",
    "moment": "^2.29.4",
    "query-string": "^8.1.0",
    "react": "^18.2.0",
    "react-bootstrap": "^2.9.1",
    "react-bootstrap-icons": "^1.10.3",
    "react-data-table-component": "^7.5.4",
    "react-dom": "^18.2.0",
    "react-query": "^3.39.3",
    "react-router-dom": "^6.16.0",
    "react-scripts": "5.0.1",
    "react-tag-autocomplete": "^7.1.0",
    "sass": "^1.69.5",
    "styled-components": "^5.3.11",
    "typescript": "^4.9.5",
    "use-local-storage": "^3.0.0",
    "web-vitals": "^2.1.4"
},
  "devDependencies": {
    "@chromatic-com/storybook": "^1.2.18",
    "@storybook/addon-essentials": "^8.0.0",
    "@storybook/addon-interactions": "^8.0.0",
    "@storybook/addon-links": "^8.0.0",
    "@storybook/addon-onboarding": "^8.0.0",
    "@storybook/blocks": "^8.0.0",
    "@storybook/preset-create-react-app": "^8.0.0",
    "@storybook/react": "^8.0.0",
    "@storybook/react-webpack5": "^8.0.0",
    "@storybook/test": "^8.0.0",
    "@types/jmespath": "^0.15.2",
    "@types/lodash": "^4.14.200",
    "eslint-plugin-storybook": "^0.8.0",
    "prop-types": "^15.8.1",
    "storybook": "^8.0.0",
    "webpack": "^5.90.3"
  }
```

Everything seems to install properly, but once storybook attempts to run for the first time we get:

```
Running Storybook

> spa@0.1.0 storybook
> storybook dev -p 6006 --initial-path=/onboarding --quiet

@storybook/cli v8.0.0

SB_CORE-SERVER_0007 (MainFileEvaluationError): Storybook couldn't evaluate your .storybook/main.ts file.

TypeError: _d.toLowerCase is not a function
    at getOptions (/node_modules/esbuild-register/dist/node.js:4761:101)
    at compile2 (/node_modules/esbuild-register/dist/node.js:4880:21)
    at Module._compile (/node_modules/esbuild-register/dist/node.js:2254:31)
    at Module._extensions..js (node:internal/modules/cjs/loader:1295:10)
    at Object.newLoader [as .ts] (/node_modules/esbuild-register/dist/node.js:2262:9)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Module._load (node:internal/modules/cjs/loader:938:12)
    at Module.require (node:internal/modules/cjs/loader:1115:19)
    at require (node:internal/modules/helpers:130:18)
    at interopRequireDefault (/node_modules/@storybook/core-common/dist/index.js:6:21)

WARN Broken build, fix the error above.
WARN You may need to refresh the browser.
```

### To Reproduce

cannot reproduce using your instructions.  Hoping the stack trace above will help.

**Comment by bcsaxon** [comment]
I'm running into this as well.  only with what I believe is a Node version installation issue. 

`SB_CORE-SERVER_0007 (MainFileEvaluationError): Storybook couldn't evaluate your .storybook/main.ts file.

Error: 
You installed esbuild for another platform than the one you're currently using.
This won't work because esbuild is written with native code and needs to
install a platform-specific binary executable.

Specifically the "@esbuild/darwin-x64" package is present but this platform
needs the "@esbuild/darwin-arm64" package instead. People often get into this
situation by installing esbuild with npm running inside of Rosetta 2 and then
trying to use it with node running outside of Rosetta 2, or vice versa (Rosetta
2 is Apple's on-the-fly x86_64-to-arm64 translation service).

If you are installing with npm, you can try ensuring that both npm and node are
not running under Rosetta 2 and then reinstalling esbuild. This likely involves
changing how you installed npm and/or node. For example, installing node with
the universal installer here should work: https://nodejs.org/en/download/. Or
you could consider using yarn instead of npm which has built-in support for
installing a package on multiple platforms simultaneously.

If you are installing with yarn, you can try listing both "arm64" and "x64"
in your ".yarnrc.yml" file using the "supportedArchitectures" feature:
https://yarnpkg.com/configuration/yarnrc/#supportedArchitectures
Keep in mind that this means multiple copies of esbuild will be present.

Another alternative is to use the "esbuild-wasm" package instead, which works
the same way on all platforms. But it comes with a heavy performance cost and
can sometimes be 10x slower than the "esbuild" package, so you may also not
want to do that.`

**Comment by dougwperez** [comment]
I am getting the same error, and I have node.js v18. @valentinpalkovic @shilman

**Comment by masterprompt** [comment]
Worth noting I was able to install storybook in other projects on the same laptop (node v20).  For some reason this project just doesnt like it.

**Comment by valentinpalkovic** [comment]
@JalalHabeeb Do you have vite installed as a dependency?

**Comment by JalalHabeeb** [comment]
@valentinpalkovic, sure I did

**Comment by JalalHabeeb** [comment]
When I remove the `viteFinal` function, it works. But when I add it it doesn't.
I don't know what is the mistake here.

**Comment by valentinpalkovic** [comment]
Can you provide a minimal reproduction? https://storybook.new

**Comment by squidjam** [comment]
Can we agree that issues that depend from upgrades cannot provide a minimal reproduction?
This has happened to me to, I have no means to show it to you
