### ISSUE TITLE
[Bug]: "Types of property 'typescript' are incompatible" with @storybook/react-webpack5

### ISSUE THREAD

**Issue by kyletsang** [storybookjs/storybook#26586]
### Describe the bug

I'm getting a typescript error when adding the `typescript` section into the config when using `react-webpack5`:

```
Types of property 'typescript' are incompatible.
      Type '{ reactDocgen: "react-docgen-typescript"; }' is not assignable to type 'PresetValue<Partial<TypescriptOptions> | undefined>'.ts(2322)
```

It's the same as this bug in the vite package:
https://github.com/storybookjs/storybook/issues/25736

### To Reproduce

Minimal config to reproduce error

```
import type { StorybookConfig } from '@storybook/react-webpack5'

const config: StorybookConfig = {
  stories: [],
  typescript: {
    reactDocgen: 'react-docgen-typescript'
  }
}

export default config

```

### System

```bash
System:
    OS: macOS 13.6.4
    CPU: (8) arm64 Apple M1 Pro
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.11.1 - ~/.nvm/versions/node/v20.11.1/bin/node
    npm: 10.2.4 - ~/.nvm/versions/node/v20.11.1/bin/npm <----- active
  Browsers:
    Chrome: 122.0.6261.129
    Firefox: 123.0
    Safari: 17.3.1
  npmPackages:
    @storybook/addon-essentials: ^8.0.2 => 8.0.2 
    @storybook/addon-interactions: ^8.0.2 => 8.0.2 
    @storybook/addon-links: ^8.0.2 => 8.0.2 
    @storybook/addon-webpack5-compiler-babel: ^3.0.3 => 3.0.3 
    @storybook/blocks: ^8.0.2 => 8.0.2 
    @storybook/react: ^8.0.2 => 8.0.2 
    @storybook/react-webpack5: ^8.0.2 => 8.0.2 
    @storybook/test: ^8.0.2 => 8.0.2 
    eslint-plugin-storybook: ^0.8.0 => 0.8.0 
    storybook: ^8.0.2 => 8.0.2
```

**Comment by luciob** [comment]
Same here with all packages to the version `8.0.5`.
I found a workaround by adding the `check` and `skipCompiler` options using their default value (see: node_modules/@storybook/types/dist/index.d.ts).
They apparently are optional, but in practice not. Maybe some issues with type validation.
I'm using TS 5.3.3

```
  typescript: {
    check: false,
    skipCompiler: false,
    reactDocgen: "react-docgen-typescript",
  },
```

**Comment by valentinpalkovic** [comment]
Can someone provide a simple reproduction? I can't reproduce it with the latest next version of Storybook.

**Comment by kyletsang** [comment]
I can no longer reproduce it as well.  Looks like it disappeared once I updated to VS Code 1.88 just now.  Will close the issue, thanks!

**Comment by Shagamii** [comment]
The issue still reproduces in my local environment. The version of Storybook is 8.0.9.
It's due to the type definition in react-webpack5's TypeScript, which is connected by the intersection `PresetValue <{ check: boolean, skipCompiler: boolean;}>`.

https://github.com/storybookjs/storybook/blob/d1b4753ba815496c9303573d2b213b71198fec49/code/frameworks/react-webpack5/src/types.ts#L34-L35

https://github.com/storybookjs/storybook/blob/d1b4753ba815496c9303573d2b213b71198fec49/code/lib/types/src/modules/core-common.ts#L453

https://github.com/storybookjs/storybook/blob/d1b4753ba815496c9303573d2b213b71198fec49/code/lib/types/src/modules/core-common.ts#L526

If the "check" or "skipCompiler" property is not in the object, it can't determine whether it's an object or a function.

**Comment by valentinpalkovic** [comment]
@Shagamii 

I've just tried to reproduce it, but I can't. Can you please provide a reproduction?
