### ISSUE TITLE
[Bug]: links on docs page for config point to 404 

### ISSUE THREAD

**Issue by dahei** [storybookjs/storybook#28648]
### Describe the bug

When on https://storybook.js.org/docs/api/main-config/main-config#config every link for a single config setting lead to a 404 page:

https://storybook.js.org/docs/api/main-config/$1

Therefore the detailed docs aren't accessible.

### Reproduction link

https://storybook.js.org/docs/api/main-config/main-config#config

### Reproduction steps

1. Go to docs page for the config 2. click any of the config settings, e.g. `stories` 3. You end up on https://storybook.js.org/docs/api/main-config/$1

### System

```bash
Mac, Chrome 126.0.6478.127
```

**Comment by jonniebigodes** [comment]
I wanted to follow up with you to let you know that the fix has already been deployed. The issue seems to have been resolved, and the links are now working as they should. 

I'm going to close this issue for now, but let me know if it surfaces again so that we can re-open it and continue to work on it.
