### ISSUE TITLE
[Documentation]: SvelteKit doc references a nextjs import

### ISSUE THREAD

**Issue by olafurw** [storybookjs/storybook#29109]
### Describe the problem

Should be `import { StorybookConfig } from '@storybook/sveltekit';`

https://github.com/storybookjs/storybook/blob/8b16feb67674d6ccfdf3a1c539ca35e56f3e1968/docs/_snippets/sveltekit-add-framework.md?plain=1#L10

**Comment by jonniebigodes** [comment]
@olafurw, thanks for taking the time to reach out to us and letting us know about that issue. We appreciate it 🙏 ! I'm still working through auditing the documentation in light of a recent update, and the frameworks pages are on my radar. I hope to get the documentation vetted accordingly and solve this and any other issues similar to this shortly so that you and the rest of the community get the correct information. 

Once the pull request is up, I'll make sure to reference this issue so that you can follow along with it.

Hope you have a great day

Stay safe

**Comment by jonniebigodes** [comment]
Sorry for the delayed response on this, but the Svelte documentation took a bit longer than required to get updated. The snippet is now fixed and it should be deployed shortly.

Have a great day.

Stay safe
