### ISSUE TITLE
Test addon should install coverage provider out of the box

### ISSUE THREAD

**Issue by shilman** [storybookjs/storybook#29797]
Currently when you install the test addon, it does not install a coverage provider. When you try to run coverage it fails. To debug you need to look at the console, which is non-intuitive. Then you need to add a coverage provider (it suggests V8) and then restart.

We should just install the coverage provider out of the box. And if we think istanbul is the better choice, we should install that and configure Vitest accordingly. (I'm still on the fence about v8 vs instanbul!).

**Comment by ndelangen** [comment]
If we do this, than there's no point in this PR: https://github.com/storybookjs/storybook/pull/29763 right?

@shilman What's the decision here? 

- Do we try to setup with `istanbul` and only install that? 
- Do we install both into the user's project?
- Do we auto-install v8, because that's the default?

I have to assume there's a reason why the `vitest` team decided to make both providers are opt-in to install.

**Comment by JReinhold** [comment]
Decision:

- During the addon's postinstall, detect if either `@vitest/coverage-v8` or `@vitest/coverage-istanbul` is installed. If _neither_ of those are, automatically install `@vitest/coverage-v8`, with a log line explaining why.
- ... That means we won't try to be smart and detect which provider is _potentially_ configured already, we assume that if a package is installed, it is correctly configured.
- This can still fail in a few edgy scenarios, which is why we still wan't to move forward with https://github.com/storybookjs/storybook/pull/29763 to ensure a good error message at runtime.
