### ISSUE TITLE
Allow withViewport() of @storybook/addon-viewport to accept viewport object for adhoc breakpoints

### ISSUE THREAD

**Issue by JasonKleban** [storybookjs/storybook#4809]
Feature Request:  Allow withViewport() of @storybook/addon-viewport to accept viewport object for adhoc breakpoints.

```
    .addDecorator(withViewport({
        name: '1024px - 1279px',
        styles: {
            minWidth: '1024px',
            maxWidth: '1279px',
            width: '100%',
            height: '100%',
        },
        type: 'desktop'
    }))
```

Use case:  There's component that has special rules for responsiveness - parts of it disappear when they need to for the component to crush down to smaller widths - heavily dependent on the pixel widths of the subcomponents.  These breakpoints are not important for other components in the application so I don't want to muck up the global list of sizes with these adhoc sizes.  Passing in the object doesn't work currently.

**Comment by stelmakh** [comment]
I'd be happy to work on this issue

**Comment by igor-dv** [comment]
@stelmakh, you are welcome to do so 😉

**Comment by ChrisSMendoza** [comment]
Hi @igor-dv, I can't tell if this still needs to be worked on. Since we can add [custom viewports](https://storybook.js.org/docs/react/essentials/viewport#add-new-devices), couldn't we add a viewports for `1024px` and `1279px`, then switch between those? I don't know the inner workings of Storybook or the viewport add-on, but it seems like setting `maxWidth` and `minWidth` wouldn't help since we can't resize the preview iframe.

**Comment by shilman** [comment]
Yeah I think you're right @ChrisSMendoza and this is more or less supported. Closing!
