### ISSUE TITLE
Addon Panel resets on story change

### ISSUE THREAD

**Issue by airtonix** [storybookjs/storybook#6077]
**Describe the bug**
When using actions, knobs and a11y, switching between stories, the selected addon tab is reset to actions tab.

**To Reproduce**

1. Have actions, a11y and knobs installed and configured
1. Click on a story
1. select the a11y tab
1. select another story
1. See that the selected tab is now actions

**Expected behavior**
last selected tab should remain selected and active.

if i had a11y selected, it should remain selected but updated with info about newly selected story.

**Screenshots**
![2019-03-14!UNITO-UNDERSCORE!10-29-58](https://user-images.githubusercontent.com/61225/54322193-2d1b6000-4644-11e9-9c64-a26cfed5c04b.gif)

**System:**

* OS: Windows10 (but our storybook runs in docker)
* Device: n/a
* Browser: Chrome Version 72.0.3626.121 (Official Build) (64-bit)
* Framework: React
* Addons: Actions, A11y, Knobs
* Version: 5.0.1

**Additional context**

**`package.json`**

```
...
  "dependencies": {
    "@babel/core": "7.2.2",
    "@babel/polyfill": "^7.0.0",
    "@storybook/react": "5.0.1",
    "@storybook/addon-actions": "5.0.1",
    "@storybook/addon-knobs": "5.0.1",
    "@storybook/addon-links": "5.0.1",
    "@storybook/addon-storysource": "5.0.1",
    "@storybook/addon-a11y": "5.0.1",
    "storybook-host": "5.0.3",
    "storybook-addon-jsx": "6.0.0",
    "axios": "^0.18.0",
    "babel-loader": "8.0.5",
    "babel-plugin-require-context-hook": "1.0.0",
    "eslint": "^5.5.0",
    "eslint-config-airbnb": "^17.1.0",
    "eslint-config-prettier": "^3.0.1",
    "eslint-plugin-import": "^2.14.0",
    "eslint-plugin-jsx-a11y": "^6.1.1",
    "eslint-plugin-prettier": "^2.6.2",
    "eslint-plugin-react": "^7.11.1",
    "formstate": "^1.0.2",
    "gatsby": "2.1.14",
    "gatsby-cli": "2.4.11",
    "gatsby-image": "^2.0.29",
    "gatsby-plugin-manifest": "^2.0.18",
    "gatsby-plugin-offline": "^2.0.24",
    "gatsby-plugin-react-helmet": "^3.0.6",
    "gatsby-plugin-sharp": "^2.0.21",
    "gatsby-source-filesystem": "^2.0.21",
    "gatsby-plugin-sass": "2.0.10",
    "gatsby-transformer-sharp": "^2.1.14",
    "gatsby-plugin-alias-imports": "1.0.5",
    "history": "^4.7.2",
    "lodash": "^4.17.11",
    "localstorage-ponyfill": "1.0.2",
    "mobx": "^5.1.0",
    "mobx-react": "^5.2.8",
    "npm-run-all": "4.1.5",
    "node-sass": "4.11.0",
    "onchange": "5.2.0",
    "prettier": "^1.14.2",
    "react": "^16.6.3",
    "react-dom": "^16.6.3",
    "react-helmet": "5.2.0",
    "react-error-overlay": "5.1.3",
    "semantic-ui-react": "^0.84.0",
    "require-context.macro": "1.0.4",
    "webpack": "4.29.5",
    "style-loader": "0.23.1",
    "css-loader": "2.1.0",
    "sass-loader": "7.1.0",
    "color": "3.1.0"
}
...
```

**Comment by malykhinvi** [comment]
@shilman that bug has the same nature as https://github.com/storybooks/storybook/issues/6114, but can be fixed relatively easy. The root cause is that on story change, setOptions is called, and selectedPanel is changed, even though it is undefined in the options.

@airtonix do you plan to work on it by yourself? If not, I could help with that.

**Comment by shilman** [comment]
Ooh-la-la!! I just released https://github.com/storybooks/storybook/releases/tag/v5.1.0-alpha.11 containing PR #6149 that references this issue. Upgrade today to try it out!

Because it's a pre-release you can find it on the `@next` NPM tag.

**Comment by Hypnosphi** [comment]
I can reproduce it in `5.3.0-alpha.23`:

– Open https://storybookjs-next.now.sh/official-storybook/
– Switch to "Actions" panel
– Select some other story in the same kind

Panel resets to "Accessibility"

**Comment by MichaelArestad** [comment]
This was something that confused me as well. Here is some clarification.

## When panels switch

On Storybook's storybook, some stories will switch to a specific panel. This is intentional on some stories and is set at a story level. For example, in the `Addons/A11y/BaseButton` story, you can see a parameter is set to switch to the accessibility panel.

```javascript
export default {
  title: 'Addons/A11y/BaseButton',
  component: BaseButton,
  parameters: {
    options: { selectedPanel: 'storybook/a11y/panel' },
  },
};
```

This behavior is mysterious to me and probably shouldn't be used much. Thankfully, it is rare that a story will select a specific panel.

## Default Behavior

By default, the panels do not switch. For example, in Storybook, [navigate to one of the stories in the Basics category](https://5a375b97f4b14f0020b0cda3-bactiuydey.chromatic.com/?path=/story/basics-button--all-buttons). Switch to a different addon panel. Then, navigate to another story in that category.
