### ISSUE TITLE
[addon-notes] How to add more languages to highlight.js support?

### ISSUE THREAD

**Issue by simbo** [storybookjs/storybook#6144]
We're using storybook 5.0.1 with addon-notes for an angular project.

Source code highlighting of code blocks from markdown docs works fine for default languages like `js`, `css` and `html`. The code parts are wrapped respective elements an are colored.

But when I want to highlight other languages, e.g. `ts`, `scss` or `pug`, all code is just black as highlight.js doesn't seem to know about these languages...

How can I add more languages to highlight.js support for code blocks in addon-notes?

**Comment by kroeder** [comment]
I am also interested in this topic because we are heavily using typescript snippets. I thought about to add typescript support as a default
If it is easy to add a couple more I also will look into this.

Adding language support yourself was possible in the old syntax but I'm not sure if it works anymore - maybe @ndelangen can answer this?

We did it that way (doesn't work anymore):

```typescript
export function withHighlightedNotes(markdown?: string) {
    return withNotes({
        markdown,
        markdownOptions
    });
}

export const markdownOptions = {
    highlight: (code: string, lang: string) => {
        const grammar = languages[lang];
        if (!grammar) {
            return code;
        }
        const highlighted = highlight(code, grammar, lang as any /* bug in @types/prismjs */).replace(/\n/g, '<br>').trim();
        const style = `padding: 7px 14px 7px 14px; background: whitesmoke; border: solid; border-width: 1px; border-color: silver`;
        return `<div style="${style}">${highlighted}</div>`;
    }
};
```

and a `manager-head.html` with
```html
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/prism/1.15.0/themes/prism.min.css">
```

If it is still possible to add own language support we should add this to the documentation.

**Comment by ndelangen** [comment]
@kroeder did you find a work-around / solution yet?

**Comment by jonkwheeler** [comment]
Is there any documentation on this? I checked out #6797 but I don't believe ability to change syntax theme changed. Any ideas?
