### ISSUE TITLE
Tree of stories loses order on HMR

### ISSUE THREAD

**Issue by snowystinger** [storybookjs/storybook#6439]
**Describe the bug**
Tree of stories loses order on hmr

**To Reproduce**
1. Run storybook
1. Edit a story
1. Watch that story drop to the bottom of the tree

**Expected behavior**
Tree should stay in order

**Screenshots**
<img width="374" alt="Screen Shot 2019-04-05 at 4 09 26 PM" src="https://user-images.githubusercontent.com/698229/55660852-3fa93500-57bd-11e9-84dc-ea658243a64d.png">
<img width="430" alt="Screen Shot 2019-04-05 at 4 09 40 PM" src="https://user-images.githubusercontent.com/698229/55660851-3fa93500-57bd-11e9-853d-e5207800df10.png">

**Code snippets**
If applicable, add code samples to help explain your problem.

**System:**
 - OS: MacOS
 - Device: Macbook Pro 2018
 - Browser: chrome, safari
 - Framework: react
 - Addons:
 - Version: 5.1.0-alpha.22

**Additional context**

**Comment by snowystinger** [comment]
I'm happy to work on a fix for this, but I'm actually having a bit of trouble tracking down where the loading of stories happens and this component

**Comment by shilman** [comment]
Related: #5827

**Comment by snowystinger** [comment]
More information on this
https://github.com/storybooks/storybook/blob/next/lib/client-api/src/story_store.js#L141 is called to add a story. When HMR fires, it calls https://github.com/storybooks/storybook/blob/next/lib/client-api/src/story_store.js#L136 and then calls https://github.com/storybooks/storybook/blob/next/lib/client-api/src/story_store.js#L141 again.

This is important because the rendering of the stories is done using https://github.com/storybooks/storybook/blob/next/lib/ui/src/components/sidebar/treeview/utils.js#L8 which loops over the object in the order in which keys were added.
So our render order cannot be preservable because import order can change from run to run.

The most straight forward solution would probably be to copy the entire this._data removing and re-adding all the keys for each "addStory" via a sorting function from global options. The good news is it's not a real copy, so it shouldn't take that long. The bad news is that it would happen a lot during start up...

Thoughts?

**Comment by shilman** [comment]
IMO the right solution is to add sorting. Users want it, and then it ends any questions about what the order should be.

**Comment by shilman** [comment]
@tmeasday does this fall under your purview?

**Comment by tmeasday** [comment]
@snowystinger sorry I did not comment on this sooner. As I mentioned here: https://github.com/storybooks/storybook/pull/6472#issuecomment-488481890 I don't think sorting in the treeview is correct, and I think probably sorting on the manager side in `setStories` is the way to go.

Another small thing is that I noticed [here](https://github.com/storybooks/storybook/issues/5925#issuecomment-487845388) that the sort order of roots is currently inconsistent across browsers due to a miswritten `.sort()` function.

While we fix this issue it would make sense to reimplement `sortStoriesByKind` (https://github.com/storybooks/storybook/issues/5827) -- I suppose this is what you are doing by default now.

I am not sure if it's going to fly with users to remove the current default (sort stories by import order), even if it does have this bug right now.

---

I wonder if we can fix this issue another way (without sorting). One hacky solution would be:

1. When removing, instead of `delete hash[id]` we do `hash[id] = removedSymbol`;
2. When publishing stories, filter out any removed symbols.

@shilman I think we should keep this problem in mind when thinking about how to handle HMR for `load`-ed stories.

**Comment by tmeasday** [comment]
@snowystinger feel free to reach out on discord if you want to get into the details of this together.

**Comment by shilman** [comment]
@tmeasday love the hack 💯

**Comment by tmeasday** [comment]
Actually I thought a bit more about this in discussions with @shilman and I'm thinking we could after all sort the stories in the preview before sending them over the wire.

Basically the format that goes over the wire is a large array of stories (although it is actually an object). We could in fact sort the stories in the `extract()` function (using the path/root separator as required).

If the stories enter the manager in the correct order then no special sorting would be required to make the treeview look right. I think this is the way to go because it makes other code that is interested in the story order able to rely on `extract` etc rather than having to re-implement sorting. It'll also allow us to support a custom sorting function.

**Comment by beshanoe** [comment]
Hi there. This bug seems pretty serious, it ruins the whole nice experience of developing in storybook. Are you waiting for PR? Is there a solution you agreed on?

**Comment by tmeasday** [comment]
Hi @beshanoe - yes, you are correct, that PR contains a fix, and will be merged into our main release branch sometime after 5.1 is released (very soon). I'm not quite sure when the fix will make it out.

**Comment by shilman** [comment]
Whoopee!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.2.0-alpha.31 containing PR #6472 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.
