### ISSUE TITLE
Expose method to stop in standalone dev server

### ISSUE THREAD

**Issue by disintegrator** [storybookjs/storybook#6554]
**Is your feature request related to a problem? Please describe.**
Currently, I am able to start a standalone storybook in dev mode but cannot stop it. I am attempting to start the server before running storyshots+puppeteer then tear it down.

I have the following jest globalSetup module but it does not seem to work because jest complains that it was unable to exit cleanly:

```js
// jest/globalSetup.js

import { join } from "path";
import storybook from "@storybook/react/standalone";

module.exports = async () => {
  await storybook({
    port: 6006,
    mode: "dev",
    ci: true,
    configDir: join(process.cwd(), ".storybook"),
    extendServer: srv => {
      srv.unref();
    }
  });
};
```

Jest output:

```
Test Suites: 1 passed, 1 total
Tests:       10 passed, 10 total
Snapshots:   0 total
Time:        7.167s
Ran all test suites.
Jest did not exit one second after the test run has completed.

This usually means that there are asynchronous operations that weren't stopped in your tests. Consider running Jest with `--detectOpenHandles` to troubleshoot this issue.
```

So it seems that calling `unref()` is not enough.

**Describe the solution you'd like**

Ideally the following would work just fine without needing jest's globalSetup:

```js
// storyshots.test.js

import { join } from "path";
import storybook from "@storybook/react/standalone";
import initStoryshots from "@storybook/addon-storyshots";
import { imageSnapshot } from "@storybook/addon-storyshots-puppeteer";

let instance = null;

beforeAll(async () => {
  instance = await storybook({
    port: 6006,
    mode: "dev",
    ci: true,
    configDir: join(process.cwd(), ".storybook"),
    extendServer: srv => {
      srv.unref();
    }
  });
})

afterAll(async () => {
  if (instance) {
    await instance.stop();
  }
})

describe("Image storyshots", () => {
  initStoryshots({ suite: , test: imageSnapshot() });
});
```

**Describe alternatives you've considered**

**Are you able to assist bring the feature to reality?**
I think I can but would appreciate guidance...

**Comment by wallynm** [comment]
For anyone that might need this in future i've achieved a nice solution using this NPM:
https://www.npmjs.com/package/start-server-and-test which is responsible for automatically starting a server and finishing it after the test process ends, you can check instructions on how to configure inside the NPM repository.

The only thing i needed to ensure was about the start process, in order to execute and finish correctly you need to use the `build-storybook` command using the `http-server` npm, heres my package.json scripts to use as example:

```
  "scripts": {
    "test:all": "start-server-and-test start:test http://localhost:6010 test",
    "start:test": "build-storybook && http-server .storybook-static -s -p 6010",
    "start:dev": "start-storybook --quiet -p 6006",
    "build-storybook": "build-storybook -o .storybook-static",
    "lint": "eslint \"./src/**/*.{js,ts,tsx,spec.js}\"",
    "test": "jest --rootDir . --maxWorkers=2 --reporters=jest-junit --reporters=default --coverage"
  }
```

The importants scripts there are: 
`test:all` starts the server and runs the test command waiting for response at the port 6010
`build-storybook` Wich build the storybook to be used statically at the CI server
`start:test` which builds and them serves the storybook using the same port configured.

With those URL's i was able to make the whole process work as i needed!
Hope this can help someone in future!
