### ISSUE TITLE
Knobs causing re-renders on react native

### ISSUE THREAD

**Issue by bryankang** [storybookjs/storybook#6679]
To reproduce, use `react-native` and install `5.1.0-alpha.36`. Add required dependencies to use `react-native-server` and register `addon-knobs`. Use a knob inside a render method and call `console.log` with something. Build it, run it, debug on browser. You can see that it'll log (implying unnecessary re-renders) every half second or so.

Possibly related to #6675 but no action is required to see the bug I mentioned above.

**Comment by lyqht** [comment]
Any updates to this? 
Might be relevant to the issue that I brought up for #6918

**Comment by y-nk** [comment]
looks to me related to Vue and other frameworks as well :/

**Comment by leoyli** [comment]
It seems a recurrent bug. The above #6705, #6863 all share the same root cause.

This probably would trace back to #6022 PR. Unfortunately, I'm currently busy in my day-time job and would stay focus on migrate `@storybook/ui` into TS. If anyone would be able to voluntarily help out would much be appreciated. 🙏

Also, I think @ndelangen have some works/explorations on rewriting knobs?
