### ISSUE TITLE
UX: Wrong search results

### ISSUE THREAD

**Issue by cestrensem** [storybookjs/storybook#6883]
**Describe the bug**
Search does't work correctly

**To Reproduce**
1. Add cursor to search box
2. Try to find something

**Screenshots**
![image](https://user-images.githubusercontent.com/3720256/58403282-90713780-8062-11e9-8008-57f4fa625ba0.png)

**System:**
 - OS: MacOS
 - Device: Macbook Pro 2018
 - Browser: chrome
 - Framework: react
 - Version: 5.0.11

**Comment by huston007** [comment]
I believe search may be more specific and show only stories which have match in story name or in hierarchy path.

**Comment by shilman** [comment]
The problem here is that search searches over more fields than just the name of the story. Some of our users, including @ndelangen (who wrote the feature), insist that it's a good idea. I think it should be removed until we implement visual feedback on the search to show why these stories are matching.

Here's the other side of the issue: https://github.com/storybookjs/storybook/issues/6483

**Comment by huston007** [comment]
@shilman Thank you for you answer!

I totally agree that there might be different cases where such smart search would be useful. But I'd also like to share what exactly issue we have in our [Ring UI library](https://jetbrains.github.io/ring-ui/) – If you want to open, for example, "Button Ng" story, it is at the very bottom:
![image](https://user-images.githubusercontent.com/4318513/59057534-3c0c5a00-88a3-11e9-8d5d-6ea71c80bb8c.png)

Storybook works really great for us, but it could be even better. You may find it useful to allow to customize search predicate in Storybook config somehow:

```js
addParameters({
  options: {
    searchPredicate: (path, notes, content) => /* search logic */
  }
});
```

**Comment by shilman** [comment]
@huston007 That is one good looking storybook!!! ❤️❤️❤️ 

That's a clean solution to the search issue & would be easy to implement. I'd modify it slightly to where the config function gets the story context (params + other metdata) & the function can return a string to be indexed.

But before we add anything, I'd like to figure out what the long-term solution should be for discoverability from a UX standpoint and then build towards that.

cc @ndelangen @domyen @tmeasday

**Comment by ndelangen** [comment]
@shilman @cestrensem How about we do normal "only on name based" filtering, and then when the user filters to 0 results we show a hint:

> Nothing found for this query, start your query with a `/` to enable fuzzy search.

And then obviously build a feature where if the query starts with a `/` we search more fields?

I'd really like it if instead of us writing it for everyone, this part of storybook would become pluggable, so addons could change this behavior.

**Comment by huston007** [comment]
I've just updated to Storybook@5.1.9 and search works much selective now. Thank you!
<img width="209" alt="Screenshot 2019-07-01 at 14 27 18" src="https://user-images.githubusercontent.com/4318513/60432995-59b3b180-9c0c-11e9-9f0e-eb7f92c7e134.png">

**Comment by shilman** [comment]
@huston007 @ndelangen LOL did we change anything? 🙀
