### ISSUE TITLE
Angular addParameters missing from index.d.ts

### ISSUE THREAD

**Issue by chriscarpenter12** [storybookjs/storybook#6927]
**Describe the bug**
`addParameters` is not defined in `app/angular/src/client/preview/index.d.ts`

**To Reproduce**
Import `addParameters` into storybook config.

**Expected behavior**
IDE warnings.

**Screenshots**
![Screenshot from 2019-05-31 14-03-17](https://user-images.githubusercontent.com/458486/58726158-fe916380-83ae-11e9-90e0-d051a157636b.png)

**System:**
 - OS: Ubuntu 18.04
 - Framework: Angular
 - Version: 5.0.11

**Comment by shilman** [comment]
Zoinks!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.1.0-rc.5 containing PR #6929 that references this issue. Upgrade today to try it out!

Because it's a pre-release you can find it on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.
