### ISSUE TITLE
"About your version" has layout issues (elements overlap) in `5.1.0-rc.4`

### ISSUE THREAD

**Issue by alechp** [storybookjs/storybook#6953]
**Describe the bug**
Elements overlap (screenshots below)

<img width="952" alt="Screen Shot 2019-06-03 at 11 10 42 AM" src="https://user-images.githubusercontent.com/3058939/58824553-2e2fae00-85f1-11e9-8dcb-07d9752be512.png">
<img width="1792" alt="Screen Shot 2019-06-03 at 11 10 47 AM" src="https://user-images.githubusercontent.com/3058939/58824554-2e2fae00-85f1-11e9-806a-0693cdc86396.png">

**To Reproduce**
1. Sample repo used to produce this can be cloned here: https://github.com/servexyz/react-native-expo-storybook-v5

**Comment by shilman** [comment]
@ndelangen I see this issue in general when I have bugs in the story loading. Seems like there's an error handling issue somewhere in Core / Storybook UI. Any ideas?

**Comment by shilman** [comment]
Kind of dupe to #6493

**Comment by shilman** [comment]
Ta-da!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.1.0-rc.5 containing PR #6968 that references this issue. Upgrade today to try it out!

Because it's a pre-release you can find it on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.
