### ISSUE TITLE
Use source-map-loader by default

### ISSUE THREAD

**Issue by aleclarson** [storybookjs/storybook#7022]
**Is your feature request related to a problem? Please describe.**
Source maps for `.js` modules aren't used

**Describe the solution you'd like**
Include [`source-map-loader`](https://github.com/webpack-contrib/source-map-loader) in the default webpack config

**Are you able to assist bring the feature to reality?**
no

**Comment by justingrant** [comment]
Be careful: the current latest of `source-map-loader` doesn't correctly handle relative URLs in the `sources` array of the sourcemap. Given that open-source libraries must use relative URLs in sourcemaps (because they won't know where the library is going to be installed on the user's machine), this makes the current `source-map-loader` essentially useless.

https://github.com/webpack-contrib/source-map-loader/pull/75 is a PR from @volune that should fix this problem, but it's been waiting for maintainer review for almost a year. Unfortunately this isn't unusual, as that library it hasn't had any commits since Aug 2018.  I assume that maintainers aren't maintaining it anymore.  ;-(

Anyway, `source-map-loader` is just one short JS file.  If you use it then given its current limitations and lack of maintainer support, you might want to fork it instead of depending on it. That's what I've been doing. I forked https://github.com/Volune/source-map-loader/tree/fixes.
