### ISSUE TITLE
Storybook 5 for React Native: "Can't find variable: document"

### ISSUE THREAD

**Issue by yongching** [storybookjs/storybook#7067]
**Describe the bug**
I'm running into this issue "Can't find variable: document" error when launching react-native app with storybook. I have commented out `addon.js` in index.js but it is still returning the same error.

**To Reproduce**
git clone https://github.com/yongching/storybook-bug
1. yarn storybook
2. yarn haul
3. react-native run-ios
4. see error

<img width="351" alt="Screenshot 2019-06-13 at 12 49 25 AM" src="https://user-images.githubusercontent.com/10132189/59370634-87c47500-8d75-11e9-95a8-5b711560eeb0.png">

**Code Snippet**
*package.json*
```js
{
  "name": "StorybookBug",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest",
    "haul": "haul --platform ios --eager ios",
    "storybook": "start-storybook -p 7007"
  },
  "dependencies": {
    "react": "16.8.3",
    "react-dom": "16.6.1",
    "react-hot-loader": "4.8.0",
    "react-native": "0.59.0"
  },
  "devDependencies": {
    "@babel/core": "^7.4.5",
    "@babel/runtime": "^7.4.5",
    "@emotion/core": "^10.0.10",
    "@storybook/addon-actions": "^5.1.3",
    "@storybook/addon-links": "^5.1.3",
    "@storybook/addons": "^5.1.3",
    "@storybook/react-native": "^5.1.3",
    "@storybook/react-native-server": "^5.1.3",
    "babel-jest": "^24.8.0",
    "babel-loader": "^8.0.6",
    "emotion-theming": "^10.0.10",
    "haul": "^1.0.0-rc.15",
    "jest": "^24.8.0",
    "metro-react-native-babel-preset": "^0.54.1",
    "react-test-renderer": "16.8.3"
  },
  "jest": {
    "preset": "react-native"
  }
}
```

**Expected behavior**
It should run without any issues.

**System:**
 - OS: [e.g. iOS, MacOS]
 - Device: [e.g. iPhoneX, Macbook Pro 2015]
 - Framework: [e.g. react-native 0.59.0]

**Comment by apexskier** [comment]
I'm seeing this as well. Looking into the stack trace, this line appears to be triggering the issue: https://github.com/emotion-js/emotion/blob/41f7ba1c6b7f74cde2c6b6fd5f3333e02e2c154b/packages/cache/src/index.js#L69
That's supposed to be stripped out for non-browser environments, but the `cache.browser.cjs.js` file is being loaded, so it's still there and is failing.

**Comment by benoitdion** [comment]
@apexskier @yongching I wonder if this is because you're using haul. Are you able to reproduce with the metro bundler?

**Comment by apexskier** [comment]
That could be the case, we're using haul as well. I'm unable to build our project with metro alone though, so I can't test reproduction there.

**Comment by benoitdion** [comment]
haven't played with the bug repro repo yet but based on what I'm seeing it looks like it may be an emotion issue with haul :(

**Comment by SerhiyZheliznjak** [comment]
Hi!
Got the same issue, not using haul.

**Comment by yongching** [comment]
@benoitdion I just did a quick experiment using metro bundler, it has the same issue. Here's the repo, https://github.com/yongching/storybook-with-metro.

**Comment by SerhiyZheliznjak** [comment]
Btw, as soon as you don't use any addons the issue is gone

**Comment by yongching** [comment]
@SerhiyZheliznjak yeah true. But when I use it with haul, even if I remove all the addons it will still have the issue.

**Comment by alexakasanjeev** [comment]
Hi @yongching @SerhiyZheliznjak I opened a similar issue #6910 , please look into it 

Basically If you are using `@storybook/react-native-server` you don't need to import action addon. `react-native-server` will do it automatically (explained in this [comment](https://github.com/storybookjs/storybook/issues/6910#issuecomment-500332291)) so in your `storybook/index.js` comment out the line which is importing addon, and it will work fine.

If it's still unclear let me know.

**Comment by yongching** [comment]
@alexakasanjeev may I know which repo did you clone? The one with metro bundler will work fine if I remove the addons https://github.com/yongching/storybook-with-metro. But not the one with haul https://github.com/yongching/storybook-bug.

**Comment by alexakasanjeev** [comment]
I cloned https://github.com/yongching/storybook-bug this repo and I did run `yarn haul` and it worked fine, also I explained in the comments above that if you are using react-native-server then you don't need to add action addon, it will do automatically

**Comment by Gongreg** [comment]
@alexakasanjeev, thank you for raising that point. Someone accidentally added the import to the template. Created PR https://github.com/storybookjs/storybook/pull/7096 to fix it.

**Comment by Gongreg** [comment]
Okay, so there are two issues. One is accidentally added ./addons import when installing storybook and two, incompatibility between haul and emotion.

Could we please leave this discussion for haul/emotion incompatibility?

**Comment by apexskier** [comment]
@SerhiyZheliznjak I'm using `@storybook/react-native@5.1.0-alpha.8`, `@storybook/react@5.1.4`, and `haul@1.0.0-rc.15` successfully.

**Comment by yongching** [comment]
@alexakasanjeev thanks for pointing that out. After commenting the addons import, android would work. But iOS still the same.

**Comment by yongching** [comment]
@apexskier that worked for me on ios! Thank you so much.

**Comment by jaridmargolin** [comment]
I've been able to track this pesky error down.

I am confident this is not an issue with Storybook, but instead, it is with **webpack** or **Haul**. The behavior I am seeing from **webpack** is what I would deem unexpected, but it is perhaps intended. I need to dig a little further to determine where exactly the fix should be introduced.

## What is happening?

`emotion` utilizes the `browser` and `react-native` fields within its [package.json](https://github.com/emotion-js/emotion/blob/master/packages/core/package.json#L6) (more information [here](https://github.com/defunctzombie/package-browser-field-spec)). Unexpectedly, when compiling, `emotion-theming` and `@emotion/core` are resolving to utilize the `browser`dist files.

This is misleading because the **Haul** config appears to [correctly set](https://github.com/callstack/haul/blob/b0b001c979f77c4a1656bfae42de0bb138858198/src/utils/makeReactNativeConfig.js#L224) `resolve.mainFields` to `['react-native', 'browser', 'main']`, which defines that `react-native` should take prescedence.


## Solutions

It turns out that there is another field, `aliasFields`, which **webpack** [adds a default option](https://github.com/webpack/webpack/blob/8522a2d86d316b9a5924c0ca4179af9634a9c44b/lib/WebpackOptionsDefaulter.js#L326) for when running with the `web` or `webworker` target (**Haul** sets `target: 'webworker'`). The `aliasFields` will be resolved regardless of what is set in `mainFields`.

The question now becomes, is it correct for **webpack** to resolve `aliasFields` regardless of if the `aliasFields` exist in `mainFields`? If the answer is yes, then **Haul** needs to update it's config to add `react-native` to `aliasFields`. If the answer is no, then **webpack** needs to be patched.


## Temporary Workaround

In the meantime, ya'll can work around this by modifying your **Haul** config:

```
const config = createWebpackConfig({ entry })(env)
config.resolve.aliasFields = ['react-native', 'browser']
return
```
