### ISSUE TITLE
Addons-docs: interaction with api

### ISSUE THREAD

**Issue by atanasster** [storybookjs/storybook#7983]
Related to  #6700, use case:

The Docs panel does not send Events.STORY_RENDERED when rendering stories. And possibly other story events. Resulting in several addons not being able to interact with the stories.

example css-resources addon
to reproduce, use the Official storybook/Cssresources story:

On the Docs page:
![screenshot817](https://user-images.githubusercontent.com/6075606/64216330-74add680-ce86-11e9-8347-d8e8f9963b85.jpg)

On the Preview page:
![screenshot816](https://user-images.githubusercontent.com/6075606/64216334-7d061180-ce86-11e9-8394-1b59220f94f7.jpg)

**Comment by shilman** [comment]
Related #6700

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid.

Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
