### ISSUE TITLE
addon-docs: Failed prop type: Invalid prop `viewMode` of value `docs` supplied to `Preview`, expected one of ["story","info"].

### ISSUE THREAD

**Issue by alisonsayarath** [storybookjs/storybook#7988]
**Describe the bug**
When using addon-docs with MDX, my component in the Canvas tab is shown, but nothing in the Docs tab shows.

**To Reproduce**
Configure the new Storybook beta with `docs-addon` while adding those presets : 
```
module.exports = [
  {
    name: "@storybook/addon-docs/react/preset",
    options: {
      configureJSX: true,
      sourceLoaderOptions: null,
    },
  },
];
```

Versions : 
- @storybook/react": "^5.2.0-beta.32"
- @storybook/addon-docs: "^5.2.0-beta.32",

**Screenshots**

Story `base.story.mdx` : 

![Screenshot 2019-09-04 at 15 31 54](https://user-images.githubusercontent.com/22907111/64259329-29003900-cf29-11e9-933f-00b5f2b34492.png)

Config `config.js` : 

![Screenshot 2019-09-04 at 15 33 41](https://user-images.githubusercontent.com/22907111/64259469-6795f380-cf29-11e9-89b4-712b43724a79.png)

My component shows well in the Canvas tab, however, when I go to the Docs tab, I am having the following errors : 

![Screenshot 2019-09-04 at 15 35 03](https://user-images.githubusercontent.com/22907111/64259621-ac218f00-cf29-11e9-932e-aa7a80fb1b08.png)

**Comment by shilman** [comment]
@alisonsayarath That error looks like you're somehow using an old version of Storybook. Can you:

1. Make sure `@storybook/*` in `package.json` are all at the same version
2. If they are, remove node_modules and (and possibly your .lock file) and reinstall
3. Try `yarn list @storybook/ui` to make there's only one version and it's the same version.

Also, I'd recommend upgrading to `5.2.0-rc.5` (the latest), but that's not related to your problem here.

**Comment by alisonsayarath** [comment]
Thanks for the quick answer!

And it shows two versions : 
- `@storybook/react@5.2.0-rc.5` 
- `@storybook/ui@5.1.11`

We have two version because we use a custom CRA (so we had to fork the 5.1.11 to make our command `yarn storybook` work). We better wait until Docs are not beta anymore 🤕

**Comment by lonyele** [comment]
@shilman yeah, it's been awhile seeing these errors. Probably when addon architecture or the routing architecture was changed. Maybe little bit more info from #7241
> What is missing here(TODO)
I think the following PR is needed to resolve this issue of PropType warnings by getting the lists of possible viewMode from all the registered addons and others for strongly type viewMode.

**Comment by shilman** [comment]
@alisonsayarath why did you need to fork it? that will def cause problems. docs should be stable release in the next two weeks.

**Comment by shilman** [comment]
@lonyele Yeah those routes were hard-coded in 5.0 due to lack of time. And I think they are hard-coded again in 5.2. But we expect our users to use the same version of our libraries, and don't make guarantees if they are not. This is not pure semver, but practically speaking it's worked for us so far aside from this kind of case (e.g. people mixing 5.1 & 5.2 together), which unfortunately happens fairly often.

**Comment by renatoholanda** [comment]
I change all in the same version on `package.json` and it works.

```js
{
// ...
"@storybook/addon-actions": "^5.2.0-rc.5", // was 5.1.11
"@storybook/addon-docs": "^5.2.0-rc.5", 
"@storybook/addon-links": "^5.2.0-rc.5", // was 5.1.11
"@storybook/addons": "^5.2.0-rc.5", // was 5.1.11
"@storybook/react": "^5.2.0-rc.5" // was 5.1.11
// ...
}
```

**Comment by alisonsayarath** [comment]
> @alisonsayarath why did you need to fork it? that will def cause problems. docs should be stable release in the next two weeks.

Oups, sorry for the late answer. We have multiple CRA base config modes.
