### ISSUE TITLE
Depend on the bundled version of the Angular library

### ISSUE THREAD

**Issue by sparqueur** [storybookjs/storybook#8012]
**Is your feature request related to a problem? Please describe.**
Currently, my storybook project does not rely the final bundled version of my library.
It directly import components.
It works well but it is not a good practice as the final package may be broken and you don't see it (eg. missing exported exported elements in public-api.ts)

**Describe the solution you'd like**
You might provide a good architecture example where the library is build with a "watch" and the storybook uses the final bundle.

**Are you able to assist bring the feature to reality?**
no

**Additional context**

**Comment by kroeder** [comment]
I think you have to add `paths` to your root tsconfig.json
```
{
  compilerOptions: {
    paths: {
      "@yourProject/*": ["dist/*"]
      // and/or
      "@yourProject": ["dist/your-entry-point.js"]
    }
  }
}
```

Haven't tested it! If you create a mono-repo with the angular cli you get the configuration you want out of the box: `ng generate library your-lib-project`

The CLI will add paths to your `dist` instead of your `ts` files. You can use this as a template for what you are trying to achieve
