### ISSUE TITLE
Easy transition from Vue Design System to Storybook

### ISSUE THREAD

**Issue by antonija-nosto** [storybookjs/storybook#8174]
**Is your feature request related to a problem? Please describe.**
I want to push my team to consider Storybook over Vue Design System but more manual work it involves, less likely it will happen.

**Describe the solution you'd like**
Maybe some converter tool. Choose DS folder and then it scaffolds everything in Storybook

**Describe alternatives you've considered**
No alternatives.

**Are you able to assist bring the feature to reality?**
I would be up for it

**Comment by shilman** [comment]
@antonija-nosto Sorry for the late response. How can I best support you on this? I'm guessing it belongs in a separate project, but I'd be happy to offer support from the Storybook Docs side!

**Comment by elevatebart** [comment]
@antonija-nosto The biggest difference between VueDS and storybook is: 
There is no automated discovery of components in storybookjs for now. 
Storybook only detect stories files even with docs. So, if a component has no story, it does not show up in your docs. 
In order to set the migration path, the first task is probably to generate default stories for the components that have none.
@shilman is it still the case in 5.2 and is this compoennt detection on the roadmap?

**Comment by shilman** [comment]
@elevatebart we don't have anyone signed up for auto-discovery. Interested?

**Comment by elevatebart** [comment]
@shilman Yes, I am! What did you have in mind? 
I could see user gives a directory and we look for components in it.
Or a regular expression as an option to the preset?

**Comment by antonija-nosto** [comment]
This auto discovery thing would make transition much easier! I will keep my eyes close to this topic!

**Comment by shilman** [comment]
@antonija-nosto communicating with @elevatebart in chat to coordinate this and we'll post here if anything comes of it!

**Comment by antonija-nosto** [comment]
@shilman hey, I guess no progress on this topic?

**Comment by shilman** [comment]
Chatted with @elevatebart and sketched out some ideas, but not sure about the current status on his side
