### ISSUE TITLE
please remove @types dependencies of @storybook/components

### ISSUE THREAD

**Issue by eightHundreds** [storybookjs/storybook#8187]
Version:5.2.1

`@storybook/components` dependencies has `@types/react-syntax-highlighter` which force me to install `@types/react` in my project.
My project use `vue-tsx-support`,it has conflict with `@types/react`

**Comment by ndelangen** [comment]
Is the solution really to remove types from our side then? or is there some way for users to configure which types take precedent?

Surely we can't be the only package that might inject some conflicting types in the entire javascript ecosystem?

**Comment by jwbay** [comment]
It's far from a solved problem unfortunately. Consuming apps should be able to do something like `declare module '@types/react-syntax-highlighter'` instead of installing the real types.

**Comment by eightHundreds** [comment]
move `@types/react-syntax-highlighter` to `devDependencies` it should not be difficult.

**Comment by gaetanmaisse** [comment]
Moving `@types/react-syntax-highlighter` to `dependencies` was made here https://github.com/storybookjs/storybook/commit/df95686aeaba7da0bdfa97a9edb53a62723514c3 to fix https://github.com/storybookjs/storybook/pull/7072 😞 
This issue needs some deeper investigation in order to not reopen https://github.com/storybookjs/storybook/pull/7072 🕵

**Comment by NikitaIT** [comment]
This problem prevents me from using the library in my vue-tsx project. Because ts does not provide exclude for typeDirs, and explicitly I cannot afford to specify all @types. The only solution I've seen in other libraries is to split the library into "@storybook/addon-knobs/vue" and "@storybook/addon-knobs/react".
```
"vue": "~2.6.10",
 "@storybook/addon-knobs": "~5.2.6"
```

**Comment by ndelangen** [comment]
Users can configure typescript manually to ignore certain things:
https://www.typescriptlang.org/docs/handbook/tsconfig-json.html#types-typeroots-and-types

**Comment by NikitaIT** [comment]
@ndelangen this only works for inclusion, but not for exception. I have 40+ @types libraries, I don’t want to specify them explicitly to exclude one.

**Comment by ndelangen** [comment]
Have a raised an issue at Typescript repo?

**Comment by NikitaIT** [comment]
@ndelangen here are a number of common related questions, but I have not found any work in this direction:
https://github.com/microsoft/TypeScript/issues/17042
https://github.com/microsoft/TypeScript/issues/35122
The impossibility of exception at the moment is due to the fact that the paths are specified as path strings. This has not been resolved in 4 years and does not seem to be planned in the future. I think I'm not the one who is ready to open
request to solve this problem again and succeed.

**Comment by NikitaIT** [comment]
I leave the discussion, because I stay with @types/react as the main source of tsx types. 
Thanks for discussion.

**Comment by ndelangen** [comment]
@NikitaIT I sympathise with your frustration here, I really do.

We've got issues if we add then `@types/*` dependencies, we've got issues if we don't.

I wonder if you'd do something like:

```
{
   "compilerOptions": {
       "types" : ["@types/!(pattern|pattern|pattern)"]
   }
}
```

Could help?
