### ISSUE TITLE
Docs pages contents disappear and l.window.docsearch is not a function is in console

### ISSUE THREAD

**Issue by sattaman** [storybookjs/storybook#8193]
**Describe the bug**

Docs pages content disappear due and the following error is in the console
`TypeError: "l.window.docsearch is not a function"`

**To Reproduce**
Steps to reproduce the behaviour:

Navigate to live docs page (tested in chrome + firefox) on osx
https://storybook.js.org/docs/basics/live-examples/

The contents disappear and the above error is in the console

**Comment by sattaman** [comment]
I've found this happens only on our vpn, it may be worth adding something in to remedy though , as it may affect others?

**Comment by shilman** [comment]
Pretty strange. I'm not sure what's going on there!

**Comment by millerdj** [comment]
This also has happens on my companies network. I'm pretty sure its from our network blocking jsdelivr, which fails to load the docsearch.min.js & docsearch.min.css. Since cdn link is in the head and loads before the sites index.js, the page initially renders and then fails on the componentDidMount in the sites react Container.

You probably want your network administrator to allow traffic from jsdelivr cdn.
