### ISSUE TITLE
Generate title by folder structure

### ISSUE THREAD

**Issue by Evalon** [storybookjs/storybook#8222]
Component Story Format is great. But also a little frustrating when you use conventions by file and folder structure. Because you need always specified title, when it can be inferred from folder structure easily. Also when default export not used explicitly it's generate warning for unused export. There is so much can be automated when you follow specific structure.

Maybe it's possible to add configurations for how to infer title when default export title is not provided?

It's a little different from #7516 because one of purposes to not write default export at all when you need only title.

Brief glance in codebase: https://github.com/storybookjs/storybook/blob/next/lib/core/src/client/preview/start.js#L353-L381
Is it only place that should be changed (+ config) or this change should be more globally?

**Comment by shilman** [comment]
Right now the `configure` code intentionally assumes that there is a default export with a title property, so that if somebody tries to load a random JS file the code will error rather than failing silently. 

I don't want to change that.

However, I think we could achieve the same result by adding an opt-in webpack loader that injects the default export based on the file path.

Any interest in trying to tackle that?

**Comment by DragorWW** [comment]
We will can use mini helper for remove boilerplate

https://gist.github.com/DragorWW/cbf4b6a2d4543cb66552874527c89723

**Comment by obweger** [comment]
@shilman @Evalon I just published https://github.com/atlassian-labs/babel-plugin-storybook-csf-title if that's helpful!

**Comment by shilman** [comment]
Very cool @obweger -- will definitely recommend it when this comes up again (and it will).

**Comment by shilman** [comment]
For anybody who finds, this has been implemented inside CSF3 as part of SB6.4 https://storybook.js.org/blog/component-story-format-3-0/
