### ISSUE TITLE
How to enable [HMR] console logging in 5.2

### ISSUE THREAD

**Issue by eldewen** [storybookjs/storybook#8308]
I'm hesitant to upgrade from 5.1 to 5.2, as it appears Webpack's [HMR] console logging has been disabled. Can this be re-enabled through configuration?

I've tried creating `./.storybook/webpack.config.js` with:

```javascript
module.exports = async ({ config, mode }) => {
  config.devServer = { stats: "verbose" };
  return config;
};
```

...and an assortment of variations, but no change.

**Comment by shilman** [comment]
@ndelangen any ideas?

**Comment by cliffpyles** [comment]
I haven't figured out the solution, but I believe I've tracked down what is causing the behavior. From what I can tell the devServer configuration is being passed to Webpack correctly, and the configuration goes to `webpack-dev-middleware` as intended. The issue is with `webpack-hot-middleware` though. It allows for a `quiet` property to be passed and currently it is being set with a `true` value, which is suppressing output.

https://github.com/webpack-contrib/webpack-hot-middleware

I hope this helps!

**Comment by eldewen** [comment]
That's it! I'm not seeing an easy way to get to it through configuration, but in the line...

https://github.com/storybookjs/storybook/blob/a2a6b9d1663990e7450768985404f8eda652d162/lib/core/src/server/preview/preview-preset.js#L15

...changing `quiet=true` to `quiet=false` enables the console output again. Thanks!

**Comment by cliffpyles** [comment]
No problem. Glad you figured out!

**Comment by BPScott** [comment]
Yo @eldewen will you be opening up a PR for bring the warnings back?

**Comment by BPScott** [comment]
poke stale bot, I'd still like to see this ticket addressed

**Comment by shilman** [comment]
@ndelangen didn't you merge a PR relating to this for 6.0?

**Comment by shilman** [comment]
@BPScott see #9535

**Comment by ndelangen** [comment]
Yes, I think that resolves this issue.
