### ISSUE TITLE
storySort function jumps to 2nd group by default when sorting by kind

### ISSUE THREAD

**Issue by kevinSuttle** [storybookjs/storybook#8395]
:wave:  Hey all! I'm trying to sort my stories a certain way _and_ get the first group of the first story to be selected. This was working until I converted them to CSF, and now no longer. 

```
 storySort: (a, b) =>
      a[1].kind === b[1].kind
        ? 0
        : a[1].id.localeCompare(b[1].id, {numeric: true}),
```

The only thing wrong with this is it now defaults to the 1st story of the 2nd group, which is not ideal. I also tried `{numeric: false}` and just leaving that object out, but it's not doing what I would like to see. Any ideas? Are there docs on `storySort`?

<img width="580" alt="image" src="https://user-images.githubusercontent.com/95672/66693159-fa862400-ec73-11e9-8de2-fe8e10fceb46.png">

**Comment by tmeasday** [comment]
Hi @kevinSuttle, I think the issue here isn't strictly story sorting, it's the way roots vs non-roots are displayed in the sidebar. In your case, I think what's happening is the story order goes something like:

```
Action List Setting Sliders:Multiple....
Action List Setting Sliders:...
...
Design System|Button:....
...
```

So logically the action list story is first.

The reason that the design system components get listed first because of the way roots are handled. If *some* of your stories have roots (the bit before `|` that is displayed in all caps) but others don't, the ones without are put into an "Others" root and placed at the end. This doesn't affect the logical story ordering however.
