### ISSUE TITLE
Storybook Docs - Not able to write CSF stories in MDX in Gatsby monorepo. 

### ISSUE THREAD

**Issue by vinayg-cp** [storybookjs/storybook#8414]
**Description**

In my Gatsby themes project, I am trying to integrate the storybook using .mdx format. 
But the webpack of storybook is not able to convert the .mdx files. 

And it gives the following error:
![image](https://user-images.githubusercontent.com/43405939/66748439-d0677880-eea4-11e9-94aa-8df6d4f43548.png)

Repository: https://github.com/vinayg-cp/storybook-poc.git 

**To Reproduce**
1. Clone the repository. 
2. Install Dependencies. 
3. Start storybook. 

**Expected behavior**
Should be able to see mdx story of Card too. 

**System:**
Environment Info:

  System:
    OS: Windows 10
    CPU: (4) x64 Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz
  Binaries:
    Node: 10.15.3 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.17.3 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.17763.771.0

**Related Issue**
The props table in docs page is not getting created correctly for a normal js file. 
You can delete the card.story.mdx file and run ```yarn storybook```. 

Then under docs, I do not see other details for the props, like type.

**Comment by kfayelun** [comment]
Hey fellow gatsby user! I've been working on a setup of storybook 5.3.whatever-new-alpha-that-comes-out for a gatsby monorepo the last week and a bit. It's up and running now, but still not seeing props. I tested your Card story, and got it to work in my repo. I think your webpack config looks good, but you are missing the return in the config file. This is new for CSF stories, and described here: https://storybook.js.org/docs/basics/writing-stories/#loading-stories. So in my config file I have: `configure(require.context('../src', true, /\.stories\.(js|mdx)$/), module);`

**Comment by apanizo** [comment]
Hi everyone!

I have had the same issue you can just fork and run `yarn install && yarn storybook` here: https://github.com/apanizo/cra-sb

And I have been able to hack it by overriding ```generateSourcesInExportedParameters``` in source-loader/dist/server/abstract-syntax-tree/generate-helpers.js: 

```
function generateSourcesInExportedParameters(source, ast, additionalParameters) {
  return source;
}
```

I have not created a PR because I am missing some dots here.

@shilman  Can you give us some insights about what is going on?

Without the hack:
<img width="1426" alt="Screenshot 2019-10-14 at 17 52 06" src="https://user-images.githubusercontent.com/4266059/66765352-0a884880-eeac-11e9-9546-394300aae3e0.png">


With the hack:
<img width="1216" alt="Screenshot 2019-10-14 at 17 53 14" src="https://user-images.githubusercontent.com/4266059/66765370-11af5680-eeac-11e9-84d1-d9eb2b5397c5.png">


Thanks!!!!

**Comment by vinayg-cp** [comment]
> Hey fellow gatsby user! I've been working on a setup of storybook 5.3.whatever-new-alpha-that-comes-out for a gatsby monorepo the last week and a bit. It's up and running now, but still not seeing props. I tested your Card story, and got it to work in my repo. I think your webpack config looks good, but you are missing the return in the config file. This is new for CSF stories, and described here: https://storybook.js.org/docs/basics/writing-stories/#loading-stories. So in my config file I have: `configure(require.context('../src', true, /\.stories\.(js|mdx)$/), module);`
> 
> Also missed this detail and got help from the maintainers :) not too obvious if you dont read thoroughly.

Hi kfayelun, 

Can you share with me your config.js file, I am not understanding where to add a return. 
Currently I am not using loadStories function.

**Comment by kfayelun** [comment]
Yep, here you go. I added a Link MDX story. https://github.com/netliferesearch/netlife2019/tree/storybook_setup_stories

**Comment by apanizo** [comment]
Hi @vinayg-cp @kfayelun,

one thing, can you guys try to remove this https://github.com/netliferesearch/netlife2019/blob/storybook_setup_stories/web/.storybook/webpack.config.js#L46-L51 from your project and try again?

I believe the problem is not on the Gatsby side nor your configuration, as I wrote in my message, unless I am missing something (this is why I asked @shilman for feedback), I believe the problem is inside storybook' source-loader package, which has a bug when dealing with CSF-MDX stories.

In my case, I am using [storysource](https://www.npmjs.com/package/@storybook/addon-storysource) in my project, which needs source-loader and therefore I am having the same issue.

Feel free to share the results! Thanks!

**Comment by vinayg-cp** [comment]
> Yep, here you go. I added a Link MDX story. https://github.com/netliferesearch/netlife2019/tree/storybook_setup_stories

Hi @kfayelun,
After using the config similar to yours, 
The initial error is solved,
But now I am getting a new error, as shown below in the image: 
![image](https://user-images.githubusercontent.com/43405939/66821716-83e17300-ef60-11e9-8a89-fc99591954aa.png)

I changed my storybook to the following version: 
![image](https://user-images.githubusercontent.com/43405939/66821756-99ef3380-ef60-11e9-81cd-40b0b58589c5.png)

When I tried running your storybook, it worked fine for me. 

@apanizo :
My webpack config does not use the '@storybook/source-loader'. 
So I am not sure if that might be the issue. 
Webpack config: https://github.com/vinayg-cp/storybook-poc/blob/7e8b031e1ff93209665dab4e171cadae995b054b/.storybook/webpack.config.js#L53

**Comment by kfayelun** [comment]
Hey @vinayg-cp 
Try `export default Card` in Card.js and `import Card from './Card';`in the story. If you want named exports you can do `export { Card }` and `import { Card } from './Card'`.

Hey @apanizo 
Not using storysource anymore,  as the new docs have the source option out of the box :) so Ill remove that loader.

**Comment by vinayg-cp** [comment]
> Hey @vinayg-cp
> Try `export default Card` in Card.js and `import Card from './Card';`in the story. If you want named exports you can do `export { Card }` and `import { Card } from './Card'`.
> 
> Hey @apanizo
> Not using storysource anymore, as the new docs have the source option out of the box :) so Ill remove that loader.

Hey @kfayelun,

No difference still the same issue. 
Am I missing something with babel transpilers? 

You can checkout the last change I made at: vinay/withDefaultExport

**Comment by kfayelun** [comment]
@vinayg-cp maybe you need to use the story source loader, maybe docs are using this to generate the code snippets? If you console out the config before you override it, maybe you can see the default loader-setup there?

**Comment by apanizo** [comment]
@vinayg-cp @kfayelun I am rushing (having many things on my plate), I will try to take a look into your comments later, but I wanted to add a comment for a small clarification, feel free to point any bad assumption.

If you want to see the `source` of your stories you need to rely directly or indirectly in source-loader.

So far there are three options:
Option 1: Using addon-docs with the [preset option](https://github.com/storybookjs/storybook/blob/next/addons/docs/README.md#preset-options), which includes source-loader out of the box unless you explicitly mark `sourceLoaderOptions: null,`. As you said, this will show the code of your stories automatically.

Option 2: Using [addon-docs with the webpack config](https://github.com/storybookjs/storybook/blob/next/addons/docs/README.md#manual-configuration), which is basically do the same as the preset but manually. As you can see in the docs the source-loader is used. You can skip it, the initial error is gone, but there are no code source at all.

Option 3: Rely on [storysource](https://www.npmjs.com/package/@storybook/addon-storysource) because you do not want to use the "story docs" (or you need both, like me), and you will need the source-loader, otherwise it won't work.

As far as I see you are using a gatsby integration, I do not know if that comes with some preconfigured stuff or not. But the relation between see the source code and source-loader is present.

And it is not working when you mix MDX-CSF and storysource (or in general source-loader) ([see my first comment](https://github.com/storybookjs/storybook/issues/8414#issuecomment-541764077)) in this thread.

**Comment by apanizo** [comment]
@vinayg-cp I have not used the MDX only approach, but if you are stuck, you can give a try to mix [CSF with MDX](https://github.com/storybookjs/storybook/blob/next/addons/docs/docs/recipes.md#csf-stories-with-mdx-docs), by creating `Card.stories.tsx`. 

Also another thing you can try is just export the Card component in this way:
` export default Card;` and then in the mdx do: `import Card from './Card'.  Hopefully it solves your problem. But again, if you need to see the source code you will have to face the source-loader problem described in my previous comment.

**Comment by kfayelun** [comment]
Hey @apanizo, Im busy on other projects today, so not a lot of time to take down your repo etc. My project is running fine, I'm not seeing this issue, was just trying to help. Have you seen this article? https://www.gatsbyjs.org/docs/visual-testing-with-storybook/ It seems like you are missing some of that in your config.js. Both CSF and MDX stories are working for me, but havnet tested using both in one.

I am not using the preset option, as the way I understand it I have to configure webpack to get storybook to work with gatsby, and you do either preset or webpack config (not sure if this is correct). Theres no gatsby integration ready-to-use as far as I know, Ive used the above guide and looked at this: https://github.com/magicspon/gatsby-storybook-netlifycms-tailwind-starter

I am not using typescript, you might run into extra trouble there. 

Have you tried setting up a "normal" story or a pure MDX story to try narrow it down?

**Comment by apanizo** [comment]
@kfayelun thanks for getting back to me. Yes TS maybe is adding noise here. 

Quick question, can you confirm me you are able to see the source code of each story on your MDX files? (you know clicking on the Show source code button at the end of each story, like [this](https://github.com/storybookjs/storybook/issues/8401))

**Comment by kfayelun** [comment]
@apanizo correct, I do see the source code for MDX files, but I use arrow functions. You can pull down my repo and have a look.

I don't quite understand your last statement/question. So if you remove the docs addon and the source-loader you see your storybook (but without docs or sourcecode)? I dont see a reason why it still couldnt be a typescript issue with loading the source code? Cus thats your problem, isnt it? Its been a long day here, sorry if Im totally misunderstanding.

**Comment by apanizo** [comment]
> So if you remove the docs addon and the source-loader you see your storybook

No, if I remove the source-loader, then everything works but I can not see the source code in any place (old stories, new CSF stories or MDX stories). But it works, no compilation problem.

> Cus thats your problem, isnt it? 

Hmmmm, not really, when I debugged the error, the files were transpiled correctly, and also with my hack (described in my first comment), I made it to work! So TS stuff went fine. 

> I do see the source code for MDX files

What I do not understand now is why this is working for you. Can you send me the link of your project? I am eager to take a look into it.

> been a long day here

I really appreciate your effort, thanks!

**Comment by vinayg-cp** [comment]
@kfayelun @apanizo ,

Appreciate your efforts guys, 
But for some reason, it is not working still for .mdx stories. 
For now I will proceed with only .js stories. 

If I figure out anything I will let update here. 
If anybody has any free time, you can clone my repository at: https://github.com/vinayg-cp/storybook-poc.git 

And take a look. 

Thanks

**Comment by kfayelun** [comment]
@vinayg-cp had a quick look at your repo; try removing the preset file (you dont need this) and add the storysource loader that I have in my config file to you webpack config. 

@apanizo it's been working for me the whole time. Ive added the links to my repo before. Maybe go back and read my comments again.

**Comment by vinayg-cp** [comment]
> @vinayg-cp had a quick look at your repo; try removing the preset file (you dont need this) and add the storysource loader that I have in my config file to you webpack config.
> 
> @apanizo it's been working for me the whole time. Ive added the links to my repo before. Maybe go back and read my comments again.

https://github.com/vinayg-cp/storybook-poc/blob/5cfa434d990306e3dd2d6c627764ac4ff07c3a4b/.storybook/webpack.config.js 

Hi @kfayelun 

I replicated your webpack config, but still the issue exists. 
![image](https://user-images.githubusercontent.com/43405939/66898261-7f779180-f016-11e9-89fc-4587c3040f2b.png)

And I removed preset too. 

You can look into this code in my branch: vinay/netlifeWebpack 
Repo: https://github.com/vinayg-cp/storybook-poc.git
