### ISSUE TITLE
Favicon

### ISSUE THREAD

**Issue by abhilakshyadobhal** [storybookjs/storybook#8638]
How could we change the default favicon of storybook , please help.

**Comment by xeviltimx** [comment]
I want to do the same.
This solution doesn't seem to work
https://github.com/storybookjs/storybook/issues/581#issuecomment-256805434

**Comment by abhilakshyadobhal** [comment]
If you will find any solution pls tell me also

**Comment by xeviltimx** [comment]
I found the solution!)
Follow these steps:
1. Create image with favicon and save to `./.storybook/images` folder for example, or another.
2. Add -s flag with images folder in `package.json` for starting storybook: `"storybook": "start-storybook -p 6006 -s ./.storybook/images"`
`-s` flag means `add source folder`
3. Create `.storybook/manager-head.html`file
4. Add `<link rel='icon' href='storybook_plus.png'/>` line in it. Where storybook_plus.png - my favicon file inside `./.storybook/images` folder, because I'm not being able to config webpack properly to load *.ico files. 
5. Restart storybook
^_^
