### ISSUE TITLE
[Addon-docs]: Required column is missing in prop table

### ISSUE THREAD

**Issue by gmukul01** [storybookjs/storybook#8655]
**Describe the bug**
Required column is missing in prop table

**Expected behavior**
Required column should appear

**Screenshots**
![image](https://user-images.githubusercontent.com/3636885/67961600-ece40e80-fc21-11e9-854a-7130a150bc17.png)

**Code snippets**
types.ts
export interface Props extends WithThemeProp {
    /** Size of the avatar */
    size: AvatarSizes;
    /** Text color */
    textColor?: string;
    /** Background color */
    bgColor?: string;
}

**Comment by shilman** [comment]
There's no required column in the docs table, just a `*` by the type name that's used when a field is required. You can see it here: https://storybookjs-next.now.sh/official-storybook/?path=/story/docs-proptable--normal

Since it's not showing up, it means that the data is not being prepared correctly, so it's probably a bug with the loader.

**Comment by gmukul01** [comment]
It came after restarting the server. Thank you for quick reply.
