### ISSUE TITLE
Addon-docs: Doc Blocks documentation

### ISSUE THREAD

**Issue by shilman** [storybookjs/storybook#9133]
- [ ] Source https://github.com/storybookjs/storybook/issues/6641
- [ ] Props https://github.com/storybookjs/storybook/issues/6640

**Comment by techieshark** [comment]
What needs doing on this in terms of docs?

**Comment by gsklee** [comment]
@shilman can we have a quick explanation/sum-up here on some of the most useful [doc block components](https://github.com/storybookjs/storybook/blob/master/addons/docs/src/blocks/index.ts)? Aside from `ColorPalette, ColorItem, IconGallery, IconItem, Typeset` since they are kinda already covered [here](https://medium.com/storybookjs/rich-docs-with-storybook-mdx-61bc145ae7bc). Even a screenshot of a kitchen sink of all these components dumped together would do. Thanks!

**Comment by shilman** [comment]
@gsklee definitely -- have a workin progress on my local machine & will try to get it ready for consumption.

**Comment by mehrad-meraji** [comment]
@shilman any update on this? would you like some help?

**Comment by shilman** [comment]
@mehrad-meraji Thanks so much for the offer! I've got my hands full with other stuff but will ping you as soon as I have the bandwidth to work with you on that.

**Comment by michaeltrilford** [comment]
Oh thank goodness, is this content hard to find for anyone else? Lifesaver

**Comment by kelly-tock** [comment]
I think we need a docs page for all the doc blocks?

**Comment by alexravenna** [comment]
Any news on when ColorPalette, IconGallery, Typeset, etc. are going to be documented? I'm currently trying to implement an icon gallery and the "example" on  [Medium](https://medium.com/storybookjs/rich-docs-with-storybook-mdx-61bc145ae7bc) really doesn't get me anywhere 😞.

**Comment by shilman** [comment]
First cut here https://storybook.js.org/docs/react/writing-docs/doc-blocks

**Comment by jonniebigodes** [comment]
Closing this issue as it's no longer relevant and we have documentation on it.
