### ISSUE TITLE
@storybook/addon-contexts : context is not passed to childs

### ISSUE THREAD

**Issue by helabenkhalfallah** [storybookjs/storybook#9215]
**Describe the bug**

I used @storybook/addon-contexts to have dynamic theme.
ThemeProvider is correctly wrapping stories and hold the correct value each time I change the theme.
However stories (Consumer) have a **null theme**.

If I import ThemeProvider and my components (consumers) inside a project outside of storybook, everything work perfectly.

**To Reproduce**

My Storybook :
https://github.com/helabenkhalfallah/react-sg-components/blob/master/packages/storybook/.storybook/config.js#L42
https://github.com/helabenkhalfallah/react-sg-components/blob/master/packages/storybook/.storybook/Contexts.js#L12

My lib of components  : 
https://github.com/helabenkhalfallah/react-sg-components/blob/master/packages/sg-button/src/lib/SGButton.jsx#L29

Theme Manager : 
https://github.com/helabenkhalfallah/react-sg-components/blob/master/packages/sg-ui-core/src/ThemeProvider.jsx#L23
https://github.com/helabenkhalfallah/react-sg-components/blob/master/packages/sg-ui-core/src/withTheme.jsx#L15

**Expected behavior**
Theme Provider context will be correctly passed to child.

**Screenshots**
![image](https://user-images.githubusercontent.com/1331451/71312547-8d89ca00-242c-11ea-8d2c-5bc10725801a.png)
![image](https://user-images.githubusercontent.com/1331451/71312550-8fec2400-242c-11ea-9e76-1e4ba3f10676.png)
![image](https://user-images.githubusercontent.com/1331451/71312551-92e71480-242c-11ea-9afe-d535f2d5fb98.png)

**System:**
```
System:
    OS: macOS High Sierra 10.13.6
    CPU: (4) x64 Intel(R) Core(TM) i5-2435M CPU @ 2.40GHz
  Binaries:
    Node: 10.15.3 - ~/.nvm/versions/node/v10.15.3/bin/node
    Yarn: 1.12.3 - /usr/local/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v10.15.3/bin/npm
  Browsers:
    Chrome: 79.0.3945.88
    Firefox: 68.0.1
    Safari: 13.0.4
  npmPackages:
    @storybook/addon-actions: =5.2.6 => 5.2.6 
    @storybook/addon-console: =1.2.1 => 1.2.1 
    @storybook/addon-contexts: ^5.2.8 => 5.2.8 
    @storybook/addon-info: =5.2.6 => 5.2.6 
    @storybook/addon-knobs: =5.2.6 => 5.2.6 
    @storybook/addon-links: =5.2.6 => 5.2.6 
    @storybook/addon-options: =5.2.6 => 5.2.6 
    @storybook/addons: =5.2.6 => 5.2.6 
    @storybook/react: =5.2.6 => 5.2.6 
```

Thanks :)

**Comment by pocka** [comment]
@helabenkhalfallah 
I guess this is an issue about the usage of React Context API. Probably root cause is that your context reads [`sg-ui-core/lib/ThemeContext`](https://github.com/helabenkhalfallah/react-sg-components/blob/1eff6052525155add45b841c0236f467155d4c91/packages/storybook/.storybook/Contexts.js#L1)(`ThemeProvider -> ThemeContext`) although your stories reads [`sg-ui-core/es/ThemeContext`](https://github.com/helabenkhalfallah/react-sg-components/blob/1eff6052525155add45b841c0236f467155d4c91/packages/sg-button/src/lib/SGButton.jsx#L2)(`withTheme -> ThemeContext`).

```
ThemeProvider (in lib/)
  ThemeContext.Provider (in lib/)
    ...
      ThemeContext.Consumer (in es/, which is a different instance!)
```

So changing the module path in `Contexts.js` to `sg-ui-core/es/ThemeProvider` would solve your problem. Could you try it, please?

**Comment by helabenkhalfallah** [comment]
Yes, I try, thanks :)

**Comment by helabenkhalfallah** [comment]
Yes, that is it, I created a separated npm module for this and everything works perfectly, thanks :)
