### ISSUE TITLE
Updating emotion breaks ThemeProvider Context

### ISSUE THREAD

**Issue by codejunkienick** [storybookjs/storybook#9313]
@emotion/core           latest  10.0.22      ❯  10.0.27      
@emotion/styled         latest  10.0.23      ❯  10.0.27        
emotion-theming         latest  10.0.19      ❯  10.0.27  

By upgrading this packages theme is not passed down to emotion wrapped components. 

Possibly related issue https://github.com/storybookjs/storybook/issues/9300

**Comment by narajaon** [comment]
I got the same issue. In my monorepo it looks like I have two different instances of emotion after the migration to `10.0.27`.

**Comment by ndelangen** [comment]
If someone would be able to create a reproduction, that's be super helpful 🙏

**Comment by narajaon** [comment]
Ok so I solved it !
As I'm using a monorepo, I had @emotion/styled@10.0.27 as a peer dependency in one of my main packages.
The problem came from the fact that I was using @storybook/react@5.1.9 **AT THE SAME TIME**.

It caused my monorepo to have two instances of emotion, the one I was using 10.0.27 and the one required by @storybook/react which was 10.0.23.

I solved the problem by updating @storybook/* to 5.3.8
