### ISSUE TITLE
MDX linkings should not rely on the remark-slug plugin to generate slug for headers

### ISSUE THREAD

**Issue by patricklafrance** [storybookjs/storybook#9329]
**Is your feature request related to a problem? Please describe.**
The current version of MDX linkings rely on the [remark-slug](https://github.com/remarkjs/remark-slug) plugin to generate the slugs for headers:

```html
<h1 id="supported-platforms" class="sbdocs sbdocs-h1 css-1j28tt">
```

There is a few issues with this approach:

- The plugin doesn't handle MDX dynamic expression:

The following dynamic expression `## <Fragment children={props.title} />` result in the following slug:

```html
<h2 id="fragment-childrenpropstitle-" class="sbdocs sbdocs-h2 css-1lg570m">
```

- Since remark-slug is an MDX plugin, it can't be used for DocsPage.

**Describe the solution you'd like**
SB should develop a set of `<Header />` components that will take care of rendering the header element and generate the appropriate slug.

These components could be used for DocsPage and also as custom MDX components for MDX linkings.

**Comment by kevin940726** [comment]
Looks like we already have a set of components like in https://github.com/storybookjs/storybook/blob/da303c5151e724551fb4b04f1ad0cbcf3e03359d/addons/docs/src/blocks/mdx.tsx#L185-L202
So now we need to _slugify_ the text content into `id`? Since the content is evaluated in run time, how should it suppose to do that 🤔?
