### ISSUE TITLE
Support for links in props addon-info

### ISSUE THREAD

**Issue by kushalmahajan** [storybookjs/storybook#9558]
I'm using `"@storybook/react": "^5.2.6"` and  `"@storybook/addon-info": "^5.2.6"`. What I would like is the ability to mention links inside the comments in my description. 

Now, below is an attempt to do so

```
         columns: any[];
         /** Config of pagination. You can ref
	 * [pagination]{@https://xyx.com/?path=/story/pagination--basic} document
	 * hide it by setting it to false
	 */
	pagination?: Pagination | boolean;
```
But this renders text only version.  The above is an example taken from JSDoc.  Please guide for a
solution or an alternative.

**Comment by shilman** [comment]
`Addon-info` is being superceded by `addon-docs`, which fixes a bunch of bugs and is easier to maintain. Please give it a try! https://medium.com/storybookjs/storybook-docspage-e185bc3622bf

**Comment by kushalmahajan** [comment]
I know @shilman. I have an update about from you earlier. I did read this medium article and had some observations and questions a while back. You might find it interesting. The very same concerns are holding me to upgrade to it plus thinking if full flown site like Gatsby is a way to go.

Importantly,  are you saying that for a definitive that`addon-docs` will have the link feature I asked for here in this issue?

**Comment by shilman** [comment]
@kushalmahajan Yes, I believe it exists or there is a good workaround. More importantly, if it doesn't exist there is a non-zero chance it will be added. In `addon-info`, it's likely that the only way you'll get the feature is if you add it yourself. It's good to upgrade to docs because it's much better than `addon-info` AND it's being improved very rapidly with every release. And of course if Storybook doesn't do what you need, you are always welcome to use something else.

**Comment by kushalmahajan** [comment]
x

**Comment by kushalmahajan** [comment]
Ok @shilman. I will have a deeper look.
