### ISSUE TITLE
Props table issue from styled component interface in addon-blocks

### ISSUE THREAD

**Issue by suraj-eai** [storybookjs/storybook#9794]
There is issue in generating props table from typescript interface in styled component. There are all the HTML properties in props table. 

`Button.tsx`
```
import styled from 'styled-components';

interface IButton{
    isUpperCase: boolean; 
}
const Button = styled.button<IButton>`
    ${props => props.isUpperCase && 'text-transform: upperase;'}
`;
export default Button;
```

`Button.stories.mdx`
```
import { Meta, Preview, Story, Props } from '@storybook/addon-docs/blocks';
import Button from './Button';

<Meta title="Button" />

<Preview>
  <Story name="Button">
    <Button>Press me</Button>
  </Story>
</Preview>

<Props of={Button} />
```

`.stortbook/main.js`

```
const path = require('path');

module.exports = {
  stories: ['../src/**/*.stories.mdx'],
  addons: [
    {
      name: '@storybook/preset-create-react-app',
      options: {
        tsDocgenLoaderOptions: {
          tsconfigPath: path.resolve(__dirname, '../tsconfig.json')
        }
      }
    },
    '@storybook/addon-actions',
    '@storybook/addon-links',
    {
      name: '@storybook/addon-docs',
      options: {
        configureJSX: true,
      },
    }
  ]
};
```

The prop table is generated like below:

![Screen Shot 2020-02-08 at 18 22 12](https://user-images.githubusercontent.com/52927184/74085312-ff32db80-4a9f-11ea-9a9f-5a36f6be5c30.png)

![Screen Shot 2020-02-08 at 18 22 57](https://user-images.githubusercontent.com/52927184/74085318-12de4200-4aa0-11ea-8f8b-f6def98713dd.png)

Here the desired behavior is to get only `isUpperCase` in props table. 
Storybook version: `5.3.12`
Styled components version: `4.4.0`

**Comment by douglaseggleton** [comment]
@suraj-eai Did you come up with a workaround for this?

**Comment by stevesims** [comment]
+1 from me on this

i have a workaround to this specific issue, which is to create a simple React functional component that wraps the styled component specifically only for use with the `Props` table.

my base component `button.tsx` file has the following code at the end:
```tsx
export const DocsButton: React.FC<Props> = props => <Button {...props} />;
DocsButton.defaultProps = Button.defaultProps;

export default Button;
```

my `button.stories.mdx` file has the following code:
```mdx
import { Meta, Story, Preview, Props } from '@storybook/addon-docs/blocks';
import Button, { DocsButton } from '.';

<Meta title="Button" component={Button} />

Documentation and examples here

<Props of={DocsButton} />
```

this is obviously slightly less than ideal (as the DocsButton component is effectively junk code) but does resolve the issue.  fortunately my build tooling throws this component away, so it's not littering the build.

**Comment by suraj-eai** [comment]
> @suraj-eai Did you come up with a workaround for this?

Sorry, not yet.

**Comment by shilman** [comment]
@stevesims we're updating the docgen recommendations for typescript in 6.0:

https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#react-prop-tables-with-typescript

the new setup has its own issues, but i expect will resolve the one you're seeing above

**Comment by suraj-eai** [comment]
> https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#react-prop-tables-with-typescript

Thanks @shilman

**Comment by shilman** [comment]
We've just released zero-config typescript support in 6.0-beta. Please upgrade and test it!

- [Release 6.0.0-beta.12+](https://github.com/storybookjs/storybook/releases/tag/v6.0.0-beta.12)
- [Migration instructions](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#zero-config-typescript)
- [Updated docs](https://github.com/storybookjs/storybook/blob/next/docs/src/pages/configurations/typescript-config/index.md)

Thanks for your help and support getting this stable for release!

**Comment by kcsuraj** [comment]
@shilman The props table issue with styled component seemed to be fixed in beta release. I tested with storybook version `v6.0.0-beta.16`. 

`main.js`
```javascript
module.exports = {
  stories: ['../src/**/*.stories.mdx'],
  addons: [
    {
      name: '@storybook/preset-create-react-app'
    },
    '@storybook/addon-actions',
    '@storybook/addon-links',
    {
      name: '@storybook/addon-docs',
      options: {
        configureJSX: true
      }
    }
  ]
};

```

Styled component:
```
import styled from 'styled-components';

interface IStyledProps {
  bold?: boolean;
  textTransform?: 'lowercase' | 'capitalize' | 'uppercase';
  display?: 'inline' | 'inline-block' | 'block';
}

const Typography = styled.p<IStyledProps>`
  ${props => props.bold && `font-weight: ${props.theme.weight.bold};`}
  ${props => props.textTransform && `text-transform: ${props.textTransform};`}
  ${props => props.display && `display: ${props.display};`}
`;
```
Generates the prop table below:
![Screen Shot 2020-05-28 at 10](https://user-images.githubusercontent.com/42274546/83099182-58b12b80-a0cc-11ea-89ed-2e89d2ea6cc5.jpg)

Thank you for the hard work.

**Comment by ajkl2533** [comment]
@shilman @kcsuraj  I see this issue is closed but I encountered the same/very similar issue with the latest `rc.13` version. I have styled-component added to Storybook but the props table is not showing any custom props defined on the component. Any idea or advice what I'm doing wrong?
```tsx
interface TextComponentProps {
  size?: Sizes;
  type?: Types;
  [key: string]: unknown;
}

const Text = styled.span<TextComponentProps>`
  font-family: ${getFontFamily('base')};
  font-weight: ${getFontWeight('regular')};
  color: ${getColor('graphite4B')};
  ${({ size }) => sizes[size]};
  ${({ type }) => types[type]};
`;

Text.defaultProps = {
  size: TextSizes.lg,
  type: TextTypes.primary,
};

export default Text;
``` 
```js
import Text from './Text';

export default {
  title: 'Components/typography/Text',
  component: Text,
};


export const largeText = () => <Text size="lg">{lipsum}</Text>;
```

<img width="745" alt="Screenshot 2020-07-21 at 17 15 04" src="https://user-images.githubusercontent.com/18654425/88072788-bf574080-cb75-11ea-841f-34e6ebb877fa.png">

**Comment by elmaurer** [comment]
hey, i encountered the same problem.
Storybooks default interface added **theme**,  **as** and **forwardedAs** to my props table.
I found a simple workaround, without wrapping the whole styled component in a wrapper.
By simple defining the components return value as React FC and your custom interface.

### Button.tsx
![image](https://user-images.githubusercontent.com/25457670/204114633-2ba7177a-0c48-4ad0-9b1c-2b2a3f537d65.png)

### Button.stories.tsx
![image](https://user-images.githubusercontent.com/25457670/204114765-b97296fd-75a1-4c38-aaab-430df099e511.png)

### Props Table
![image](https://user-images.githubusercontent.com/25457670/204114780-95e7fbc6-3969-4e71-9ecf-ad3b2d7fdfea.png)

I hope this helps someone, because i've been struggling a little bit aswell... :D
