### ISSUE TITLE
Addon-docs: Copy action should be smaller

### ISSUE THREAD

**Issue by patricklafrance** [storybookjs/storybook#9904]
**Is your feature request related to a problem? Please describe.**

When a code sample takes the full width of the container, the copy action button is very close to the text.

![image](https://user-images.githubusercontent.com/794579/74775524-de1e7780-5263-11ea-891e-0f84fb87cf68.png)

**Describe the solution you'd like**
Easy solution, reduce the padding of the copy action button to `1px 6px`:

![image](https://user-images.githubusercontent.com/794579/74775584-fdb5a000-5263-11ea-91e0-dd5efe82f60e.png)

Or add an escape hatches to allow the end user to apply custom CSS.

Alternative solution would be to have the buttons outside the source code container.

Material UI:
![image](https://user-images.githubusercontent.com/794579/74775738-57b66580-5264-11ea-822b-7a208d134e3b.png)

Antd:
![image](https://user-images.githubusercontent.com/794579/74775753-5edd7380-5264-11ea-9c03-ac95a4e35031.png)

**Comment by patricklafrance** [comment]
What do you think @domyen ?

**Comment by domyen** [comment]
Thanks for the suggestion Patrick. This is a the default behavior of that component, which is used across Storybook and its sub-projects. I don't have a solution 😅 but am hesitant to make a change because it would prompt a change to a lot of other un-related things.

An idea that might sidestep this behavior is to hide the "ActionBar" and reveal it on `:hover`.

**Comment by patricklafrance** [comment]
Hiding the action bar until hovered seems like a great idea to me @domyen!
