### ISSUE TITLE
Storysource addon does not work with CRA + MDX

### ISSUE THREAD

**Issue by gsklee** [storybookjs/storybook#9930]
As the title suggests, I am using a Create React App + MDX docs setup. After installing the Storysource addon, I am seeing this `loading source...` message in the addon panel where the source code was supposed to be shown.

I managed to put together a few config code snippets from some (outdated) discussion threads; unfortunately none of them works for me now (Storybook v5.3.13).

### main.js (Attempt 1)
```js
  addons: [
    ...

    {
      name: "@storybook/addon-storysource",
      options: {
        rule: {
          test: [/\.mdx?$/],
          include: path.resolve('../src/component/Button'),
        }
      }
    }
  ]
```

### main.js (Attempt 2)
```js
  webpackFinal: async (config, { configType }) => {
    config.module.rules.push({
      test: [/\.mdx?$/],
      include: path.resolve("../src/component/Button"),
      loaders: [ require.resolve('@storybook/addon-storysource/loader') ],
    });

    return config;
  }
```

**Comment by shilman** [comment]
MDX was introduced as a feature of `addon-docs` long after `addon-storysource` was created, so giving `addon-storysource` is a feature request. (Tho, since both are "core" addons it would also be fair to call it a bug).

Both Docs and Storysource depend on `source-loader`, but in the case of MDX, the MDX compiler simply hacks in a story parameter called `mdxSource` that bypasses the entire `source-loader` thing:

https://github.com/storybookjs/storybook/blob/master/addons/docs/src/mdx/mdx-compiler-plugin.js#L97-L103

Thus, the easiest fix for this would be to modify Storysource to display `mdxSource` if it's available.

**Comment by shilman** [comment]
This appears to be fixed in SB6.0 thanks to https://github.com/storybookjs/storybook/pull/9547

Closing this!
